In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('OpenAlexData.csv', index_col=0)

C:\Users\wieke\AppData\Local\Temp\ipykernel_24272\2055085896.py:1: DtypeWarning: Columns (8,26) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('OpenAlexData.csv', index_col=0)

In [3]:
pd.set_option("display.max_columns", 55)

In [4]:
df

,id,doi,type,funding_type,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,https://openalex.org/I79576946,University of Pennsylvania,"Psychology,University of Pennsylvania",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,dataset,funder,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,en,https://openalex.org/T12308,Mental Health and Psychiatry,https://openalex.org/subfields/1211,Philosophy,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5091505956,Jerome C. Wakefield,last,https://orcid.org/0000-0002-6809-5515,https://openalex.org/I57206974,New York University,"New York University, New York, NY, US",US,https://ror.org/0190ak572,https://openalex.org/I57206974
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,dataset,funder,Cognitive Therapy for Depression,1996,1996-01-01,en,https://openalex.org/T13272,Psychological Treatments and Assessments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5047792029,Aaron T. Beck,last,NaN,https://openalex.org/I79576946,University of Pennsylvania,"Department of Psychiatry, School of Medicine, ...",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517775,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5008503776,Ronald G. Ehrenberg,first,NaN,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517776,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5020341649,Michael L. Bognanno,last,NaN,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517777,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,funder,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5057810294,Ronald C. Kessler,first,https://orcid.org/0000-0003-4831-2305,https://openalex.org/I27837315,University of Michigan–Ann Arbor,"Institute for Social Research, University of M...",US,https://ror.org/00jmfr291,https://openalex.org/I27837315
517778,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,funder,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,True,green,NaN,https://openalex.org/A5013000614,Thomas A. Romberg,first,NaN,https://openalex.org/I79576946,University of Pennsylvania,University of Pennsylvania ScholarlyCommons,US,https://ror.org/00b30xv10,https://openalex.org/I79576946
517779,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,funder,"National Support for World Order, 1966",1984,1984-05-03,en,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5048046292,Robert C. Angell,first,NaN,https://openalex.org/I27837315,University of Michigan–Ann Arbor,Department of Sociology University of Michigan,US,https://ror.org/00jmfr291,https://openalex.org/I27837315

In [5]:
df['oa_status'].value_counts()

oa_status
hybrid    435283
gold       48314
closed     29063
bronze      4714
green        406
Name: count, dtype: int64

In [6]:
df['Repository'].unique()

array(['PsycEXTRA Dataset', 'Harvard Dataverse',
       'Artifact Digital Object Group', 'Figshare',
       'Zenodo (CERN European Organization for Nuclear Research)',
       'Global Biodiversity Information Facility', nan,
       'The SHAFR Guide Online',
       'Carbon Dioxide Information Analysis Center (CDIAC) Datasets',
       'IUPAC Standards Online', 'AEA Randomized Controlled Trials',
       'immuneACCESS',
       'Pancreapedia: The Exocrine Pancreas Knowledge Base',
       'ICPSR Data Holdings', 'Forest Service Research Data Archive',
       'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)',
       'PsycTESTS Dataset',
       'Faculty Opinions – Post-Publication Peer Review of the Biomedical Literature',
       'Authorea', 'nano Online', 'Human Rights Documents online',
       'ENCODE Datasets', 'The Winnower',
       'Biological and Chemical Oceanography Data Management Office',
       'energyo', 'EcoSal',
       'APS Division of Plasma Physics Meeting Abstracts',
       'Default Digital Object Group', 'SciVee', 'Radiographics',
       'Oxford Bibliographies Online Datasets', 'Access Science',
       'Inactive DOIs',
       'F1000 - Post-publication peer review of the biomedical literature',
       'Wolfram Demonstrations Project', 'PMC',
       'Research Data Repository, Duke University', 'Radiology'],
      dtype=object)

In [107]:
df= df[df['Repository'] != 'Faculty Opinions – Post-Publication Peer Review of the Biomedical Literature']

In [108]:
df['Repository'].unique()

array(['PsycEXTRA Dataset', 'Harvard Dataverse',
       'Artifact Digital Object Group', 'Figshare',
       'Zenodo (CERN European Organization for Nuclear Research)',
       'Global Biodiversity Information Facility', nan,
       'The SHAFR Guide Online',
       'Carbon Dioxide Information Analysis Center (CDIAC) Datasets',
       'IUPAC Standards Online', 'AEA Randomized Controlled Trials',
       'immuneACCESS',
       'Pancreapedia: The Exocrine Pancreas Knowledge Base',
       'ICPSR Data Holdings', 'Forest Service Research Data Archive',
       'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)',
       'PsycTESTS Dataset', 'Authorea', 'nano Online',
       'Human Rights Documents online', 'ENCODE Datasets', 'The Winnower',
       'Biological and Chemical Oceanography Data Management Office',
       'energyo', 'EcoSal',
       'APS Division of Plasma Physics Meeting Abstracts',
       'Default Digital Object Group', 'SciVee', 'Radiographics',
       'Oxford Bibliographies Online Datasets', 'Access Science',
       'Inactive DOIs',
       'F1000 - Post-publication peer review of the biomedical literature',
       'Wolfram Demonstrations Project', 'PMC',
       'Research Data Repository, Duke University', 'Radiology'],
      dtype=object)

In [109]:
field_name_df = df.groupby('field_name').size().sort_values(ascending=False)
field_name_df.head(25)

field_name
Earth and Planetary Sciences                    10386
Biochemistry, Genetics and Molecular Biology     8374
Physics and Astronomy                            7906
Medicine                                         7317
Environmental Science                            6957
Social Sciences                                  6840
Engineering                                      6781
Chemistry                                        6317
Computer Science                                 6258
Agricultural and Biological Sciences             3040
Materials Science                                2694
Economics, Econometrics and Finance              2288
Decision Sciences                                2187
Business, Management and Accounting              1500
Pharmacology, Toxicology and Pharmaceutics        597
Immunology and Microbiology                       527
Neuroscience                                      482
Mathematics                                       463
Psychology                                        443
Health Professions                                411
Arts and Humanities                               290
Energy                                            176
Chemical Engineering                              123
Dentistry                                          94
Nursing                                            40
dtype: int64

In [110]:
domain_df = df.groupby(['domain_name', 'institution_name']).size().sort_values(ascending=False)
domain_df.head(25)

domain_name        institution_name
Physical Sciences  University of Michigan–Ann Arbor           18264
Life Sciences      University of Michigan–Ann Arbor            8274
Physical Sciences  Cornell University                          7408
                   Washington University in St. Louis          5308
Health Sciences    University of Michigan–Ann Arbor            5108
Social Sciences    University of Michigan–Ann Arbor            5094
Physical Sciences  University of Wisconsin–Madison             3985
                   Duke University                             3019
                   Princeton University                        2183
                   University of Nebraska–Lincoln              1901
                   Pennsylvania State University               1544
Social Sciences    New York University                         1285
                   Princeton University                        1257
Physical Sciences  New York University                         1178
Social Sciences    Duke University                             1019
Physical Sciences  University of Illinois Urbana-Champaign      896
Life Sciences      Cornell University                           860
Social Sciences    Cornell University                           816
                   Pennsylvania State University                725
                   Washington University in St. Louis           722
                   University of Pennsylvania                   660
                   University of Virginia                       560
Physical Sciences  University of Virginia                       530
                   Virginia Tech                                527
Life Sciences      University of Wisconsin–Madison              481
dtype: int64

In [111]:
inst_domain_df = df.groupby(['institution_name', 'domain_name']).size().sort_values(ascending=False)
inst_domain_df.head(50)

institution_name                         domain_name
University of Michigan–Ann Arbor         Physical Sciences    18264
                                         Life Sciences         8274
Cornell University                       Physical Sciences     7408
Washington University in St. Louis       Physical Sciences     5308
University of Michigan–Ann Arbor         Health Sciences       5108
                                         Social Sciences       5094
University of Wisconsin–Madison          Physical Sciences     3985
Duke University                          Physical Sciences     3019
Princeton University                     Physical Sciences     2183
University of Nebraska–Lincoln           Physical Sciences     1901
Pennsylvania State University            Physical Sciences     1544
New York University                      Social Sciences       1285
Princeton University                     Social Sciences       1257
New York University                      Physical Sciences     1178
Duke University                          Social Sciences       1019
University of Illinois Urbana-Champaign  Physical Sciences      896
Cornell University                       Life Sciences          860
                                         Social Sciences        816
Pennsylvania State University            Social Sciences        725
Washington University in St. Louis       Social Sciences        722
University of Pennsylvania               Social Sciences        660
University of Virginia                   Social Sciences        560
                                         Physical Sciences      530
Virginia Tech                            Physical Sciences      527
University of Wisconsin–Madison          Life Sciences          481
University of Minnesota                  Physical Sciences      473
Cornell University                       Health Sciences        463
University of Pennsylvania               Physical Sciences      448
University of Wisconsin–Madison          Social Sciences        439
Princeton University                     Life Sciences          404
Washington University in St. Louis       Life Sciences          396
Duke University                          Health Sciences        387
                                         Life Sciences          376
New York University                      Life Sciences          363
Pennsylvania State University            Life Sciences          362
University of Illinois Urbana-Champaign  Life Sciences          350
University of Colorado Boulder           Physical Sciences      336
Washington University in St. Louis       Health Sciences        331
University of Nebraska–Lincoln           Life Sciences          319
University of Wisconsin–Madison          Health Sciences        296
University of Virginia                   Life Sciences          285
New York University                      Health Sciences        283
University of Illinois Urbana-Champaign  Social Sciences        259
University of Colorado Boulder           Social Sciences        255
Princeton University                     Health Sciences        236
University of Minnesota                  Social Sciences        206
University of Nebraska–Lincoln           Social Sciences        179
Virginia Tech                            Life Sciences          171
University of Virginia                   Health Sciences        162
University of Pennsylvania               Life Sciences          143
dtype: int64

In [112]:
oa_count_df = df.groupby(['institution_name', 'is_oa']).size().sort_values(ascending=False)
oa_count_df.head(25)

institution_name                         is_oa
University of Michigan–Ann Arbor         True     445209
Cornell University                       True       7972
Princeton University                     True       5568
Washington University in St. Louis       False      4835
Duke University                          True       4114
New York University                      True       4105
University of Wisconsin–Madison          True       3446
Pennsylvania State University            True       3098
Washington University in St. Louis       True       2545
University of Wisconsin–Madison          False      2392
Cornell University                       False      2332
Duke University                          False      2256
University of Pennsylvania               True       1881
University of Virginia                   True       1781
University of Nebraska–Lincoln           False      1774
University of Illinois Urbana-Champaign  True       1639
University of Michigan–Ann Arbor         False       998
Virginia Tech                            True        891
University of Colorado Boulder           True        855
University of Minnesota                  True        736
University of Nebraska–Lincoln           True        724
Pennsylvania State University            False       448
University of Illinois Urbana-Champaign  False       354
University of Minnesota                  False       347
New York University                      False       305
dtype: int64

In [113]:
oa_count_df = df.groupby(['institution_name'])['is_oa'].value_counts().unstack('is_oa').reset_index()
oa_count_df

is_oa                         institution_name  False    True
0                           Cornell University   2332    7972
1                              Duke University   2256    4114
2                    Michael J. Fox Foundation      1       5
3                          New York University    305    4105
4                Pennsylvania State University    448    3098
5                         Princeton University    219    5568
6               University of Colorado Boulder     95     855
7      University of Illinois Urbana-Champaign    354    1639
8             University of Michigan–Ann Arbor    998  445209
9                      University of Minnesota    347     736
10              University of Nebraska–Lincoln   1774     724
11                    University of New Mexico     29      85
12                  University of Pennsylvania     69    1881
13                      University of Virginia    216    1781
14             University of Wisconsin–Madison   2392    3446
15                               Virginia Tech    120     891
16          Washington University in St. Louis   4835    2545

In [114]:
df['Repository'].value_counts()

Repository
ENCODE Datasets                                                                        435461
Harvard Dataverse                                                                       30117
Zenodo (CERN European Organization for Nuclear Research)                                16798
OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)     13256
Figshare                                                                                 2976
IUPAC Standards Online                                                                    915
Default Digital Object Group                                                              579
PsycEXTRA Dataset                                                                         370
Authorea                                                                                  102
Artifact Digital Object Group                                                             101
energyo                                                                                    85
Pancreapedia: The Exocrine Pancreas Knowledge Base                                         71
Biological and Chemical Oceanography Data Management Office                                69
AEA Randomized Controlled Trials                                                           51
Forest Service Research Data Archive                                                       40
The SHAFR Guide Online                                                                     27
Radiology                                                                                  25
immuneACCESS                                                                               23
SciVee                                                                                     21
Global Biodiversity Information Facility                                                   18
ICPSR Data Holdings                                                                        12
Radiographics                                                                              12
The Winnower                                                                               11
Carbon Dioxide Information Analysis Center (CDIAC) Datasets                                 9
Human Rights Documents online                                                               8
PsycTESTS Dataset                                                                           7
PMC                                                                                         5
Research Data Repository, Duke University                                                   5
EcoSal                                                                                      4
Access Science                                                                              4
Inactive DOIs                                                                               4
nano Online                                                                                 3
APS Division of Plasma Physics Meeting Abstracts                                            2
Oxford Bibliographies Online Datasets                                                       2
F1000 - Post-publication peer review of the biomedical literature                           1
Wolfram Demonstrations Project                                                              1
Name: count, dtype: int64

In [115]:
oa_count_s = df.groupby(['institution_name'])['is_oa'].value_counts().unstack('is_oa').reset_index()
oa_count_s['OA %'] = oa_count_s[True] / (oa_count_s[False] + oa_count_s[True])
#oa_count_s
oa_count_s.sort_values(by=['OA %'], ascending=False)

is_oa                         institution_name  False    True      OA %
8             University of Michigan–Ann Arbor    998  445209  0.997763
12                  University of Pennsylvania     69    1881  0.964615
5                         Princeton University    219    5568  0.962157
3                          New York University    305    4105  0.930839
6               University of Colorado Boulder     95     855  0.900000
13                      University of Virginia    216    1781  0.891838
15                               Virginia Tech    120     891  0.881306
4                Pennsylvania State University    448    3098  0.873660
2                    Michael J. Fox Foundation      1       5  0.833333
7      University of Illinois Urbana-Champaign    354    1639  0.822378
0                           Cornell University   2332    7972  0.773680
11                    University of New Mexico     29      85  0.745614
9                      University of Minnesota    347     736  0.679594
1                              Duke University   2256    4114  0.645840
14             University of Wisconsin–Madison   2392    3446  0.590271
16          Washington University in St. Louis   4835    2545  0.344851
10              University of Nebraska–Lincoln   1774     724  0.289832

In [152]:
def counts(col1, col2, col3, df):
    oa_count_s = df.groupby([col1])[col2].value_counts().unstack(col2).reset_index()
    oa_count_s = oa_count_s.fillna(0)
    
    oa_count_s[col3] = oa_count_s[True] / (oa_count_s[False] + oa_count_s[True])
    oa_count_s
    return oa_count_s.sort_values(by=[col3], ascending=False)

In [153]:
def oa_status(df, col1, col2, sorted):
    oa_status_df = df.groupby([col1])[col2].value_counts().unstack(col2).reset_index()
    oa_status_df = oa_status_df.fillna(0)
    oa_status_df['total'] = oa_status_df['bronze'] + oa_status_df['closed'] + oa_status_df['gold'] + oa_status_df['green'] + oa_status_df['hybrid']
    oa_status_df['hybrid %'] = oa_status_df['hybrid'] / oa_status_df['total']
    oa_status_df['green %'] = oa_status_df['green'] / oa_status_df['total']
    oa_status_df['gold %'] = oa_status_df['gold'] / oa_status_df['total']
    oa_status_df['closed %'] = oa_status_df['closed'] / oa_status_df['total']
    oa_status_df['bronze %'] = oa_status_df['bronze'] / oa_status_df['total']
    dct = {'hybrid %': 'hybrid', 'green %': 'green', 'gold %': 'gold', 'closed %': 'closed', 'bronze %': 'bronze'}
    oa_status_df['Most used OA type'] = oa_status_df[['hybrid %', 'green %', 'gold %', 'closed %', 'bronze %']].idxmax(axis=1).map(dct)

    #oa_status_df = oa_status_df.sort_values(by=[sort], ascending=False)
    oa_status_df = oa_status_df.sort_values(by=[sorted], ascending=False).reset_index(drop=True)

    return oa_status_df

In [165]:
field_oa_df = counts('field_name', 'is_oa', 'OA %', df)
field_oa_df

is_oa                                    field_name   False    True      OA %
20                                          Nursing     0.0    40.0  1.000000
8                                         Dentistry     0.0    94.0  1.000000
10              Economics, Econometrics and Finance     9.0  2279.0  0.996066
5                                         Chemistry    80.0  6237.0  0.987336
14                               Health Professions     6.0   405.0  0.985401
3               Business, Management and Accounting    22.0  1478.0  0.985333
24                                  Social Sciences   115.0  6725.0  0.983187
17                                      Mathematics    10.0   453.0  0.978402
7                                 Decision Sciences    48.0  2139.0  0.978052
15                      Immunology and Microbiology    17.0   510.0  0.967742
0              Agricultural and Biological Sciences   121.0  2919.0  0.960197
18                                         Medicine   310.0  7007.0  0.957633
2      Biochemistry, Genetics and Molecular Biology   360.0  8014.0  0.957010
16                                Materials Science   130.0  2564.0  0.951745
22                            Physics and Astronomy   405.0  7501.0  0.948773
21       Pharmacology, Toxicology and Pharmaceutics    37.0   560.0  0.938023
12                                      Engineering   422.0  6359.0  0.937767
6                                  Computer Science   403.0  5855.0  0.935602
11                                           Energy    16.0   160.0  0.909091
1                               Arts and Humanities    35.0   255.0  0.879310
23                                       Psychology    57.0   386.0  0.871332
4                              Chemical Engineering    25.0    98.0  0.796748
19                                     Neuroscience   117.0   365.0  0.757261
25                                       Veterinary     5.0    15.0  0.750000
13                            Environmental Science  3936.0  3021.0  0.434239
9                      Earth and Planetary Sciences  9100.0  1286.0  0.123821

In [166]:
domain_oa_df = counts('domain_name', 'is_oa', 'OA %', df)
domain_oa_df

is_oa        domain_name  False   True      OA %
3        Social Sciences    286  13262  0.978890
0        Health Sciences    321   7561  0.959274
1          Life Sciences    652  12368  0.949923
2      Physical Sciences  14527  33534  0.697738

In [167]:
subfield_name_df = counts('subfield_name', 'is_oa', 'OA %', df)
subfield_name_df.head(25)

is_oa                                      subfield_name  False   True  OA %
159                                         Oral Surgery    0.0    3.0   1.0
103                                               Health    0.0   94.0   1.0
169                                         Periodontics    0.0   90.0   1.0
38                                              Classics    0.0    3.0   1.0
125                                                  Law    0.0  147.0   1.0
123                     Issues, ethics and legal aspects    0.0    3.0   1.0
43                Complementary and alternative medicine    0.0   50.0   1.0
172                                             Pharmacy    0.0    9.0   1.0
46           Computer Graphics and Computer-Aided Design    0.0   59.0   1.0
115                                 Industrial relations    0.0    8.0   1.0
48                         Computer Science Applications    0.0   61.0   1.0
174    Physical Therapy, Sports Therapy and Rehabilit...    0.0    6.0   1.0
1                              Acoustics and Ultrasonics    0.0    2.0   1.0
108                                           Hepatology    0.0    7.0   1.0
203                                   Speech and Hearing    0.0   56.0   1.0
107                                           Hematology    0.0  311.0   1.0
55                                           Dermatology    0.0    6.0   1.0
208                                   Structural Biology    0.0    6.0   1.0
56                                           Development    0.0  129.0   1.0
100                           Geriatrics and Gerontology    0.0    4.0   1.0
58                            Developmental Neuroscience    0.0    1.0   1.0
98                                 Geometry and Topology    0.0   19.0   1.0
60                Discrete Mathematics and Combinatorics    0.0   10.0   1.0
93                               General Social Sciences    0.0  228.0   1.0
195                                      Sensory Systems    0.0    3.0   1.0

In [168]:
topic_name_df = counts('topic_name', 'is_oa', 'OA %', df)
topic_name_df.head(25)

is_oa                                         topic_name  False   True  OA %
0                          2D Materials and Applications    0.0    6.0   1.0
1378         Microbial bioremediation and biosurfactants    0.0    3.0   1.0
1395                        Migration and Labor Dynamics    0.0  102.0   1.0
1394                       Migraine and Headache Studies    0.0    2.0   1.0
1393                    Middle East and Rwanda Conflicts    0.0    7.0   1.0
1392                    Middle East Politics and Society    0.0   46.0   1.0
1391       Microwave-Assisted Synthesis and Applications    0.0    3.0   1.0
1390     Microwave and Dielectric Measurement Techniques    0.0    2.0   1.0
1389           Microwave Imaging and Scattering Analysis    0.0    2.0   1.0
1388                Microwave Engineering and Waveguides    0.0    2.0   1.0
1387             Microwave Dielectric Ceramics Synthesis    0.0    7.0   1.0
1385   Microstructure and Mechanical Properties of St...    0.0    2.0   1.0
1382                Microfinance and Financial Inclusion    0.0   10.0   1.0
1381             Microencapsulation and Drying Processes    0.0    1.0   1.0
1377         Microbial Natural Products and Biosynthesis    0.0    2.0   1.0
1397                   Migration, Ethnicity, and Economy    0.0    5.0   1.0
1376               Microbial Metabolism and Applications    0.0   53.0   1.0
1372                      MicroRNA in disease regulation    0.0   50.0   1.0
1366                     Metallurgy and Material Forming    0.0    6.0   1.0
1365          Metallurgical Processes and Thermodynamics    0.0   43.0   1.0
1364             Metalloenzymes and iron-sulfur proteins    0.0    4.0   1.0
1363               Metallic Glasses and Amorphous Alloys    0.0   10.0   1.0
1362   Metal-Organic Frameworks: Synthesis and Applic...    0.0   10.0   1.0
1360                 Metal Forming Simulation Techniques    0.0    9.0   1.0
1358                    Metabolism, Diabetes, and Cancer    0.0    5.0   1.0

In [169]:
MN_df = df[df['institution_name'] == 'University of Minnesota']
MN_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
6,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
7,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
9,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5114168374,Cole Kelleher,middle,NaN,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
10,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111210501,Michael Cloutier,middle,NaN,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
11,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5098790376,Eric Husby,middle,NaN,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517323,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,dataset,funder,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,en,https://openalex.org/T10557,Social Media and Politics,https://openalex.org/subfields/3315,Communication,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5072630732,James R. Hollyer,first,https://orcid.org/0000-0001-5896-816X,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
517412,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,dataset,funder,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,en,https://openalex.org/T11147,Misinformation and Its Impacts,https://openalex.org/subfields/3312,Sociology and Political Science,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5022408597,Emily K. Vraga,first,https://orcid.org/0000-0002-3016-3869,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
517418,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,funder,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
517564,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,funder,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,NaN,https://openalex.org/I130238516,University of Minnesota,"(Department of Applied Economics, University o...",US,https://ror.org/017zqws13,https://openalex.org/I130238516
517585,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,funder,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,NaN,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516

In [170]:
non_MN_df = df[df['institution_name'] != 'University of Minnesota']
non_MN_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,https://openalex.org/I79576946,University of Pennsylvania,"Psychology,University of Pennsylvania",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,dataset,funder,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,en,https://openalex.org/T12308,Mental Health and Psychiatry,https://openalex.org/subfields/1211,Philosophy,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5091505956,Jerome C. Wakefield,last,https://orcid.org/0000-0002-6809-5515,https://openalex.org/I57206974,New York University,"New York University, New York, NY, US",US,https://ror.org/0190ak572,https://openalex.org/I57206974
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,dataset,funder,Cognitive Therapy for Depression,1996,1996-01-01,en,https://openalex.org/T13272,Psychological Treatments and Assessments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5047792029,Aaron T. Beck,last,NaN,https://openalex.org/I79576946,University of Pennsylvania,"Department of Psychiatry, School of Medicine, ...",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517775,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5008503776,Ronald G. Ehrenberg,first,NaN,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517776,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5020341649,Michael L. Bognanno,last,NaN,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517777,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,funder,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5057810294,Ronald C. Kessler,first,https://orcid.org/0000-0003-4831-2305,https://openalex.org/I27837315,University of Michigan–Ann Arbor,"Institute for Social Research, University of M...",US,https://ror.org/00jmfr291,https://openalex.org/I27837315
517778,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,funder,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,True,green,NaN,https://openalex.org/A5013000614,Thomas A. Romberg,first,NaN,https://openalex.org/I79576946,University of Pennsylvania,University of Pennsylvania ScholarlyCommons,US,https://ror.org/00b30xv10,https://openalex.org/I79576946
517779,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,funder,"National Support for World Order, 1966",1984,1984-05-03,en,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5048046292,Robert C. Angell,first,NaN,https://openalex.org/I27837315,University of Michigan–Ann Arbor,Department of Sociology University of Michigan,US,https://ror.org/00jmfr291,https://openalex.org/I27837315

In [171]:
len(df), len(MN_df), len(non_MN_df), len(MN_df) + len(non_MN_df)

(501444, 1083, 500361, 501444)

In [172]:
funding_oa_status_df = oa_status(non_MN_df, 'funding_type', 'oa_status', 'green %')
funding_oa_status_df

oa_status,funding_type,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,funder,649.0,16442.0,47621.0,397.0,435242.0,500351.0,0.869873,0.000793,0.095175,0.032861,0.001297,hybrid
1,education,0.0,0.0,2.0,0.0,2.0,4.0,0.500000,0.000000,0.500000,0.000000,0.000000,hybrid
2,nonprofit,0.0,1.0,5.0,0.0,0.0,6.0,0.000000,0.000000,0.833333,0.166667,0.000000,gold

In [173]:
funding_oa_status_df = oa_status(MN_df, 'funding_type', 'oa_status', 'green %')
funding_oa_status_df

oa_status,funding_type,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,funder,33,347,686,9,8,1083,0.007387,0.00831,0.633426,0.320406,0.030471,gold

In [174]:
non_MN_df.head()

,id,doi,type,funding_type,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,https://openalex.org/I79576946,University of Pennsylvania,"Psychology,University of Pennsylvania",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,dataset,funder,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,en,https://openalex.org/T12308,Mental Health and Psychiatry,https://openalex.org/subfields/1211,Philosophy,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5091505956,Jerome C. Wakefield,last,https://orcid.org/0000-0002-6809-5515,https://openalex.org/I57206974,New York University,"New York University, New York, NY, US",US,https://ror.org/0190ak572,https://openalex.org/I57206974
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,dataset,funder,Cognitive Therapy for Depression,1996,1996-01-01,en,https://openalex.org/T13272,Psychological Treatments and Assessments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5047792029,Aaron T. Beck,last,NaN,https://openalex.org/I79576946,University of Pennsylvania,"Department of Psychiatry, School of Medicine, ...",US,https://ror.org/00b30xv10,https://openalex.org/I79576946

In [175]:
MN_oa_df = counts('field_name', 'is_oa', 'OA %', MN_df)
MN_oa_df

is_oa                                    field_name  False   True      OA %
8               Economics, Econometrics and Finance    0.0   36.0  1.000000
15                                      Mathematics    0.0    7.0  1.000000
3               Business, Management and Accounting    0.0   19.0  1.000000
6                                 Decision Sciences    0.0   17.0  1.000000
9                                            Energy    0.0    4.0  1.000000
1                               Arts and Humanities    0.0    4.0  1.000000
12                               Health Professions    0.0    1.0  1.000000
20                                  Social Sciences    2.0  117.0  0.983193
18                            Physics and Astronomy    6.0   77.0  0.927711
19                                       Psychology    1.0   10.0  0.909091
7                      Earth and Planetary Sciences    4.0   37.0  0.902439
4                                         Chemistry   12.0   34.0  0.739130
10                                      Engineering   20.0   54.0  0.729730
0              Agricultural and Biological Sciences    9.0   24.0  0.727273
14                                Materials Science    2.0    3.0  0.600000
16                                         Medicine   24.0   30.0  0.555556
13                      Immunology and Microbiology    1.0    1.0  0.500000
11                            Environmental Science   36.0   31.0  0.462687
2      Biochemistry, Genetics and Molecular Biology   45.0   22.0  0.328358
5                                  Computer Science  114.0   32.0  0.219178
17       Pharmacology, Toxicology and Pharmaceutics   34.0    0.0  0.000000
21                                       Veterinary    4.0    0.0  0.000000

In [176]:
x_oa_df = counts('field_name', 'is_oa', 'OA %', df)
x_oa_df

is_oa                                    field_name   False    True      OA %
20                                          Nursing     0.0    40.0  1.000000
8                                         Dentistry     0.0    94.0  1.000000
10              Economics, Econometrics and Finance     9.0  2279.0  0.996066
5                                         Chemistry    80.0  6237.0  0.987336
14                               Health Professions     6.0   405.0  0.985401
3               Business, Management and Accounting    22.0  1478.0  0.985333
24                                  Social Sciences   115.0  6725.0  0.983187
17                                      Mathematics    10.0   453.0  0.978402
7                                 Decision Sciences    48.0  2139.0  0.978052
15                      Immunology and Microbiology    17.0   510.0  0.967742
0              Agricultural and Biological Sciences   121.0  2919.0  0.960197
18                                         Medicine   310.0  7007.0  0.957633
2      Biochemistry, Genetics and Molecular Biology   360.0  8014.0  0.957010
16                                Materials Science   130.0  2564.0  0.951745
22                            Physics and Astronomy   405.0  7501.0  0.948773
21       Pharmacology, Toxicology and Pharmaceutics    37.0   560.0  0.938023
12                                      Engineering   422.0  6359.0  0.937767
6                                  Computer Science   403.0  5855.0  0.935602
11                                           Energy    16.0   160.0  0.909091
1                               Arts and Humanities    35.0   255.0  0.879310
23                                       Psychology    57.0   386.0  0.871332
4                              Chemical Engineering    25.0    98.0  0.796748
19                                     Neuroscience   117.0   365.0  0.757261
25                                       Veterinary     5.0    15.0  0.750000
13                            Environmental Science  3936.0  3021.0  0.434239
9                      Earth and Planetary Sciences  9100.0  1286.0  0.123821

In [177]:
oa_df_comp = pd.concat([MN_oa_df, x_oa_df], axis=1).reset_index()
oa_df_comp

is_oa,index,field_name,False,True,OA %,field_name,False,True,OA %
0,8,"Economics, Econometrics and Finance",0.0,36.0,1.000000,Dentistry,0.0,94.0,1.000000
1,15,Mathematics,0.0,7.0,1.000000,Immunology and Microbiology,17.0,510.0,0.967742
2,3,"Business, Management and Accounting",0.0,19.0,1.000000,"Business, Management and Accounting",22.0,1478.0,0.985333
3,6,Decision Sciences,0.0,17.0,1.000000,Computer Science,403.0,5855.0,0.935602
4,9,Energy,0.0,4.0,1.000000,Earth and Planetary Sciences,9100.0,1286.0,0.123821
5,1,Arts and Humanities,0.0,4.0,1.000000,Arts and Humanities,35.0,255.0,0.879310
6,12,Health Professions,0.0,1.0,1.000000,Engineering,422.0,6359.0,0.937767
7,20,Social Sciences,2.0,117.0,0.983193,Nursing,0.0,40.0,1.000000
8,18,Physics and Astronomy,6.0,77.0,0.927711,Medicine,310.0,7007.0,0.957633
9,19,Psychology,1.0,10.0,0.909091,Neuroscience,117.0,365.0,0.757261
10,7,Earth and Planetary Sciences,4.0,37.0,0.902439,Decision Sciences,48.0,2139.0,0.978052
11,4,Chemistry,12.0,34.0,0.739130,Chemical Engineering,25.0,98.0,0.796748
12,10,Engineering,20.0,54.0,0.729730,"Economics, Econometrics and Finance",9.0,2279.0,0.996066
13,0,Agricultural and Biological Sciences,9.0,24.0,0.727273,Agricultural and Biological Sciences,121.0,2919.0,0.960197
14,14,Materials Science,2.0,3.0,0.600000,Health Professions,6.0,405.0,0.985401
15,16,Medicine,24.0,30.0,0.555556,Materials Science,130.0,2564.0,0.951745
16,13,Immunology and Microbiology,1.0,1.0,0.500000,Environmental Science,3936.0,3021.0,0.434239
17,11,Environmental Science,36.0,31.0,0.462687,Energy,16.0,160.0,0.909091
18,2,"Biochemistry, Genetics and Molecular Biology",45.0,22.0,0.328358,"Biochemistry, Genetics and Molecular Biology",360.0,8014.0,0.957010
19,5,Computer Science,114.0,32.0,0.219178,Chemistry,80.0,6237.0,0.987336
20,17,"Pharmacology, Toxicology and Pharmaceutics",34.0,0.0,0.000000,Mathematics,10.0,453.0,0.978402
21,21,Veterinary,4.0,0.0,0.000000,"Pharmacology, Toxicology and Pharmaceutics",37.0,560.0,0.938023
22,24,NaN,NaN,NaN,NaN,Social Sciences,115.0,6725.0,0.983187
23,22,NaN,NaN,NaN,NaN,Physics and Astronomy,405.0,7501.0,0.948773
24,23,NaN,NaN,NaN,NaN,Psychology,57.0,386.0,0.871332
25,25,NaN,NaN,NaN,NaN,Veterinary,5.0,15.0,0.750000

In [178]:
pubyear_df = counts('publication_year', 'is_oa', 'OA %', df)
pubyear_df

is_oa  publication_year   False      True      OA %
17                 1997     0.0       7.0  1.000000
3                  1969     0.0       1.0  1.000000
4                  1972     0.0       1.0  1.000000
7                  1980     0.0       2.0  1.000000
8                  1982     0.0       2.0  1.000000
9                  1984     0.0       3.0  1.000000
1                  1960     0.0       1.0  1.000000
27                 2007     2.0     877.0  0.997725
42                 2022  9181.0  439093.0  0.979519
38                 2018   153.0    4222.0  0.965029
29                 2009    28.0     511.0  0.948052
28                 2008    19.0     301.0  0.940625
37                 2017    88.0    1304.0  0.936782
23                 2003     2.0      23.0  0.920000
32                 2012   117.0    1332.0  0.919255
39                 2019  1230.0   12806.0  0.912368
31                 2011    46.0     465.0  0.909980
40                 2020  1771.0   13567.0  0.884535
30                 2010    56.0     381.0  0.871854
33                 2013   102.0     655.0  0.865258
22                 2002     1.0       6.0  0.857143
43                 2023   907.0    4450.0  0.830689
36                 2016   194.0     871.0  0.817840
14                 1994     1.0       4.0  0.800000
35                 2015    75.0     280.0  0.788732
21                 2001     1.0       3.0  0.750000
20                 2000     3.0       7.0  0.700000
24                 2004     7.0      15.0  0.681818
2                  1967     1.0       2.0  0.666667
19                 1999     4.0       8.0  0.666667
26                 2006    15.0      30.0  0.666667
34                 2014    89.0     165.0  0.649606
16                 1996     3.0       4.0  0.571429
41                 2021  2388.0    3072.0  0.562637
15                 1995     1.0       1.0  0.500000
5                  1974     3.0       3.0  0.500000
44                 2024   274.0     169.0  0.381490
11                 1988     5.0       3.0  0.375000
25                 2005    12.0       6.0  0.333333
18                 1998     2.0       1.0  0.333333
0                  1955     1.0       0.0  0.000000
13                 1991     1.0       0.0  0.000000
12                 1990     1.0       0.0  0.000000
10                 1985     1.0       0.0  0.000000
6                  1975     1.0       0.0  0.000000
45                 2025     4.0       0.0  0.000000

In [179]:
inst_oa_status_df = oa_status(df, 'institution_name', 'oa_status', 'green %')
inst_oa_status_df

oa_status,institution_name,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,University of New Mexico,5.0,29.0,64.0,8.0,8.0,114.0,0.070175,0.070175,0.561404,0.254386,0.043860,gold
1,University of Pennsylvania,13.0,69.0,1793.0,67.0,8.0,1950.0,0.004103,0.034359,0.919487,0.035385,0.006667,gold
2,Virginia Tech,66.0,120.0,752.0,26.0,47.0,1011.0,0.046489,0.025717,0.743818,0.118694,0.065282,gold
3,University of Illinois Urbana-Champaign,25.0,354.0,1570.0,29.0,15.0,1993.0,0.007526,0.014551,0.787757,0.177622,0.012544,gold
4,University of Colorado Boulder,12.0,95.0,825.0,11.0,7.0,950.0,0.007368,0.011579,0.868421,0.100000,0.012632,gold
5,University of Minnesota,33.0,347.0,686.0,9.0,8.0,1083.0,0.007387,0.008310,0.633426,0.320406,0.030471,gold
6,University of Virginia,18.0,216.0,1748.0,14.0,1.0,1997.0,0.000501,0.007011,0.875313,0.108162,0.009014,gold
7,University of Nebraska–Lincoln,3.0,1774.0,701.0,17.0,3.0,2498.0,0.001201,0.006805,0.280624,0.710168,0.001201,closed
8,Duke University,125.0,2256.0,3382.0,42.0,565.0,6370.0,0.088697,0.006593,0.530926,0.354160,0.019623,gold
9,University of Wisconsin–Madison,26.0,2392.0,3354.0,32.0,34.0,5838.0,0.005824,0.005481,0.574512,0.409729,0.004454,gold
10,New York University,12.0,305.0,4061.0,20.0,12.0,4410.0,0.002721,0.004535,0.920862,0.069161,0.002721,gold
11,Princeton University,10.0,219.0,5511.0,24.0,23.0,5787.0,0.003974,0.004147,0.952307,0.037843,0.001728,gold
12,Pennsylvania State University,12.0,448.0,2867.0,13.0,206.0,3546.0,0.058094,0.003666,0.808517,0.126340,0.003384,gold
13,Cornell University,166.0,2332.0,7708.0,24.0,74.0,10304.0,0.007182,0.002329,0.748059,0.226320,0.016110,gold
14,Washington University in St. Louis,8.0,4835.0,2511.0,11.0,15.0,7380.0,0.002033,0.001491,0.340244,0.655149,0.001084,closed
15,University of Michigan–Ann Arbor,148.0,998.0,10776.0,59.0,434226.0,446207.0,0.973149,0.000132,0.024150,0.002237,0.000332,hybrid
16,Michael J. Fox Foundation,0.0,1.0,5.0,0.0,0.0,6.0,0.000000,0.000000,0.833333,0.166667,0.000000,gold

In [180]:
field_oa_status_df = oa_status(df,  'field_name', 'oa_status', 'green %')
field_oa_status_df

oa_status,field_name,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,Psychology,20.0,57.0,284.0,80.0,2.0,443.0,0.004515,0.180587,0.641084,0.128668,0.045147,gold
1,Nursing,1.0,0.0,35.0,4.0,0.0,40.0,0.000000,0.100000,0.875000,0.000000,0.025000,gold
2,Arts and Humanities,4.0,35.0,187.0,12.0,52.0,290.0,0.179310,0.041379,0.644828,0.120690,0.013793,gold
3,Immunology and Microbiology,2.0,17.0,273.0,16.0,219.0,527.0,0.415560,0.030361,0.518027,0.032258,0.003795,gold
4,Health Professions,1.0,6.0,246.0,11.0,147.0,411.0,0.357664,0.026764,0.598540,0.014599,0.002433,gold
5,Neuroscience,1.0,117.0,345.0,9.0,10.0,482.0,0.020747,0.018672,0.715768,0.242739,0.002075,gold
6,Social Sciences,22.0,115.0,5299.0,84.0,1320.0,6840.0,0.192982,0.012281,0.774708,0.016813,0.003216,gold
7,Decision Sciences,0.0,48.0,1062.0,22.0,1055.0,2187.0,0.482396,0.010059,0.485597,0.021948,0.000000,gold
8,Mathematics,1.0,10.0,447.0,3.0,2.0,463.0,0.004320,0.006479,0.965443,0.021598,0.002160,gold
9,Engineering,177.0,422.0,3219.0,30.0,2933.0,6781.0,0.432532,0.004424,0.474709,0.062233,0.026102,gold
10,Agricultural and Biological Sciences,8.0,121.0,1841.0,13.0,1057.0,3040.0,0.347697,0.004276,0.605592,0.039803,0.002632,gold
11,"Biochemistry, Genetics and Molecular Biology",40.0,360.0,4324.0,32.0,3618.0,8374.0,0.432052,0.003821,0.516360,0.042990,0.004777,gold
12,"Economics, Econometrics and Finance",1.0,9.0,1671.0,8.0,599.0,2288.0,0.261801,0.003497,0.730332,0.003934,0.000437,gold
13,Medicine,30.0,310.0,2660.0,20.0,4297.0,7317.0,0.587263,0.002733,0.363537,0.042367,0.004100,hybrid
14,Computer Science,27.0,403.0,3132.0,13.0,2683.0,6258.0,0.428731,0.002077,0.500479,0.064398,0.004314,gold
15,Physics and Astronomy,13.0,405.0,5554.0,12.0,1922.0,7906.0,0.243107,0.001518,0.702504,0.051227,0.001644,gold
16,Environmental Science,14.0,3936.0,2834.0,8.0,165.0,6957.0,0.023717,0.001150,0.407359,0.565761,0.002012,closed
17,Materials Science,72.0,130.0,447.0,3.0,2042.0,2694.0,0.757981,0.001114,0.165924,0.048255,0.026726,hybrid
18,Chemistry,60.0,80.0,1122.0,5.0,5050.0,6317.0,0.799430,0.000792,0.177616,0.012664,0.009498,hybrid
19,Earth and Planetary Sciences,7.0,9100.0,1237.0,7.0,35.0,10386.0,0.003370,0.000674,0.119103,0.876179,0.000674,closed
20,"Business, Management and Accounting",2.0,22.0,783.0,1.0,692.0,1500.0,0.461333,0.000667,0.522000,0.014667,0.001333,gold
21,Energy,0.0,16.0,153.0,0.0,7.0,176.0,0.039773,0.000000,0.869318,0.090909,0.000000,gold
22,Dentistry,0.0,0.0,94.0,0.0,0.0,94.0,0.000000,0.000000,1.000000,0.000000,0.000000,gold
23,"Pharmacology, Toxicology and Pharmaceutics",2.0,37.0,45.0,0.0,513.0,597.0,0.859296,0.000000,0.075377,0.061977,0.003350,hybrid
24,Chemical Engineering,5.0,25.0,21.0,0.0,72.0,123.0,0.585366,0.000000,0.170732,0.203252,0.040650,hybrid
25,Veterinary,2.0,5.0,9.0,0.0,4.0,20.0,0.200000,0.000000,0.450000,0.250000,0.100000,gold

In [182]:
license_oa_status_df = oa_status(df,  'license', 'oa_status', 'gold %')
license_oa_status_df

oa_status,license,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,cc-by-nd,0.0,0.0,4.0,0.0,0.0,4.0,0.000000,0.000000,1.000000,0.000000,0.00000,gold
1,other-oa,0.0,29.0,31883.0,9.0,3.0,31924.0,0.000094,0.000282,0.998716,0.000908,0.00000,gold
2,cc-by-sa,0.0,1.0,48.0,0.0,0.0,49.0,0.000000,0.000000,0.979592,0.020408,0.00000,gold
3,gpl-v3,0.0,3.0,60.0,0.0,0.0,63.0,0.000000,0.000000,0.952381,0.047619,0.00000,gold
4,mit,0.0,10.0,66.0,0.0,8.0,84.0,0.095238,0.000000,0.785714,0.119048,0.00000,gold
5,cc-by-nc-nd,0.0,12.0,24.0,0.0,1.0,37.0,0.027027,0.000000,0.648649,0.324324,0.00000,gold
6,cc-by-nc,0.0,1.0,92.0,0.0,71.0,164.0,0.432927,0.000000,0.560976,0.006098,0.00000,gold
7,cc-by-nc-sa,0.0,18.0,11.0,0.0,1.0,30.0,0.033333,0.000000,0.366667,0.600000,0.00000,closed
8,apache-2-0,0.0,11.0,5.0,0.0,0.0,16.0,0.000000,0.000000,0.312500,0.687500,0.00000,closed
9,cc-by,9.0,838.0,15920.0,19.0,435062.0,451848.0,0.962850,0.000042,0.035233,0.001855,0.00002,hybrid
10,public-domain,0.0,0.0,0.0,0.0,1.0,1.0,1.000000,0.000000,0.000000,0.000000,0.00000,hybrid

In [183]:
index_oa_status_df = oa_status(df, 'index location', 'oa_status', 'green %')
index_oa_status_df

oa_status,index location,bronze,closed,gold,green,hybrid,total,hybrid %,green %,gold %,closed %,bronze %,Most used OA type
0,arxiv,0.0,0.0,0.0,13.0,0.0,13.0,0.000000,1.000000,0.000000,0.000000,0.000000,green
1,crossref,673.0,1994.0,0.0,349.0,435249.0,438265.0,0.993118,0.000796,0.000000,0.004550,0.001536,hybrid
2,datacite,9.0,1555.0,48314.0,21.0,3.0,49902.0,0.000060,0.000421,0.968178,0.031161,0.000180,gold

In [ ]:
Michigan_df = df[df['institution_name'] == 'University of Michigan–Ann Arbor']
#ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572')]
Michigan_df.head(25)

In [ ]:
Michigan_df

In [ ]:
Michigan_df = Michigan_df.groupby(['institution_name', 'field_name']).size().sort_values(ascending=False) #/len(Michigan_df)
Michigan_df.head(25)