In [32]:
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv('3-16-UMN-Source-Data-Download.csv', index_col=0)

C:\Users\wieke\AppData\Local\Temp\ipykernel_4800\155771855.py:1: DtypeWarning: Columns (8,12,13) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('3-18-UMN-Source-API.csv', index_col=0)

In [41]:
len(df)

517786

In [38]:
pd.set_option("display.max_columns", 55)

In [39]:
df.head()

,authorships.author.display_name,authorships.author.id,authorships.author.orcid,authorships.countries,authorships.institutions.display_name,authorships.institutions.id,authorships.is_corresponding,best_oa_location.license,cited_by_count,corresponding_institution_ids,display_name,doi,funders.display_name,fwci,is_retracted,language,open_access.is_oa,open_access.oa_status,primary_location.source.display_name,primary_location.source.id,primary_location.source.issn_l,primary_location.source.type,primary_topic.display_name,publication_date,publication_year,type
id,,,,,,,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W3081810959,Aleksandr V. Marenich|Casey P. Kelly|Jason D. ...,https://openalex.org/A5061017744|https://opena...,https://orcid.org/0000-0003-0288-843X||https:/...,|||||||US|US,|||||||University of Minnesota System|Universi...,|||||||https://openalex.org/I2800403580|https:...,True|False|False|False|False|False|False|False...,cc-by-nc-nd,41,NaN,Minnesota Solvation Database (MNSOL) version 2012,https://doi.org/10.13020/3eks-j059,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Geochemistry and Geologic Mapping,1998-01-01,1998,dataset
https://openalex.org/W2297941261,Brian F. Walters|Christopher W. Woodall|Matthe...,https://openalex.org/A5014726860|https://opena...,https://orcid.org/0000-0001-7408-9704|https://...,||,NaN,NaN,True|False|False,cc-by-sa,28,NaN,White-tailed deer density estimates across the...,https://doi.org/10.13020/d6g014,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Wildlife Ecology and Conservation,2016-01-01,2016,dataset
https://openalex.org/W2898833073,Daniel Ackerman,https://openalex.org/A5031063931,https://orcid.org/0000-0002-9305-4184,NaN,NaN,NaN,True,NaN,17,NaN,Global nitrogen deposition (2°×2.5° grid resol...,https://doi.org/10.13020/d6kx2r,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Atmospheric and Environmental Gas Dynamics,2018-01-01,2018,dataset
https://openalex.org/W2525336510,Lian P. Rampi,https://openalex.org/A5077086878,NaN,NaN,NaN,NaN,True,public-domain,12,NaN,Minnesota Land Cover Classification and Imperv...,https://doi.org/10.13020/d6jp4s,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Rangeland and Wildlife Management,2016-01-01,2016,dataset
https://openalex.org/W3043928535,Jungseok Hong|Michael Fulton|Junaed Sattar,https://openalex.org/A5110745295|https://opena...,|https://orcid.org/0000-0003-1842-6045|https:/...,||,NaN,NaN,True|False|False,NaN,12,NaN,TrashCan 1.0 An Instance-Segmentation Labeled ...,https://doi.org/10.13020/g1gx-y834,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Electron and X-Ray Spectroscopy Techniques,2019-06-24,2019,dataset

In [37]:
t = pd.json_normalize(df['authorships.author.display_name'])
t

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[729 rows x 0 columns]

In [17]:
df.columns

Index(['authorships.author.display_name', 'authorships.author.id',
       'authorships.author.orcid', 'authorships.countries',
       'authorships.institutions.display_name', 'authorships.institutions.id',
       'authorships.is_corresponding', 'best_oa_location.license',
       'cited_by_count', 'corresponding_institution_ids', 'display_name',
       'doi', 'funders.display_name', 'fwci', 'is_retracted', 'language',
       'open_access.is_oa', 'open_access.oa_status',
       'primary_location.source.display_name', 'primary_location.source.id',
       'primary_location.source.issn_l', 'primary_location.source.type',
       'primary_topic.display_name', 'publication_date', 'publication_year',
       'type'],
      dtype='object')

In [30]:
df = df.rename(columns={'authorships.author.display_name': 'id', 'authorships.countries	': 'countries'})

In [31]:
df

,id,authorships.author.id,authorships.author.orcid,authorships.countries,authorships.institutions.display_name,authorships.institutions.id,authorships.is_corresponding,best_oa_location.license,cited_by_count,corresponding_institution_ids,display_name,doi,funders.display_name,fwci,is_retracted,language,open_access.is_oa,open_access.oa_status,primary_location.source.display_name,primary_location.source.id,primary_location.source.issn_l,primary_location.source.type,primary_topic.display_name,publication_date,publication_year,type
id,,,,,,,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W3081810959,Aleksandr V. Marenich|Casey P. Kelly|Jason D. ...,https://openalex.org/A5061017744|https://opena...,https://orcid.org/0000-0003-0288-843X||https:/...,|||||||US|US,|||||||University of Minnesota System|Universi...,|||||||https://openalex.org/I2800403580|https:...,True|False|False|False|False|False|False|False...,cc-by-nc-nd,41,NaN,Minnesota Solvation Database (MNSOL) version 2012,https://doi.org/10.13020/3eks-j059,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Geochemistry and Geologic Mapping,1998-01-01,1998,dataset
https://openalex.org/W2297941261,Brian F. Walters|Christopher W. Woodall|Matthe...,https://openalex.org/A5014726860|https://opena...,https://orcid.org/0000-0001-7408-9704|https://...,||,NaN,NaN,True|False|False,cc-by-sa,28,NaN,White-tailed deer density estimates across the...,https://doi.org/10.13020/d6g014,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Wildlife Ecology and Conservation,2016-01-01,2016,dataset
https://openalex.org/W2898833073,Daniel Ackerman,https://openalex.org/A5031063931,https://orcid.org/0000-0002-9305-4184,NaN,NaN,NaN,True,NaN,17,NaN,Global nitrogen deposition (2°×2.5° grid resol...,https://doi.org/10.13020/d6kx2r,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Atmospheric and Environmental Gas Dynamics,2018-01-01,2018,dataset
https://openalex.org/W2525336510,Lian P. Rampi,https://openalex.org/A5077086878,NaN,NaN,NaN,NaN,True,public-domain,12,NaN,Minnesota Land Cover Classification and Imperv...,https://doi.org/10.13020/d6jp4s,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Rangeland and Wildlife Management,2016-01-01,2016,dataset
https://openalex.org/W3043928535,Jungseok Hong|Michael Fulton|Junaed Sattar,https://openalex.org/A5110745295|https://opena...,|https://orcid.org/0000-0003-1842-6045|https:/...,||,NaN,NaN,True|False|False,NaN,12,NaN,TrashCan 1.0 An Instance-Segmentation Labeled ...,https://doi.org/10.13020/g1gx-y834,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Electron and X-Ray Spectroscopy Techniques,2019-06-24,2019,dataset
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
https://openalex.org/W7135383485,Peter V Kelly|Alison Block|Brenden D. Hoehn|Pa...,https://openalex.org/A5129287127|https://opena...,|https://orcid.org/0000-0001-9196-462X|https:/...,US|US|US|US|US|US,University of Minnesota System|University of M...,https://openalex.org/I2800403580|https://opena...,True|False|False|False|False|False,public-domain,0,https://openalex.org/I2800403580,Polyhydroxyalkanoate block-polymer adhesives d...,https://doi.org/10.13020/z7az-ra35,NaN,NaN,False,NaN,True,green,Data Repository for the University of Minnesota,https://openalex.org/S7407053140,NaN,repository,NaN,2026-01-01,2026,dataset
https://openalex.org/W7135717134,"Hall, Victoria L|Cardona, Carol|Mendoza, Kris...",||||||,||||||,||||||,NaN,NaN,True|False|False|False|False|False|False,cc-by,0,NaN,Surveillance for highly pathogenic avian influ...,NaN,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,NaN,2024-03-11,2024,dataset
https://openalex.org/W830385225,G.N. Meyer,https://openalex.org/A5052355904,NaN,NaN,NaN,NaN,True,NaN,0,NaN,"C-35, Geologic Atlas of Meeker County, Minneso...",NaN,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Archaeology and Natural History,2015-01-01,2015,dataset
https://openalex.org/W89491114,Zongxuan Sun,https://openalex.org/A5010750676,https://orcid.org/0000-0001-9929-4085,NaN,NaN,NaN,True,NaN,0,NaN,Tracking of references with varying frequency,NaN,NaN,NaN,False,en,False,closed,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Speech and dialogue systems,2014-09-30,2014,dataset
https://openalex.org/W925720530,Christopher Brink|Benjamin Gosack|Len Kne|Yuan...,https://openalex.org/A5043005748|https://opena...,||||https://orcid.org/0000-0002-7129-9367||htt...,||||||||||||,NaN,NaN,True|False|False|False|False|False|False|False...,cc-by,0,NaN,"Solar Insolation, Minnesota (2006-2012)",https://doi.org/10.13020/d6x59x,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Solar Radiation and Photovoltaics,2015-06-29,2015,dataset

In [ ]:
['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location', 'is_oa', 'oa_status',
       'license', 'Repository', 'author_id', 'author_name', 'orcid',
       'institution_id', 'institution_name', 'ror', 'country_code',
       'funding_type', 'lineage', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name']

In [18]:
df.head()

,authorships.author.display_name,authorships.author.id,authorships.author.orcid,authorships.countries,authorships.institutions.display_name,authorships.institutions.id,authorships.is_corresponding,best_oa_location.license,cited_by_count,corresponding_institution_ids,display_name,doi,funders.display_name,fwci,is_retracted,language,open_access.is_oa,open_access.oa_status,primary_location.source.display_name,primary_location.source.id,primary_location.source.issn_l,primary_location.source.type,primary_topic.display_name,publication_date,publication_year,type
id,,,,,,,,,,,,,,,,,,,,,,,,,,
https://openalex.org/W3081810959,Aleksandr V. Marenich|Casey P. Kelly|Jason D. ...,https://openalex.org/A5061017744|https://opena...,https://orcid.org/0000-0003-0288-843X||https:/...,|||||||US|US,|||||||University of Minnesota System|Universi...,|||||||https://openalex.org/I2800403580|https:...,True|False|False|False|False|False|False|False...,cc-by-nc-nd,41,NaN,Minnesota Solvation Database (MNSOL) version 2012,https://doi.org/10.13020/3eks-j059,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Geochemistry and Geologic Mapping,1998-01-01,1998,dataset
https://openalex.org/W2297941261,Brian F. Walters|Christopher W. Woodall|Matthe...,https://openalex.org/A5014726860|https://opena...,https://orcid.org/0000-0001-7408-9704|https://...,||,NaN,NaN,True|False|False,cc-by-sa,28,NaN,White-tailed deer density estimates across the...,https://doi.org/10.13020/d6g014,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Wildlife Ecology and Conservation,2016-01-01,2016,dataset
https://openalex.org/W2898833073,Daniel Ackerman,https://openalex.org/A5031063931,https://orcid.org/0000-0002-9305-4184,NaN,NaN,NaN,True,NaN,17,NaN,Global nitrogen deposition (2°×2.5° grid resol...,https://doi.org/10.13020/d6kx2r,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Atmospheric and Environmental Gas Dynamics,2018-01-01,2018,dataset
https://openalex.org/W2525336510,Lian P. Rampi,https://openalex.org/A5077086878,NaN,NaN,NaN,NaN,True,public-domain,12,NaN,Minnesota Land Cover Classification and Imperv...,https://doi.org/10.13020/d6jp4s,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Rangeland and Wildlife Management,2016-01-01,2016,dataset
https://openalex.org/W3043928535,Jungseok Hong|Michael Fulton|Junaed Sattar,https://openalex.org/A5110745295|https://opena...,|https://orcid.org/0000-0003-1842-6045|https:/...,||,NaN,NaN,True|False|False,NaN,12,NaN,TrashCan 1.0 An Instance-Segmentation Labeled ...,https://doi.org/10.13020/g1gx-y834,NaN,NaN,False,en,True,green,University of Minnesota Digital Conservancy (U...,https://openalex.org/S4306402521,NaN,repository,Electron and X-Ray Spectroscopy Techniques,2019-06-24,2019,dataset