In [90]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('OpenAlexData.csv', index_col=0)

C:\Users\wieke\AppData\Local\Temp\ipykernel_20640\2055085896.py:1: DtypeWarning: Columns (6,24) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('OpenAlexData.csv', index_col=0)

In [3]:
pd.set_option("display.max_columns", 55)

In [4]:
df

,id,doi,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,instiution_id,institution_name,type,country_code,ror,lineage,raw_affiliation_string,afilliation_lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,https://openalex.org/I79576946,University of Pennsylvania,education,US,https://ror.org/00b30xv10,https://openalex.org/I79576946,"Psychology,University of Pennsylvania",https://openalex.org/I79576946
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,https://openalex.org/I114395901,University of Nebraska–Lincoln,education,US,https://ror.org/043mer456,https://openalex.org/I114395901,University of Nebraska— Lincoln,https://openalex.org/I114395901
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,https://openalex.org/I114395901,University of Nebraska–Lincoln,education,US,https://ror.org/043mer456,https://openalex.org/I114395901,University of Nebraska— Lincoln,https://openalex.org/I114395901
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,en,https://openalex.org/T12308,Mental Health and Psychiatry,https://openalex.org/subfields/1211,Philosophy,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5091505956,Jerome C. Wakefield,last,https://orcid.org/0000-0002-6809-5515,https://openalex.org/I57206974,New York University,education,US,https://ror.org/0190ak572,https://openalex.org/I57206974,"New York University, New York, NY, US",https://openalex.org/I57206974
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,Cognitive Therapy for Depression,1996,1996-01-01,en,https://openalex.org/T13272,Psychological Treatments and Assessments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5047792029,Aaron T. Beck,last,NaN,https://openalex.org/I79576946,University of Pennsylvania,education,US,https://ror.org/00b30xv10,https://openalex.org/I79576946,"Department of Psychiatry, School of Medicine, ...",https://openalex.org/I79576946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517779,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5008503776,Ronald G. Ehrenberg,first,NaN,https://openalex.org/I205783295,Cornell University,education,US,https://ror.org/05bnh6r87,https://openalex.org/I205783295,NaN,NaN
517780,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5020341649,Michael L. Bognanno,last,NaN,https://openalex.org/I205783295,Cornell University,education,US,https://ror.org/05bnh6r87,https://openalex.org/I205783295,NaN,NaN
517781,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,NaN,https://openalex.org/A5057810294,Ronald C. Kessler,first,https://orcid.org/0000-0003-4831-2305,https://openalex.org/I27837315,University of Michigan–Ann Arbor,education,US,https://ror.org/00jmfr291,https://openalex.org/I27837315,NaN,NaN
517782,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,True,green,NaN,https://openalex.org/A5013000614,Thomas A. Romberg,first,NaN,https://openalex.org/I79576946,University of Pennsylvania,education,US,https://ror.org/00b30xv10,https://openalex.org/I79576946,NaN,NaN
517783,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,"National Support for World Order, 1966",1984,1984-05-03,en,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,NaN,https://openalex.org/A5048046292,Robert C. Angell,first,NaN,https://openalex.org/I27837315,University of Michigan–Ann Arbor,education,US,https://ror.org/00jmfr291,https://openalex.org/I27837315,NaN,NaN

In [89]:
df['oa_status'].value_counts()

oa_status
hybrid    435283
gold       48316
closed     29044
bronze      4735
green        406
Name: count, dtype: int64

In [70]:
df['Repository'].unique()

array(['PsycEXTRA Dataset', 'Harvard Dataverse',
       'Global Biodiversity Information Facility',
       'Artifact Digital Object Group', 'Figshare',
       'Zenodo (CERN European Organization for Nuclear Research)', nan,
       'The SHAFR Guide Online',
       'Carbon Dioxide Information Analysis Center (CDIAC) Datasets',
       'IUPAC Standards Online', 'AEA Randomized Controlled Trials',
       'immuneACCESS',
       'Pancreapedia: The Exocrine Pancreas Knowledge Base',
       'ICPSR Data Holdings', 'Forest Service Research Data Archive',
       'OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)',
       'PsycTESTS Dataset',
       'Faculty Opinions – Post-Publication Peer Review of the Biomedical Literature',
       'Authorea', 'nano Online', 'Human Rights Documents online',
       'ENCODE Datasets', 'The Winnower',
       'Biological and Chemical Oceanography Data Management Office',
       'energyo', 'EcoSal',
       'APS Division of Plasma Physics Meeting Abstracts',
       'Default Digital Object Group', 'SciVee', 'Radiographics',
       'Oxford Bibliographies Online Datasets', 'Access Science',
       'Inactive DOIs',
       'F1000 - Post-publication peer review of the biomedical literature',
       'Wolfram Demonstrations Project', 'PMC',
       'Research Data Repository, Duke University', 'Radiology'],
      dtype=object)

In [5]:
field_name_df = df.groupby('field_name').size().sort_values(ascending=False)
field_name_df.head(25)

field_name
Biochemistry, Genetics and Molecular Biology    13605
Medicine                                        12700
Earth and Planetary Sciences                    10428
Physics and Astronomy                            7969
Environmental Science                            7407
Engineering                                      7179
Social Sciences                                  7093
Chemistry                                        6637
Computer Science                                 6413
Agricultural and Biological Sciences             4110
Materials Science                                2762
Economics, Econometrics and Finance              2317
Decision Sciences                                2229
Neuroscience                                     1533
Business, Management and Accounting              1524
Immunology and Microbiology                      1288
Psychology                                        839
Health Professions                                670
Pharmacology, Toxicology and Pharmaceutics        657
Mathematics                                       483
Arts and Humanities                               330
Energy                                            216
Nursing                                           148
Chemical Engineering                              133
Dentistry                                         108
dtype: int64

In [68]:
domain_df = df.groupby(['domain_name', 'institution_name']).size().sort_values(ascending=False)
domain_df.head(25)

domain_name        institution_name
Physical Sciences  University of Michigan–Ann Arbor           18441
Life Sciences      University of Michigan–Ann Arbor            9480
Physical Sciences  Cornell University                          7522
Health Sciences    University of Michigan–Ann Arbor            6087
Physical Sciences  Washington University in St. Louis          5352
Social Sciences    University of Michigan–Ann Arbor            5283
Physical Sciences  University of Wisconsin–Madison             4094
                   Duke University                             3133
                   Princeton University                        2276
                   University of Nebraska–Lincoln              1919
Life Sciences      Cornell University                          1649
Physical Sciences  Pennsylvania State University               1627
Social Sciences    New York University                         1348
Physical Sciences  New York University                         1315
Social Sciences    Princeton University                        1301
Physical Sciences  University of Illinois Urbana-Champaign     1191
Life Sciences      University of Wisconsin–Madison             1184
                   Duke University                             1133
                   University of Illinois Urbana-Champaign     1110
Social Sciences    Duke University                             1097
Health Sciences    Cornell University                          1075
                   University of Wisconsin–Madison              929
Life Sciences      University of Minnesota                      924
Health Sciences    Duke University                              916
Life Sciences      New York University                          897
dtype: int64

In [7]:
inst_domain_df = df.groupby(['institution_name', 'domain_name']).size().sort_values(ascending=False)
inst_domain_df.head(50)

institution_name                         domain_name
University of Michigan–Ann Arbor         Physical Sciences    18441
                                         Life Sciences         9480
Cornell University                       Physical Sciences     7522
University of Michigan–Ann Arbor         Health Sciences       6087
Washington University in St. Louis       Physical Sciences     5352
University of Michigan–Ann Arbor         Social Sciences       5283
University of Wisconsin–Madison          Physical Sciences     4094
Duke University                          Physical Sciences     3133
Princeton University                     Physical Sciences     2276
University of Nebraska–Lincoln           Physical Sciences     1919
Cornell University                       Life Sciences         1649
Pennsylvania State University            Physical Sciences     1627
New York University                      Social Sciences       1348
                                         Physical Sciences     1315
Princeton University                     Social Sciences       1301
University of Illinois Urbana-Champaign  Physical Sciences     1191
University of Wisconsin–Madison          Life Sciences         1184
Duke University                          Life Sciences         1133
University of Illinois Urbana-Champaign  Life Sciences         1110
Duke University                          Social Sciences       1097
Cornell University                       Health Sciences       1075
University of Wisconsin–Madison          Health Sciences        929
University of Minnesota                  Life Sciences          924
Duke University                          Health Sciences        916
New York University                      Life Sciences          897
University of Pennsylvania               Health Sciences        889
University of Virginia                   Life Sciences          876
Cornell University                       Social Sciences        865
Washington University in St. Louis       Social Sciences        762
Pennsylvania State University            Social Sciences        755
Princeton University                     Life Sciences          743
University of Pennsylvania               Social Sciences        715
Pennsylvania State University            Life Sciences          701
University of Pennsylvania               Life Sciences          699
Washington University in St. Louis       Health Sciences        642
University of Virginia                   Physical Sciences      636
Washington University in St. Louis       Life Sciences          618
University of Minnesota                  Physical Sciences      606
University of Virginia                   Social Sciences        603
New York University                      Health Sciences        571
University of Minnesota                  Health Sciences        544
University of Virginia                   Health Sciences        541
Virginia Tech                            Physical Sciences      535
University of Pennsylvania               Physical Sciences      502
University of Wisconsin–Madison          Social Sciences        484
University of Nebraska–Lincoln           Life Sciences          414
Princeton University                     Health Sciences        403
University of Colorado Boulder           Life Sciences          382
                                         Physical Sciences      380
Pennsylvania State University            Health Sciences        341
dtype: int64

In [14]:
oa_count_df = df.groupby(['institution_name', 'is_oa']).size().sort_values(ascending=False)
oa_count_df.head(25)

institution_name                         is_oa
University of Michigan–Ann Arbor         True     445928
Cornell University                       True       8326
Princeton University                     True       5720
Washington University in St. Louis       False      5264
Duke University                          True       4463
New York University                      True       4344
University of Wisconsin–Madison          True       3773
                                         False      3558
Cornell University                       False      3547
Duke University                          False      3389
Pennsylvania State University            True       3267
University of Michigan–Ann Arbor         False      2834
Washington University in St. Louis       True       2733
University of Pennsylvania               True       2217
University of Virginia                   True       2100
University of Illinois Urbana-Champaign  True       1967
University of Nebraska–Lincoln           False      1856
University of Minnesota                  False      1432
University of Illinois Urbana-Champaign  False      1333
University of Pennsylvania               False      1158
University of Minnesota                  True       1119
New York University                      False      1092
University of Virginia                   False      1019
University of Colorado Boulder           True        956
Pennsylvania State University            False       933
dtype: int64

In [ ]:
oa_count_df = df.groupby(['institution_name'])['is_oa'].value_counts().unstack('is_oa').reset_index()
oa_count_df

is_oa                                    False   True
institution_name
Cornell University                        3547    8326
Duke University                           3389    4463
Michael J. Fox Foundation                    1       5
New York University                       1092    4344
Pennsylvania State University              933    3267
Princeton University                       711    5720
University of Colorado Boulder             475     956
University of Illinois Urbana-Champaign   1333    1967
University of Michigan–Ann Arbor          2834  445928
University of Minnesota                   1432    1119
University of Nebraska–Lincoln            1856     767
University of New Mexico                   272     148
University of Pennsylvania                1158    2217
University of Virginia                    1019    2100
University of Wisconsin–Madison           3558    3773
Virginia Tech                              170     907
Washington University in St. Louis        5264    2733

In [71]:
df['Repository'].value_counts()

Repository
ENCODE Datasets                                                                        435461
Harvard Dataverse                                                                       30117
Zenodo (CERN European Organization for Nuclear Research)                                16803
Faculty Opinions – Post-Publication Peer Review of the Biomedical Literature            16336
OSTI OAI (U.S. Department of Energy Office of Scientific and Technical Information)     13258
Figshare                                                                                 2975
IUPAC Standards Online                                                                    915
Default Digital Object Group                                                              579
PsycEXTRA Dataset                                                                         370
Authorea                                                                                  102
Artifact Digital Object Group                                                             101
energyo                                                                                    85
Pancreapedia: The Exocrine Pancreas Knowledge Base                                         71
Biological and Chemical Oceanography Data Management Office                                69
AEA Randomized Controlled Trials                                                           51
Forest Service Research Data Archive                                                       40
The SHAFR Guide Online                                                                     27
Radiology                                                                                  25
immuneACCESS                                                                               23
SciVee                                                                                     21
Global Biodiversity Information Facility                                                   18
ICPSR Data Holdings                                                                        12
Radiographics                                                                              12
The Winnower                                                                               11
Carbon Dioxide Information Analysis Center (CDIAC) Datasets                                 9
Human Rights Documents online                                                               8
PsycTESTS Dataset                                                                           7
PMC                                                                                         5
Research Data Repository, Duke University                                                   5
EcoSal                                                                                      4
Access Science                                                                              4
Inactive DOIs                                                                               4
nano Online                                                                                 3
APS Division of Plasma Physics Meeting Abstracts                                            2
Oxford Bibliographies Online Datasets                                                       2
F1000 - Post-publication peer review of the biomedical literature                           1
Wolfram Demonstrations Project                                                              1
Name: count, dtype: int64

In [53]:
oa_count_s = df.groupby(['institution_name'])['is_oa'].value_counts().unstack('is_oa').reset_index()
oa_count_s['OA %'] = oa_count_s[True] / (oa_count_s[False] + oa_count_s[True])
#oa_count_s
oa_count_s.sort_values(by=['OA %'], ascending=False)

is_oa                         institution_name  False    True      OA %
8             University of Michigan–Ann Arbor   2834  445928  0.993685
5                         Princeton University    711    5720  0.889442
15                               Virginia Tech    170     907  0.842154
2                    Michael J. Fox Foundation      1       5  0.833333
3                          New York University   1092    4344  0.799117
4                Pennsylvania State University    933    3267  0.777857
0                           Cornell University   3547    8326  0.701255
13                      University of Virginia   1019    2100  0.673293
6               University of Colorado Boulder    475     956  0.668064
12                  University of Pennsylvania   1158    2217  0.656889
7      University of Illinois Urbana-Champaign   1333    1967  0.596061
1                              Duke University   3389    4463  0.568390
14             University of Wisconsin–Madison   3558    3773  0.514664
9                      University of Minnesota   1432    1119  0.438652
11                    University of New Mexico    272     148  0.352381
16          Washington University in St. Louis   5264    2733  0.341753
10              University of Nebraska–Lincoln   1856     767  0.292413

In [83]:
def counts(col1, col2, col3, df):
    oa_count_s = df.groupby([col1])[col2].value_counts().unstack(col2).reset_index()
    oa_count_s[col3] = oa_count_s[True] / (oa_count_s[False] + oa_count_s[True])
    oa_count_s
    return oa_count_s.sort_values(by=[col3], ascending=False)

In [65]:
field_oa_df = counts('field_name', 'is_oa', 'OA %')
field_oa_df

is_oa                                    field_name  False  True      OA %
10              Economics, Econometrics and Finance     32  2285  0.986189
3               Business, Management and Accounting     45  1479  0.970472
7                                 Decision Sciences     75  2154  0.966353
17                                      Mathematics     22   461  0.954451
24                                  Social Sciences    324  6769  0.954321
5                                         Chemistry    338  6299  0.949073
22                            Physics and Astronomy    451  7518  0.943406
16                                Materials Science    175  2587  0.936640
6                                  Computer Science    521  5892  0.918759
12                                      Engineering    719  6460  0.899847
8                                         Dentistry     12    96  0.888889
21       Pharmacology, Toxicology and Pharmaceutics     82   575  0.875190
1                               Arts and Humanities     69   261  0.790909
11                                           Energy     46   170  0.787037
0              Agricultural and Biological Sciences    955  3155  0.767640
4                              Chemical Engineering     32   101  0.759398
2      Biochemistry, Genetics and Molecular Biology   4064  9541  0.701286
14                               Health Professions    207   463  0.691045
18                                         Medicine   4500  8200  0.645669
23                                       Psychology    357   482  0.574493
15                      Immunology and Microbiology    561   727  0.564441
20                                          Nursing     81    67  0.452703
25                                       Veterinary     24    18  0.428571
19                                     Neuroscience    881   652  0.425310
13                            Environmental Science   4309  3098  0.418253
9                      Earth and Planetary Sciences   9136  1292  0.123897

In [ ]:
domain_oa_df = counts('domain_name', 'is_oa', 'OA %')
domain_oa_df

is_oa        domain_name  False   True      OA %
3        Social Sciences    902  13430  0.937064
1          Life Sciences   6543  14650  0.691266
2      Physical Sciences  15749  33878  0.682653
0        Health Sciences   4824   8844  0.647059

In [74]:
subfield_name_df = counts('subfield_name', 'is_oa', 'OA %')
subfield_name_df.head(25)

is_oa                                  subfield_name  False    True      OA %
146                                Metals and Alloys    1.0   423.0  0.997642
96                         General Materials Science    3.0  1173.0  0.997449
93       General Economics, Econometrics and Finance    1.0   191.0  0.994792
124                              Inorganic Chemistry   19.0  2521.0  0.992520
84                                           Finance    1.0   129.0  0.992308
6                               Analytical Chemistry    3.0   309.0  0.990385
215                          Strategy and Management    6.0   588.0  0.989899
214          Statistics, Probability and Uncertainty   14.0  1167.0  0.988146
185    Political Science and International Relations   25.0  1937.0  0.987258
52           Computer Vision and Pattern Recognition    4.0   295.0  0.986622
134                   Management Information Systems   10.0   680.0  0.985507
68                        Economics and Econometrics   30.0  1965.0  0.984962
50              Computer Networks and Communications   37.0  2020.0  0.982013
130                                              Law    3.0   147.0  0.980000
190                            Public Administration    1.0    45.0  0.978261
129                         Language and Linguistics    2.0    79.0  0.975309
193                                        Radiation   50.0  1911.0  0.974503
44                                     Communication   11.0   415.0  0.974178
148                          Modeling and Simulation    3.0   100.0  0.970874
167                                Organic Chemistry   86.0  2811.0  0.970314
207                  Sociology and Political Science  101.0  2870.0  0.966005
213                       Statistics and Probability   11.0   303.0  0.964968
7                                            Anatomy   19.0   508.0  0.963947
28                                        Biophysics   43.0  1049.0  0.960623
54                   Control and Systems Engineering   14.0   336.0  0.960000

In [75]:
topic_name_df = counts('topic_name', 'is_oa', 'OA %')
topic_name_df.head(25)

is_oa,topic_name,False,True,OA %
1440,Inorganic and Organometallic Chemistry,1.0,963.0,0.998963
2439,Sensor Technology and Measurement Systems,2.0,1724.0,0.998841
1439,Inorganic Fluorides and Related Compounds,3.0,2369.0,0.998735
870,Electoral Systems and Political Participation,1.0,736.0,0.998643
455,Cardiac tumors and thrombi,1.0,697.0,0.998567
1653,Material Properties and Applications,2.0,1142.0,0.998252
1352,Hydrogen embrittlement and corrosion behaviors...,1.0,423.0,0.997642
2258,Pulsars and Gravitational Waves Research,8.0,3319.0,0.997595
2420,Scientific Measurement and Uncertainty Evaluation,3.0,1064.0,0.997188
505,Chemistry and Stereochemistry Studies,1.0,348.0,0.997135
500,Chemical Synthesis and Reactions,4.0,1324.0,0.996988
2567,Steroid Chemistry and Biochemistry,2.0,605.0,0.996705
2265,Quality of Life Measurement,4.0,978.0,0.995927
342,Biomedical Text Mining and Ontologies,4.0,917.0,0.995657
188,Analytical Methods in Pharmaceuticals,1.0,216.0,0.995392
242,Arctic and Antarctic ice dynamics,1.0,202.0,0.995074
624,"Conservation, Biodiversity, and Resource Manag...",1.0,187.0,0.994681
200,Animal Disease Management and Epidemiology,4.0,741.0,0.994631
2519,Solid-state spectroscopy and crystallography,2.0,334.0,0.994048
1101,Gamma-ray bursts and supernovae,1.0,147.0,0.993243
1912,Nuclear Physics and Applications,13.0,1828.0,0.992939
543,Climate Change Policy and Economics,1.0,140.0,0.992908
90,Advanced Scientific Research Methods,1.0,121.0,0.991803
1964,Optics and Image Analysis,5.0,598.0,0.991708
1045,Fluorine in Organic Chemistry,4.0,400.0,0.990099

In [76]:
MN_df = df[df['institution_name'] == 'University of Minnesota']
MN_df

,id,doi,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,instiution_id,institution_name,type,country_code,ror,lineage,raw_affiliation_string,afilliation_lineage
6,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
7,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
9,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5114168374,Cole Kelleher,middle,NaN,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
10,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111210501,Michael Cloutier,middle,NaN,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
11,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5098790376,Eric Husby,middle,NaN,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517326,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,en,https://openalex.org/T10557,Social Media and Politics,https://openalex.org/subfields/3315,Communication,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5072630732,James R. Hollyer,first,https://orcid.org/0000-0001-5896-816X,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
517415,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,en,https://openalex.org/T11147,Misinformation and Its Impacts,https://openalex.org/subfields/3312,Sociology and Political Science,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5022408597,Emily K. Vraga,first,https://orcid.org/0000-0002-3016-3869,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
517421,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
517567,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,NaN,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
517588,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,NaN,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN

In [85]:
MN_oa_df = counts('field_name', 'is_oa', 'OA %', MN_df)
MN_oa_df

is_oa                                    field_name  False   True      OA %
9               Economics, Econometrics and Finance    3.0   36.0  0.923077
6                                 Decision Sciences    2.0   17.0  0.894737
23                                  Social Sciences   16.0  123.0  0.884892
21                            Physics and Astronomy   11.0   78.0  0.876404
16                                      Mathematics    1.0    7.0  0.875000
8                      Earth and Planetary Sciences   11.0   37.0  0.770833
3               Business, Management and Accounting    6.0   19.0  0.760000
10                                           Energy    3.0    9.0  0.750000
15                                Materials Science    2.0    3.0  0.600000
11                                      Engineering   46.0   63.0  0.577982
1                               Arts and Humanities    3.0    4.0  0.571429
4                                         Chemistry   39.0   37.0  0.486842
22                                       Psychology   22.0   17.0  0.435897
12                            Environmental Science   65.0   40.0  0.380952
0              Agricultural and Biological Sciences   92.0   49.0  0.347518
2      Biochemistry, Genetics and Molecular Biology  433.0  193.0  0.308307
14                      Immunology and Microbiology   62.0   26.0  0.295455
17                                         Medicine  356.0  137.0  0.277890
18                                     Neuroscience   20.0    7.0  0.259259
5                                  Computer Science  122.0   32.0  0.207792
13                               Health Professions   25.0    5.0  0.166667
24                                       Veterinary    6.0    1.0  0.142857
19                                          Nursing   11.0    1.0  0.083333
20       Pharmacology, Toxicology and Pharmaceutics   40.0    2.0  0.047619
7                                         Dentistry    2.0    NaN       NaN

In [86]:
x_oa_df = counts('field_name', 'is_oa', 'OA %', df)
x_oa_df

is_oa                                    field_name  False  True      OA %
10              Economics, Econometrics and Finance     32  2285  0.986189
3               Business, Management and Accounting     45  1479  0.970472
7                                 Decision Sciences     75  2154  0.966353
17                                      Mathematics     22   461  0.954451
24                                  Social Sciences    324  6769  0.954321
5                                         Chemistry    338  6299  0.949073
22                            Physics and Astronomy    451  7518  0.943406
16                                Materials Science    175  2587  0.936640
6                                  Computer Science    521  5892  0.918759
12                                      Engineering    719  6460  0.899847
8                                         Dentistry     12    96  0.888889
21       Pharmacology, Toxicology and Pharmaceutics     82   575  0.875190
1                               Arts and Humanities     69   261  0.790909
11                                           Energy     46   170  0.787037
0              Agricultural and Biological Sciences    955  3155  0.767640
4                              Chemical Engineering     32   101  0.759398
2      Biochemistry, Genetics and Molecular Biology   4064  9541  0.701286
14                               Health Professions    207   463  0.691045
18                                         Medicine   4500  8200  0.645669
23                                       Psychology    357   482  0.574493
15                      Immunology and Microbiology    561   727  0.564441
20                                          Nursing     81    67  0.452703
25                                       Veterinary     24    18  0.428571
19                                     Neuroscience    881   652  0.425310
13                            Environmental Science   4309  3098  0.418253
9                      Earth and Planetary Sciences   9136  1292  0.123897

In [88]:
oa_df_comp = pd.concat([MN_oa_df, x_oa_df], axis=1).reset_index()
oa_df_comp

is_oa,index,field_name,False,True,OA %,field_name,False,True,OA %
0,9,"Economics, Econometrics and Finance",3.0,36.0,0.923077,Earth and Planetary Sciences,9136,1292,0.123897
1,6,Decision Sciences,2.0,17.0,0.894737,Computer Science,521,5892,0.918759
2,23,Social Sciences,16.0,123.0,0.884892,Psychology,357,482,0.574493
3,21,Physics and Astronomy,11.0,78.0,0.876404,"Pharmacology, Toxicology and Pharmaceutics",82,575,0.875190
4,16,Mathematics,1.0,7.0,0.875000,Materials Science,175,2587,0.936640
5,8,Earth and Planetary Sciences,11.0,37.0,0.770833,Dentistry,12,96,0.888889
6,3,"Business, Management and Accounting",6.0,19.0,0.760000,"Business, Management and Accounting",45,1479,0.970472
7,10,Energy,3.0,9.0,0.750000,"Economics, Econometrics and Finance",32,2285,0.986189
8,15,Materials Science,2.0,3.0,0.600000,Immunology and Microbiology,561,727,0.564441
9,11,Engineering,46.0,63.0,0.577982,Energy,46,170,0.787037
10,1,Arts and Humanities,3.0,4.0,0.571429,Arts and Humanities,69,261,0.790909
11,4,Chemistry,39.0,37.0,0.486842,Chemical Engineering,32,101,0.759398
12,22,Psychology,22.0,17.0,0.435897,Physics and Astronomy,451,7518,0.943406
13,12,Environmental Science,65.0,40.0,0.380952,Engineering,719,6460,0.899847
14,0,Agricultural and Biological Sciences,92.0,49.0,0.347518,Agricultural and Biological Sciences,955,3155,0.767640
15,2,"Biochemistry, Genetics and Molecular Biology",433.0,193.0,0.308307,"Biochemistry, Genetics and Molecular Biology",4064,9541,0.701286
16,14,Immunology and Microbiology,62.0,26.0,0.295455,Health Professions,207,463,0.691045
17,17,Medicine,356.0,137.0,0.277890,Mathematics,22,461,0.954451
18,18,Neuroscience,20.0,7.0,0.259259,Medicine,4500,8200,0.645669
19,5,Computer Science,122.0,32.0,0.207792,Chemistry,338,6299,0.949073
20,13,Health Professions,25.0,5.0,0.166667,Environmental Science,4309,3098,0.418253
21,24,Veterinary,6.0,1.0,0.142857,Social Sciences,324,6769,0.954321
22,19,Nursing,11.0,1.0,0.083333,Neuroscience,881,652,0.425310
23,20,"Pharmacology, Toxicology and Pharmaceutics",40.0,2.0,0.047619,Nursing,81,67,0.452703
24,7,Dentistry,2.0,NaN,NaN,Decision Sciences,75,2154,0.966353
25,25,NaN,NaN,NaN,NaN,Veterinary,24,18,0.428571

In [78]:
MN_df['raw_affiliation_string'].unique()

array(['(University of Minnesota)', '(Ohio Supercomputing Center)',
       'Max Planck Institute of Molecular Physiology',
       'University of Wisconsin–Madison', 'Graduate School of Education',
       '(National Center for Supercomputing Applications)',
       'Department of Geology & Geophysics, Louisiana State University',
       'Duke Evidence-based Practice Center',
       ' University of Pennsylvania - The Wharton School',
       'University of California, Berkeley - Haas School of Business',
       '(Stanford University)',
       'CSIRO Environment, Aspendale, Victoria, Australia',
       'Computational Biology and Biophysics, Sandia National Laboratories, Livermore, CA, USA',
       'Food and Agricultural Organization of the United Nations, Rome, Italy',
       'School of Biological Sciences, University of Aberdeen, Aberdeen, UK',
       'Department of Earth System Science, Ministry of Education Key Laboratory for Earth System Modelling, Institute for Global Change Studies, Tsinghua University, Beijing, China',
       'Department of Chemistry, University of Copenhagen, Universitetsparken 5, DK-2100 Copenhagen Ø, Denmark',
       'Department of Chemistry, University of Pisa, Via Risorgimento 35 Pisa 1-56125, Italy',
       'CORNELL U', 'Brown University - Department of Economics',
       "Institute for Theoretical and Experimental Physics named by A.I. Alikhanov of National Research Centre ``Kurchatov Institute'' and National Research Nuclear University MEPhI (Moscow Engineering Physics Institute)",
       'Department of Physics, Indiana University',
       'Department of Physics and Astronomy, University of Tennessee',
       'Annenberg School for Communication University of Pennsylvania',
       'Pennsylvania State University', 'University of Kochi',
       'Zhejiang University', 'University of Colorado Boulder',
       'Carnegie Mellon University',
       'Eaton Peabody Laboratories, Mass Eye and Ear, Boston, MA, 02114 USA; Department of Otolaryngology, Head and Neck Surgery, Harvard Medical School, Boston, MA, 02114, USA; Speech and Hearing Biosciences and Technology graduate program, Harvard University, Cambridge, MA, USA',
       'Eaton Peabody Laboratories, Mass Eye and Ear, Boston, MA, 02114 USA; Department of Otolaryngology, Head and Neck Surgery, Harvard Medical School, Boston, MA, 02114, USA',
       'Anton Pannekoek Institute for Astronomy, University of Amsterdam',
       'University of Wisconsin-Madison',
       'Division of Pediatric Endocrinology,', 'New York University',
       'Department of Human Development, University of California, Davis',
       'U.S. Naval Research Laboratory',
       'Max-Planck-Institut für RadioastronomieMax-Plank',
       '(University of West Georgia)', 'Carnegie Mellon University, USA',
       'Institute of Applied and Basic Science, Zanjan, I.R. Iran',
       'Institute of Geophysics, University of Alaska Fairbanks',
       'California Institute of Technology',
       'University of Southern California',
       'Department of Earth System Science, Stanford University, Stanford, California',
       'Allen Institute for Brain Science',
       'Princeton Neuroscience Institute, Princeton University',
       'Cornell University',
       'College of Land Science and Technology, China Agricultural University',
       'Case Western Reserve University', '(University of Michigan)',
       'Department of Biomedical Engineering, Oregon Health & Science University, Portland, OR USA; The Knight Cancer Institute, Oregon Health & Science University, Portland, OR USA; Current affiliation: Department of Machine Learning, H. Lee Moffitt Cancer Center, Tampa, FL USA; Current affiliation: Department of Biostatistics and Bioinformatics, H. Lee Moffitt Cancer Center, Tampa, FL USA',
       'Duke University', 'Georgia State University',
       'Utrecht University', 'Max Planck Institute for Chemistry',
       'Department  of Biomedical Engineering and Physics, Academic Medical Center, Meibergdreef 9, 1105 AZ Amsterdam Zuidoost, The Netherlands',
       'Center for Decision Research at the University of North Carolina at Chapel Hill.',
       'Cornell University, Ithaca, NY, USA',
       'University of Washington, Department of Atmospheric Sciences',
       'University of Melbourne', 'CIRA, Colorado State University',
       'University of Wisconsin Eau Claire',
       'Envrionmental Sciences Divison, Argonne National Laboratory, Argonne, IL, USA',
       '***University of Illinois at Urbana-Champaign',
       'University of Western Ontario;', 'Colby College;',
       'Glaciology, Alfred Wegener Institute, Helmholtz Centre for Polar and Marine Research, Bremerhaven, Germany',
       "Center for Data-Driven Discovery in Biomedicine, Children's Hospital of Philadelphia; Division of Neurosurgery, Children's Hospital of Philadelphia",
       'Cooperative Institute for Research in Environmental Sciences, CU Boulder; NOAA GML',
       'Pondicherry Univerisity', 'University of Colorado Boulder, USA',
       'Moore Center for Science, Conservation International',
       'National University of Life and Environmental Sciences of Ukraine',
       'Institute for Astronomy, University of Hawaii',
       'Faculty of Geosciences, Copernicus Institute of Sustainable Development',
       'Johns Hopkins University',
       'University of Chinese Academy of Sciences', 'Jilin University',
       'Estafeta Universitaria, Universidad de Panama, Apartado 10767, Panama.',
       'Southern Medical University',
       'Duke University, Political Science',
       'Department of Pharmacochemistry, Vrije University, Amsterdam, Netherlands (now Emeritus Section Molecular Toxicology), (TGM)',
       'MPI Research, Inc., Mattawan, Michigan, USA, (ST)',
       'Western Sydney University', 'Princeton University',
       'UFZ-Helmholtz Centre for Environmental Research, Department of Computational Hydrosystems, Leipzig, Germany',
       'Ronald O. Perelman Department of Dermatology and Department of Pathology, NYU Grossman School of Medicine, New York, United States',
       'Department of Physics, University of Genoa & INFN, via Dodecaneso 33, 16146, Genoa, Italy',
       'CERN, the European Organization for Nuclear Research, CH-1211 Geneve 23, Switzerland',
       'Department of Atmospheric and Oceanic Sciences, University of Colorado Boulder, CO 80309, Boulder, USA',
       'Institute for Atmospheric and Earth System Research INAR, University of Helsinki, 00560, Finland; Aerodyne Research, Inc., Billerica, MA, 01821, USA',
       'Penn State', 'University of Iowa',
       'University of California, Berkeley',
       "Listening Observatory for Hawaiian Ecosystems, University of Hawai'i at Hilo",
       'Institute of Social Medicine, Occupational Health and Public Health, University of Leipzig, Leipzig, Germany.',
       'Washington University in St. Louis',
       'National Institute of Hospital Administration',
       '(Pennsylvania State University)', '(University of Chicago)',
       '(Florida State University)', 'Rutgers University',
       'Finnish Meteorological Institute, Erik Palménin aukio 1, P.O. Box 503, FIN-00100 Helsinki, Finland',
       'NOAA/Geophysical Fluid Dynamics Laboratory', 'University of Bern',
       'University of Canterbury, Christchurch, New Zealand',
       'King Abdullah University of Science & Technology',
       'Jet Propulsion Laboratory, California Institute of Technology, Pasadena, CA, USA.',
       'Irstea, Montpellier, France.',
       'Irstea, Aix Marseille Université, RECOVER, Aix-en-Provence, France',
       'Department of Geological Sciences, University of North Carolina, Chapel Hill, North Carolina, USA',
       'Wisconsin Insect Research Collection (WIRC), University of Wisconsin',
       'Jet Propulsion Laboratory, California Institute of Technology',
       '(Ohio State University)',
       'Stem Cell Institute, University of Minnesota, USA',
       'University of Connecticut', 'City University of New York',
       'University of Minnesota', 'Arizona State University',
       'Computer Science Department, Centro de Investigación en Matemáticas, A.C., Guanajuato, México',
       'Clinical Science, Philips Healthcare, Germany',
       'The Pennsylvania State University',
       'Center for Computational Astrophysics, Flatiron Institute',
       'Columbia University',
       'Columbia University, Center for Computational Astrophysics, Flatiron Institute',
       'Water Protection Program, Missouri Department of Natural Resources; Jefferson City, MO 65101, USA',
       'Frederick Research Center Cyprus',
       'Center of Functional and Evolutionary Ecology; Department of Public and Ecosystem Health, Cornell University, New York, United States ; Université de Toulouse, INRAE, CEFS, 31326 Castanet Tolosan Cedex, France.',
       'Duke Clinical Research Institute, Duke University Medical Center, Durham, NC, 27701, USA',
       'Duke Molecular Physiology Institute (DMPI), Duke University Medical Center, Durham, NC, 27701, USA  Sarah W. Stedman Nutrition and Metabolism Center, Duke University Medical Center, Durham, NC, 27705, USA',
       'Department Cardiac Surgery, IRCCS Policlinico San Donato, Milan, Italy.',
       'New York University School of Medicine',
       'Institute for Atmospheric and Earth System Research/Physics, Faculty of Science, 00014 University of Helsinki, Helsinki, Finland.',
       'Los Alamos National Laboratory',
       'Department of Physics and Astronomy, Purdue University, West Lafayette, IN 47907, USA',
       'Space Telescope Science Institute',
       'School of Natural Resources, University of Nebraska-Lincoln',
       'University of Virginia',
       'Biophysics Graduate Group, University of California, Davis, CA',
       'Arizona State University: Tempe, AZ, US',
       'University of Colorado, Boulder',
       'Harvard University, Department of Physics',
       'Centro de Astronomı́a (CITEVA), Universidad de Antofagasta, Avenida U. de Antofagasta 02800, Antofagasta, Chile.',
       'Finnish Museum of Natural History', 'Imperial College London',
       'New York University Langone Health',
       'Virginia Tech, Ardhi University', 'The University of Leicester',
       'Boyce Thompson Institute',
       'Departamento de Ciencias Forestales, Universidad Nacional de Colombia, Medellín, Colombia',
       'Center for Precision Health Research, National Human Genome Research Institute, National Institutes of Health',
       'Montana State University, Department of Microbiology and Cell Biology, Bozeman, MT 59717',
       'Virginia Tech', 'University of Michigan',
       'Shanghai Jiao Tong University',
       'Pediatric Urology, University of Wisconsin, USA',
       'Benjamin Levich Institute and Department of Chemical Engineering, City College of the City University of New York, New York, New York 10031, USA',
       'Department of Physics, University of Illinois at Urbana-Champaign, Urbana, Illinois 61801, USA',
       'University Montpellier 1, Montpellier, France',
       'World Health Organization, TDR, Special Programme for Research and Training for Neglected Disease, 20 Avenue Appia, 1211 Geneva, Switzerland',
       'Department of Obstetrics and Gynecology, McMaster University, HSC 3N52, 1200 Main St. West, Hamilton, ON L8N 3Z5, Canada',
       'Institut für Physikalische und Theoretische Chemie, Universität Tübingen, Auf der Morgenstelle 8, D-72076 Tübingen, Germany',
       'GlaxoSmithKline Pharmaceuticals, 709 Swedeland Road, King of Prussia, PA 19406, USA',
       'CSIRO Materials Science and Engineering, Clayton South, Victoria, Australia',
       'Department of Chemistry, Duke University, P.O. Box 90346, Durham, NC 27708-0346, USA',
       'Max-Planck-Institut für Strahlenchemie, Postfach 10 13 65, D 45413 Mülheim an der Ruhr, Germany',
       'Department of Chemistry and Biochemistry, University of Colorado at Boulder, USA',
       'Department of Cell Biology, Skirball Institute of Biomolecular Medicine, New York University School of Medicine, USA',
       'IFR 85 “Biomolécules et Innovations Thérapeutiques” 74 Route du Rhin BP 60024, 67401 Illkirch, France',
       'Department of Chemistry, Graduate School of Science, Kyoto University, Kyoto, 606-8502, Japan',
       'University of Manchester, Manchester, UK',
       'Department of Molecular Biology and Genetics, Cornell University, USA',
       'Department of Chemical and Biological Engineering, University at Buffalo, Buffalo, New York 14222, USA',
       'Department of Pediatrics & Communicable Diseases, University of Michigan, USA',
       'Burke Medical Research Institute, Weil Medical College of Cornell, USA',
       'Department of Medicine - Hematology, Duke University, USA',
       'Departments of Chemistry and Physics, 80 St. George St., University of Toronto, Toronto, ON, M5S 3H6, Canada',
       'Boehringer Ingelheim Pharmaceuticals, Inc., 900 Ridgebury Road, Ridgefield, CT 06877, USA',
       'McMaster HTS Laboratory, Department of Biochemistry and Biomedical Sciences, McMaster University, HSC 4N45-D, 1200 Main St. West, Hamilton, ON L8N 3Z5, Canada',
       'AJLW Consulting, Inc., 649 Via Rialto, Oakland, CA 94619, USA',
       'Department of Zoology, University of Wisconsin-Madison, USA',
       'Department of Forest Resources, University of Minnesota Center for Forest Ecology, USA',
       'Department of Urology, University of Minnesota, USA',
       'School of Molecular and Cellular Biology, University of Illinois at Urbana-Champaign, USA',
       'Division of Gastroenterology & Hepatology, Rush University Medical Center, USA',
       'Institute of Macromolecular Chemistry, Academy of Sciences of the Czech Republic, Praha, Czech Republic',
       'Department of Microbilogy and Immunology, Columbia University Medical Center, USA',
       'Department of Anesthesiology and Critical Care, Perelman School of Medicine, University of Pennsylvania, USA',
       'Department of Medicine, Duke University, USA',
       'Australian Institute of Marine Science, PMB 3, Townsville 4810, Australia',
       'Boehringer Ingelheim Pharmaceuticals, Inc. (retired)',
       'Department of Biology, University of Pennsylvania, USA',
       'Department of Psychology, University of Michigan, USA',
       'School of Medicine, Department of Pharmacology, University of Virginia, USA',
       'Department of Biochemistry, University of Alberta, Edmonton, Alberta, Canada',
       'Department of Obstetrics & Gynecology, Perelman School of Medicine, University of Pennsylvania, USA',
       'Department of Molecular and Integrative Physiology University of Michigan, Ann Arbor MI 48109',
       'Imperial College of Science and Technology, London S.W.7, U.K.',
       'Institute of Macromolecular Chemistry, Academy of Sciences of the Czech Republic, Heyrovsky Sq. 2, 162 06 Praha 6, Czech Republic',
       'School of Materials, The University of Manchester, Manchester M1 7HS, UK.',
       'National Center for Natural Products Research, The University of Mississippi, P.O. Box 1848, University, MS 38677, USA',
       'Department of Laboratory Medicine and Pathology, University of Minnesota, USA',
       'Department of Pharmacology, University of Michigan, Ann Arbor, MI 48109-1055, USA',
       'Department of Neuroscience, University of Virginia, USA',
       'The Hormel Institute, University of Minnesota, USA',
       'Department of Psychiatry, Washington University in St Louis, USA',
       'Department of Mechanical and Industrial Engineering, University of Toronto, 5 King’s College Rd. Toronto, Ontario M5S 1A4, Canada',
       'Neuroscience Institute, Princeton University, USA',
       'Department of Microbiology and Immunology, Weill Medical College of Cornell University, USA',
       'Weill Institute for Cell and Molecular Biology, Cornell University, USA',
       'Department of Natural Sciences, University of Michigan-Dearborn, Dearborn, MI 48128–1491, USA',
       'Department of Biology, Duke University, USA',
       'Brown University, Department of Chemistry, Providence, RI 02912, USA',
       'Department of Obstetrics and Gynecology, University of Wisconsin Hospital and Clinics, USA',
       'Department K63E, Metrology & Materials Processing, IBM Almaden Research Center, USA: deceased',
       'Department of Inorganic and Physical Chemistry, Indian Institute of Science, Bangalore 560012, India',
       '30 Kimberley Road, Chesterton, Cambridge, CB4 1HH, UK',
       'Department of Chemistry, New York University, USA',
       'Department of Biochemistry & Molecular Biology, Pennsylvania State University, USA',
       'Department of Biomolecular Chemistry, University of Wisconsin-Madison, USA',
       'Department of Chemical and Biological Engineering, University of Colorado Boulder, USA',
       'Department of Medicine, University of Pennsylvania Perelman School of Medicine, USA',
       'Department of Biomedical Engineering, Duke University, USA',
       'University of Kent, Canterbury, UK',
       'Department of Pediatrics, University of Minnesota, USA',
       'Department of Immunology, Duke University, USA',
       'Department of Molecular Genetics, University of Toronto, Canada',
       'Laboratory of Cell and Molecular Biology, National Institute of Diabetes and Digestive and Kidney Diseases, National Institutes of Health, USA',
       'Servier Research Institute, 125 Chemin de Ronde, 78290 Croissysur-Seine, France',
       'HHMI & Department of Neuroscience, University of Wisconsin, USA',
       'Department of Agronomy and Plant Genetics, University of Minnesota, USA',
       'Department of Chemistry, University of Illinois at Urbana-Champaign, USA',
       'Department of Biology, Eberly College of Science, Pennsylvania State University, USA',
       'Department of Molecular Medicine, Cornell University, USA',
       'Department of Chemistry, University of Michigan, USA',
       'Center for Male Reproductive Medicine, Weill-Cornell Medical College, USA',
       'Princeton Plasma Physics Lab. (PPPL), Princeton, NJ (United States)',
       'Univ. of Wisconsin, Madison, WI (United States)',
       'Michigan State Univ., East Lansing, MI (United States)',
       'Queen Mary University of London',
       'Division of Basic Sciences, Fred Hutchinson Cancer Research Center, 1100 Fairview Avenue North, PO Box 19024, Mailstop A1-162, Seattle, WA 98109, USA.',
       'AT&T Labs-Research',
       'McWilliams Center for Cosmology, Carnegie Mellon University',
       'Faculty of Health Studies, Sogn og Fjordane University College, Førde, Norway. Department of Surgery, Førde Central Hospital, Norway. ',
       'Department of Global Public Health and Primary Care, Bergen, Norway. ',
       'Joint BSC-CRG-IRB Research Program in Computational Biology, Barcelona Supercomputing Center (BSC-CNS)',
       'Carleton University', '(DARPA)',
       '(University of Illinois Chicago and NBER)',
       '(Washington University in St. Louis)',
       '(Massachusetts Institute of Technology)', '(Duke University)',
       '(University of Pennsylvania)', '(Brigham Young University)',
       '(Balang,NGO in Bantaeng, South Sulawesi)', '(Lockheed Martin)',
       '(CIFOR)', '(Strategic Analysis Enterprises)',
       '(Strategic Analysis Enterprises, Inc.)',
       '(University of North Carolina at Chapel Hill)',
       '(Strategic Analysis Enteprrises)', '(Yale University)',
       '(World Agroforestry Centre)', '(University of Nairobi)',
       '(Institute de Recherches Economiques et Sociales - Universite Catholique de Louvain)',
       '(University of Ghana - Legon)', '(UW Madison)',
       '(New York University at Abu Dhabi)', '(Princeton University)',
       '(Penn State)', '(Vanderbilt University)', '(Nebraska)',
       '(University of Illinois)', 'National Marine Fisheries Service',
       'University of Washington',
       'Department of Nutritional Sciences, The Pennsylvania State University, USA',

In [ ]:
Michigan_df = df[df['institution_name'] == 'University of Michigan–Ann Arbor']
#ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572')]
Michigan_df.head(25)

In [ ]:
Michigan_df

In [ ]:
Michigan_df = Michigan_df.groupby(['institution_name', 'field_name']).size().sort_values(ascending=False) #/len(Michigan_df)
Michigan_df.head(25)