In [90]:
import requests
import pandas as pd
import time
import json

In [91]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Create a container
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        
        # create a loop iterator
        record_number = 0
        page += 1
       
       # Loop over all the records
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'type': record['type'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                'index location': record['indexed_in'],
                                'primary_location': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'], 
                                'authors': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions'],
                                'apc_list': record['apc_list'],
                                'apc_paid': record['apc_paid'],
                                'fwci': record['fwci'],
                                'has_fulltext': record['has_fulltext'],
                                'institution_assertions': record['institution_assertions'],
                                'cited_by_count': record['cited_by_count'], 
                                'citation_normalized_percentile': record['citation_normalized_percentile'],
                                'cited_by_percentile_year': record['cited_by_percentile_year'],
                                'biblio': record['biblio']
                                })         

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

parameters = {
    "per-page": 100,
}   
# types/dataset,
#parameters = {
    #"filter": f"authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549",  # University of Tasmania
    #"per-page": 100,
    #"select": "id,doi,publication_year,title,primary_location,authorships,topics",
#}

In [ ]:
# API Call to scrape UMN Data
#df = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901', parameters)

In [92]:
# API Call to scrape UMN Data
#MN_df = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters)
#MN_df.to_csv('OpenAlexMNData.csv')
with open('OpenAlexDataCitation.json', 'w') as outfile:
    json.dump(OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters), outfile)
    
df = pd.read_json('OpenAlexDataCitation.json')
df

Status code: 200 ; Page number:  0
Status code: 200 ; Page number:  1
Status code: 200 ; Page number:  2
Status code: 200 ; Page number:  3
Status code: 200 ; Page number:  4
Status code: 200 ; Page number:  5
Status code: 200 ; Page number:  6
Status code: 200 ; Page number:  7
Status code: 200 ; Page number:  8
Status code: 200 ; Page number:  9
Status code: 200 ; Page number:  10
Status code: 200 ; Page number:  11
Status code: 200 ; Page number:  12
Status code: 200 ; Page number:  13
Status code: 200 ; Page number:  14
Status code: 200 ; Page number:  15
Status code: 200 ; Page number:  16
Status code: 200 ; Page number:  17
Status code: 200 ; Page number:  18
Status code: 200 ; Page number:  19
Status code: 200 ; Page number:  20
Status code: 200 ; Page number:  21
Status code: 200 ; Page number:  22
Status code: 200 ; Page number:  23
Status code: 200 ; Page number:  24
Status code: 200 ; Page number:  25
Status code: 200 ; Page number:  26

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,institution_assertions,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],36,"{'value': 0.991525, 'is_in_top_1_percent': Tru...","{'min': 98, 'max': 99}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],36,"{'value': 0.992406, 'is_in_top_1_percent': Tru...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],32,"{'value': 0.9978629999999999, 'is_in_top_1_per...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],20,"{'value': 0.999201, 'is_in_top_1_percent': Tru...","{'min': 94, 'max': 95}","{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T10557', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2514,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T11147', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2515,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2516,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Fletcher Sch...,"[{'id': 'https://openalex.org/I121934306', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2517,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."

In [ ]:
with open('OpenAlexData.json', 'w') as outfile:
    json.dump(OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i57206974 \
        |i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901', parameters), outfile)

In [93]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [94]:
def missing_index(df):
    missing_indices = ([i for i in range(0, len(df)) if i not in df.index])
    return missing_indices

In [95]:
pd.set_option("display.max_columns", 55)

In [ ]:
df = pd.read_json('OpenAlexData.json')
df.head()

In [96]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'institution_assertions', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio'],
      dtype='object')

In [97]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,institution_assertions,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],36,"{'value': 0.991525, 'is_in_top_1_percent': Tru...","{'min': 98, 'max': 99}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],36,"{'value': 0.992406, 'is_in_top_1_percent': Tru...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],32,"{'value': 0.9978629999999999, 'is_in_top_1_per...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],20,"{'value': 0.999201, 'is_in_top_1_percent': Tru...","{'min': 94, 'max': 95}","{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T10557', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2514,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T11147', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2515,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2516,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Fletcher Sch...,"[{'id': 'https://openalex.org/I121934306', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
2517,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,dataset,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."

In [98]:
# normalize  citation metric columns data

citation_normalized_percentile_df = pd.json_normalize(df['citation_normalized_percentile'])
cited_by_percentile_year_df = pd.json_normalize(df['cited_by_percentile_year'])
biblio_df = pd.json_normalize(df['biblio'])
# concat normalized data into original df

df = pd.concat([df, citation_normalized_percentile_df], axis=1)
df = pd.concat([df, cited_by_percentile_year_df], axis=1)
df = pd.concat([df, biblio_df], axis=1)

#r ename column
df = df.rename(columns={'value': 'citation_normalized_value'})


df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,institution_assertions,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.997735,True,True,99,100,None,None,None,None
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],36,"{'value': 0.991525, 'is_in_top_1_percent': Tru...","{'min': 98, 'max': 99}","{'volume': None, 'issue': None, 'first_page': ...",0.991525,True,True,98,99,None,None,None,None
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],36,"{'value': 0.992406, 'is_in_top_1_percent': Tru...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ...",0.992406,True,True,97,98,None,None,None,None
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,[],32,"{'value': 0.9978629999999999, 'is_in_top_1_per...","{'min': 97, 'max': 98}","{'volume': None, 'issue': None, 'first_page': ...",0.997863,True,True,97,98,None,None,None,None
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,[],20,"{'value': 0.999201, 'is_in_top_1_percent': Tru...","{'min': 94, 'max': 95}","{'volume': None, 'issue': None, 'first_page': ...",0.999201,True,True,94,95,None,None,None,None

In [99]:
# normalize columns data
primary_location_df = pd.json_normalize(df['primary_location'])


# extract only display name column
primary_location_df = primary_location_df[['display_name']]

#rename display name column
primary_location_df = primary_location_df.rename(columns={'display_name': 'Repository'})

#primary_location_df = primary_location_df.reindex(range(primary_location_df.index.min(), primary_location_df .index.max()+1))

# concat display name column to main df
df = pd.concat([df, primary_location_df], axis=1)

In [100]:
# Use function to normalize Authors nested list
authors_df = CleanJSON('authors', df)
authors_df['raw_affiliation_strings'] = authors_df['raw_affiliation_strings'].str[0]
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...
...,...,...,...,...,...,...,...,...
2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...
2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...
2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...
2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...

In [101]:
missing_index(authors_df['raw_affiliation_strings'])

[2518,
 2519,
 2520,
 2521,
 2522,
 2523,
 2524,
 2525,
 2526,
 2527,
 2528,
 2529,
 2530,
 2531,
 2532,
 2533,
 2534,
 2535,
 2536,
 2537,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2545,
 2546,
 2547,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2563,
 2564,
 2565,
 2566,
 2567,
 2568,
 2569,
 2570,
 2571,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 2582,
 2583,
 2584,
 2585,
 2586,
 2587,
 2588,
 2589,
 2590,
 2591,
 2592,
 2593,
 2594,
 2595,
 2596,
 2597,
 2598,
 2599,
 2600,
 2601,
 2602,
 2603,
 2604,
 2605,
 2606,
 2607,
 2608,
 2609,
 2610,
 2611,
 2612,
 2613,
 2614,
 2615,
 2616,
 2617,
 2618,
 2619,
 2620,
 2621,
 2622,
 2623,
 2624,
 2625,
 2626,
 2627,
 2628,
 2629,
 2630,
 2631,
 2632,
 2633,
 2634,
 2635,
 2636,
 2637,
 2638,
 2639,
 2640,
 2641,
 2642,
 2643,
 2644,
 2645,
 2646,
 2647,
 2648,
 2649,
 2650,
 2651,
 2652,
 2653,
 2654,
 2655,
 2656,
 2657,
 2658,
 2659,
 2660,
 2661,
 2662,
 2663,
 2664,
 2665,
 2666,
 2667,
 2668,
 2669,
 2670,
 2671,
 2672,
 2673,
 2674,
 2675,
 2676,
 2677,
 2678,
 2679,
 2680,
 2681,
 2682,
 2683,
 2684,
 2685,
 2686,
 2687,
 2688,
 2689,
 2690,
 2691,
 2692,
 2693,
 2694,
 2695,
 2696,
 2697,
 2698,
 2699,
 2700,
 2701,
 2702,
 2703,
 2704,
 2705,
 2706,
 2707,
 2708,
 2709,
 2710,
 2711,
 2712,
 2713,
 2714,
 2715,
 2716,
 2717,
 2718,
 2719,
 2720,
 2721,
 2722,
 2723,
 2724,
 2725,
 2726,
 2727,
 2728,
 2729,
 2730,
 2731,
 2732,
 2733,
 2734,
 2735,
 2736,
 2737,
 2738,
 2739,
 2740,
 2741,
 2742,
 2743,
 2744,
 2745,
 2746,
 2747,
 2748,
 2749,
 2750,
 2751,
 2752,
 2753,
 2754,
 2755,
 2756,
 2757,
 2758,
 2759,
 2760,
 2761,
 2762,
 2763,
 2764,
 2765,
 2766,
 2767,
 2768,
 2769,
 2770,
 2771,
 2772,
 2773,
 2774,
 2775,
 2776,
 2777,
 2778,
 2779,
 2780,
 2781,
 2782,
 2783,
 2784,
 2785,
 2786,
 2787,
 2788,
 2789,
 2790,
 2791,
 2792,
 2793,
 2794,
 2795,
 2796,
 2797,
 2798,
 2799,
 2800,
 2801,
 2802,
 2803,
 2804,
 2805,
 2806,
 2807,
 2808,
 2809,
 2810,
 2811,
 2812,
 2813,
 2814,
 2815,
 2816,
 2817,
 2818,
 2819,
 2820,
 2821,
 2822,
 2823,
 2824,
 2825,
 2826,
 2827,
 2828,
 2829,
 2830,
 2831,
 2832,
 2833,
 2834,
 2835,
 2836,
 2837,
 2838,
 2839,
 2840,
 2841,
 2842,
 2843,
 2844,
 2845,
 2846,
 2847,
 2848,
 2849,
 2850,
 2851,
 2852,
 2853,
 2854,
 2855,
 2856,
 2857,
 2858,
 2859,
 2860,
 2861,
 2862,
 2863,
 2864,
 2865,
 2866,
 2867,
 2868,
 2869,
 2870,
 2871,
 2872,
 2873,
 2874,
 2875,
 2876,
 2877,
 2878,
 2879,
 2880,
 2881,
 2882,
 2883,
 2884,
 2885,
 2886,
 2887,
 2888,
 2889,
 2890,
 2891,
 2892,
 2893,
 2894,
 2895,
 2896,
 2897,
 2898,
 2899,
 2900,
 2901,
 2902,
 2903,
 2904,
 2905,
 2906,
 2907,
 2908,
 2909,
 2910,
 2911,
 2912,
 2913,
 2914,
 2915,
 2916,
 2917,
 2918,
 2919,
 2920,
 2921,
 2922,
 2923,
 2924,
 2925,
 2926,
 2927,
 2928,
 2929,
 2930,
 2931,
 2932,
 2933,
 2934,
 2935,
 2936,
 2937,
 2938,
 2939,
 2940,
 2941,
 2942,
 2943,
 2944,
 2945,
 2946,
 2947,
 2948,
 2949,
 2950,
 2951,
 2952,
 2953,
 2954,
 2955,
 2956,
 2957,
 2958,
 2959,
 2960,
 2961,
 2962,
 2963,
 2964,
 2965,
 2966,
 2967,
 2968,
 2969,
 2970,
 2971,
 2972,
 2973,
 2974,
 2975,
 2976,
 2977,
 2978,
 2979,
 2980,
 2981,
 2982,
 2983,
 2984,
 2985,
 2986,
 2987,
 2988,
 2989,
 2990,
 2991,
 2992,
 2993,
 2994,
 2995,
 2996,
 2997,
 2998,
 2999,
 3000,
 3001,
 3002,
 3003,
 3004,
 3005,
 3006,
 3007,
 3008,
 3009,
 3010,
 3011,
 3012,
 3013,
 3014,
 3015,
 3016,
 3017,
 3018,
 3019,
 3020,
 3021,
 3022,
 3023,
 3024,
 3025,
 3026,
 3027,
 3028,
 3029,
 3030,
 3031,
 3032,
 3033,
 3034,
 3035,
 3036,
 3037,
 3038,
 3039,
 3040,
 3041,
 3042,
 3043,
 3044,
 3045,
 3046,
 3047,
 3048,
 3049,
 3050,
 3051,
 3052,
 3053,
 3054,
 3055,
 3056,
 3057,
 3058,
 3059,
 3060,
 3061,
 3062,
 3063,
 3064,
 3065,
 3066,
 3067,
 3068,
 3069,
 3070,
 3071,
 3072,
 3073,
 3074,
 3075,
 3076,
 3077,
 3078,
 3079,
 3080,
 3081,
 3082,
 3083,
 3084,
 3085,
 3086,
 3087,
 3088,
 3089,
 3090,
 3091,
 3092,
 3093,
 3094,
 3095,
 3096,
 3097,
 3098,
 3099,
 3100,
 3101,
 3102,
 3103,
 3104,
 3105,
 3106,
 3107,
 3108,
 3109,
 3110,
 3111,
 3112,
 3113,
 3114,
 3115,
 3116,
 3117,
 3118,
 3119,
 3120,
 3121,
 3122,
 3123,
 3124,
 3125,
 3126,
 3127,
 3128,
 3129,
 3130,
 3131,
 3132,
 3133,
 3134,
 3135,
 3136,
 3137,
 3138,
 3139,
 3140,
 3141,
 3142,
 3143,
 3144,
 3145,
 3146,
 3147,
 3148,
 3149,
 3150,
 3151,
 3152,
 3153,
 3154,
 3155,
 3156,
 3157,
 3158,
 3159,
 3160,
 3161,
 3162,
 3163,
 3164,
 3165,
 3166,
 3167,
 3168,
 3169,
 3170,
 3171,
 3172,
 3173,
 3174,
 3175,
 3176,
 3177,
 3178,
 3179,
 3180,
 3181,
 3182,
 3183,
 3184,
 3185,
 3186,
 3187,
 3188,
 3189,
 3190,
 3191,
 3192,
 3193,
 3194,
 3195,
 3196,
 3197,
 3198,
 3199,
 3200,
 3201,
 3202,
 3203,
 3204,
 3205,
 3206,
 3207,
 3208,
 3209,
 3210,
 3211,
 3212,
 3213,
 3214,
 3215,
 3216,
 3217,
 3218,
 3219,
 3220,
 3221,
 3222,
 3223,
 3224,
 3225,
 3226,
 3227,
 3228,
 3229,
 3230,
 3231,
 3232,
 3233,
 3234,
 3235,
 3236,
 3237,
 3238,
 3239,
 3240,
 3241,
 3242,
 3243,
 3244,
 3245,
 3246,
 3247,
 3248,
 3249,
 3250,
 3251,
 3252,
 3253,
 3254,
 3255,
 3256,
 3257,
 3258,
 3259,
 3260,
 3261,
 3262,
 3263,
 3264,
 3265,
 3266,
 3267,
 3268,
 3269,
 3270,
 3271,
 3272,
 3273,
 3274,
 3275,
 3276,
 3277,
 3278,
 3279,
 3280,
 3281,
 3282,
 3283,
 3284,
 3285,
 3286,
 3287,
 3288,
 3289,
 3290,
 3291,
 3292,
 3293,
 3294,
 3295,
 3296,
 3297,
 3298,
 3299,
 3300,
 3301,
 3302,
 3303,
 3304,
 3305,
 3306,
 3307,
 3308,
 3309,
 3310,
 3311,
 3312,
 3313,
 3314,
 3315,
 3316,
 3317,
 3318,
 3319,
 3320,
 3321,
 3322,
 3323,
 3324,
 3325,
 3326,
 3327,
 3328,
 3329,
 3330,
 3331,
 3332,
 3333,
 3334,
 3335,
 3336,
 3337,
 3338,
 3339,
 3340,
 3341,
 3342,
 3343,
 3344,
 3345,
 3346,
 3347,
 3348,
 3349,
 3350,
 3351,
 3352,
 3353,
 3354,
 3355,
 3356,
 3357,
 3358,
 3359,
 3360,
 3361,
 3362,
 3363,
 3364,
 3365,
 3366,
 3367,
 3368,
 3369,
 3370,
 3371,
 3372,
 3373,
 3374,
 3375,
 3376,
 3377,
 3378,
 3379,
 3380,
 3381,
 3382,
 3383,
 3384,
 3385,
 3386,
 3387,
 3388,
 3389,
 3390,
 3391,
 3392,
 3393,
 3394,
 3395,
 3396,
 3397,
 3398,
 3399,
 3400,
 3401,
 3402,
 3403,
 3404,
 3405,
 3406,
 3407,
 3408,
 3409,
 3410,
 3411,
 3412,
 3413,
 3414,
 3415,
 3416,
 3417,
 3418,
 3419,
 3420,
 3421,
 3422,
 3423,
 3424,
 3425,
 3426,
 3427,
 3428,
 3429,
 3430,
 3431,
 3432,
 3433,
 3434,
 3435,
 3436,
 3437,
 3438,
 3439,
 3440,
 3441,
 3442,
 3443,
 3444,
 3445,
 3446,
 3447,
 3448,
 3449,
 3450,
 3451,
 3452,
 3453,
 3454,
 3455,
 3456,
 3457,
 3458,
 3459,
 3460,
 3461,
 3462,
 3463,
 3464,
 3465,
 3466,
 3467,
 3468,
 3469,
 3470,
 3471,
 3472,
 3473,
 3474,
 3475,
 3476,
 3477,
 3478,
 3479,
 3480,
 3481,
 3482,
 3483,
 3484,
 3485,
 3486,
 3487,
 3488,
 3489,
 3490,
 3491,
 3492,
 3493,
 3494,
 3495,
 3496,
 3497,
 3498,
 3499,
 3500,
 3501,
 3502,
 3503,
 3504,
 3505,
 3506,
 3507,
 3508,
 3509,
 3510,
 3511,
 3512,
 3513,
 3514,
 3515,
 3516,
 3517,
 ...]

In [102]:
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'institution_assertions', 'cited_by_count',
       'citation_normalized_percentile', 'cited_by_percentile_year', 'biblio',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page',
       'last_page', 'Repository'],
      dtype='object')

In [103]:
# Create new DataFrame to concat original data from
cleaned_df = df[['id', 'doi', 'type', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'Repository', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value', 'is_in_top_1_percent', 'is_in_top_10_percent']].copy()
cleaned_df

,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,dataset,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,36,0.991525,True,True
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,dataset,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,36,0.992406,True,True
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,dataset,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,32,0.997863,True,True
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,dataset,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,20,0.999201,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,dataset,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10557', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2514,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,dataset,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,"[{'id': 'https://openalex.org/T11147', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2515,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2516,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2517,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False

In [104]:
# concat original data to unnested authors_df
authors_df = pd.concat([authors_df, cleaned_df], axis=1)
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False
2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False

In [105]:
# reset index to concat with author information_df
authors_df = authors_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(authors_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'author_id', 'display_name': 'author_name'})
author_info_df

,author_id,author_name,orcid
0,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...
10563,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,https://openalex.org/A5111425891,Paul Glewwe,None
10566,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,https://openalex.org/A5031469107,Paul Goren,None

In [106]:
# concat author_info_df to author_df
authors_df = pd.concat([authors_df, author_info_df], axis=1).reset_index(drop=True)
authors_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5109469110,B. Bates,None

In [107]:
# normalize nested Insituttion column
institution_df = CleanJSON('institutions', authors_df)

# remove list format for lineage
institution_df['lineage'] = institution_df['lineage'].str[0]
institution_df

# rename columns
institution_df = institution_df.rename(columns={'id': 'institution_id', 'display_name': 'institution_name', 'type': 'funding_type'})

In [108]:
# remove duplicate indices 
institution_df = institution_df[~institution_df.index.duplicated(keep='first')]

# fill nan values on missinging indices
institution_df = institution_df.reindex(range(institution_df.index.min(), institution_df.index.max()+1))

In [109]:
institution_df.head(25)

,institution_id,institution_name,ror,country_code,funding_type,lineage
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
5,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
6,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
7,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
8,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,funder,https://openalex.org/I34077533
9,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,funder,https://openalex.org/I34077533
10,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,funder,https://openalex.org/I188538660
11,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
12,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
13,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
14,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
15,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
16,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
17,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
18,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,funder,https://openalex.org/I1292842697
24,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,funder,https://openalex.org/I1292842697

In [110]:
missing_index(institution_df)

[]

In [111]:
#  Use afiliations column that is already fixed
# normalize nested  column
#affiliations_df = CleanJSON('affiliations', authors_df)

# remove list format for lineage
#affiliations_df['institution_ids'] = affiliations_df['institution_ids'].str[0]

# rename columns
#affiliations_df = affiliations_df.rename(columns={'institution_ids': 'affiliations_lineage'})
#affiliations_df

#affiliations_df

In [112]:
#missing_index(affiliations_df)

In [113]:
#len(affiliations_df)

In [114]:
#remove duplicate indices 
#affiliations_df = affiliations_df.reset_index()
#affiliations_df = affiliations_df.reindex(range(affiliations_df.index.min(), affiliations_df.index.max()+1))
#affiliations_df

In [115]:
#  check if there are any mission indices
#missing_index(affiliations_df)

In [116]:
topics_df = CleanJSON('topics', authors_df)
topics_df = topics_df.rename(columns={'id': 'topic_id', 'display_name': 'topic_name'})
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13126,Scientific Research and Discoveries,0.6482,"{'id': 'https://openalex.org/subfields/3109', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
10566,https://openalex.org/T12338,Digital literacy in education,0.3392,"{'id': 'https://openalex.org/subfields/1710', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
10566,https://openalex.org/T13895,Educational Leadership and Innovation,0.2918,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T10443,Social Policy and Reform Studies,0.8562,"{'id': 'https://openalex.org/subfields/3320', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T13825,Economic Policies and Impacts,0.7859,"{'id': 'https://openalex.org/subfields/2002', ...","{'id': 'https://openalex.org/fields/20', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T11544,"Gender, Labor, and Family Dynamics",0.7775,"{'id': 'https://openalex.org/subfields/3318', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."

In [117]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [118]:
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
10563,https://openalex.org/T13283,Mental Health Research Topics,0.1228,"{'id': 'https://openalex.org/subfields/3205', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10564,https://openalex.org/T13532,Education Systems and Policy,0.3401,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10565,https://openalex.org/T13532,Education Systems and Policy,0.3401,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10566,https://openalex.org/T13532,Education Systems and Policy,0.3401,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T10443,Social Policy and Reform Studies,0.8562,"{'id': 'https://openalex.org/subfields/3320', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."

In [119]:
missing_index(topics_df)

[]

In [120]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'subfield_id', 'display_name': 'subfield_name'})
field_df = field_df.rename(columns={'id': 'field_id', 'display_name': 'field_name'})
domain_df = domain_df.rename(columns={'id': 'domain_id', 'display_name': 'domain_name'})

field_df

                             field_id             field_name
0      https://openalex.org/fields/23  Environmental Science
1      https://openalex.org/fields/23  Environmental Science
2      https://openalex.org/fields/23  Environmental Science
3      https://openalex.org/fields/23  Environmental Science
4      https://openalex.org/fields/23  Environmental Science
...                               ...                    ...
10563  https://openalex.org/fields/32             Psychology
10564  https://openalex.org/fields/33        Social Sciences
10565  https://openalex.org/fields/33        Social Sciences
10566  https://openalex.org/fields/33        Social Sciences
10567  https://openalex.org/fields/33        Social Sciences

[10568 rows x 2 columns]

In [121]:
topics_df = topics_df[['topic_id', 'topic_name']]

In [122]:
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...
10563,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [123]:
# concat insitution_df and topics_df
#institution_df = institution_df.reset_index()
#merged_list = [institution_df, affiliations_df, topics_df]

merged_list = [institution_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,funder,https://openalex.org/I121934306,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [124]:
unnested_df = authors_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/A5111425891,Paul Glewwe,None
10566,2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/A5031469107,Paul Goren,None

In [125]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'topics', 'language', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'author_id',
       'author_name', 'orcid'],
      dtype='object')

In [126]:
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'author_id',
       'author_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid
0,first,[US],False,Claire Porter,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,middle,[US],False,Paul Morin,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,middle,[US],False,Ian Howat,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,middle,[US],False,Myoung-Jon Noh,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,middle,[US],False,Brian Bates,(National Geospatial-Intelligence Agency),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,first,[US],True,Yoon-Hee Cha,(University of Minnesota),https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,first,[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,middle,[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5111425891,Paul Glewwe,None
10566,last,[],False,Uttam Sharma,(Independent Consultant),https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,first,[US],True,Paul Goren,(University of Minnesota),https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5031469107,Paul Goren,None

In [127]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,first,[US],False,Claire Porter,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,middle,[US],False,Paul Morin,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,middle,[US],False,Ian Howat,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,middle,[US],False,Myoung-Jon Noh,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5102675431,Myoung-Jon Noh,None,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,middle,[US],False,Brian Bates,(National Geospatial-Intelligence Agency),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5109469110,B. Bates,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,first,[US],True,Yoon-Hee Cha,(University of Minnesota),https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,first,[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5069760554,Julie Anderson Schaffner,None,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,funder,https://openalex.org/I121934306,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,middle,[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5111425891,Paul Glewwe,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,last,[],False,Uttam Sharma,(Independent Consultant),https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,first,[US],True,Paul Goren,(University of Minnesota),https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,False,datacite,True,gold,other-oa,Harvard Dataverse,https://openalex.org/A5031469107,Paul Goren,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [128]:
# check for nan authors
unnested_df['author_name'].isnull().values.any()

False

In [129]:
# remove rows where authors are NaN
#unnested_df = unnested_df.iloc[:10568]
#unnested_df

In [130]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'Repository', 'author_id', 'author_name',
       'orcid', 'institution_id', 'institution_name', 'ror', 'country_code',
       'funding_type', 'lineage', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name'],
      dtype='object')

In [131]:
unnested_df = unnested_df[['id', 'doi', 'type', 'funding_type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name', 'retracted', 'index location',
       'Repository', 'is_oa', 'oa_status', 'license', 'author_id',
       'author_name', 'author_position', 'orcid', 
       'institution_id', 'institution_name', 'raw_affiliation_strings',  'country_code', 'ror',
        'lineage']]
unnested_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,middle,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,(The Ohio State University),US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,middle,None,https://openalex.org/I52357470,The Ohio State University,(The Ohio State University),US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,middle,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,(National Geospatial-Intelligence Agency),US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,funder,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
10564,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,funder,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,first,None,https://openalex.org/I121934306,Tufts University,"(The Fletcher School, Tufts University)",US,https://ror.org/05wvpxv85,https://openalex.org/I121934306
10565,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,funder,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,None,https://openalex.org/I130238516,University of Minnesota,"(Department of Applied Economics, University o...",US,https://ror.org/017zqws13,https://openalex.org/I130238516
10566,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,NaN,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,last,https://orcid.org/0000-0001-5108-8872,NaN,NaN,(Independent Consultant),NaN,NaN,NaN
10567,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,funder,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,None,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516

In [132]:
#unnested_df.to_csv('DCNAuthorsOpenAlexData.csv')

In [133]:
# subset to ror ids
ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572') | (unnested_df['ror'] == 'https://ror.org/017zqws13') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') 
                                            | (unnested_df['ror'] == 'https://ror.org/00x6h5n95') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') | (unnested_df['ror'] == 'https://ror.org/047426m28') 
                                            | (unnested_df['ror'] == 'https://ror.org/03arq3225') | (unnested_df['ror'] == 'https://ror.org/04sac7215') | (unnested_df['ror'] == 'https://ror.org/02ttsq026') 
                                            | (unnested_df['ror'] == 'https://ror.org/05bnh6r87') | (unnested_df['ror'] == 'https://ror.org/02smfhw86') | (unnested_df['ror'] == 'https://ror.org/01y2jtd41') 
                                            | (unnested_df['ror'] == 'https://ror.org/00hx57361') | (unnested_df['ror'] == 'https://ror.org/04p491231') | (unnested_df['ror'] == 'https://ror.org/0153tk833')
                                            | (unnested_df['ror'] == 'https://ror.org/00b30xv10') | (unnested_df['ror'] == 'https://ror.org/00py81415') | (unnested_df['ror'] == 'https://ror.org/01yc7t268') 
                                            | (unnested_df['ror'] == 'https://ror.org/05fs6jp91') | (unnested_df['ror'] == 'https://ror.org/043mer456')].reset_index(drop=True)
ror_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,author_id,author_name,author_position,orcid,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5018856299,M. J. Willis,middle,https://orcid.org/0000-0001-7872-770X,https://openalex.org/I188538660,University of Colorado Boulder,(University of Colorado Boulder),US,https://ror.org/02ttsq026,https://openalex.org/I188538660
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5114168374,Cole Kelleher,middle,None,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,funder,"ArcticDEM, Version 3",2018,2018-01-01,en,NaN,NaN,NaN,False,484,0.997735,True,True,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111210501,Michael Cloutier,middle,None,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,dataset,funder,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T10557,Social Media and Politics,https://openalex.org/subfields/3315,Communication,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5038879126,Rocío Titiunik,last,https://orcid.org/0000-0001-5145-3059,https://openalex.org/I20089843,Princeton University,(Princeton University),US,https://ror.org/00hx57361,https://openalex.org/I20089843
3015,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,dataset,funder,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T11147,Misinformation and Its Impacts,https://openalex.org/subfields/3312,Sociology and Political Science,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5022408597,Emily K. Vraga,first,https://orcid.org/0000-0002-3016-3869,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
3016,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,dataset,funder,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516
3017,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,dataset,funder,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,None,https://openalex.org/I130238516,University of Minnesota,"(Department of Applied Economics, University o...",US,https://ror.org/017zqws13,https://openalex.org/I130238516
3018,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,dataset,funder,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,NaN,NaN,NaN,False,0,0.000000,False,False,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,None,https://openalex.org/I130238516,University of Minnesota,(University of Minnesota),US,https://ror.org/017zqws13,https://openalex.org/I130238516

In [ ]:
# Only authors from DCN institutions
ror_df.to_csv('OpenAlexDataCitation.csv')

In [137]:
# Only authors from UMN 
ror_df.to_csv('OpenAlexMNData.csv')