In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('2026-04-22-UMN-Source.csv', index_col=0)

In [4]:
pd.set_option("display.max_columns", 55)

In [5]:
df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
def Matching_columns(df, col1, col2):
    match = df[col1].equals(df[col2])
    return match

In [7]:
# primary topic
Matching_columns(df, 'primary_topic-display_name', 'topics-display_name')

True

In [8]:
# subfield
Matching_columns(df, 'primary_topic-subfield', 'topics-subfield-id')

True

In [9]:
# field
Matching_columns(df, 'primary_topic-field', 'topics-field-id')

True

In [10]:
# domain
Matching_columns(df, 'primary_topic-domain', 'topics-domain-id')

True

In [11]:
len(df['topics-display_name'])

2459

In [12]:
df['ror'].isna().sum(), df['orcid'].isna().sum(), (df['is_oa'] == False).sum()

(2177, 872, 268)

In [13]:
(df['ror'].isna() & df['orcid'].isna()).sum()

767

In [14]:
df['ror'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['ror'], ascending=False).reset_index(drop=True)

    publication_year  ror
0               2026   88
1               2025   65
2               2018   25
3               2019   20
4               2020   17
5               2021   15
6               2022   12
7               2016   10
8               2017    8
9               2014    5
10              2015    5
11              2006    3
12              1998    2
13              2003    2
14              2011    2
15              2023    1
16              2005    1
17              2010    1
18              1990    0
19              1971    0
20              1973    0
21              1972    0
22              1966    0
23              1970    0
24              1969    0
25              1979    0
26              2024    0
27              1964    0
28              1975    0
29              2012    0
30              1983    0
31              2013    0
32              1993    0
33              2009    0
34              2008    0
35              2007    0
36              1959    0
37              2004    0
38              2002    0
39              2001    0
40              1912    0

In [15]:
topics_display_name_ror_perc = df['ror'].count()
print('the # of ROR IDs assigned to DOIs is:', topics_display_name_ror_perc), print('the % of ROR IDs assigned to DOIs is:', round(topics_display_name_ror_perc / len(df) * 100, 3),'%')

the # of ROR IDs assigned to DOIs is: 282
the % of ROR IDs assigned to DOIs is: 11.468 %

(None, None)

In [16]:
topics_display_name_ror = df['ror'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_display_name_ror['ror %'] = round(topics_display_name_ror['ror'] / sum(topics_display_name_ror['ror']) * 100, 4)
topics_display_name_ror.head(15).reset_index(drop=True)

                           topics-display_name  ror   ror %
0               Smoking Behavior and Cessation  102  5.0271
1   Nanopore and Nanochannel Transport Studies   71  3.4993
2          Fish Ecology and Management Studies   39  1.9221
3            Rangeland and Wildlife Management   36  1.7743
4               DNA and Nucleic Acid Chemistry   35  1.7250
5           3D Printing in Biomedical Research   34  1.6757
6      Species Distribution and Climate Change   33  1.6264
7                Forest ecology and management   33  1.6264
8      Wheat and Barley Genetics and Pathology   31  1.5278
9              Archaeology and Natural History   26  1.2814
10   Aquatic Invertebrate Ecology and Behavior   24  1.1828
11       Remote Sensing and LiDAR Applications   24  1.1828
12                        Data Analysis with R   23  1.1336
13  Genetic and phenotypic traits in livestock   21  1.0350
14  Groundwater flow and contamination studies   19  0.9364

In [17]:
df['orcid'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['orcid'], ascending=False).reset_index(drop=True)

    publication_year  orcid
0               2018    235
1               2017    174
2               2019    159
3               2020    152
4               2016    135
5               2015    126
6               2021    117
7               2014    105
8               2013    102
9               2025     53
10              2026     40
11              2010     40
12              2012     35
13              2009     19
14              2022     14
15              2006     14
16              1993     10
17              1983      9
18              2007      8
19              1998      5
20              2011      5
21              1964      4
22              2008      4
23              2001      4
24              2005      3
25              1975      3
26              1990      2
27              1979      2
28              1966      1
29              2024      1
30              2023      1
31              2002      1
32              2003      1
33              1959      1
34              2004      1
35              1912      1
36              1972      0
37              1971      0
38              1970      0
39              1969      0
40              1973      0

In [18]:
topics_display_name_orcid_perc = df['orcid'].count()
print('the # of ORCID IDs assigned to DOIs is:', topics_display_name_orcid_perc), print('the % of ORCID IDs assigned to DOIs is:', round(topics_display_name_orcid_perc / len(df) * 100, 3),'%')

the # of ORCID IDs assigned to DOIs is: 1587
the % of ORCID IDs assigned to DOIs is: 64.538 %

(None, None)

In [19]:
topics_display_name_orcid = df['orcid'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['orcid'], ascending=False)
topics_display_name_orcid['orcid %'] = round(topics_display_name_orcid['orcid'] / sum(topics_display_name_orcid['orcid']) * 100, 4)
topics_display_name_orcid.head(15).reset_index(drop=True)

                           topics-display_name  orcid  orcid %
0               Smoking Behavior and Cessation    102  15.3614
1              Archaeology and Natural History     24   3.6145
2   Nanopore and Nanochannel Transport Studies     17   2.5602
3          Fish Ecology and Management Studies     14   2.1084
4        Remote Sensing and LiDAR Applications     14   2.1084
5   Genetic and phenotypic traits in livestock     13   1.9578
6   Groundwater flow and contamination studies     11   1.6566
7            Solar Radiation and Photovoltaics     11   1.6566
8            Rangeland and Wildlife Management     11   1.6566
9          Water Quality and Resources Studies     10   1.5060
10              DNA and Nucleic Acid Chemistry      9   1.3554
11                        Data Analysis with R      9   1.3554
12           Urban Transport and Accessibility      9   1.3554
13               Forest ecology and management      8   1.2048
14              Soil Geostatistics and Mapping      8   1.2048

In [20]:
topics_subfield_display_name_ror = df['ror'].isna().groupby(df['topics-subfield-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_subfield_display_name_ror.head(15).reset_index(drop=True)

                    topics-subfield-display_name  ror
0                                        Ecology  153
1                         Biomedical Engineering  139
2                              Molecular Biology  132
3                                  Plant Science  111
4                                     Physiology  102
5                        Artificial Intelligence   93
6              Nature and Landscape Conservation   76
7                      Environmental Engineering   75
8                            Materials Chemistry   65
9                    Global and Planetary Change   48
10                                      Genetics   44
11  Ecology, Evolution, Behavior and Systematics   37
12                  Water Science and Technology   34
13                           Ecological Modeling   33
14                         Aerospace Engineering   30

In [21]:

topics_field_display_name_ror = df['ror'].isna().groupby(df['topics-field-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_field_display_name_ror.head(15).reset_index(drop=True)

                       topics-field-display_name  ror
0                          Environmental Science  498
1                                    Engineering  277
2   Biochemistry, Genetics and Molecular Biology  211
3           Agricultural and Biological Sciences  209
4                               Computer Science  153
5                                       Medicine  147
6                                Social Sciences  101
7                              Materials Science   96
8                                      Chemistry   69
9                   Earth and Planetary Sciences   45
10                                    Psychology   32
11           Economics, Econometrics and Finance   25
12                         Physics and Astronomy   25
13                            Health Professions   22
14                          Chemical Engineering   19

In [22]:
df['orcid'].notna().groupby(df['cited_by_count']).sum().reset_index().sort_values(by=['cited_by_count'], ascending=False).reset_index(drop=True)

    cited_by_count  orcid
0               41      5
1               28      3
2               17      1
3               12      5
4               11      3
5               10      0
6                9      2
7                8      3
8                7      1
9                6      4
10               5      8
11               4     14
12               3     31
13               2     59
14               1    229
15               0   1219

In [23]:
df['title'].groupby(df['cited_by_count']).sum().reset_index().sort_values(by=['cited_by_count'], ascending=False).reset_index(drop=True)

    cited_by_count                                              title
0               41  Minnesota Solvation Database (MNSOL) version 2...
1               28  White-tailed deer density estimates across the...
2               17  Global nitrogen deposition (2°×2.5° grid resol...
3               12  Minnesota Land Cover Classification and Imperv...
4               11  Home range overlap indices implemented using k...
5               10  Data Related to: Association studies of up to ...
6                9  Geometries for Minnesota Database 2019Geometri...
7                8  Clinical Abbreviation Sense InventoryClinical ...
8                7  Historical Population Estimates for 2010 U.S. ...
9                6  datasets for Using Verbs and Adjectives to Aut...
10               5  Access Across America: Transit 2014 DataAccess...
11               4  Small UAV Position and Attitude, Raw Sensor, a...
12               3  Transportation and Quality of Life: An Annotat...
13               2  Karst Features of MinnesotaKarst Features of M...
14               1  1958 Twin Cities Land Use Map from the Twin Ci...
15               0  OFR14-05, A HYDROCHEMICAL SURVEY OF GROUNDWATE...

In [75]:
OpenAccessdf = df[df['is_oa'] == True]
OpenAccessdf = OpenAccessdf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total open access cited by count is:', OpenAccessdf['cited_by_count'].sum())
print('Average open access cited by count is:', OpenAccessdf['cited_by_count'].mean())
OpenAccessdf.head(15)

Total open access cited by count is: 410
Average open access cited by count is: 0.6376360808709176

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   White-tailed deer density estimates across the...              28
2   Global nitrogen deposition (2°×2.5° grid resol...              17
3   Minnesota Land Cover Classification and Imperv...              12
4   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
5   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
6   Trash-ICRA19: A bounding box labeled dataset o...              11
7   Home range overlap indices implemented using k...              11
8   Data Related to: Association studies of up to ...              10
9              Geometries for Minnesota Database 2019               9
10           Access Across America: Transit 2017 Data               8
11  Historical Population Estimates for 2010 U.S. ...               7
12  Twin Cities Metropolitan Area 1-Meter Land Cov...               7
13                           APAL Coupling Study 2019               6
14  DynamoVis - Dynamic Visualization of Animal Mo...               6

In [25]:
NonOpenAccessdf = df[df['is_oa'] == False]
NonOpenAccessdf = NonOpenAccessdf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total non open access cited by count is:', NonOpenAccessdf['cited_by_count'].sum())
print('Average non open access cited by count is:', NonOpenAccessdf['cited_by_count'].mean())
NonOpenAccessdf.head(15)

Total non open access cited by count is: 17
Average non open access cited by count is: 0.18888888888888888

                                                title  cited_by_count
0               Clinical Abbreviation Sense Inventory               8
1   datasets for Using Verbs and Adjectives to Aut...               6
2    GRAVITY AND AEROMAGNETIC DATA GRIDS OF MINNESOTA               3
3   Data from: One-parameter scaling theory for DN...               0
4   Data from: The backfolded Odijk regime for wor...               0
5   Data from: Simulation of DNA Extension in Nano...               0
6   Data from: Entropic Depletion of DNA in Triang...               0
7   Data from: Alpha-Synuclein Modulates the Physi...               0
8   Data from: Wall depletion length of a channel-...               0
9   Data from: Odijk excluded volume interactions ...               0
10  Data from: Effect of excluded volume on the fo...               0
11  Data from: Coupled Flow and Reaction during Na...               0
12  Data from: Rapid, selective, label-free aptame...               0
13            Black Spruce Diameter Growth Model Data               0
14  Data from: Microfluidic chemostat for measurin...               0

In [26]:
HasAnyOrcidDf = df.groupby('title').filter(lambda x: x['orcid'].str.contains('orcid').any())
HasAnyOrcidDf.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [27]:
HasAnyOrcidDf['orcid'].value_counts().notna().any()

True

In [28]:
HasNoOrcidDf = df[~df.isin(HasAnyOrcidDf.to_dict(orient="list")).all(axis=1)]
HasNoOrcidDf.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
13,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,dataset,NaN,Minnesota Land Cover Classification and Imperv...,2016,2016-01-01,en,https://openalex.org/A5077086878,Lian P. Rampi,first,NaN,https://openalex.org/T13388,Rangeland and Wildlife Management,0.9871,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T13388,Rangeland and Wildlife Management,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,12,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN
24,https://openalex.org/W2929793724,https://doi.org/10.13020/3b1n-ff32,dataset,NaN,Data Related to: Association studies of up to ...,2019,2019-01-28,en,NaN,GSCAN consortium,first,NaN,https://openalex.org/T10060,Smoking Behavior and Cessation,0.5695,https://openalex.org/subfields/2737,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T10060,Smoking Behavior and Cessation,https://openalex.org/subfields/2737,Physiology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,NaN,NaN,NaN,False,10,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN
33,https://openalex.org/W2521289635,https://doi.org/10.13020/d6959b,dataset,NaN,Twin Cities Metropolitan Area 1-Meter Land Cov...,2016,2016-01-01,en,https://openalex.org/A5079806805,Trevor K Host,first,NaN,https://openalex.org/T13890,Remote Sensing and Land Use,0.8833,https://openalex.org/subfields/1902,https://openalex.org/fields/19,https://openalex.org/domains/3,https://openalex.org/T13890,Remote Sensing and Land Use,https://openalex.org/subfields/1902,Atmospheric Science,https://openalex.org/fields/19,Earth and Planetary Sciences,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,7,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN
59,https://openalex.org/W1601229860,https://doi.org/10.13020/d6bc7z,dataset,NaN,"Small UAV Position and Attitude, Raw Sensor, a...",2015,2015-03-04,en,https://openalex.org/A5109359043,Hamid Mokhtarzadeh,first,NaN,https://openalex.org/T10191,Robotics and Sensor-Based Localization,0.9650,https://openalex.org/subfields/2202,https://openalex.org/fields/22,https://openalex.org/domains/3,https://openalex.org/T10191,Robotics and Sensor-Based Localization,https://openalex.org/subfields/2202,Aerospace Engineering,https://openalex.org/fields/22,Engineering,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,4,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN
60,https://openalex.org/W1601229860,https://doi.org/10.13020/d6bc7z,dataset,NaN,"Small UAV Position and Attitude, Raw Sensor, a...",2015,2015-03-04,en,https://openalex.org/A5051569912,Todd Colten,last,NaN,https://openalex.org/T10191,Robotics and Sensor-Based Localization,0.9650,https://openalex.org/subfields/2202,https://openalex.org/fields/22,https://openalex.org/domains/3,https://openalex.org/T10191,Robotics and Sensor-Based Localization,https://openalex.org/subfields/2202,Aerospace Engineering,https://openalex.org/fields/22,Engineering,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,4,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN

In [29]:
HasNoOrcidDf['orcid'].value_counts().isna().all()

True

In [30]:
has_matching_rows = not HasNoOrcidDf.merge(HasAnyOrcidDf).empty
has_matching_rows

False

In [31]:
has_matching_rows = pd.merge(HasAnyOrcidDf, HasNoOrcidDf, how='inner')
has_matching_rows

Empty DataFrame
Columns: [id, doi, type, institutions-type, title, publication_year, publication_date, language, authorships-author-author_id, authorships-author-display_name, author_position, orcid, primary_topic-id, primary_topic-display_name, primary_topic-score, primary_topic-subfield, primary_topic-field, primary_topic-domain, topics-id, topics-display_name, topics-subfield-id, topics-subfield-display_name, topics-field-id, topics-field-display_name, topics-domain-id, topics-domain-display_name, apc_list, apc_paid, fwci, has_fulltext, cited_by_count, volume, issue, first_page, last_page, index location, primary_location-source-display_name, retracted, is_oa, oa_status, license, institutions-id, institutions-display_name, raw_affiliation_strings, country_code, ror, lineage]
Index: []

In [51]:
OrcidDF = HasAnyOrcidDf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total Orcid cited by count is:', OrcidDF['cited_by_count'].sum())
print('Average Orcid cited by count is:', OrcidDF['cited_by_count'].mean())
OrcidDF.head(15)

Total Orcid cited by count is: 376
Average Orcid cited by count is: 0.6045016077170418

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   White-tailed deer density estimates across the...              28
2   Global nitrogen deposition (2°×2.5° grid resol...              17
3   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
4   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
5   Home range overlap indices implemented using k...              11
6   Trash-ICRA19: A bounding box labeled dataset o...              11
7              Geometries for Minnesota Database 2019               9
8               Clinical Abbreviation Sense Inventory               8
9            Access Across America: Transit 2017 Data               8
10  Historical Population Estimates for 2010 U.S. ...               7
11                           APAL Coupling Study 2019               6
12  datasets for Using Verbs and Adjectives to Aut...               6
13  DynamoVis - Dynamic Visualization of Animal Mo...               6
14  R Code and Output Supporting: Resampling-Based...               5

In [52]:
NAOrcidDF = HasNoOrcidDf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total NaN Orcid cited by count is:', NAOrcidDF['cited_by_count'].sum())
print('Average NaN Orcid cited by count is:', NAOrcidDF['cited_by_count'].mean())
NAOrcidDF.head(15)

Total NaN Orcid cited by count is: 51
Average NaN Orcid cited by count is: 0.4594594594594595

                                                title  cited_by_count
0   Minnesota Land Cover Classification and Imperv...              12
1   Data Related to: Association studies of up to ...              10
2   Twin Cities Metropolitan Area 1-Meter Land Cov...               7
3   Small UAV Position and Attitude, Raw Sensor, a...               4
4    GRAVITY AND AEROMAGNETIC DATA GRIDS OF MINNESOTA               3
5   2011 Rock Properties Database: Density, Magnet...               2
6   Complete Data and Analysis for: Fungicide Effe...               1
7                                           ProDenCeR               1
8   ableC: Extensible Specification of C Using the...               1
9   Cross-Cultural Interaction and Migration: Reth...               1
10  Investigation of Human First-Person Motion Gui...               1
11  Supplemental Materials to Hierarchical Modelin...               1
12  Rochester 1-Meter Land Cover Classification (U...               1
13                    FASER Static Test 153 NASA LaRC               1
14  Duluth 1-Meter Land Cover Classification (Urba...               1

In [53]:
HasAnyrorDf = df.groupby('title').filter(lambda x: x['ror'].str.contains('ror').any())
HasAnyrorDf.head(15)

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
5,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5016283052,David J. Giesen,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
6,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5024124704,Paul Winget,middle,https://orcid.org/0000-0002-3443-7556,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
7,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,education,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5048985028,Christopher J. Cramer,middle,https://orcid.org/0000-0001-5048-1859,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
8,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,education,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061717048,Donald G. Truhlar,last,https://orcid.org/0000-0002-7742-7294,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
45,https://openalex.org/W1527143013,https://doi.org/10.13020/d6mw2q,dataset,education,Access Across America: Transit 2014 Data,2014,2014-12-08,en,https://openalex.org/A5110314160,Andrew Owen,first,NaN,https://openalex.org/T11344,Traffic Prediction and Management Techniques,0.5395,https://openalex.org/subfields/2215,https://openalex.org/fields/22,https://openalex.org/domains/3,https://openalex.org/T11344,Traffic Prediction and Management Techniques,https://openalex.org/subfields/2215,Building and Construction,https://openalex.org/fields/22,Engineering,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,True,5,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,other-oa,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
46,https://openalex.org/W1527143013,https://doi.org/10.13020/d6mw2q,dataset,education,Access Across America: Transit 2014 Data,2014,2014-12-08,en,https://openalex.org/A5084766858,David Levinson,last,https://orcid.org/0000-0002-4563-2963,https://openalex.org/T11344,Traffic Prediction and Management Techniques,0.5395,https://openalex.org/subfields/2215,https://openalex.org/fields/22,https://openalex.org/domains/3,https://openalex.org/T11344,Traffic Prediction and Management Techniques,https://openalex.org/subfields/2215,Building and Construction,https://openalex.org/fields/22,Engineering,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,True,5,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,other-oa,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
56,https://openalex.org/W3121198388,https://doi.org/10.13020/wn56-9y75,dataset,education,R Code and Output Supporting: Resampling-Based...,2020,2020-03-02,en,https://openalex.org/A5030821429,John Fieberg,first,https://orcid.org/0000-0002-3180-7021,https://openalex.org/T13398,Data Analysis with R,0.6752,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T13398,Data Analysis with R,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,5,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
57,https://openalex.org/W3121198388,https://doi.org/10.13020/wn56-9y75,dataset,NaN,R Code and Output Supporting: Resampling-Based...,2020,2020-03-02,en,NaN,"Vitense, Kelsy",middle,NaN,https://openalex.org/T13398,Data Analysis with R,0.6752,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T13398,Data Analysis with R,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,5,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
58,https://openalex.org/W3121198388,https://doi.org/10.13020/wn56-9y75,dataset,NaN,R Code and Output Supporting: Resampling-Based...,2020,2020-03-02,en,https://openalex.org/A5012150828,Douglas H. Johnson,last,https://orcid.org/0000-0002-7778-6641,https://openalex.org/T13398,Data Analysis with R,0.6752,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T13398,Data Analysis with R,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,5,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,https://openalex.org/W3186285238,https://doi.org/10.13020/zqw9-mk81,dataset,education,"Lake Superior moored temperature and currents,...",2005,2005-09-01,en,https://openalex.org/A5082130798,Jay A. Austin,first,https://orcid.org/0000-0002-3580-1794,https://openalex.org/T10302,Fish Ecology and Management Studies,0.8587,https://openalex.org/subfields/2309,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10302,Fish Ecology and Management Studies,https://openalex.org/subfields/2309,Nature and Landscape Conservation,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,4,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,https://openalex.org/I4210115145,"University of Minnesota, Duluth","University of Minnesota, Duluth",US,https://ror.org/01hy4qx27,https://openalex.org/I4210115145

In [54]:
HasAnyrorDf['ror'].value_counts().notna().any()

True

In [55]:
HasNoRor = df[~df.isin(HasAnyrorDf.to_dict(orient="list")).all(axis=1)]
HasNoRor.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
9,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,dataset,NaN,White-tailed deer density estimates across the...,2016,2016-01-01,en,https://openalex.org/A5014726860,Brian F. Walters,first,https://orcid.org/0000-0001-7408-9704,https://openalex.org/T10199,Wildlife Ecology and Conservation,0.9984,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10199,Wildlife Ecology and Conservation,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,28,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,dataset,NaN,White-tailed deer density estimates across the...,2016,2016-01-01,en,https://openalex.org/A5039275273,Christopher W. Woodall,middle,https://orcid.org/0000-0001-8076-6214,https://openalex.org/T10199,Wildlife Ecology and Conservation,0.9984,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10199,Wildlife Ecology and Conservation,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,28,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,dataset,NaN,White-tailed deer density estimates across the...,2016,2016-01-01,en,https://openalex.org/A5008534219,Matthew B. Russell,last,https://orcid.org/0000-0002-7044-9650,https://openalex.org/T10199,Wildlife Ecology and Conservation,0.9984,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10199,Wildlife Ecology and Conservation,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,28,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,dataset,NaN,Global nitrogen deposition (2°×2.5° grid resol...,2018,2018-01-01,en,https://openalex.org/A5031063931,Daniel Ackerman,first,https://orcid.org/0000-0002-9305-4184,https://openalex.org/T11588,Atmospheric and Environmental Gas Dynamics,0.9984,https://openalex.org/subfields/2306,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T11588,Atmospheric and Environmental Gas Dynamics,https://openalex.org/subfields/2306,Global and Planetary Change,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,17,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,dataset,NaN,Minnesota Land Cover Classification and Imperv...,2016,2016-01-01,en,https://openalex.org/A5077086878,Lian P. Rampi,first,NaN,https://openalex.org/T13388,Rangeland and Wildlife Management,0.9871,https://openalex.org/subfields/2303,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T13388,Rangeland and Wildlife Management,https://openalex.org/subfields/2303,Ecology,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,12,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,public-domain,NaN,NaN,NaN,NaN,NaN,NaN

In [56]:
HasNoRor['ror'].value_counts().isna().all()

True

In [57]:
Ror_has_matching_rows = not HasAnyrorDf.merge(HasNoRor).empty
Ror_has_matching_rows

False

In [58]:
RorDF = HasAnyrorDf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total Ror cited by count is:', RorDF['cited_by_count'].sum())
print('Average Ror cited by count is:', RorDF['cited_by_count'].mean())

RorDF.head(15)

Total Ror cited by count is: 74
Average Ror cited by count is: 0.8043478260869565

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   R Code and Output Supporting: Resampling-Based...               5
2            Access Across America: Transit 2014 Data               5
3   Lake Superior moored temperature and currents,...               4
4              Value of Curation Survey, January 2021               3
5   Three-Dimensional Models of Experimentally-Pro...               2
6   2011 Rock Properties Database: Density, Magnet...               2
7   Data supporting: "Testing Our Assumptions: Pre...               1
8   Complete Data and Analysis for: Constraining i...               1
9   Experimental alluvial-river and landsliding re...               1
10      Wildlife community data in black ash wetlands               1
11  Winter and summer zooplankton community and en...               1
12  Heating, Susceptibility, and XRD data for Diff...               1
13  APAL 2019: Postural Data, Game Performance, an...               1
14  2003 Rock Properties Database: Density, Magnet...               1

In [59]:
NARorDF = HasNoRor[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('total NaN Ror cited by count is:', NARorDF['cited_by_count'].sum())
print('Average  NaN Ror cited by count is:', NARorDF['cited_by_count'].mean())


NARorDF.head(15)

total NaN Ror cited by count is: 353
Average  NaN Ror cited by count is: 0.5507020280811232

                                                title  cited_by_count
0   White-tailed deer density estimates across the...              28
1   Global nitrogen deposition (2°×2.5° grid resol...              17
2   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
3   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
4   Minnesota Land Cover Classification and Imperv...              12
5   Home range overlap indices implemented using k...              11
6   Trash-ICRA19: A bounding box labeled dataset o...              11
7   Data Related to: Association studies of up to ...              10
8              Geometries for Minnesota Database 2019               9
9            Access Across America: Transit 2017 Data               8
10              Clinical Abbreviation Sense Inventory               8
11  Historical Population Estimates for 2010 U.S. ...               7
12  Twin Cities Metropolitan Area 1-Meter Land Cov...               7
13                           APAL Coupling Study 2019               6
14  datasets for Using Verbs and Adjectives to Aut...               6

In [80]:
topic_view_df = df[['title', 'doi', 'topics-domain-display_name', 'topics-field-display_name', 'topics-field-display_name', 'primary_topic-display_name']]
topic_view_df = topic_view_df.drop_duplicates(subset=['title']).reset_index(drop=True)
topic_view_df.head(15)

,title,doi,topics-domain-display_name,topics-field-display_name,topics-field-display_name,primary_topic-display_name
0,Minnesota Solvation Database (MNSOL) version 2012,https://doi.org/10.13020/3eks-j059,Physical Sciences,Computer Science,Computer Science,Geochemistry and Geologic Mapping
1,White-tailed deer density estimates across the...,https://doi.org/10.13020/d6g014,Physical Sciences,Environmental Science,Environmental Science,Wildlife Ecology and Conservation
2,Global nitrogen deposition (2°×2.5° grid resol...,https://doi.org/10.13020/d6kx2r,Physical Sciences,Environmental Science,Environmental Science,Atmospheric and Environmental Gas Dynamics
3,Minnesota Land Cover Classification and Imperv...,https://doi.org/10.13020/d6jp4s,Physical Sciences,Environmental Science,Environmental Science,Rangeland and Wildlife Management
4,TrashCan 1.0 An Instance-Segmentation Labeled ...,https://doi.org/10.13020/g1gx-y834,Physical Sciences,Materials Science,Materials Science,Electron and X-Ray Spectroscopy Techniques
5,Updated Code of GEOS-Chem Adjoint v35 for TROP...,https://doi.org/10.13020/g5xc-nj81,Physical Sciences,Environmental Science,Environmental Science,Methane Hydrates and Related Phenomena
6,Home range overlap indices implemented using k...,https://doi.org/10.13020/d6g59w,Physical Sciences,Mathematics,Mathematics,Statistical Methods and Inference
7,Trash-ICRA19: A bounding box labeled dataset o...,https://doi.org/10.13020/x0qn-y082,Physical Sciences,Earth and Planetary Sciences,Earth and Planetary Sciences,Underwater Acoustics Research
8,Data Related to: Association studies of up to ...,https://doi.org/10.13020/3b1n-ff32,Health Sciences,Medicine,Medicine,Smoking Behavior and Cessation
9,Geometries for Minnesota Database 2019,https://doi.org/10.13020/217y-8g32,Social Sciences,Social Sciences,Social Sciences,Geographic Information Systems Studies
10,Clinical Abbreviation Sense Inventory,NaN,Health Sciences,Health Professions,Health Professions,Medical Research and Practices
11,Access Across America: Transit 2017 Data,https://doi.org/10.13020/d6g68v,Physical Sciences,Engineering,Engineering,Traffic Prediction and Management Techniques
12,Historical Population Estimates for 2010 U.S. ...,https://doi.org/10.13020/d6xw2h,Physical Sciences,Mathematics,Mathematics,Census and Population Estimation
13,Twin Cities Metropolitan Area 1-Meter Land Cov...,https://doi.org/10.13020/d6959b,Physical Sciences,Earth and Planetary Sciences,Earth and Planetary Sciences,Remote Sensing and Land Use
14,datasets for Using Verbs and Adjectives to Aut...,NaN,Physical Sciences,Computer Science,Computer Science,Sentiment Analysis and Opinion Mining

In [62]:
domain_df = df.drop_duplicates(subset=['doi']).groupby(['topics-domain-display_name']).agg(cited_by_count=('cited_by_count', 'sum'), dataset_count=('topics-domain-display_name', 'count')).reset_index()

domain_df['domain_dataset %'] = domain_df['dataset_count'] / domain_df['dataset_count'].sum()
domain_df['domain_citation_mean'] = domain_df['cited_by_count'] / domain_df['dataset_count']
domain_df = domain_df[['topics-domain-display_name', 'cited_by_count', 'domain_citation_mean', 'dataset_count', 'domain_dataset %']]

domain_df.sort_values(by='domain_citation_mean', ascending=False).reset_index(drop=True).head(15)

,topics-domain-display_name,cited_by_count,domain_citation_mean,dataset_count,domain_dataset %
0,Health Sciences,24,1.090909,22,0.043137
1,Physical Sciences,315,0.969231,325,0.637255
2,Social Sciences,40,0.666667,60,0.117647
3,Life Sciences,26,0.252427,103,0.201961

In [ ]:
field_df = df.drop_duplicates(subset=['doi']).groupby(['topics-field-display_name']).agg(cited_by_count=('cited_by_count', 'sum'), dataset_count=('topics-field-display_name', 'count')).reset_index()

field_df['field_dataset %'] = field_df['dataset_count'] / field_df['dataset_count'].sum()
field_df['field_citation_mean'] = field_df['cited_by_count'] / field_df['dataset_count']
field_df = field_df[['topics-field-display_name', 'cited_by_count', 'field_citation_mean', 'dataset_count', 'field_dataset %']]

field_df.sort_values(by='field_citation_mean', ascending=False).reset_index(drop=True).head(15)

,topics-field-display_name,cited_by_count,field_citation_mean,dataset_count,field_dataset %
0,Mathematics,18,3.600000,5,0.009804
1,Health Professions,12,2.000000,6,0.011765
2,Earth and Planetary Sciences,34,1.478261,23,0.045098
3,Computer Science,68,1.478261,46,0.090196
4,Environmental Science,141,1.101562,128,0.250980
5,Dentistry,1,1.000000,1,0.001961
6,"Business, Management and Accounting",1,1.000000,1,0.001961
7,Medicine,11,0.785714,14,0.027451
8,Decision Sciences,7,0.777778,9,0.017647
9,Social Sciences,24,0.727273,33,0.064706
10,Materials Science,16,0.615385,26,0.050980
11,"Economics, Econometrics and Finance",4,0.571429,7,0.013725
12,"Biochemistry, Genetics and Molecular Biology",18,0.473684,38,0.074510
13,Engineering,30,0.461538,65,0.127451
14,Psychology,3,0.428571,7,0.013725

In [ ]:
subfield_df = df.drop_duplicates(subset=['doi']).groupby(['topics-subfield-display_name']).agg(cited_by_count=('cited_by_count', 'sum'), dataset_count=('topics-subfield-display_name', 'count')).reset_index()

subfield_df['subfield_dataset %'] = subfield_df['dataset_count'] / subfield_df['dataset_count'].sum()
subfield_df['subfield_citation_mean'] = subfield_df['cited_by_count'] / subfield_df['dataset_count']
subfield_df = subfield_df[['topics-subfield-display_name', 'cited_by_count', 'subfield_citation_mean', 'dataset_count', 'subfield_dataset %']]

subfield_df.sort_values(by='subfield_citation_mean', ascending=False).reset_index(drop=True).head(15)

,topics-subfield-display_name,cited_by_count,subfield_citation_mean,dataset_count,subfield_dataset %
0,Medical Terminology,8,8.000000,1,0.001961
1,Statistics and Probability,18,4.500000,4,0.007843
2,Physiology,11,3.666667,3,0.005882
3,"Surfaces, Coatings and Films",12,3.000000,4,0.007843
4,General Social Sciences,3,3.000000,1,0.001961
5,Oceanography,15,2.500000,6,0.011765
6,Artificial Intelligence,50,2.272727,22,0.043137
7,"General Economics, Econometrics and Finance",2,2.000000,1,0.001961
8,Computer Vision and Pattern Recognition,8,2.000000,4,0.007843
9,Information Systems and Management,6,2.000000,3,0.005882
10,Environmental Chemistry,16,2.000000,8,0.015686
11,"Geography, Planning and Development",10,1.666667,6,0.011765
12,Atmospheric Science,13,1.625000,8,0.015686
13,Cell Biology,3,1.500000,2,0.003922
14,Geophysics,3,1.500000,2,0.003922

In [42]:
df.head(5)

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [43]:
topic_df = df.drop_duplicates(subset=['doi']).groupby(['primary_topic-display_name']).agg(cited_by_count=('cited_by_count', 'sum'), dataset_count=('primary_topic-display_name', 'count')).reset_index()

topic_df['topic_dataset %'] = topic_df['dataset_count'] / topic_df['dataset_count'].sum()
topic_df['topic_citation_mean'] = topic_df['cited_by_count'] / topic_df['dataset_count']
topic_df = topic_df[['primary_topic-display_name', 'cited_by_count', 'topic_citation_mean', 'dataset_count', 'topic_dataset %']]

topic_df.sort_values(by='topic_citation_mean', ascending=False).reset_index(drop=True).head(15)

,primary_topic-display_name,cited_by_count,topic_citation_mean,dataset_count,topic_dataset %
0,Geochemistry and Geologic Mapping,41,20.500000,2,0.003922
1,Wildlife Ecology and Conservation,29,14.500000,2,0.003922
2,Statistical Methods and Inference,11,11.000000,1,0.001961
3,Medical Research and Practices,8,8.000000,1,0.001961
4,Census and Population Estimation,7,7.000000,1,0.001961
5,Methane Hydrates and Related Phenomena,13,6.500000,2,0.003922
6,Underwater Acoustics Research,12,6.000000,2,0.003922
7,Context-Aware Activity Recognition Systems,6,6.000000,1,0.001961
8,Atmospheric and Environmental Gas Dynamics,18,4.500000,4,0.007843
9,Robotics and Sensor-Based Localization,4,4.000000,1,0.001961
10,Survey Methodology and Nonresponse,4,4.000000,1,0.001961
11,Electron and X-Ray Spectroscopy Techniques,12,4.000000,3,0.005882
12,Environmental Conservation and Management,4,4.000000,1,0.001961
13,Smoking Behavior and Cessation,11,3.666667,3,0.005882
14,Biomedical Text Mining and Ontologies,7,3.500000,2,0.003922

In [44]:
df['topics-subfield-display_name'].value_counts().head(15)

topics-subfield-display_name
Ecology                                         159
Biomedical Engineering                          143
Molecular Biology                               134
Plant Science                                   113
Physiology                                      102
Artificial Intelligence                          97
Nature and Landscape Conservation                84
Environmental Engineering                        75
Materials Chemistry                              69
Global and Planetary Change                      48
Genetics                                         44
Information Systems                              40
Ecology, Evolution, Behavior and Systematics     37
Aerospace Engineering                            37
Water Science and Technology                     35
Name: count, dtype: int64

In [45]:
df['topics-subfield-display_name'].value_counts().sort_index()

topics-subfield-display_name
Aerospace Engineering           37
Agronomy and Crop Science       16
Analytical Chemistry            11
Animal Science and Zoology      12
Anthropology                    29
                                ..
Surfaces, Coatings and Films    11
Surgery                          1
Transportation                  31
Urban Studies                    1
Water Science and Technology    35
Name: count, Length: 125, dtype: int64

In [46]:
df.groupby(['topics-subfield-display_name', 'cited_by_count']).mean().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True).head(15)

TypeError: agg function failed [how->mean,dtype->object]

In [ ]:
df.groupby(['topics-subfield-display_name', 'title']).size().reset_index().sort_values(by=0, ascending=False).reset_index(drop=True).head(25)

,topics-subfield-display_name,title,0
0,Physiology,"Data Related to Meta-analysis of up to 622,409...",100
1,Biomedical Engineering,"Supporting data for ""3D Printed Organ Models w...",17
2,Environmental Engineering,Banking Groundwater - A study examining aquife...,16
3,Ocean Engineering,"Report to Dr. A. Petersen, Vice President for ...",14
4,Ecology,Data from range-wide study of migratory connec...,14
5,Global and Planetary Change,Supporting data for The hidden value of trees:...,14
6,Artificial Intelligence,"Solar Insolation, Minnesota (2006-2012)",13
7,Molecular Biology,Regions of High Confidence in Chinese Hamster ...,13
8,Environmental Engineering,"Digital Surface Model, Minnesota (2006-2012)",13
9,Nature and Landscape Conservation,Data for: Decades of tree planting in Northern...,12
10,Plant Science,Supporting data for Development of a multi-par...,11
11,Plant Science,Phenotypic and genotypic data of barley Gen10 ...,11
12,Biomedical Engineering,Supporting data for 3D Printed Stem-Cell Deriv...,11
13,Artificial Intelligence,R Code and Output Supporting: Computational re...,11
14,Molecular Biology,Raw data for: Biphasic Control of Cell Expansi...,11
15,Molecular Biology,Ensembles from dynamic refinement of non-phosp...,11
16,Plant Science,Maize 509 line TE PAV calls,10
17,Ecology,Data and R code for analysis of walleye and ye...,10
18,Plant Science,"Variants from ""The role of deleterious substit...",10
19,Materials Chemistry,"Supporting data for ""Catalysis-in-a-Box: Robot...",10
20,Nature and Landscape Conservation,Characterization of streams and rivers in the ...,9
21,Biomedical Engineering,Supporting Data for Internal Structure of Meth...,9
22,Organic Chemistry,Data from: Hairpins in the conformations of a ...,9
23,Social Psychology,MNREAD Baseline Data for Normal Vision Across ...,9
24,Ecology,Raw Light-Level Geolocator Data from Golden-Wi...,9

In [ ]:
df['topics-subfield-display_name'].value_counts()

topics-subfield-display_name
Ecology                                  159
Biomedical Engineering                   143
Molecular Biology                        134
Plant Science                            113
Physiology                               102
                                        ...
Archeology                                 1
Museology                                  1
Occupational Therapy                       1
Safety, Risk, Reliability and Quality      1
Safety Research                            1
Name: count, Length: 125, dtype: int64

In [ ]:
df

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2454,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,NaN,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,https://openalex.org/A5019127857,Stephen Palka,middle,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by,NaN,NaN,NaN,NaN,NaN,NaN
2455,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,NaN,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,https://openalex.org/A5048502234,Devon Piernot,middle,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by,NaN,NaN,NaN,NaN,NaN,NaN
2456,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,NaN,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,https://openalex.org/A5006917855,Dan Thiede,middle,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by,NaN,NaN,NaN,NaN,NaN,NaN
2457,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,NaN,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,https://openalex.org/A5007673815,Yiquan Xie,middle,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by,NaN,NaN,NaN,NaN,NaN,NaN
2458,https://openalex.org/W925720530,https://doi.org/10.13020/d6x59x,dataset,NaN,"Solar Insolation, Minnesota (2006-2012)",2015,2015-06-29,en,https://openalex.org/A5025818352,Andrew Walz,last,NaN,https://openalex.org/T11276,Solar Radiation and Photovoltaics,0.9639,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T11276,Solar Radiation and Photovoltaics,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,0,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
topic_cited_df = df.drop_duplicates(subset=['doi'])
topic_cited_df = topic_cited_df.groupby(['primary_topic-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True)
topic_cited_df['cited_by_count_mean'] = topic_cited_df['cited_by_count'] / doi_count


topic_cited_df.head(15)

,primary_topic-display_name,cited_by_count,cited_by_count_mean
0,Geochemistry and Geologic Mapping,41,0.071304
1,Wildlife Ecology and Conservation,29,0.050435
2,Atmospheric and Environmental Gas Dynamics,18,0.031304
3,Fish Ecology and Management Studies,15,0.026087
4,Traffic Prediction and Management Techniques,15,0.026087
5,Rangeland and Wildlife Management,13,0.022609
6,Methane Hydrates and Related Phenomena,13,0.022609
7,Underwater Acoustics Research,12,0.020870
8,Electron and X-Ray Spectroscopy Techniques,12,0.020870
9,Species Distribution and Climate Change,11,0.019130
10,Smoking Behavior and Cessation,11,0.019130
11,Statistical Methods and Inference,11,0.019130
12,Geographic Information Systems Studies,10,0.017391
13,Remote Sensing and Land Use,9,0.015652
14,Medical Research and Practices,8,0.013913