In [88]:
import pandas as pd
import matplotlib.pyplot as plt

In [99]:
df = pd.read_csv('2026-04-22-UMN-Source.csv', index_col=0)

In [100]:
pd.set_option("display.max_columns", 55)

In [101]:
df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [102]:
def Matching_columns(df, col1, col2):
    match = df[col1].equals(df[col2])
    return match

In [103]:
# primary topic
Matching_columns(df, 'primary_topic-display_name', 'topics-display_name')

True

In [104]:
# subfield
Matching_columns(df, 'primary_topic-subfield', 'topics-subfield-id')

True

In [105]:
# field
Matching_columns(df, 'primary_topic-field', 'topics-field-id')

True

In [106]:
# domain
Matching_columns(df, 'primary_topic-domain', 'topics-domain-id')

True

In [107]:
len(df['topics-display_name'])

2459

In [123]:
df['ror'].isna().sum(), df['orcid'].isna().sum(), (df['is_oa'] == False).sum()

(2177, 872, 268)

In [12]:
(df['ror'].isna() & df['orcid'].isna()).sum()

767

In [13]:
df['ror'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['ror'], ascending=False).reset_index(drop=True)

    publication_year  ror
0               2026   88
1               2025   65
2               2018   25
3               2019   20
4               2020   17
5               2021   15
6               2022   12
7               2016   10
8               2017    8
9               2014    5
10              2015    5
11              2006    3
12              1998    2
13              2003    2
14              2011    2
15              2023    1
16              2005    1
17              2010    1
18              1990    0
19              1971    0
20              1973    0
21              1972    0
22              1966    0
23              1970    0
24              1969    0
25              1979    0
26              2024    0
27              1964    0
28              1975    0
29              2012    0
30              1983    0
31              2013    0
32              1993    0
33              2009    0
34              2008    0
35              2007    0
36              1959    0
37              2004    0
38              2002    0
39              2001    0
40              1912    0

In [14]:
topics_display_name_ror_perc = df['ror'].count()
print('the # of ROR IDs assigned to DOIs is:', topics_display_name_ror_perc), print('the % of ROR IDs assigned to DOIs is:', round(topics_display_name_ror_perc / len(df) * 100, 3),'%')

the # of ROR IDs assigned to DOIs is: 282
the % of ROR IDs assigned to DOIs is: 11.468 %

(None, None)

In [15]:
topics_display_name_ror = df['ror'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_display_name_ror['ror %'] = round(topics_display_name_ror['ror'] / sum(topics_display_name_ror['ror']) * 100, 4)
topics_display_name_ror.head(15).reset_index(drop=True)

                           topics-display_name  ror   ror %
0               Smoking Behavior and Cessation  102  5.0271
1   Nanopore and Nanochannel Transport Studies   71  3.4993
2          Fish Ecology and Management Studies   39  1.9221
3            Rangeland and Wildlife Management   36  1.7743
4               DNA and Nucleic Acid Chemistry   35  1.7250
5           3D Printing in Biomedical Research   34  1.6757
6      Species Distribution and Climate Change   33  1.6264
7                Forest ecology and management   33  1.6264
8      Wheat and Barley Genetics and Pathology   31  1.5278
9              Archaeology and Natural History   26  1.2814
10   Aquatic Invertebrate Ecology and Behavior   24  1.1828
11       Remote Sensing and LiDAR Applications   24  1.1828
12                        Data Analysis with R   23  1.1336
13  Genetic and phenotypic traits in livestock   21  1.0350
14  Groundwater flow and contamination studies   19  0.9364

In [16]:
df['orcid'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['orcid'], ascending=False).reset_index(drop=True)

    publication_year  orcid
0               2018    235
1               2017    174
2               2019    159
3               2020    152
4               2016    135
5               2015    126
6               2021    117
7               2014    105
8               2013    102
9               2025     53
10              2026     40
11              2010     40
12              2012     35
13              2009     19
14              2022     14
15              2006     14
16              1993     10
17              1983      9
18              2007      8
19              1998      5
20              2011      5
21              1964      4
22              2008      4
23              2001      4
24              2005      3
25              1975      3
26              1990      2
27              1979      2
28              1966      1
29              2024      1
30              2023      1
31              2002      1
32              2003      1
33              1959      1
34              2004      1
35              1912      1
36              1972      0
37              1971      0
38              1970      0
39              1969      0
40              1973      0

In [17]:
topics_display_name_orcid_perc = df['orcid'].count()
print('the # of ORCID IDs assigned to DOIs is:', topics_display_name_orcid_perc), print('the % of ORCID IDs assigned to DOIs is:', round(topics_display_name_orcid_perc / len(df) * 100, 3),'%')

the # of ORCID IDs assigned to DOIs is: 1587
the % of ORCID IDs assigned to DOIs is: 64.538 %

(None, None)

In [18]:
topics_display_name_orcid = df['orcid'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['orcid'], ascending=False)
topics_display_name_orcid['orcid %'] = round(topics_display_name_orcid['orcid'] / sum(topics_display_name_orcid['orcid']) * 100, 4)
topics_display_name_orcid.head(15).reset_index(drop=True)

                           topics-display_name  orcid  orcid %
0               Smoking Behavior and Cessation    102  15.3614
1              Archaeology and Natural History     24   3.6145
2   Nanopore and Nanochannel Transport Studies     17   2.5602
3          Fish Ecology and Management Studies     14   2.1084
4        Remote Sensing and LiDAR Applications     14   2.1084
5   Genetic and phenotypic traits in livestock     13   1.9578
6   Groundwater flow and contamination studies     11   1.6566
7            Solar Radiation and Photovoltaics     11   1.6566
8            Rangeland and Wildlife Management     11   1.6566
9          Water Quality and Resources Studies     10   1.5060
10              DNA and Nucleic Acid Chemistry      9   1.3554
11                        Data Analysis with R      9   1.3554
12           Urban Transport and Accessibility      9   1.3554
13               Forest ecology and management      8   1.2048
14              Soil Geostatistics and Mapping      8   1.2048

In [19]:
topics_subfield_display_name_ror = df['ror'].isna().groupby(df['topics-subfield-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_subfield_display_name_ror.head(15).reset_index(drop=True)

                    topics-subfield-display_name  ror
0                                        Ecology  153
1                         Biomedical Engineering  139
2                              Molecular Biology  132
3                                  Plant Science  111
4                                     Physiology  102
5                        Artificial Intelligence   93
6              Nature and Landscape Conservation   76
7                      Environmental Engineering   75
8                            Materials Chemistry   65
9                    Global and Planetary Change   48
10                                      Genetics   44
11  Ecology, Evolution, Behavior and Systematics   37
12                  Water Science and Technology   34
13                           Ecological Modeling   33
14                         Aerospace Engineering   30

In [20]:

topics_field_display_name_ror = df['ror'].isna().groupby(df['topics-field-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_field_display_name_ror.head(15).reset_index(drop=True)

                       topics-field-display_name  ror
0                          Environmental Science  498
1                                    Engineering  277
2   Biochemistry, Genetics and Molecular Biology  211
3           Agricultural and Biological Sciences  209
4                               Computer Science  153
5                                       Medicine  147
6                                Social Sciences  101
7                              Materials Science   96
8                                      Chemistry   69
9                   Earth and Planetary Sciences   45
10                                    Psychology   32
11           Economics, Econometrics and Finance   25
12                         Physics and Astronomy   25
13                            Health Professions   22
14                          Chemical Engineering   19

In [ ]:
df['orcid'].notna().groupby(df['cited_by_count']).sum().reset_index().sort_values(by=['cited_by_count'], ascending=False).reset_index(drop=True)

cited_by_count
0     1219
1      229
2       59
3       31
4       14
5        8
6        4
7        1
8        3
9        2
10       0
11       3
12       5
17       1
28       3
41       5
Name: orcid, dtype: int64

In [213]:
df['title'].groupby(df['cited_by_count']).sum().reset_index().sort_values(by=['cited_by_count'], ascending=False).reset_index(drop=True)

    cited_by_count                                              title
0               41  Minnesota Solvation Database (MNSOL) version 2...
1               28  White-tailed deer density estimates across the...
2               17  Global nitrogen deposition (2°×2.5° grid resol...
3               12  Minnesota Land Cover Classification and Imperv...
4               11  Home range overlap indices implemented using k...
5               10  Data Related to: Association studies of up to ...
6                9  Geometries for Minnesota Database 2019Geometri...
7                8  Clinical Abbreviation Sense InventoryClinical ...
8                7  Historical Population Estimates for 2010 U.S. ...
9                6  datasets for Using Verbs and Adjectives to Aut...
10               5  Access Across America: Transit 2014 DataAccess...
11               4  Small UAV Position and Attitude, Raw Sensor, a...
12               3  Transportation and Quality of Life: An Annotat...
13               2  Karst Features of MinnesotaKarst Features of M...
14               1  1958 Twin Cities Land Use Map from the Twin Ci...
15               0  OFR14-05, A HYDROCHEMICAL SURVEY OF GROUNDWATE...

In [216]:
OpenAccessdf = df[df['is_oa'] == True]
OpenAccessdf = OpenAccessdf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total open access cited by count is:', OpenAccessdf['cited_by_count'].sum())
print('Average open access cited by count is:', OpenAccessdf['cited_by_count'].mean())
OpenAccessdf.head(15)

Total open access cited by count is: 410
Average open access cited by count is: 0.6376360808709176

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   White-tailed deer density estimates across the...              28
2   Global nitrogen deposition (2°×2.5° grid resol...              17
3   Minnesota Land Cover Classification and Imperv...              12
4   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
5   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
6   Trash-ICRA19: A bounding box labeled dataset o...              11
7   Home range overlap indices implemented using k...              11
8   Data Related to: Association studies of up to ...              10
9              Geometries for Minnesota Database 2019               9
10           Access Across America: Transit 2017 Data               8
11  Historical Population Estimates for 2010 U.S. ...               7
12  Twin Cities Metropolitan Area 1-Meter Land Cov...               7
13                           APAL Coupling Study 2019               6
14  DynamoVis - Dynamic Visualization of Animal Mo...               6

In [217]:
NonOpenAccessdf = df[df['is_oa'] == False]
NonOpenAccessdf = NonOpenAccessdf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total non open access cited by count is:', NonOpenAccessdf['cited_by_count'].sum())
print('Average non open access cited by count is:', NonOpenAccessdf['cited_by_count'].mean())
NonOpenAccessdf.head(15)

Total non open access cited by count is: 17
Average non open access cited by count is: 0.18888888888888888

                                                title  cited_by_count
0               Clinical Abbreviation Sense Inventory               8
1   datasets for Using Verbs and Adjectives to Aut...               6
2    GRAVITY AND AEROMAGNETIC DATA GRIDS OF MINNESOTA               3
3   Data from: One-parameter scaling theory for DN...               0
4   Data from: The backfolded Odijk regime for wor...               0
5   Data from: Simulation of DNA Extension in Nano...               0
6   Data from: Entropic Depletion of DNA in Triang...               0
7   Data from: Alpha-Synuclein Modulates the Physi...               0
8   Data from: Wall depletion length of a channel-...               0
9   Data from: Odijk excluded volume interactions ...               0
10  Data from: Effect of excluded volume on the fo...               0
11  Data from: Coupled Flow and Reaction during Na...               0
12  Data from: Rapid, selective, label-free aptame...               0
13            Black Spruce Diameter Growth Model Data               0
14  Data from: Microfluidic chemostat for measurin...               0

In [218]:
OrcidDF = df[df['orcid'].notna()]
OrcidDF = OrcidDF[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total Orcid cited by count is:', OrcidDF['cited_by_count'].sum())
print('Average Orcid cited by count is:', OrcidDF['cited_by_count'].mean())

OrcidDF.head(15)

Total Orcid cited by count is: 376
Average Orcid cited by count is: 0.6045016077170418

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   White-tailed deer density estimates across the...              28
2   Global nitrogen deposition (2°×2.5° grid resol...              17
3   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
4   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
5   Trash-ICRA19: A bounding box labeled dataset o...              11
6   Home range overlap indices implemented using k...              11
7              Geometries for Minnesota Database 2019               9
8               Clinical Abbreviation Sense Inventory               8
9            Access Across America: Transit 2017 Data               8
10  Historical Population Estimates for 2010 U.S. ...               7
11  datasets for Using Verbs and Adjectives to Aut...               6
12  DynamoVis - Dynamic Visualization of Animal Mo...               6
13                           APAL Coupling Study 2019               6
14  Characterization of streams and rivers in the ...               5

In [219]:
NAOrcidDF = df[df['orcid'].isna()]
NAOrcidDF = NAOrcidDF[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total NaN Orcid cited by count is:', NAOrcidDF['cited_by_count'].sum())
print('Average NaN Orcid cited by count is:', NAOrcidDF['cited_by_count'].mean())
NAOrcidDF.head(15)

Total NaN Orcid cited by count is: 237
Average NaN Orcid cited by count is: 0.5780487804878048

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   Minnesota Land Cover Classification and Imperv...              12
2   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
3   Trash-ICRA19: A bounding box labeled dataset o...              11
4   Data Related to: Association studies of up to ...              10
5               Clinical Abbreviation Sense Inventory               8
6            Access Across America: Transit 2017 Data               8
7   Twin Cities Metropolitan Area 1-Meter Land Cov...               7
8                            APAL Coupling Study 2019               6
9   datasets for Using Verbs and Adjectives to Aut...               6
10           Access Across America: Transit 2014 Data               5
11  Characterization of streams and rivers in the ...               5
12  R Code and Output Supporting: Resampling-Based...               5
13                Racial Covenants in Hennepin County               4
14  Lake Superior moored temperature and currents,...               4

In [ ]:
RorDF = df[df['ror'].notna()]
RorDF = RorDF[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('Total Ror cited by count is:', RorDF['cited_by_count'].sum())
print('Average Ror cited by count is:', RorDF['cited_by_count'].mean())

RorDF.head(15)

Total Ror cited by count is: 74
Average NaN Ror cited by count is: 0.8043478260869565

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1            Access Across America: Transit 2014 Data               5
2   R Code and Output Supporting: Resampling-Based...               5
3   Lake Superior moored temperature and currents,...               4
4              Value of Curation Survey, January 2021               3
5   2011 Rock Properties Database: Density, Magnet...               2
6   Three-Dimensional Models of Experimentally-Pro...               2
7   APAL 2019: Postural Data, Game Performance, an...               1
8   Heating, Susceptibility, and XRD data for Diff...               1
9       Wildlife community data in black ash wetlands               1
10  Winter and summer zooplankton community and en...               1
11  Data supporting: "Testing Our Assumptions: Pre...               1
12  Experimental alluvial-river and landsliding re...               1
13  Complete Data and Analysis for: Constraining i...               1
14  Rich Data for Wind Turbine Power Performance A...               1

In [221]:
NARorDF = df[df['ror'].isna()]
NARorDF = NARorDF[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
print('total NaN Ror cited by count is:', NARorDF['cited_by_count'].sum())
print('Average  NaN Ror cited by count is:', NARorDF['cited_by_count'].mean())


NARorDF.head(15)

total NaN Ror cited by count is: 406
Average  NaN Ror cited by count is: 0.6132930513595166

                                                title  cited_by_count
0   Minnesota Solvation Database (MNSOL) version 2012              41
1   White-tailed deer density estimates across the...              28
2   Global nitrogen deposition (2°×2.5° grid resol...              17
3   TrashCan 1.0 An Instance-Segmentation Labeled ...              12
4   Updated Code of GEOS-Chem Adjoint v35 for TROP...              12
5   Minnesota Land Cover Classification and Imperv...              12
6   Home range overlap indices implemented using k...              11
7   Trash-ICRA19: A bounding box labeled dataset o...              11
8   Data Related to: Association studies of up to ...              10
9              Geometries for Minnesota Database 2019               9
10              Clinical Abbreviation Sense Inventory               8
11           Access Across America: Transit 2017 Data               8
12  Twin Cities Metropolitan Area 1-Meter Land Cov...               7
13  Historical Population Estimates for 2010 U.S. ...               7
14                           APAL Coupling Study 2019               6

In [246]:
doi_count = df['doi'].nunique()

domain_cited_df = df.drop_duplicates(subset=['doi'])
domain_cited_df = domain_cited_df.groupby(['topics-domain-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True)
#OpenAccessdf = OpenAccessdf[['title', 'cited_by_count']].sort_values(by=['cited_by_count'], ascending=False).drop_duplicates().reset_index(drop=True)
#print('total cited by count is:', OpenAccessdf['cited_by_count'].sum())
#domain['cited by mean'] = domain_cited_df.groupby(['topics-domain-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True) / len 
domain_cited_df['cited_by_count_mean'] = domain_cited_df['cited_by_count'] / doi_count
domain_cited_df

  topics-domain-display_name  cited_by_count  cited_by_count_mean
0          Physical Sciences             315             0.547826
1            Social Sciences              40             0.069565
2              Life Sciences              26             0.045217
3            Health Sciences              24             0.041739

In [248]:
field_df = df.drop_duplicates(subset=['doi'])
field_df = field_df.groupby(['topics-field-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True)
field_df['cited_by_count_mean'] = field_df['cited_by_count'] / doi_count

field_df.head(15)

,topics-field-display_name,cited_by_count,cited_by_count_mean
0,Environmental Science,141,0.245217
1,Computer Science,68,0.118261
2,Earth and Planetary Sciences,34,0.059130
3,Engineering,30,0.052174
4,Social Sciences,24,0.041739
5,"Biochemistry, Genetics and Molecular Biology",18,0.031304
6,Mathematics,18,0.031304
7,Materials Science,16,0.027826
8,Health Professions,12,0.020870
9,Medicine,11,0.019130
10,Agricultural and Biological Sciences,7,0.012174
11,Decision Sciences,7,0.012174
12,Chemistry,6,0.010435
13,"Economics, Econometrics and Finance",4,0.006957
14,Psychology,3,0.005217

In [249]:
subfield_df = df
subfield_df = subfield_df.groupby(['topics-subfield-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True)
subfield_df['cited_by_count_mean'] = subfield_df['cited_by_count'] / doi_count

subfield_df.head(15)

,topics-subfield-display_name,cited_by_count,cited_by_count_mean
0,Artificial Intelligence,425,0.739130
1,Ecology,145,0.252174
2,Nature and Landscape Conservation,98,0.170435
3,Environmental Chemistry,51,0.088696
4,Information Systems,50,0.086957
5,Environmental Engineering,45,0.078261
6,Oceanography,40,0.069565
7,Computer Vision and Pattern Recognition,38,0.066087
8,"Surfaces, Coatings and Films",36,0.062609
9,Building and Construction,31,0.053913
10,Molecular Biology,31,0.053913
11,Sociology and Political Science,26,0.045217
12,Ecological Modeling,26,0.045217
13,"Management, Monitoring, Policy and Law",24,0.041739
14,Global and Planetary Change,24,0.041739

In [250]:
topic_cited_df = df.drop_duplicates(subset=['doi'])
topic_cited_df = topic_cited_df.groupby(['primary_topic-display_name'])['cited_by_count'].sum().reset_index().sort_values(by='cited_by_count', ascending=False).reset_index(drop=True)
topic_cited_df['cited_by_count_mean'] = topic_cited_df['cited_by_count'] / doi_count


topic_cited_df.head(15)

,primary_topic-display_name,cited_by_count,cited_by_count_mean
0,Geochemistry and Geologic Mapping,41,0.071304
1,Wildlife Ecology and Conservation,29,0.050435
2,Atmospheric and Environmental Gas Dynamics,18,0.031304
3,Fish Ecology and Management Studies,15,0.026087
4,Traffic Prediction and Management Techniques,15,0.026087
5,Rangeland and Wildlife Management,13,0.022609
6,Methane Hydrates and Related Phenomena,13,0.022609
7,Underwater Acoustics Research,12,0.020870
8,Electron and X-Ray Spectroscopy Techniques,12,0.020870
9,Species Distribution and Climate Change,11,0.019130
10,Smoking Behavior and Cessation,11,0.019130
11,Statistical Methods and Inference,11,0.019130
12,Geographic Information Systems Studies,10,0.017391
13,Remote Sensing and Land Use,9,0.015652
14,Medical Research and Practices,8,0.013913

In [175]:
len(df)

2459

In [21]:
topic_view = df.copy()

In [22]:
topic_view.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [23]:
topic_view = topic_view[~topic_view.id.duplicated(keep='first')]

In [24]:
topic_view = topic_view[['id', 'doi', 'title', 'publication_date', 'topics-display_name', 'topics-field-display_name', 'topics-subfield-display_name', 'topics-domain-display_name']]
topic_view.head()

,id,doi,title,publication_date,topics-display_name,topics-field-display_name,topics-subfield-display_name,topics-domain-display_name
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,1998-01-01,Geochemistry and Geologic Mapping,Computer Science,Artificial Intelligence,Physical Sciences
9,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,2016-01-01,Wildlife Ecology and Conservation,Environmental Science,Ecology,Physical Sciences
12,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,2018-01-01,Atmospheric and Environmental Gas Dynamics,Environmental Science,Global and Planetary Change,Physical Sciences
13,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,2016-01-01,Rangeland and Wildlife Management,Environmental Science,Ecology,Physical Sciences
14,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,2019-06-24,Electron and X-Ray Spectroscopy Techniques,Materials Science,"Surfaces, Coatings and Films",Physical Sciences

In [25]:
topic_view.to_csv('2026-04-22-UMN-Source-Topics-View.csv')