In [50]:
import pandas as pd
import matplotlib.pyplot as plt

In [51]:
df = pd.read_csv('2026-04-22-UMN-Source.csv', index_col=0)

In [52]:
pd.set_option("display.max_columns", 55)

In [53]:
df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [54]:
def Matching_columns(df, col1, col2):
    match = df[col1].equals(df[col2])
    return match

In [55]:
# primary topic
Matching_columns(df, 'primary_topic-display_name', 'topics-display_name')

True

In [56]:
# subfield
Matching_columns(df, 'primary_topic-subfield', 'topics-subfield-id')

True

In [57]:
# field
Matching_columns(df, 'primary_topic-field', 'topics-field-id')

True

In [58]:
# domain
Matching_columns(df, 'primary_topic-domain', 'topics-domain-id')

True

In [59]:
len(df['topics-display_name'])

2459

In [60]:
df['ror'].isna().sum(), df['orcid'].isna().sum()

(2177, 872)

In [61]:
(df['ror'].isna() & df['orcid'].isna()).sum()

767

In [62]:
df['ror'].isna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['ror'], ascending=False).reset_index(drop=True)

    publication_year  ror
0               2019  296
1               2018  281
2               2017  214
3               2015  187
4               2016  186
5               2020  185
6               2013  142
7               2021  135
8               2014  133
9               2025  104
10              2012   53
11              2010   49
12              2026   35
13              2009   25
14              2006   21
15              1983   13
16              2011   13
17              1993   12
18              2007   12
19              1973   10
20              2024    9
21              2008    7
22              1998    7
23              2022    5
24              2005    5
25              1975    5
26              1959    4
27              1990    4
28              2004    4
29              1964    4
30              2001    4
31              2003    3
32              1979    2
33              2002    2
34              1970    1
35              1969    1
36              1966    1
37              1971    1
38              1972    1
39              1912    1
40              2023    0

In [98]:
topics_display_name_ror_perc = df['ror'].count()
print('the # of ROR IDs assigned to DOIs is:', topics_display_name_ror_perc), print('the % of ROR IDs assigned to DOIs is:', round(topics_display_name_ror_perc / len(df) * 100, 3),'%')

the # of ROR IDs assigned to DOIs is: 282
the % of ROR IDs assigned to DOIs is: 11.468 %

(None, None)

In [104]:
topics_display_name_ror = df['ror'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_display_name_ror['ror %'] = round(topics_display_name_ror['ror'] / sum(topics_display_name_ror['ror']) * 100, 4)
topics_display_name_ror.head(15).reset_index(drop=True)

                           topics-display_name  ror   ror %
0               Smoking Behavior and Cessation  102  5.0271
1   Nanopore and Nanochannel Transport Studies   71  3.4993
2          Fish Ecology and Management Studies   39  1.9221
3            Rangeland and Wildlife Management   36  1.7743
4               DNA and Nucleic Acid Chemistry   35  1.7250
5           3D Printing in Biomedical Research   34  1.6757
6      Species Distribution and Climate Change   33  1.6264
7                Forest ecology and management   33  1.6264
8      Wheat and Barley Genetics and Pathology   31  1.5278
9              Archaeology and Natural History   26  1.2814
10   Aquatic Invertebrate Ecology and Behavior   24  1.1828
11       Remote Sensing and LiDAR Applications   24  1.1828
12                        Data Analysis with R   23  1.1336
13  Genetic and phenotypic traits in livestock   21  1.0350
14  Groundwater flow and contamination studies   19  0.9364

In [91]:
df['orcid'].isna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['orcid'], ascending=False).reset_index(drop=True)

    publication_year  orcid
0               2019    157
1               2025    116
2               2026     83
3               2018     71
4               2015     66
5               2016     61
6               2020     50
7               2017     48
8               2013     40
9               2021     33
10              2014     33
11              2012     18
12              2010     10
13              2011     10
14              2006     10
15              1973     10
16              2024      8
17              2009      6
18              2003      4
19              2007      4
20              1998      4
21              1983      4
22              2022      3
23              2004      3
24              2005      3
25              1959      3
26              2008      3
27              1975      2
28              1990      2
29              1993      2
30              2002      1
31              1972      1
32              1971      1
33              1970      1
34              1969      1
35              1964      0
36              2001      0
37              1979      0
38              2023      0
39              1966      0
40              1912      0

In [97]:
topics_display_name_orcid_perc = df['orcid'].count()
print('the # of ORCID IDs assigned to DOIs is:', topics_display_name_orcid_perc), print('the % of ORCID IDs assigned to DOIs is:', round(topics_display_name_orcid_perc / len(df) * 100, 3),'%')

the # of ORCID IDs assigned to DOIs is: 1587
the % of ORCID IDs assigned to DOIs is: 64.538 %

(None, None)

In [103]:
topics_display_name_orcid = df['orcid'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['orcid'], ascending=False)
topics_display_name_orcid['orcid %'] = round(topics_display_name_orcid['orcid'] / sum(topics_display_name_orcid['orcid']) * 100, 4)
topics_display_name_orcid.head(15).reset_index(drop=True)

                           topics-display_name  orcid  orcid %
0               Smoking Behavior and Cessation    102  15.3614
1              Archaeology and Natural History     24   3.6145
2   Nanopore and Nanochannel Transport Studies     17   2.5602
3          Fish Ecology and Management Studies     14   2.1084
4        Remote Sensing and LiDAR Applications     14   2.1084
5   Genetic and phenotypic traits in livestock     13   1.9578
6   Groundwater flow and contamination studies     11   1.6566
7            Solar Radiation and Photovoltaics     11   1.6566
8            Rangeland and Wildlife Management     11   1.6566
9          Water Quality and Resources Studies     10   1.5060
10              DNA and Nucleic Acid Chemistry      9   1.3554
11                        Data Analysis with R      9   1.3554
12           Urban Transport and Accessibility      9   1.3554
13               Forest ecology and management      8   1.2048
14              Soil Geostatistics and Mapping      8   1.2048

In [ ]:
topics_subfield_display_name_ror = df['ror'].isna().groupby(df['topics-subfield-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_subfield_display_name_ror.head(15).reset_index(drop=True)

In [ ]:

topics_field_display_name_ror = df['ror'].isna().groupby(df['topics-field-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_field_display_name_ror.head(15).reset_index(drop=True)