In [2]:
import requests
import pandas as pd
import time
import json
import datetime

In [3]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Create a container
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        
        # create a loop iterator
        record_number = 0
        page += 1
       
       # Loop over all the records
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'type': record['type'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'primary_topic': record['primary_topic'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                'index location': record['indexed_in'],
                                'primary_location': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'], 
                                'authorships': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions'],
                                'apc_list': record['apc_list'],
                                'apc_paid': record['apc_paid'],
                                'fwci': record['fwci'],
                                'has_fulltext': record['has_fulltext'],
                                'cited_by_count': record['cited_by_count'], 
                                'citation_normalized_percentile': record['citation_normalized_percentile'],
                                'cited_by_percentile_year': record['cited_by_percentile_year'],
                                'biblio': record['biblio']
                                })         

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

parameters = {
    "per-page": 100,
}

In [4]:
Institution_URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i2800403580|i130238516|i4210115145|i4210120349|i4210159608'
Source_JSONOutFile = str(datetime.datetime.today()).split()[0] + '-UMN-Institutions.json'
with open(Source_JSONOutFile, 'w') as outfile:
    json.dump(OpenAlexAPI(Institution_URL, parameters), outfile)

Status code: 200 ; Page number:  0
Status code: 200 ; Page number:  1
Status code: 200 ; Page number:  2
Status code: 200 ; Page number:  3
Status code: 200 ; Page number:  4
Status code: 200 ; Page number:  5
Status code: 200 ; Page number:  6
Status code: 200 ; Page number:  7
Status code: 200 ; Page number:  8
Status code: 200 ; Page number:  9
Status code: 200 ; Page number:  10
Status code: 200 ; Page number:  11
Status code: 200 ; Page number:  12
Status code: 200 ; Page number:  13
Status code: 200 ; Page number:  14
Status code: 200 ; Page number:  15
Status code: 200 ; Page number:  16
Status code: 200 ; Page number:  17
Status code: 200 ; Page number:  18
Status code: 200 ; Page number:  19
Status code: 200 ; Page number:  20
Status code: 200 ; Page number:  21
Status code: 200 ; Page number:  22
Status code: 200 ; Page number:  23
Status code: 200 ; Page number:  24
Status code: 200 ; Page number:  25
Status code: 200 ; Page number:  26
Status code: 200 ; Page number:  27
Status code: 200 ; Page number:  28
Status code: 200 ; Page number:  29
Status code: 200 ; Page number:  30
Status code: 200 ; Page number:  31
Status code: 200 ; Page number:  32
Status code: 200 ; Page number:  33
Status code: 200 ; Page number:  34
Status code: 200 ; Page number:  35
Status code: 200 ; Page number:  36
Status code: 200 ; Page number:  37
Status code: 200 ; Page number:  38
Status code: 200 ; Page number:  39
Status code: 200 ; Page number:  40
Status code: 200 ; Page number:  41

In [5]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [6]:
def missing_index(df):
    missing_indices = ([i for i in range(0, len(df)) if i not in df.index])
    return missing_indices

In [7]:
pd.set_option("display.max_columns", 55)

In [8]:
df = pd.read_json(Source_JSONOutFile)
df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,748,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"{'id': 'https://openalex.org/T13067', 'display...","[{'id': 'https://openalex.org/T13067', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,75,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T14163', 'display...","[{'id': 'https://openalex.org/T14163', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,67,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T10644', 'display...","[{'id': 'https://openalex.org/T10644', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'The Ohio State Un...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,62,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4255862108,https://doi.org/10.3886/icpsr04652,"Midlife in the United States (MIDUS 2), 2004-2006",dataset,2014,2014-01-10,"{'id': 'https://openalex.org/T12781', 'display...","[{'id': 'https://openalex.org/T12781', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Wis...,"[{'id': 'https://openalex.org/I135310074', 'di...",NaN,NaN,NaN,False,42,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."

In [9]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'primary_topic', 'topics', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'authorships',
       'affiliations', 'Institution', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio'],
      dtype='object')

In [10]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,748,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"{'id': 'https://openalex.org/T13067', 'display...","[{'id': 'https://openalex.org/T13067', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,75,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T14163', 'display...","[{'id': 'https://openalex.org/T14163', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,67,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T10644', 'display...","[{'id': 'https://openalex.org/T10644', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'The Ohio State Un...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,62,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4255862108,https://doi.org/10.3886/icpsr04652,"Midlife in the United States (MIDUS 2), 2004-2006",dataset,2014,2014-01-10,"{'id': 'https://openalex.org/T12781', 'display...","[{'id': 'https://openalex.org/T12781', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Wis...,"[{'id': 'https://openalex.org/I135310074', 'di...",NaN,NaN,NaN,False,42,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,https://openalex.org/W7154972851,https://doi.org/10.17632/bpcpfns6vb,A global genetic interaction network of a huma...,dataset,2026,2026-01-01,None,[],None,0.0,datacite,"{'id': 'https://openalex.org/S7407050775', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4008,https://openalex.org/W7154995270,https://doi.org/10.13020/wxbd-8t05,ccSpill manuscript supplement,dataset,2025,2025-12-11,None,[],None,0.0,datacite,"{'id': 'https://openalex.org/S7407053140', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4009,https://openalex.org/W7155010658,https://doi.org/10.17632/bpcpfns6vb.1,A global genetic interaction network of a huma...,dataset,2026,2026-01-01,None,[],None,0.0,datacite,"{'id': 'https://openalex.org/S7407050775', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4010,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,Data from: Preliminary efficacy of cognitive m...,dataset,2026,2026-03-19,None,[],en,0.0,datacite,"{'id': 'https://openalex.org/S7407051161', 'di...",True,green,public-domain,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I4210135252', 'd...",NaN,NaN,NaN,False,0,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."
4011,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,4070 Automated Screening System for Detecting ...,dataset,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4363604086', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,0,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ..."

In [11]:
# normalize  citation metric columns data

citation_normalized_percentile_df = pd.json_normalize(df['citation_normalized_percentile'])
cited_by_percentile_year_df = pd.json_normalize(df['cited_by_percentile_year'])
biblio_df = pd.json_normalize(df['biblio'])
# concat normalized data into original df

df = pd.concat([df, citation_normalized_percentile_df], axis=1)
df = pd.concat([df, cited_by_percentile_year_df], axis=1)
df = pd.concat([df, biblio_df], axis=1)

#rename column
df = df.rename(columns={'value': 'citation_normalized_percentile-value'})


df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,volume,issue,first_page,last_page
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,748,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"{'id': 'https://openalex.org/T13067', 'display...","[{'id': 'https://openalex.org/T13067', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,75,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None
2,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T14163', 'display...","[{'id': 'https://openalex.org/T14163', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,67,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None
3,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T10644', 'display...","[{'id': 'https://openalex.org/T10644', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'The Ohio State Un...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,62,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None
4,https://openalex.org/W4255862108,https://doi.org/10.3886/icpsr04652,"Midlife in the United States (MIDUS 2), 2004-2006",dataset,2014,2014-01-10,"{'id': 'https://openalex.org/T12781', 'display...","[{'id': 'https://openalex.org/T12781', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Wis...,"[{'id': 'https://openalex.org/I135310074', 'di...",NaN,NaN,NaN,False,42,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None

In [12]:
# normalize columns data
primary_location_df = pd.json_normalize(df['primary_location'])


# extract only display name column
primary_location_df = primary_location_df[['display_name']]

#rename display name column
primary_location_df = primary_location_df.rename(columns={'display_name': 'primary_location-source-display_name'}) 

#primary_location_df = primary_location_df.reindex(range(primary_location_df.index.min(), primary_location_df .index.max()+1))

# concat display name column to main df
df = pd.concat([df, primary_location_df], axis=1)

In [13]:
# Use function to normalize Authors nested list
authorships_df = CleanJSON('authorships', df)
authorships_df['raw_affiliation_strings'] = authorships_df['raw_affiliation_strings'].str[0]
authorships_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,"Porter, Claire",University of Minnesota,[{'raw_affiliation_string': 'University of Min...
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,"Morin, Paul",University of Minnesota,[{'raw_affiliation_string': 'University of Min...
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Howat, Ian",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Noh, Myoung-Jon",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,[{'raw_affiliation_string': 'National Geospati...
...,...,...,...,...,...,...,...,...
4010,last,"{'id': 'https://openalex.org/A5134098806', 'di...","[{'id': 'https://openalex.org/I145608581', 'di...",[US],False,"Morse, Leslie R.",University of Miami,[{'raw_affiliation_string': 'University of Mia...
4011,first,"{'id': 'https://openalex.org/A5050360160', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],True,Sohini RoyChowdhury,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...
4011,middle,"{'id': 'https://openalex.org/A5007884053', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Keshab K. Parhi,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...
4011,middle,"{'id': 'https://openalex.org/A5104048359', 'di...","[{'id': 'https://openalex.org/I4210140408', 'd...",[US],False,Mary G. Lawrence,"Ophthalmology, Minneapolis VA Medical Center, ...","[{'raw_affiliation_string': 'Ophthalmology, Mi..."
4011,last,"{'id': 'https://openalex.org/A5089355316', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Dara Koozekanani,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...

In [14]:
missing_index(authorships_df['raw_affiliation_strings'])

[4012,
 4013,
 4014,
 4015,
 4016,
 4017,
 4018,
 4019,
 4020,
 4021,
 4022,
 4023,
 4024,
 4025,
 4026,
 4027,
 4028,
 4029,
 4030,
 4031,
 4032,
 4033,
 4034,
 4035,
 4036,
 4037,
 4038,
 4039,
 4040,
 4041,
 4042,
 4043,
 4044,
 4045,
 4046,
 4047,
 4048,
 4049,
 4050,
 4051,
 4052,
 4053,
 4054,
 4055,
 4056,
 4057,
 4058,
 4059,
 4060,
 4061,
 4062,
 4063,
 4064,
 4065,
 4066,
 4067,
 4068,
 4069,
 4070,
 4071,
 4072,
 4073,
 4074,
 4075,
 4076,
 4077,
 4078,
 4079,
 4080,
 4081,
 4082,
 4083,
 4084,
 4085,
 4086,
 4087,
 4088,
 4089,
 4090,
 4091,
 4092,
 4093,
 4094,
 4095,
 4096,
 4097,
 4098,
 4099,
 4100,
 4101,
 4102,
 4103,
 4104,
 4105,
 4106,
 4107,
 4108,
 4109,
 4110,
 4111,
 4112,
 4113,
 4114,
 4115,
 4116,
 4117,
 4118,
 4119,
 4120,
 4121,
 4122,
 4123,
 4124,
 4125,
 4126,
 4127,
 4128,
 4129,
 4130,
 4131,
 4132,
 4133,
 4134,
 4135,
 4136,
 4137,
 4138,
 4139,
 4140,
 4141,
 4142,
 4143,
 4144,
 4145,
 4146,
 4147,
 4148,
 4149,
 4150,
 4151,
 4152,
 4153,
 4154,
 4155,
 4156,
 4157,
 4158,
 4159,
 4160,
 4161,
 4162,
 4163,
 4164,
 4165,
 4166,
 4167,
 4168,
 4169,
 4170,
 4171,
 4172,
 4173,
 4174,
 4175,
 4176,
 4177,
 4178,
 4179,
 4180,
 4181,
 4182,
 4183,
 4184,
 4185,
 4186,
 4187,
 4188,
 4189,
 4190,
 4191,
 4192,
 4193,
 4194,
 4195,
 4196,
 4197,
 4198,
 4199,
 4200,
 4201,
 4202,
 4203,
 4204,
 4205,
 4206,
 4207,
 4208,
 4209,
 4210,
 4211,
 4212,
 4213,
 4214,
 4215,
 4216,
 4217,
 4218,
 4219,
 4220,
 4221,
 4222,
 4223,
 4224,
 4225,
 4226,
 4227,
 4228,
 4229,
 4230,
 4231,
 4232,
 4233,
 4234,
 4235,
 4236,
 4237,
 4238,
 4239,
 4240,
 4241,
 4242,
 4243,
 4244,
 4245,
 4246,
 4247,
 4248,
 4249,
 4250,
 4251,
 4252,
 4253,
 4254,
 4255,
 4256,
 4257,
 4258,
 4259,
 4260,
 4261,
 4262,
 4263,
 4264,
 4265,
 4266,
 4267,
 4268,
 4269,
 4270,
 4271,
 4272,
 4273,
 4274,
 4275,
 4276,
 4277,
 4278,
 4279,
 4280,
 4281,
 4282,
 4283,
 4284,
 4285,
 4286,
 4287,
 4288,
 4289,
 4290,
 4291,
 4292,
 4293,
 4294,
 4295,
 4296,
 4297,
 4298,
 4299,
 4300,
 4301,
 4302,
 4303,
 4304,
 4305,
 4306,
 4307,
 4308,
 4309,
 4310,
 4311,
 4312,
 4313,
 4314,
 4315,
 4316,
 4317,
 4318,
 4319,
 4320,
 4321,
 4322,
 4323,
 4324,
 4325,
 4326,
 4327,
 4328,
 4329,
 4330,
 4331,
 4332,
 4333,
 4334,
 4335,
 4336,
 4337,
 4338,
 4339,
 4340,
 4341,
 4342,
 4343,
 4344,
 4345,
 4346,
 4347,
 4348,
 4349,
 4350,
 4351,
 4352,
 4353,
 4354,
 4355,
 4356,
 4357,
 4358,
 4359,
 4360,
 4361,
 4362,
 4363,
 4364,
 4365,
 4366,
 4367,
 4368,
 4369,
 4370,
 4371,
 4372,
 4373,
 4374,
 4375,
 4376,
 4377,
 4378,
 4379,
 4380,
 4381,
 4382,
 4383,
 4384,
 4385,
 4386,
 4387,
 4388,
 4389,
 4390,
 4391,
 4392,
 4393,
 4394,
 4395,
 4396,
 4397,
 4398,
 4399,
 4400,
 4401,
 4402,
 4403,
 4404,
 4405,
 4406,
 4407,
 4408,
 4409,
 4410,
 4411,
 4412,
 4413,
 4414,
 4415,
 4416,
 4417,
 4418,
 4419,
 4420,
 4421,
 4422,
 4423,
 4424,
 4425,
 4426,
 4427,
 4428,
 4429,
 4430,
 4431,
 4432,
 4433,
 4434,
 4435,
 4436,
 4437,
 4438,
 4439,
 4440,
 4441,
 4442,
 4443,
 4444,
 4445,
 4446,
 4447,
 4448,
 4449,
 4450,
 4451,
 4452,
 4453,
 4454,
 4455,
 4456,
 4457,
 4458,
 4459,
 4460,
 4461,
 4462,
 4463,
 4464,
 4465,
 4466,
 4467,
 4468,
 4469,
 4470,
 4471,
 4472,
 4473,
 4474,
 4475,
 4476,
 4477,
 4478,
 4479,
 4480,
 4481,
 4482,
 4483,
 4484,
 4485,
 4486,
 4487,
 4488,
 4489,
 4490,
 4491,
 4492,
 4493,
 4494,
 4495,
 4496,
 4497,
 4498,
 4499,
 4500,
 4501,
 4502,
 4503,
 4504,
 4505,
 4506,
 4507,
 4508,
 4509,
 4510,
 4511,
 4512,
 4513,
 4514,
 4515,
 4516,
 4517,
 4518,
 4519,
 4520,
 4521,
 4522,
 4523,
 4524,
 4525,
 4526,
 4527,
 4528,
 4529,
 4530,
 4531,
 4532,
 4533,
 4534,
 4535,
 4536,
 4537,
 4538,
 4539,
 4540,
 4541,
 4542,
 4543,
 4544,
 4545,
 4546,
 4547,
 4548,
 4549,
 4550,
 4551,
 4552,
 4553,
 4554,
 4555,
 4556,
 4557,
 4558,
 4559,
 4560,
 4561,
 4562,
 4563,
 4564,
 4565,
 4566,
 4567,
 4568,
 4569,
 4570,
 4571,
 4572,
 4573,
 4574,
 4575,
 4576,
 4577,
 4578,
 4579,
 4580,
 4581,
 4582,
 4583,
 4584,
 4585,
 4586,
 4587,
 4588,
 4589,
 4590,
 4591,
 4592,
 4593,
 4594,
 4595,
 4596,
 4597,
 4598,
 4599,
 4600,
 4601,
 4602,
 4603,
 4604,
 4605,
 4606,
 4607,
 4608,
 4609,
 4610,
 4611,
 4612,
 4613,
 4614,
 4615,
 4616,
 4617,
 4618,
 4619,
 4620,
 4621,
 4622,
 4623,
 4624,
 4625,
 4626,
 4627,
 4628,
 4629,
 4630,
 4631,
 4632,
 4633,
 4634,
 4635,
 4636,
 4637,
 4638,
 4639,
 4640,
 4641,
 4642,
 4643,
 4644,
 4645,
 4646,
 4647,
 4648,
 4649,
 4650,
 4651,
 4652,
 4653,
 4654,
 4655,
 4656,
 4657,
 4658,
 4659,
 4660,
 4661,
 4662,
 4663,
 4664,
 4665,
 4666,
 4667,
 4668,
 4669,
 4670,
 4671,
 4672,
 4673,
 4674,
 4675,
 4676,
 4677,
 4678,
 4679,
 4680,
 4681,
 4682,
 4683,
 4684,
 4685,
 4686,
 4687,
 4688,
 4689,
 4690,
 4691,
 4692,
 4693,
 4694,
 4695,
 4696,
 4697,
 4698,
 4699,
 4700,
 4701,
 4702,
 4703,
 4704,
 4705,
 4706,
 4707,
 4708,
 4709,
 4710,
 4711,
 4712,
 4713,
 4714,
 4715,
 4716,
 4717,
 4718,
 4719,
 4720,
 4721,
 4722,
 4723,
 4724,
 4725,
 4726,
 4727,
 4728,
 4729,
 4730,
 4731,
 4732,
 4733,
 4734,
 4735,
 4736,
 4737,
 4738,
 4739,
 4740,
 4741,
 4742,
 4743,
 4744,
 4745,
 4746,
 4747,
 4748,
 4749,
 4750,
 4751,
 4752,
 4753,
 4754,
 4755,
 4756,
 4757,
 4758,
 4759,
 4760,
 4761,
 4762,
 4763,
 4764,
 4765,
 4766,
 4767,
 4768,
 4769,
 4770,
 4771,
 4772,
 4773,
 4774,
 4775,
 4776,
 4777,
 4778,
 4779,
 4780,
 4781,
 4782,
 4783,
 4784,
 4785,
 4786,
 4787,
 4788,
 4789,
 4790,
 4791,
 4792,
 4793,
 4794,
 4795,
 4796,
 4797,
 4798,
 4799,
 4800,
 4801,
 4802,
 4803,
 4804,
 4805,
 4806,
 4807,
 4808,
 4809,
 4810,
 4811,
 4812,
 4813,
 4814,
 4815,
 4816,
 4817,
 4818,
 4819,
 4820,
 4821,
 4822,
 4823,
 4824,
 4825,
 4826,
 4827,
 4828,
 4829,
 4830,
 4831,
 4832,
 4833,
 4834,
 4835,
 4836,
 4837,
 4838,
 4839,
 4840,
 4841,
 4842,
 4843,
 4844,
 4845,
 4846,
 4847,
 4848,
 4849,
 4850,
 4851,
 4852,
 4853,
 4854,
 4855,
 4856,
 4857,
 4858,
 4859,
 4860,
 4861,
 4862,
 4863,
 4864,
 4865,
 4866,
 4867,
 4868,
 4869,
 4870,
 4871,
 4872,
 4873,
 4874,
 4875,
 4876,
 4877,
 4878,
 4879,
 4880,
 4881,
 4882,
 4883,
 4884,
 4885,
 4886,
 4887,
 4888,
 4889,
 4890,
 4891,
 4892,
 4893,
 4894,
 4895,
 4896,
 4897,
 4898,
 4899,
 4900,
 4901,
 4902,
 4903,
 4904,
 4905,
 4906,
 4907,
 4908,
 4909,
 4910,
 4911,
 4912,
 4913,
 4914,
 4915,
 4916,
 4917,
 4918,
 4919,
 4920,
 4921,
 4922,
 4923,
 4924,
 4925,
 4926,
 4927,
 4928,
 4929,
 4930,
 4931,
 4932,
 4933,
 4934,
 4935,
 4936,
 4937,
 4938,
 4939,
 4940,
 4941,
 4942,
 4943,
 4944,
 4945,
 4946,
 4947,
 4948,
 4949,
 4950,
 4951,
 4952,
 4953,
 4954,
 4955,
 4956,
 4957,
 4958,
 4959,
 4960,
 4961,
 4962,
 4963,
 4964,
 4965,
 4966,
 4967,
 4968,
 4969,
 4970,
 4971,
 4972,
 4973,
 4974,
 4975,
 4976,
 4977,
 4978,
 4979,
 4980,
 4981,
 4982,
 4983,
 4984,
 4985,
 4986,
 4987,
 4988,
 4989,
 4990,
 4991,
 4992,
 4993,
 4994,
 4995,
 4996,
 4997,
 4998,
 4999,
 5000,
 5001,
 5002,
 5003,
 5004,
 5005,
 5006,
 5007,
 5008,
 5009,
 5010,
 5011,
 ...]

In [15]:
authorships_df.iloc[736]

author_position                                                       middle
author                     {'id': 'https://openalex.org/A5105194369', 'di...
institutions               [{'id': 'https://openalex.org/I40120149', 'dis...
countries                                                               [GB]
is_corresponding                                                       False
raw_author_name                                               Green, Patrick
raw_affiliation_strings                                 University of Oxford
affiliations               [{'raw_affiliation_string': 'University of Oxf...
Name: 63, dtype: object

In [16]:
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'primary_topic', 'topics', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'authorships',
       'affiliations', 'Institution', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio', 'volume', 'issue', 'first_page',
       'last_page', 'primary_location-source-display_name'],
      dtype='object')

In [17]:
df.head()

,id,doi,title,type,publication_year,publication_date,primary_topic,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authorships,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,volume,issue,first_page,last_page,primary_location-source-display_name
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,748,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None,Harvard Dataverse
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",dataset,2023,2023-01-01,"{'id': 'https://openalex.org/T13067', 'display...","[{'id': 'https://openalex.org/T13067', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",NaN,NaN,NaN,False,75,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None,Harvard Dataverse
2,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T14163', 'display...","[{'id': 'https://openalex.org/T14163', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I2800403580', 'd...",NaN,NaN,NaN,False,67,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None,Harvard Dataverse
3,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,dataset,2022,2022-09-29,"{'id': 'https://openalex.org/T10644', 'display...","[{'id': 'https://openalex.org/T10644', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'The Ohio State Un...,"[{'id': 'https://openalex.org/I52357470', 'dis...",NaN,NaN,NaN,False,62,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None,Harvard Dataverse
4,https://openalex.org/W4255862108,https://doi.org/10.3886/icpsr04652,"Midlife in the United States (MIDUS 2), 2004-2006",dataset,2014,2014-01-10,"{'id': 'https://openalex.org/T12781', 'display...","[{'id': 'https://openalex.org/T12781', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Wis...,"[{'id': 'https://openalex.org/I135310074', 'di...",NaN,NaN,NaN,False,42,NaN,NaN,"{'volume': None, 'issue': None, 'first_page': ...",None,None,None,None,ICPSR Data Holdings

In [20]:
# what was , 'min', 'max'
# Create new DataFrame to concat original data from
# no longer in OpenAlex: 'citation_normalized_percentile-value', 'is_in_top_1_percent', 'is_in_top_10_percent', 
cleaned_df = df[['id', 'doi', 'type', 'title', 'publication_year', 'publication_date', 'primary_topic', 'topics',
       'language', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'primary_location-source-display_name',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext','cited_by_count',
       'volume', 'issue', 'first_page',
       'last_page',]].copy()
cleaned_df

,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,dataset,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,"{'id': 'https://openalex.org/T13067', 'display...","[{'id': 'https://openalex.org/T13067', 'displa...",en,0.0,datacite,True,green,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,75,None,None,None,None
2,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,dataset,"ArcticDEM - Strips, Version 4.1",2022,2022-09-29,"{'id': 'https://openalex.org/T14163', 'display...","[{'id': 'https://openalex.org/T14163', 'displa...",en,0.0,datacite,True,green,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,67,None,None,None,None
3,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,dataset,The Reference Elevation Model of Antarctica - ...,2022,2022-09-29,"{'id': 'https://openalex.org/T10644', 'display...","[{'id': 'https://openalex.org/T10644', 'displa...",en,0.0,datacite,True,green,other-oa,Harvard Dataverse,NaN,NaN,NaN,False,62,None,None,None,None
4,https://openalex.org/W4255862108,https://doi.org/10.3886/icpsr04652,dataset,"Midlife in the United States (MIDUS 2), 2004-2006",2014,2014-01-10,"{'id': 'https://openalex.org/T12781', 'display...","[{'id': 'https://openalex.org/T12781', 'displa...",en,0.0,datacite,True,green,None,ICPSR Data Holdings,NaN,NaN,NaN,False,42,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4007,https://openalex.org/W7154972851,https://doi.org/10.17632/bpcpfns6vb,dataset,A global genetic interaction network of a huma...,2026,2026-01-01,None,[],None,0.0,datacite,True,green,cc-by,Mendeley Data,NaN,NaN,NaN,False,0,None,None,None,None
4008,https://openalex.org/W7154995270,https://doi.org/10.13020/wxbd-8t05,dataset,ccSpill manuscript supplement,2025,2025-12-11,None,[],None,0.0,datacite,True,green,cc-by,Data Repository for the University of Minnesota,NaN,NaN,NaN,False,0,None,None,None,None
4009,https://openalex.org/W7155010658,https://doi.org/10.17632/bpcpfns6vb.1,dataset,A global genetic interaction network of a huma...,2026,2026-01-01,None,[],None,0.0,datacite,True,green,cc-by,Mendeley Data,NaN,NaN,NaN,False,0,None,None,None,None
4010,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,dataset,Data from: Preliminary efficacy of cognitive m...,2026,2026-03-19,None,[],en,0.0,datacite,True,green,public-domain,DRYAD,NaN,NaN,NaN,False,0,None,None,None,None
4011,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None

In [21]:
# concat original data to unnested cleaned_df
cleaned_df = pd.concat([authorships_df, cleaned_df], axis=1)
cleaned_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,"Porter, Claire",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,"Morin, Paul",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Howat, Ian",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Noh, Myoung-Jon",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,[{'raw_affiliation_string': 'National Geospati...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4010,last,"{'id': 'https://openalex.org/A5134098806', 'di...","[{'id': 'https://openalex.org/I145608581', 'di...",[US],False,"Morse, Leslie R.",University of Miami,[{'raw_affiliation_string': 'University of Mia...,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,dataset,Data from: Preliminary efficacy of cognitive m...,2026,2026-03-19,None,[],en,0.0,datacite,True,green,public-domain,DRYAD,NaN,NaN,NaN,False,0,None,None,None,None
4011,first,"{'id': 'https://openalex.org/A5050360160', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],True,Sohini RoyChowdhury,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None
4011,middle,"{'id': 'https://openalex.org/A5007884053', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Keshab K. Parhi,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None
4011,middle,"{'id': 'https://openalex.org/A5104048359', 'di...","[{'id': 'https://openalex.org/I4210140408', 'd...",[US],False,Mary G. Lawrence,"Ophthalmology, Minneapolis VA Medical Center, ...","[{'raw_affiliation_string': 'Ophthalmology, Mi...",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None
4011,last,"{'id': 'https://openalex.org/A5089355316', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Dara Koozekanani,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None

In [22]:
cleaned_df.iloc[736]

author_position                                                                    middle
author                                  {'id': 'https://openalex.org/A5105194369', 'di...
institutions                            [{'id': 'https://openalex.org/I40120149', 'dis...
countries                                                                            [GB]
is_corresponding                                                                    False
raw_author_name                                                            Green, Patrick
raw_affiliation_strings                                              University of Oxford
affiliations                            [{'raw_affiliation_string': 'University of Oxf...
id                                                       https://openalex.org/W4393652843
doi                                                https://doi.org/10.5281/zenodo.7261921
type                                                                              dataset
title                                   MicroBooNE BNB Electron Neutrino Overlay Sampl...
publication_year                                                                     2022
publication_date                                                               2022-11-01
primary_topic                           {'id': 'https://openalex.org/T10921', 'display...
topics                                  [{'id': 'https://openalex.org/T10921', 'displa...
language                                                                               en
retracted                                                                             0.0
index location                                                                   datacite
is_oa                                                                                True
oa_status                                                                           green
license                                                                             cc-by
primary_location-source-display_name    OSTI OAI (U.S. Department of Energy Office of ...
apc_list                                                                              NaN
apc_paid                                                                              NaN
fwci                                                                                  NaN
has_fulltext                                                                        False
cited_by_count                                                                          3
volume                                                                               None
issue                                                                                None
first_page                                                                           None
last_page                                                                            None
Name: 63, dtype: object

In [23]:
# reset index to concat with author information_df
cleaned_df = cleaned_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(cleaned_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'authorships-author-author_id', 'display_name': 'authorships-author-display_name'})
author_info_df

,authorships-author-author_id,authorships-author-display_name,orcid
0,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,https://openalex.org/A5068237537,Ian M. Howat,https://orcid.org/0000-0002-8072-6260
3,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...
24328,https://openalex.org/A5134098806,Leslie R. Morse,None
24329,https://openalex.org/A5050360160,Sohini Roychowdhury,https://orcid.org/0000-0001-6416-9890
24330,https://openalex.org/A5007884053,Keshab K. Parhi,https://orcid.org/0000-0001-6543-2793
24331,https://openalex.org/A5104048359,Mary Lawrence,None
24332,https://openalex.org/A5089355316,Dara D. Koozekanani,None

In [24]:
# concat author_info_df to cleaned_df
cleaned_df = pd.concat([cleaned_df, author_info_df], axis=1).reset_index(drop=True)
cleaned_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,authorships-author-author_id,authorships-author-display_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,"Porter, Claire",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,"Morin, Paul",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Howat, Ian",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5068237537,Ian M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Noh, Myoung-Jon",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,[{'raw_affiliation_string': 'National Geospati...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5109469110,B. Bates,None

In [25]:
# normalize nested Insituttion column
institutions_df = CleanJSON('institutions', cleaned_df)

# remove list format for lineage
institutions_df['lineage'] = institutions_df['lineage'].str[0]
institutions_df

# rename columns
institutions_df = institutions_df.rename(columns={'id': 'institutions-id', 'display_name': 'institutions-display_name', 'type': 'institutions-type'})

In [26]:
# remove duplicate indices 
institutions_df = institutions_df[~institutions_df.index.duplicated(keep='first')]

# fill nan values on missinging indices
institutions_df = institutions_df.reindex(range(institutions_df.index.min(), institutions_df.index.max()+1))

In [27]:
missing_index(institutions_df)

[]

In [28]:
institutions_df.head(50)

,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
1,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
5,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
6,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
7,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
8,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
9,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
10,https://openalex.org/I2802236040,University of Colorado System,https://ror.org/00jc20583,US,education,https://openalex.org/I2802236040
11,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
12,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
13,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
14,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
15,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
16,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
17,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
18,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
24,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
25,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
26,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
27,https://openalex.org/I4210116747,Office of Science and Technology Policy,https://ror.org/02bjkqr85,US,government,https://openalex.org/I1308683654
28,https://openalex.org/I4210154540,Asiaq Greenland Survey,https://ror.org/05pzd7w96,GL,government,https://openalex.org/I4210154540
29,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
30,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
31,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
32,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
33,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
34,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
35,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
36,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
37,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
38,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
39,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
40,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
41,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
42,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
43,NaN,NaN,NaN,NaN,NaN,NaN
44,NaN,NaN,NaN,NaN,NaN,NaN
45,NaN,NaN,NaN,NaN,NaN,NaN
46,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
47,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580
48,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
49,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470

In [29]:
primary_topic_df = CleanJSON('primary_topic', cleaned_df)
primary_topic_df = primary_topic_df.rename(columns={'id': 'primary_topic-id', 'score': 'primary_topic-score', 'display_name': 'primary_topic-display_name', 
                                      'subfield': 'primary_topic-subfield', 'field': 'primary_topic-field', 'domain': 'primary_topic-domain'})
primary_topic_df

,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,Environmental Chemistry,Environmental Science,Physical Sciences
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,Environmental Chemistry,Environmental Science,Physical Sciences
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
...,...,...,...,...,...,...
24330,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,"Radiology, Nuclear Medicine and Imaging",Medicine,Health Sciences
24331,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4
24331,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,"Radiology, Nuclear Medicine and Imaging",Medicine,Health Sciences
24332,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4
24332,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,"Radiology, Nuclear Medicine and Imaging",Medicine,Health Sciences

In [30]:
primary_topic_df = primary_topic_df[~primary_topic_df.index.duplicated(keep='first')]

primary_topic_df = primary_topic_df.reindex(range(primary_topic_df.index.min(), primary_topic_df.index.max()+1))

In [31]:
primary_topic_df

,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3
...,...,...,...,...,...,...
24328,NaN,NaN,NaN,NaN,NaN,NaN
24329,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4
24330,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4
24331,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4
24332,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4

In [32]:
missing_index(primary_topic_df)

[]

In [33]:
topics_df = CleanJSON('topics', cleaned_df)
topics_df = topics_df.rename(columns={'id': 'topics-id', 'display_name': 'topics-display_name'})
topics_df

,topics-id,topics-display_name,score,subfield,field,domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13126,Scientific Research and Discoveries,0.6482,"{'id': 'https://openalex.org/subfields/3109', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
24330,https://openalex.org/T11396,Artificial Intelligence in Healthcare,0.9608,"{'id': 'https://openalex.org/subfields/3605', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
24331,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,"{'id': 'https://openalex.org/subfields/2741', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
24331,https://openalex.org/T11396,Artificial Intelligence in Healthcare,0.9608,"{'id': 'https://openalex.org/subfields/3605', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
24332,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,"{'id': 'https://openalex.org/subfields/2741', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
24332,https://openalex.org/T11396,Artificial Intelligence in Healthcare,0.9608,"{'id': 'https://openalex.org/subfields/3605', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."

In [34]:
missing_index(topics_df)

[1386,
 1387,
 1388,
 1389,
 1390,
 1391,
 1392,
 1393,
 1394,
 1395,
 1396,
 1397,
 1398,
 1399,
 1400,
 1401,
 1402,
 1403,
 1404,
 1405,
 1406,
 1407,
 1408,
 1409,
 1410,
 1411,
 1412,
 1413,
 1414,
 1415,
 1416,
 1417,
 1418,
 1419,
 1420,
 1421,
 1422,
 1423,
 1424,
 1425,
 1426,
 1427,
 1428,
 1429,
 1430,
 1431,
 1432,
 1433,
 1434,
 1435,
 1436,
 1437,
 1438,
 1439,
 1440,
 1441,
 1442,
 1443,
 1444,
 1445,
 1446,
 1447,
 1448,
 1449,
 1450,
 1451,
 1452,
 1453,
 1454,
 1455,
 1456,
 1457,
 1458,
 1459,
 1460,
 1461,
 1462,
 1463,
 1464,
 1465,
 1466,
 1467,
 1468,
 1469,
 1470,
 1471,
 1472,
 1473,
 1474,
 1475,
 1476,
 1477,
 1478,
 1479,
 1480,
 1481,
 1482,
 1483,
 1484,
 1485,
 2387,
 2388,
 2389,
 2390,
 2538,
 2539,
 2540,
 2541,
 2542,
 2543,
 2544,
 2545,
 2546,
 2547,
 2548,
 2549,
 2550,
 2551,
 2552,
 2553,
 2554,
 2555,
 2556,
 2557,
 2558,
 2559,
 2560,
 2561,
 2562,
 2563,
 2564,
 2565,
 2566,
 2567,
 2568,
 2569,
 2570,
 2571,
 2572,
 2573,
 2574,
 2575,
 2576,
 2577,
 2578,
 2579,
 2580,
 2581,
 3203,
 3204,
 3205,
 3206,
 3207,
 3239,
 3240,
 3241,
 3242,
 3383,
 3384,
 3385,
 3386,
 3407,
 3531,
 3532,
 3533,
 3534,
 3535,
 3536,
 3537,
 3538,
 3539,
 3540,
 3541,
 3542,
 3543,
 3544,
 3545,
 3546,
 3547,
 3548,
 3549,
 3550,
 3551,
 3552,
 3553,
 3554,
 3555,
 3556,
 3557,
 3558,
 3559,
 3560,
 3561,
 3562,
 3563,
 3564,
 3565,
 3566,
 3567,
 3568,
 3569,
 3570,
 3571,
 3572,
 3573,
 3574,
 3575,
 3576,
 3577,
 3578,
 3579,
 3580,
 3581,
 3582,
 3583,
 3584,
 3585,
 3586,
 3587,
 3588,
 3589,
 3590,
 3591,
 3592,
 3593,
 3594,
 3595,
 3596,
 3597,
 3598,
 3599,
 3600,
 3601,
 3602,
 3603,
 3604,
 3605,
 3606,
 3607,
 3608,
 3609,
 3610,
 3611,
 3612,
 3613,
 3614,
 3615,
 3616,
 3617,
 3618,
 3619,
 3620,
 3621,
 3622,
 3623,
 3624,
 3625,
 3626,
 3627,
 3628,
 3629,
 3630,
 3666,
 3667,
 3712,
 3713,
 3748,
 3749,
 3798,
 3835,
 3836,
 3837,
 3838,
 3852,
 3853,
 3854,
 3855,
 3856,
 3883,
 3884,
 3895,
 3896,
 3897,
 3898,
 3918,
 3919,
 3969,
 3970,
 4005,
 4006,
 4007,
 4008,
 4018,
 4091,
 4092,
 4093,
 4094,
 4095,
 4096,
 4097,
 4098,
 4099,
 4245,
 4246,
 4247,
 4248,
 4249,
 4250,
 4251,
 4252,
 4253,
 4312,
 4313,
 4386,
 4387,
 4400,
 4401,
 4402,
 4403,
 4404,
 4405,
 4406,
 4407,
 4520,
 4521,
 4575,
 4576,
 4577,
 4578,
 4579,
 4587,
 4588,
 4606,
 4607,
 4608,
 4609,
 4610,
 4611,
 4612,
 4615,
 4648,
 4649,
 4698,
 4699,
 4736,
 4737,
 4759,
 4760,
 4761,
 4762,
 4898,
 4899,
 4929,
 4930,
 4931,
 4979,
 4980,
 4981,
 4982,
 4983,
 4984,
 4985,
 4986,
 4987,
 4988,
 4989,
 4990,
 4991,
 4992,
 4993,
 4994,
 4995,
 4996,
 4997,
 4998,
 4999,
 5000,
 5001,
 5059,
 5060,
 5061,
 5062,
 5063,
 5064,
 5074,
 5075,
 5204,
 5205,
 5206,
 5249,
 5250,
 5265,
 5266,
 5272,
 5296,
 5297,
 5298,
 5299,
 5300,
 5301,
 5317,
 5318,
 5319,
 5320,
 5321,
 5347,
 5348,
 5353,
 5354,
 5355,
 5356,
 11819,
 13247,
 16003,
 16004,
 16005,
 16006,
 16007,
 16008,
 16009,
 16010,
 16011,
 16012,
 16425,
 16426,
 16427,
 16428,
 16429,
 16430,
 16431,
 16432,
 16433,
 16434,
 18044,
 18045,
 18046,
 18062,
 18126,
 18127,
 18128,
 18129,
 18130,
 18131,
 18142,
 18143,
 18144,
 18151,
 18152,
 18158,
 18159,
 18160,
 18219,
 18220,
 18221,
 18228,
 18237,
 18238,
 18239,
 18250,
 18292,
 18293,
 18294,
 18309,
 18319,
 18320,
 18321,
 18322,
 18329,
 18330,
 18331,
 18344,
 18345,
 18346,
 18347,
 18348,
 18349,
 18350,
 18351,
 18352,
 18353,
 18354,
 18355,
 18356,
 18357,
 18361,
 18362,
 18372,
 18373,
 18374,
 18375,
 18376,
 18377,
 18378,
 18379,
 18380,
 18385,
 18386,
 18387,
 18424,
 18425,
 18426,
 18443,
 18444,
 18445,
 18447,
 18448,
 18449,
 18450,
 18451,
 18464,
 18465,
 18466,
 18467,
 18468,
 18469,
 18470,
 18474,
 18478,
 18481,
 18482,
 18483,
 18484,
 18485,
 18486,
 18487,
 18488,
 18489,
 18491,
 18492,
 18493,
 18494,
 18495,
 18496,
 18497,
 18498,
 18499,
 18507,
 18508,
 18509,
 18511,
 18512,
 18513,
 18514,
 18515,
 18516,
 18526,
 18527,
 18530,
 18531,
 18532,
 18533,
 18534,
 18535,
 18536,
 18537,
 18538,
 18539,
 18540,
 18546,
 18547,
 18548,
 18552,
 18556,
 18557,
 18558,
 18559,
 18561,
 18562,
 18563,
 18564,
 18571,
 18572,
 18573,
 18589,
 18590,
 18591,
 18592,
 18593,
 18644,
 18645,
 18646,
 18654,
 18655,
 18658,
 18664,
 18665,
 18666,
 18674,
 18675,
 18676,
 18677,
 18678,
 18679,
 18680,
 18681,
 18682,
 18695,
 18696,
 18697,
 18708,
 18709,
 18710,
 18714,
 18715,
 18716,
 18717,
 18718,
 18719,
 18720,
 18721,
 18723,
 18724,
 18728,
 18729,
 18730,
 18735,
 18736,
 18737,
 18738,
 18743,
 18744,
 18745,
 18748,
 18749,
 18750,
 18757,
 18758,
 18759,
 18760,
 18761,
 18762,
 18763,
 18764,
 18765,
 18766,
 18768,
 18769,
 18776,
 18777,
 18778,
 18779,
 18780,
 18781,
 18782,
 18783,
 18824,
 18825,
 18826,
 18827,
 18828,
 18829,
 18830,
 18831,
 18837,
 18838,
 18839,
 18842,
 18843,
 18844,
 18845,
 18846,
 18850,
 18851,
 18852,
 18853,
 18854,
 18855,
 18860,
 18861,
 18862,
 18872,
 18879,
 18880,
 18881,
 18896,
 18897,
 18898,
 18899,
 18900,
 18901,
 18902,
 18903,
 18904,
 18905,
 18906,
 18907,
 18908,
 18909,
 18910,
 18914,
 18915,
 18916,
 18917,
 18922,
 18923,
 18924,
 18928,
 18929,
 18930,
 18931,
 18935,
 18936,
 18937,
 18952,
 18953,
 18970,
 18972,
 18973,
 18974,
 18975,
 18976,
 18977,
 18978,
 18979,
 18982,
 18983,
 19009,
 19010,
 19011,
 19059,
 19060,
 19061,
 19062,
 19063,
 19064,
 19065,
 19066,
 19067,
 19068,
 19069,
 19070,
 19071,
 19072,
 19085,
 19086,
 19087,
 19099,
 19100,
 19101,
 19102,
 19103,
 19104,
 19105,
 19106,
 19108,
 19109,
 19110,
 19111,
 19112,
 19122,
 19123,
 19124,
 19125,
 19134,
 19135,
 19136,
 19137,
 19138,
 19139,
 19197,
 19198,
 19199,
 19200,
 19201,
 19202,
 19203,
 19204,
 19205,
 19209,
 19210,
 19211,
 19218,
 19219,
 19220,
 19221,
 19222,
 19223,
 19224,
 19225,
 19226,
 19227,
 19228,
 19229,
 19230,
 19231,
 19232,
 19233,
 19240,
 19241,
 19242,
 19243,
 19244,
 19245,
 19246,
 19247,
 19251,
 19252,
 19253,
 19260,
 19261,
 19262,
 19267,
 19268,
 19269,
 19270,
 19271,
 19272,
 19273,
 19274,
 19275,
 19276,
 19277,
 19280,
 19281,
 19282,
 19292,
 19293,
 19294,
 19295,
 19296,
 19297,
 19298,
 19299,
 19300,
 19301,
 19302,
 19303,
 19304,
 19305,
 19306,
 19307,
 19308,
 19329,
 19330,
 19331,
 19334,
 19335,
 19336,
 19337,
 19338,
 19339,
 19340,
 19341,
 19349,
 19350,
 19351,
 19358,
 19359,
 19360,
 19361,
 19362,
 19363,
 19364,
 19365,
 19366,
 19387,
 19406,
 19407,
 19408,
 19409,
 19411,
 19412,
 19413,
 19414,
 19415,
 19416,
 19417,
 19418,
 19424,
 19425,
 19426,
 19427,
 19428,
 19435,
 19436,
 19437,
 19438,
 19454,
 19455,
 19458,
 19459,
 19460,
 19461,
 19462,
 19463,
 19464,
 19465,
 19466,
 19467,
 19468,
 19469,
 19470,
 19486,
 19487,
 19496,
 19497,
 19505,
 19506,
 19507,
 19508,
 19509,
 19521,
 19522,
 19523,
 19524,
 19525,
 19532,
 19533,
 19553,
 19554,
 19555,
 19556,
 19557,
 19558,
 19559,
 19560,
 19561,
 19562,
 19577,
 19578,
 19579,
 19580,
 19581,
 19586,
 19587,
 19588,
 19589,
 19594,
 19595,
 19605,
 19606,
 19607,
 19608,
 19630,
 19631,
 19632,
 19633,
 19634,
 19660,
 19661,
 19662,
 19663,
 19664,
 19698,
 19699,
 19700,
 19701,
 19702,
 19722,
 19723,
 19742,
 19743,
 19744,
 19745,
 19748,
 19749,
 19755,
 19756,
 19757,
 19758,
 19759,
 19760,
 19761,
 19762,
 19763,
 19764,
 19765,
 19766,
 19767,
 19768,
 19769,
 19770,
 19771,
 19772,
 19773,
 19774,
 19775,
 19776,
 19777,
 19778,
 19779,
 19780,
 19781,
 19793,
 19794,
 19795,
 19796,
 19797,
 19798,
 19799,
 19800,
 19801,
 19802,
 19803,
 19804,
 19805,
 19806,
 19807,
 19808,
 19809,
 ...]

In [35]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [36]:
missing_index(topics_df)

[]

In [37]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'topics-subfield-id', 'display_name': 'topics-subfield-display_name'})
field_df = field_df.rename(columns={'id': 'topics-field-id', 'display_name': 'topics-field-display_name'})
domain_df = domain_df.rename(columns={'id': 'topics-domain-id', 'display_name': 'topics-domain-display_name'})

field_df

                      topics-field-id topics-field-display_name
0      https://openalex.org/fields/23     Environmental Science
1      https://openalex.org/fields/23     Environmental Science
2      https://openalex.org/fields/23     Environmental Science
3      https://openalex.org/fields/23     Environmental Science
4      https://openalex.org/fields/23     Environmental Science
...                               ...                       ...
24328                             NaN                       NaN
24329  https://openalex.org/fields/27                  Medicine
24330  https://openalex.org/fields/27                  Medicine
24331  https://openalex.org/fields/27                  Medicine
24332  https://openalex.org/fields/27                  Medicine

[24333 rows x 2 columns]

In [38]:
topics_df = topics_df[['topics-id', 'topics-display_name']]

In [39]:
topics_df=topics_df.reset_index(drop=True)
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...
24328,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24329,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24330,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24331,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24332,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [40]:
# concat insitution_df and topics_df
merged_list = [institutions_df, primary_topic_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24328,https://openalex.org/I145608581,University of Miami,https://ror.org/02dgjyy92,US,education,https://openalex.org/I145608581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24329,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24330,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24331,https://openalex.org/I4210140408,Minneapolis VA Medical Center,https://ror.org/032b8d361,US,healthcare,https://openalex.org/I1322918889,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24332,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [41]:
unnested_df = cleaned_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,primary_topic,topics,language,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,authorships-author-author_id,authorships-author-display_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,"Porter, Claire",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,"Morin, Paul",University of Minnesota,[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Howat, Ian",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5068237537,Ian M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,"Noh, Myoung-Jon",The Ohio State University,[{'raw_affiliation_string': 'The Ohio State Un...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,[{'raw_affiliation_string': 'National Geospati...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,"{'id': 'https://openalex.org/T10995', 'display...","[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,NaN,NaN,NaN,False,748,None,None,None,None,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24328,4010,last,"{'id': 'https://openalex.org/A5134098806', 'di...","[{'id': 'https://openalex.org/I145608581', 'di...",[US],False,"Morse, Leslie R.",University of Miami,[{'raw_affiliation_string': 'University of Mia...,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,dataset,Data from: Preliminary efficacy of cognitive m...,2026,2026-03-19,None,[],en,0.0,datacite,True,green,public-domain,DRYAD,NaN,NaN,NaN,False,0,None,None,None,None,https://openalex.org/A5134098806,Leslie R. Morse,None
24329,4011,first,"{'id': 'https://openalex.org/A5050360160', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],True,Sohini RoyChowdhury,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None,https://openalex.org/A5050360160,Sohini Roychowdhury,https://orcid.org/0000-0001-6416-9890
24330,4011,middle,"{'id': 'https://openalex.org/A5007884053', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Keshab K. Parhi,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None,https://openalex.org/A5007884053,Keshab K. Parhi,https://orcid.org/0000-0001-6543-2793
24331,4011,middle,"{'id': 'https://openalex.org/A5104048359', 'di...","[{'id': 'https://openalex.org/I4210140408', 'd...",[US],False,Mary G. Lawrence,"Ophthalmology, Minneapolis VA Medical Center, ...","[{'raw_affiliation_string': 'Ophthalmology, Mi...",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None,https://openalex.org/A5104048359,Mary Lawrence,None
24332,4011,last,"{'id': 'https://openalex.org/A5089355316', 'di...","[{'id': 'https://openalex.org/I2800403580', 'd...",[US],False,Dara Koozekanani,"University of Minnesota, Minneapolis, Minnesota",[{'raw_affiliation_string': 'University of Min...,https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,"{'id': 'https://openalex.org/T11438', 'display...","[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,NaN,NaN,NaN,False,0,None,None,None,None,https://openalex.org/A5089355316,Dara D. Koozekanani,None

In [42]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'primary_topic', 'topics', 'language', 'retracted',
       'index location', 'is_oa', 'oa_status', 'license',
       'primary_location-source-display_name', 'apc_list', 'apc_paid', 'fwci',
       'has_fulltext', 'cited_by_count', 'volume', 'issue', 'first_page',
       'last_page', 'authorships-author-author_id',
       'authorships-author-display_name', 'orcid'],
      dtype='object')

In [44]:
# no longer in OpenAlex: 'citation_normalized_percentile-value', 'is_in_top_1_percent', 'is_in_top_10_percent', 
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count',
       'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'primary_location-source-display_name', 'authorships-author-author_id',
       'authorships-author-display_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,authorships-author-author_id,authorships-author-display_name,orcid
0,first,[US],True,"Porter, Claire",University of Minnesota,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,middle,[US],False,"Morin, Paul",University of Minnesota,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,middle,[US],False,"Howat, Ian",The Ohio State University,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5068237537,Ian M. Howat,https://orcid.org/0000-0002-8072-6260
3,middle,[US],False,"Noh, Myoung-Jon",The Ohio State University,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,middle,[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24328,last,[US],False,"Morse, Leslie R.",University of Miami,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,dataset,Data from: Preliminary efficacy of cognitive m...,2026,2026-03-19,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,datacite,True,green,public-domain,DRYAD,https://openalex.org/A5134098806,Leslie R. Morse,None
24329,first,[US],True,Sohini RoyChowdhury,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5050360160,Sohini Roychowdhury,https://orcid.org/0000-0001-6416-9890
24330,middle,[US],False,Keshab K. Parhi,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5007884053,Keshab K. Parhi,https://orcid.org/0000-0001-6543-2793
24331,middle,[US],False,Mary G. Lawrence,"Ophthalmology, Minneapolis VA Medical Center, ...",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5104048359,Mary Lawrence,None
24332,last,[US],False,Dara Koozekanani,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5089355316,Dara D. Koozekanani,None

In [45]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,primary_location-source-display_name,authorships-author-author_id,authorships-author-display_name,orcid,institutions-id,institutions-display_name,ror,country_code,institutions-type,lineage,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name
0,first,[US],True,"Porter, Claire",University of Minnesota,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,middle,[US],False,"Morin, Paul",University of Minnesota,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,middle,[US],False,"Howat, Ian",The Ohio State University,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5068237537,Ian M. Howat,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,middle,[US],False,"Noh, Myoung-Jon",The Ohio State University,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5102675431,Myoung-Jon Noh,None,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,middle,[US],False,"Bates, Brian",National Geospatial-Intelligence Agency,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-09-26,en,NaN,NaN,NaN,False,748,None,None,None,None,0.0,datacite,True,green,None,Harvard Dataverse,https://openalex.org/A5109469110,B. Bates,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24328,last,[US],False,"Morse, Leslie R.",University of Miami,https://openalex.org/W7155096279,https://doi.org/10.5061/dryad.7h44j1007,dataset,Data from: Preliminary efficacy of cognitive m...,2026,2026-03-19,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,datacite,True,green,public-domain,DRYAD,https://openalex.org/A5134098806,Leslie R. Morse,None,https://openalex.org/I145608581,University of Miami,https://ror.org/02dgjyy92,US,education,https://openalex.org/I145608581,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24329,first,[US],True,Sohini RoyChowdhury,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5050360160,Sohini Roychowdhury,https://orcid.org/0000-0001-6416-9890,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24330,middle,[US],False,Keshab K. Parhi,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5007884053,Keshab K. Parhi,https://orcid.org/0000-0001-6543-2793,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24331,middle,[US],False,Mary G. Lawrence,"Ophthalmology, Minneapolis VA Medical Center, ...",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5104048359,Mary Lawrence,None,https://openalex.org/I4210140408,Minneapolis VA Medical Center,https://ror.org/032b8d361,US,healthcare,https://openalex.org/I1322918889,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
24332,last,[US],False,Dara Koozekanani,"University of Minnesota, Minneapolis, Minnesota",https://openalex.org/W869100622,https://doi.org/10.4016/40856.01,dataset,4070 Automated Screening System for Detecting ...,2012,2012-03-12,en,NaN,NaN,NaN,False,0,None,None,None,None,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5089355316,Dara D. Koozekanani,None,https://openalex.org/I2800403580,University of Minnesota System,https://ror.org/03grvy078,US,education,https://openalex.org/I2800403580,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9921,https://openalex.org/subfields/2741,https://openalex.org/fields/27,https://openalex.org/domains/4,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [46]:
# check for nan authors
unnested_df['authorships-author-display_name'].isnull().values.any()

False

In [47]:
# remove rows where authors are NaN
#unnested_df = unnested_df.iloc[:10568]
#unnested_df

In [48]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'volume', 'issue',
       'first_page', 'last_page', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'primary_location-source-display_name',
       'authorships-author-author_id', 'authorships-author-display_name',
       'orcid', 'institutions-id', 'institutions-display_name', 'ror',
       'country_code', 'institutions-type', 'lineage', 'primary_topic-id',
       'primary_topic-display_name', 'primary_topic-score',
       'primary_topic-subfield', 'primary_topic-field', 'primary_topic-domain',
       'topics-id', 'topics-display_name', 'topics-subfield-id',
       'topics-subfield-display_name', 'topics-field-id',
       'topics-field-display_name', 'topics-domain-id',
       'topics-domain-display_name'],
      dtype='object')

In [50]:
# no longer in OpenAlex: 'citation_normalized_percentile-value', 'is_in_top_1_percent', 'is_in_top_10_percent', 
unnested_df = unnested_df[['id', 'doi', 'type', 'institutions-type', 'title', 'publication_year', 'publication_date', 'language', 
       'authorships-author-author_id','authorships-author-display_name', 'author_position', 'orcid',
       'primary_topic-id', 'primary_topic-display_name', 'primary_topic-score', 'primary_topic-subfield', 'primary_topic-field',
       'primary_topic-domain', 'topics-id', 'topics-display_name', 'topics-subfield-id', 'topics-subfield-display_name', 
       'topics-field-id', 'topics-field-display_name', 'topics-domain-id','topics-domain-display_name', 
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'volume', 'issue', 'first_page', 'last_page', 
       'index location', 'primary_location-source-display_name',
       'retracted', 'index location', 'primary_location-source-display_name', 'is_oa', 'oa_status', 'license',  
       'institutions-id', 'institutions-display_name', 'raw_affiliation_strings',  'country_code', 'ror', 'lineage']]
unnested_df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,index location,primary_location-source-display_name,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I130238516,University of Minnesota,University of Minnesota,US,https://ror.org/017zqws13,https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5068237537,Ian M. Howat,middle,https://orcid.org/0000-0002-8072-6260,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I52357470,The Ohio State University,The Ohio State University,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5102675431,Myoung-Jon Noh,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I52357470,The Ohio State University,The Ohio State University,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5109469110,B. Bates,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,National Geospatial-Intelligence Agency,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000

In [51]:
unnested_df['authorships-author-display_name'].isnull().values.any()

False

In [52]:
unnested_df.head(10)

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,index location,primary_location-source-display_name,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I130238516,University of Minnesota,University of Minnesota,US,https://ror.org/017zqws13,https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I2800403580,University of Minnesota System,University of Minnesota,US,https://ror.org/03grvy078,https://openalex.org/I2800403580
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5068237537,Ian M. Howat,middle,https://orcid.org/0000-0002-8072-6260,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I52357470,The Ohio State University,The Ohio State University,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,education,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5102675431,Myoung-Jon Noh,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I52357470,The Ohio State University,The Ohio State University,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5109469110,B. Bates,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,National Geospatial-Intelligence Agency,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000
5,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5108935247,Kenneth Peterman,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,National Geospatial-Intelligence Agency,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000
6,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5098790383,Scott Keesey,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,National Geospatial-Intelligence Agency,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000
7,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,government,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5098790384,Matthew Schlenk,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,National Geospatial-Intelligence Agency,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000
8,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,facility,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5110085007,Judith D. Gardiner,middle,None,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I34077533,Ohio Supercomputer Center,Ohio Supercomputer Center,US,https://ror.org/01apna436,https://openalex.org/I34077533
9,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,facility,"ArcticDEM, Version 3",2018,2018-09-26,en,https://openalex.org/A5040711735,Karen Tomko,middle,https://orcid.org/0000-0002-6542-853X,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,https://openalex.org/subfields/2304,https://openalex.org/fields/23,https://openalex.org/domains/3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,748,None,None,None,None,datacite,Harvard Dataverse,0.0,datacite,Harvard Dataverse,True,green,None,https://openalex.org/I34077533,Ohio Supercomputer Center,Ohio Supercomputer Center,US,https://ror.org/01apna436,https://openalex.org/I34077533

In [53]:
unnested_df.to_csv(str(datetime.datetime.today()).split()[0] +'-UMN-Institutions.csv')