In [150]:
import requests
import pandas as pd
import time
import json

In [151]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Loop through pages
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        record_number = 0
        page += 1
        for record in records:
            record_number += 1
            print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                
                                'index location': record['indexed_in'],
                                
                                'primary_location': record['primary_location']['source']['display_name'],
                                
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'],
                                
                                'authors': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions']
                                })


                                
    
            

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

    
# types/dataset,
parameters = {
    #"filter": f"authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549",  # University of Tasmania
    "per-page": 100,
    #"select": "id,doi,publication_year,title,primary_location,authorships,topics",
}

In [72]:
# API Call to scrape UMN Data
#df = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901', parameters)

In [80]:
# API Call to scrape UMN Data
#MN_df = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters)

In [ ]:
with open('OpenAlexMNData.json', 'w') as outfile:
    json.dump(OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters), outfile)

In [152]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [153]:
pd.set_option("display.max_columns", 55)

In [154]:
df = pd.read_json('OpenAlexMNData.json')
df.head()

,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,[datacite],Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,[datacite],Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,[datacite],Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis..."
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,[datacite],Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,[datacite],Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis..."

In [155]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'primary_location', 'is_oa',
       'oa_status', 'license', 'authors', 'affiliations', 'Institution'],
      dtype='object')

In [156]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis..."
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Ohio State U...,"[{'id': 'https://openalex.org/I52357470', 'dis..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10557', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
2514,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,"[{'id': 'https://openalex.org/T11147', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
2515,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."
2516,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(The Fletcher Sch...,"[{'id': 'https://openalex.org/I121934306', 'di..."
2517,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di..."

In [157]:
# Use function to normalize Authors nested list
authors_df = CleanJSON('authors', df)
authors_df['raw_affiliation_strings'] = authors_df['raw_affiliation_strings'].str[0]
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...
...,...,...,...,...,...,...,...,...
2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...
2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...
2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...
2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...
2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...

In [158]:
df.columns

Index(['id', 'doi', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'primary_location', 'is_oa',
       'oa_status', 'license', 'authors', 'affiliations', 'Institution'],
      dtype='object')

In [159]:
# Create new DataFrame to concat original data from
new_df = df[['id', 'doi', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'primary_location', 'is_oa',
       'oa_status', 'license']].copy()
new_df

,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,"[{'id': 'https://openalex.org/T13067', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,"[{'id': 'https://openalex.org/T14163', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,"[{'id': 'https://openalex.org/T10644', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2513,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10557', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2514,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,"[{'id': 'https://openalex.org/T11147', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2515,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2516,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2517,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa

In [160]:
# concat original data to unnested authors_df
authors_df = pd.concat([authors_df, new_df], axis=1)
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa
2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa

In [161]:
# reset index to concat with author information_df
authors_df = authors_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(authors_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'author_id', 'display_name': 'author_name'})
author_info_df

,author_id,author_name,orcid
0,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...
10563,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,https://openalex.org/A5111425891,Paul Glewwe,None
10566,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,https://openalex.org/A5031469107,Paul Goren,None

In [162]:
# concat author_info_df to author_df
authors_df = pd.concat([authors_df, author_info_df], axis=1).reset_index(drop=True)
authors_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,None

In [163]:
# normalize nested Insituttion column
institution_df = CleanJSON('institutions', authors_df)

# remove list format for lineage
institution_df['lineage'] = institution_df['lineage'].str[0]
institution_df

# rename columns
institution_df = institution_df.rename(columns={'id': 'instiution_id', 'display_name': 'institution_name'})


# remove duplicate indices 
## newest change
institution_df = institution_df[~institution_df.index.duplicated(keep='first')]

In [164]:
def missing_index(df):
    missing_indices = ([i for i in range(0, 10568) if i not in df.index])
    return missing_indices

In [165]:
# fill nan values on missinging indices
institution_df = institution_df.reindex(range(institution_df.index.min(), institution_df.index.max()+1))

In [166]:
institution_df.head(25)

,instiution_id,institution_name,ror,country_code,type,lineage
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
5,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
6,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
7,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
8,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
9,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
10,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,education,https://openalex.org/I188538660
11,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
12,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
13,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
14,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
15,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
16,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
17,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
18,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
19,NaN,NaN,NaN,NaN,NaN,NaN
20,NaN,NaN,NaN,NaN,NaN,NaN
21,NaN,NaN,NaN,NaN,NaN,NaN
22,NaN,NaN,NaN,NaN,NaN,NaN
23,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
24,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697

In [167]:
topics_df = CleanJSON('topics', authors_df)
topics_df = topics_df.rename(columns={'id': 'topic_id', 'display_name': 'topic_name'})
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T13126,Scientific Research and Discoveries,0.6482,"{'id': 'https://openalex.org/subfields/3109', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T13925,Offshore Engineering and Technologies,0.7390,"{'id': 'https://openalex.org/subfields/2212', ...","{'id': 'https://openalex.org/fields/22', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
10566,https://openalex.org/T12338,Digital literacy in education,0.3392,"{'id': 'https://openalex.org/subfields/1710', ...","{'id': 'https://openalex.org/fields/17', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
10566,https://openalex.org/T13895,Educational Leadership and Innovation,0.2918,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T10443,Social Policy and Reform Studies,0.8562,"{'id': 'https://openalex.org/subfields/3320', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T13825,Economic Policies and Impacts,0.7859,"{'id': 'https://openalex.org/subfields/2002', ...","{'id': 'https://openalex.org/fields/20', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
10567,https://openalex.org/T11544,"Gender, Labor, and Family Dynamics",0.7775,"{'id': 'https://openalex.org/subfields/3318', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."

In [168]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

In [169]:
topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [170]:
topics_df.head()

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,0.7555,"{'id': 'https://openalex.org/subfields/2304', ...","{'id': 'https://openalex.org/fields/23', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."

In [171]:
missing_index(topics_df)

[]

In [172]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'subfield_id', 'display_name': 'subfield_name'})
field_df = field_df.rename(columns={'id': 'field_id', 'display_name': 'field_name'})
domain_df = domain_df.rename(columns={'id': 'domain_id', 'display_name': 'domain_name'})

field_df

                             field_id             field_name
0      https://openalex.org/fields/23  Environmental Science
1      https://openalex.org/fields/23  Environmental Science
2      https://openalex.org/fields/23  Environmental Science
3      https://openalex.org/fields/23  Environmental Science
4      https://openalex.org/fields/23  Environmental Science
...                               ...                    ...
10563  https://openalex.org/fields/32             Psychology
10564  https://openalex.org/fields/33        Social Sciences
10565  https://openalex.org/fields/33        Social Sciences
10566  https://openalex.org/fields/33        Social Sciences
10567  https://openalex.org/fields/33        Social Sciences

[10568 rows x 2 columns]

In [173]:
# authors_df = pd.concat([authors_df, author_info_df], axis=1).reset_index(drop=True)

In [174]:
topics_df = topics_df[['topic_id', 'topic_name']]

In [175]:
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...
10563,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [176]:
# normalize nested affiliations column
affilliations_df = CleanJSON('affiliations', authors_df)
affilliations_df['institution_ids'] = affilliations_df['institution_ids'].str[0]
affilliations_df = affilliations_df.rename(columns={'institution_ids': 'afilliation_lineage'})

# remove duplicate indices 
affilliations_df = affilliations_df[~affilliations_df.index.duplicated(keep='first')]
affilliations_df

,raw_affiliation_string,afilliation_lineage
0,(University of Minnesota),https://openalex.org/I130238516
1,(University of Minnesota),https://openalex.org/I130238516
2,(The Ohio State University),https://openalex.org/I52357470
3,(The Ohio State University),https://openalex.org/I52357470
4,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...
10563,(University of Minnesota),https://openalex.org/I130238516
10564,"(The Fletcher School, Tufts University)",https://openalex.org/I121934306
10565,"(Department of Applied Economics, University o...",https://openalex.org/I130238516
10566,(Independent Consultant),NaN
10567,(University of Minnesota),https://openalex.org/I130238516

In [177]:
missing_index(affilliations_df)

[43,
 44,
 45,
 117,
 125,
 127,
 128,
 363,
 364,
 365,
 366,
 367,
 368,
 370,
 371,
 498,
 1154,
 2394,
 2421,
 3457,
 3467,
 3477,
 3702,
 3706,
 3707,
 3708,
 3709,
 3710,
 3711,
 3712,
 3713,
 3714,
 3715,
 3748,
 3749,
 3750,
 3753,
 3755,
 3756,
 3757,
 3836,
 3837,
 3838,
 3841,
 3843,
 3844,
 3845,
 9656,
 9670,
 9674,
 9678,
 9682,
 9686,
 9692,
 9700,
 9712,
 9716,
 9724,
 9728,
 9732,
 9736,
 9747,
 9751,
 9760,
 9764,
 9776,
 9780,
 9784,
 9788,
 9792,
 9796,
 9802,
 9806,
 9810,
 9814,
 9820,
 9824,
 9830,
 9834,
 9840,
 9844]

In [178]:
missing_index(topics_df)

[]

In [179]:
affilliations_df = affilliations_df.reset_index()

In [180]:
affilliations_df = affilliations_df.reindex(range(affilliations_df.index.min(), affilliations_df.index.max()+1))

In [181]:
missing_index(affilliations_df)

[10487,
 10488,
 10489,
 10490,
 10491,
 10492,
 10493,
 10494,
 10495,
 10496,
 10497,
 10498,
 10499,
 10500,
 10501,
 10502,
 10503,
 10504,
 10505,
 10506,
 10507,
 10508,
 10509,
 10510,
 10511,
 10512,
 10513,
 10514,
 10515,
 10516,
 10517,
 10518,
 10519,
 10520,
 10521,
 10522,
 10523,
 10524,
 10525,
 10526,
 10527,
 10528,
 10529,
 10530,
 10531,
 10532,
 10533,
 10534,
 10535,
 10536,
 10537,
 10538,
 10539,
 10540,
 10541,
 10542,
 10543,
 10544,
 10545,
 10546,
 10547,
 10548,
 10549,
 10550,
 10551,
 10552,
 10553,
 10554,
 10555,
 10556,
 10557,
 10558,
 10559,
 10560,
 10561,
 10562,
 10563,
 10564,
 10565,
 10566,
 10567]

In [182]:
# concat insitution_df, affiliations_df, and topics_df
#institution_df = institution_df.reset_index()
#affilliations_df = affilliations_df.reset_index()
merged_list = [institution_df, affilliations_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,instiution_id,institution_name,ror,country_code,type,lineage,index,raw_affiliation_string,afilliation_lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [183]:
unnested_df = authors_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,title,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,(The Ohio State University),[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,(National Geospatial-Intelligence Agency),[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,2515,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,"[{'id': 'https://openalex.org/T13283', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,2516,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",[{'raw_affiliation_string': '(The Fletcher Sch...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,2516,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",[{'raw_affiliation_string': '(Department of Ap...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,None
10566,2516,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,(Independent Consultant),[{'raw_affiliation_string': '(Independent Cons...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,"[{'id': 'https://openalex.org/T13532', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,2517,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,(University of Minnesota),[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,"[{'id': 'https://openalex.org/T10443', 'displa...",en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,None

In [184]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'title', 'publication_year',
       'publication_date', 'topics', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'author_id',
       'author_name', 'orcid'],
      dtype='object')

In [185]:
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'title', 'publication_year',
       'publication_date', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'author_id',
       'author_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,title,publication_year,publication_date,language,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,orcid
0,first,[US],False,Claire Porter,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778
1,middle,[US],False,Paul Morin,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642
2,middle,[US],False,Ian Howat,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260
3,middle,[US],False,Myoung-Jon Noh,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,None
4,middle,[US],False,Brian Bates,(National Geospatial-Intelligence Agency),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,first,[US],True,Yoon-Hee Cha,(University of Minnesota),https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879
10564,first,[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,None
10565,middle,[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,None
10566,last,[],False,Uttam Sharma,(Independent Consultant),https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872
10567,first,[US],True,Paul Goren,(University of Minnesota),https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,None

In [188]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,title,publication_year,publication_date,language,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,orcid,instiution_id,institution_name,ror,country_code,type,lineage,index,raw_affiliation_string,afilliation_lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,first,[US],False,Claire Porter,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,middle,[US],False,Paul Morin,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,middle,[US],False,Ian Howat,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,middle,[US],False,Myoung-Jon Noh,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,None,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,middle,[US],False,Brian Bates,(National Geospatial-Intelligence Agency),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,first,[US],True,Yoon-Hee Cha,(University of Minnesota),https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,first,[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,None,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,middle,[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,last,[],False,Uttam Sharma,(Independent Consultant),https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,first,[US],True,Paul Goren,(University of Minnesota),https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [189]:
# remove rows where authors are NaN
unnested_df = unnested_df.iloc[:10568]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,title,publication_year,publication_date,language,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,orcid,instiution_id,institution_name,ror,country_code,type,lineage,index,raw_affiliation_string,afilliation_lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,first,[US],False,Claire Porter,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
1,middle,[US],False,Paul Morin,(University of Minnesota),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
2,middle,[US],False,Ian Howat,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
3,middle,[US],False,Myoung-Jon Noh,(The Ohio State University),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,None,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
4,middle,[US],False,Brian Bates,(National Geospatial-Intelligence Agency),https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,first,[US],True,Yoon-Hee Cha,(University of Minnesota),https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
10564,first,[US],False,Julie Schaffner,"(The Fletcher School, Tufts University)",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,None,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10565,middle,[US],False,Paul Glewwe,"(Department of Applied Economics, University o...",https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10566,last,[],False,Uttam Sharma,(Independent Consultant),https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,https://orcid.org/0000-0001-5108-8872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
10567,first,[US],True,Paul Goren,(University of Minnesota),https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,None,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences

In [190]:
# check for nan authors
unnested_df['author_name'].isnull().values.any()

False

In [191]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'title', 'publication_year',
       'publication_date', 'language', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'author_id',
       'author_name', 'orcid', 'instiution_id', 'institution_name', 'ror',
       'country_code', 'type', 'lineage', 'index', 'raw_affiliation_string',
       'afilliation_lineage', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name'],
      dtype='object')

In [198]:
unnested_df = unnested_df[['id', 'doi', 'title', 'publication_year',
       'publication_date', 'language', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name', 'retracted', 'index location',
       'primary_location', 'is_oa', 'oa_status', 'license', 'author_id',
       'author_name', 'author_position', 'orcid', 
       'instiution_id', 'institution_name', 'type', 'country_code', 'ror',
        'lineage', 'raw_affiliation_string', 'afilliation_lineage']]
unnested_df

,id,doi,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,author_position,orcid,instiution_id,institution_name,type,country_code,ror,lineage,raw_affiliation_string,afilliation_lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5068237537,I. M. Howat,middle,https://orcid.org/0000-0002-8072-6260,https://openalex.org/I52357470,The Ohio State University,education,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470,(The Ohio State University),https://openalex.org/I52357470
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5102675431,Myoung-Jon Noh,middle,None,https://openalex.org/I52357470,The Ohio State University,education,US,https://ror.org/00rs6vg23,https://openalex.org/I52357470,(The Ohio State University),https://openalex.org/I52357470
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5109469110,B. Bates,middle,None,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,government,US,https://ror.org/02k4pxv54,https://openalex.org/I1319259000,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10563,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
10564,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5069760554,Julie Anderson Schaffner,first,None,https://openalex.org/I121934306,Tufts University,education,US,https://ror.org/05wvpxv85,https://openalex.org/I121934306,NaN,NaN
10565,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
10566,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5059288908,Uttam Sharma,last,https://orcid.org/0000-0001-5108-8872,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10567,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN

In [207]:
# subset to ror ids
ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572') | (unnested_df['ror'] == 'https://ror.org/017zqws13') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') 
                                            | (unnested_df['ror'] == 'https://ror.org/00x6h5n95') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') | (unnested_df['ror'] == 'https://ror.org/047426m28') 
                                            | (unnested_df['ror'] == 'https://ror.org/03arq3225') | (unnested_df['ror'] == 'https://ror.org/04sac7215') | (unnested_df['ror'] == 'https://ror.org/02ttsq026') 
                                            | (unnested_df['ror'] == 'https://ror.org/05bnh6r87') | (unnested_df['ror'] == 'https://ror.org/02smfhw86') | (unnested_df['ror'] == 'https://ror.org/01y2jtd41') 
                                            | (unnested_df['ror'] == 'https://ror.org/00hx57361') | (unnested_df['ror'] == 'https://ror.org/04p491231') | (unnested_df['ror'] == 'https://ror.org/0153tk833')
                                            | (unnested_df['ror'] == 'https://ror.org/00b30xv10') | (unnested_df['ror'] == 'https://ror.org/00py81415') | (unnested_df['ror'] == 'https://ror.org/01yc7t268') 
                                            | (unnested_df['ror'] == 'https://ror.org/05fs6jp91') | (unnested_df['ror'] == 'https://ror.org/043mer456')].reset_index(drop=True)
ror_df

,id,doi,title,publication_year,publication_date,language,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,primary_location,is_oa,oa_status,license,author_id,author_name,author_position,orcid,instiution_id,institution_name,type,country_code,ror,lineage,raw_affiliation_string,afilliation_lineage
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5016996755,Claire Porter,first,https://orcid.org/0009-0005-4979-9778,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
1,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5074382278,Paul Morin,middle,https://orcid.org/0000-0002-4512-0642,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
2,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5018856299,M. J. Willis,middle,https://orcid.org/0000-0001-7872-770X,https://openalex.org/I188538660,University of Colorado Boulder,education,US,https://ror.org/02ttsq026,https://openalex.org/I188538660,(University of Colorado Boulder),https://openalex.org/I188538660
3,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5114168374,Cole Kelleher,middle,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,en,https://openalex.org/T10995,Methane Hydrates and Related Phenomena,https://openalex.org/subfields/2304,Environmental Chemistry,https://openalex.org/fields/23,Environmental Science,https://openalex.org/domains/3,Physical Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111210501,Michael Cloutier,middle,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3013,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,en,https://openalex.org/T10557,Social Media and Politics,https://openalex.org/subfields/3315,Communication,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5038879126,Rocío Titiunik,last,https://orcid.org/0000-0001-5145-3059,https://openalex.org/I20089843,Princeton University,education,US,https://ror.org/00hx57361,https://openalex.org/I20089843,NaN,NaN
3014,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,en,https://openalex.org/T11147,Misinformation and Its Impacts,https://openalex.org/subfields/3312,Sociology and Political Science,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5022408597,Emily K. Vraga,first,https://orcid.org/0000-0002-3016-3869,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
3015,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,en,https://openalex.org/T13283,Mental Health Research Topics,https://openalex.org/subfields/3205,Experimental and Cognitive Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5046355938,Yoon‐Hee Cha,first,https://orcid.org/0000-0003-3804-0879,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
3016,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,en,https://openalex.org/T13532,Education Systems and Policy,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5111425891,Paul Glewwe,middle,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN
3017,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,en,https://openalex.org/T10443,Social Policy and Reform Studies,https://openalex.org/subfields/3320,Political Science and International Relations,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,datacite,Harvard Dataverse,True,gold,other-oa,https://openalex.org/A5031469107,Paul Goren,first,None,https://openalex.org/I130238516,University of Minnesota,education,US,https://ror.org/017zqws13,https://openalex.org/I130238516,NaN,NaN

In [205]:
ror_df.to_csv('CleanedOpenAlexData.csv')

In [201]:
departments = ror_df.groupby('raw_affiliation_string').size().sort_values(ascending=False)
departments.head(25)

raw_affiliation_string
Ceuticare, Inc., Sylvania, Ohio, USA, (TGM and ST)                                                                                                209
Department of Genetics, Cell Biology and Development, University of Minnesota, USA                                                                171
(University of Minnesota)                                                                                                                         144
Department of Biochemistry, Molecular Biology and Biophysics, University of Minnesota, USA                                                        112
Department of Pediatrics, University of Minnesota, USA                                                                                             93
Department of Plant Biology, University of Minnesota, USA                                                                                          93
Department of Veterinary and Biomedical Sciences, University of Minnesota, USA                                                                     48
Department of Laboratory Medicine and Pathology, University of Minnesota, USA                                                                      47
Department of Forest Resources, University of Minnesota Center for Forest Ecology, USA                                                             44
Stem Cell Institute, University of Minnesota, USA                                                                                                  35
Department of Medicine, Masonic Canter Center, University of Minnesota, USA                                                                        35
University of Minnesota                                                                                                                            33
Institute for Therapeutics Discovery & Development, University of Minnesota, USA                                                                   26
Department of Urology, University of Minnesota, USA                                                                                                25
Department of Medicinal Chemistry, University of Minnesota, USA                                                                                    24
Center for Magnetic Resonance Research, University of Minnesota, USA                                                                               24
Department of Aerospace Engineering and Mechanics, University of Minnesota, Minneapolis, Minnesota 55455, USA                                      23
Department of Pediatrics, Division of Blood and Marrow Transplantation, University of Minnesota, USA                                               22
University of Minnesota, Minneapolis 14, Minn., U.S.A.                                                                                             21
Imperial College of Science and Technology, London S.W.7, U.K.                                                                                     20
Department of Otolaryngology  Head & Neck Surgery, University of Minnesota, USA                                                                   19
School of Kinesiology, University of Minnesota, USA                                                                                                18
Laboratory of Cell and Molecular Biology, National Institute of Diabetes and Digestive and Kidney Diseases, National Institutes of Health, USA     17
The Hormel Institute, University of Minnesota, USA                                                                                                 16
School of Mechanical and Materials Engineering, Indian Institute of Technology Mandi, Kamand, 175075 Mandi, India                                  16
dtype: int64

In [ ]:
departments.tail(25)