In [275]:
import requests
import pandas as pd
import time

In [276]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Loop through pages
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        record_number = 0
        page += 1
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'publication_year': record['publication_year'],
                                'publiation_date': record['publication_date'],
                                'URL': record['primary_location']['landing_page_url'],
                                'language': record['language'],
                                'Primary Location': record['primary_location']['source'],
                                #'Host Source': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'type': record['type'],
                                'index location': record['indexed_in'],
                                'Authors': record['authorships'][:],
                                'author ID': record['authorships'][0]['author']['id'],
                                
                                
                                
                                
                                #'author_position': record['authorships'][0]['author_position'],
                                # 'author': record['authorships'][0]['author']['display_name'],
                                # 'Orcid ID': record['authorships'][0]['author']['orcid'],
                                #'Institution id': record['primary_location']['source']['id'],
                               # 'Institution': record['authorships'][0]['institutions'],
                                #'ror': record['authorships'][0]['Institutions']['ror'],
                               # 'linneage': record['authorships']['Institutions']['lineage'],

                                #'type test': record['type'][:],
                                #'Instiution URL Code': url,
                                
                                #'Index Location': record['type']['indexed_in'][0]
                                #"index location": record['type'][0],

                                })

                                #'Institution': record['institutions'][0],
                                
                            
                                #'Institution': record['institutions'][0],

                                #'authorships 3': record['authorships'][1]['institutions']['display_name'],
                                #'authorships 3': record.get("authorships")[0].get('institutions')[1],
                                #'institution 4': record['authorships'][0]['institutions'],
                                #'institution 5': record['authorships'][2][2]
                                
    
            

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

    
# types/dataset,
parameters = {
    #"filter": f"authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549",  # University of Tasmania
    "per-page": 100,
    #"select": "id,doi,publication_year,title,primary_location,authorships,topics",
}

In [277]:
# API Call to scrape UMN Data
MN_df = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters)

Status code: 200 ; Page number:  0
Status code: 200 ; Page number:  1
Status code: 200 ; Page number:  2
Status code: 200 ; Page number:  3
Status code: 200 ; Page number:  4
Status code: 200 ; Page number:  5
Status code: 200 ; Page number:  6
Status code: 200 ; Page number:  7
Status code: 200 ; Page number:  8
Status code: 200 ; Page number:  9
Status code: 200 ; Page number:  10
Status code: 200 ; Page number:  11
Status code: 200 ; Page number:  12
Status code: 200 ; Page number:  13
Status code: 200 ; Page number:  14
Status code: 200 ; Page number:  15
Status code: 200 ; Page number:  16
Status code: 200 ; Page number:  17
Status code: 200 ; Page number:  18
Status code: 200 ; Page number:  19
Status code: 200 ; Page number:  20
Status code: 200 ; Page number:  21
Status code: 200 ; Page number:  22
Status code: 200 ; Page number:  23
Status code: 200 ; Page number:  24
Status code: 200 ; Page number:  25
Status code: 200 ; Page number:  26

In [278]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [279]:
pd.set_option("display.max_columns", 55)

In [280]:
# Pandas Method to normalize json
MN_df =pd.json_normalize(MN_df)
MN_df

,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Authors,author ID,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.issn,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.is_core,Primary Location.host_organization,Primary Location.host_organization_name,Primary Location.host_organization_lineage,Primary Location.host_organization_lineage_names,Primary Location.type
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5016996755,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5016996755,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5068237537,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5016996755,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5068237537,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5072630732,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
2513,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5022408597,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
2514,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5046355938,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
2515,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5069760554,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository
2516,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/A5031469107,https://openalex.org/S4377196806,Harvard Dataverse,None,None,False,False,False,https://openalex.org/I136199984,Harvard University,[https://openalex.org/I136199984],[Harvard University],repository

In [281]:
MN_df.to_csv('OpenAlexDataRaw.csv')

In [282]:
# investigate the columns
MN_df.columns

Index(['id', 'doi', 'title', 'publication_year', 'publiation_date', 'URL',
       'language', 'is_oa', 'oa_status', 'type', 'index location', 'Authors',
       'author ID', 'Primary Location.id', 'Primary Location.display_name',
       'Primary Location.issn_l', 'Primary Location.issn',
       'Primary Location.is_oa', 'Primary Location.is_in_doaj',
       'Primary Location.is_core', 'Primary Location.host_organization',
       'Primary Location.host_organization_name',
       'Primary Location.host_organization_lineage',
       'Primary Location.host_organization_lineage_names',
       'Primary Location.type'],
      dtype='object')

In [283]:
# Remove columns that I don't want
MN_df = MN_df[['id', 'doi', 'title', 'publication_year', 'publiation_date', 'URL',
       'language', 'is_oa', 'oa_status', 'author ID', 'type', 'index location',
       'Authors', 'Primary Location.id', 'Primary Location.display_name',
       'Primary Location.issn_l', 'Primary Location.is_oa', 'Primary Location.is_in_doaj',
       'Primary Location.type']]
MN_df.head(5)

,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,author ID,type,index location,Authors,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5068237537,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5068237537,dataset,[datacite],"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [284]:
# Remove list element from column
MN_df['index location'] = MN_df['index location'].str[0]
MN_df

C:\Users\wieke\AppData\Local\Temp\ipykernel_1868\1049445453.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  MN_df['index location'] = MN_df['index location'].str[0]

,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,author ID,type,index location,Authors,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5068237537,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5016996755,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5068237537,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5072630732,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2513,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5022408597,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2514,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5046355938,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2515,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5069760554,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2516,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,https://openalex.org/A5031469107,dataset,datacite,"[{'author_position': 'first', 'author': {'id':...",https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [285]:
# Use function to normalize Authors nested list
authors_df = CleanJSON('Authors', MN_df)
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,[(National Geospatial-Intelligence Agency)],[{'raw_affiliation_string': '(National Geospat...
...,...,...,...,...,...,...,...,...
2514,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...
2515,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"[(The Fletcher School, Tufts University)]",[{'raw_affiliation_string': '(The Fletcher Sch...
2515,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"[(Department of Applied Economics, University ...",[{'raw_affiliation_string': '(Department of Ap...
2515,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,[(Independent Consultant)],[{'raw_affiliation_string': '(Independent Cons...
2516,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...

In [286]:
# Create new DataFrame to concat original data from
doi_df = MN_df[['id', 'doi', 'title', 'publication_year', 'publiation_date', 'URL',
       'language', 'is_oa', 'oa_status', 'type', 'index location', 'Primary Location.id', 'Primary Location.display_name',
       'Primary Location.issn_l', 'Primary Location.is_oa',
       'Primary Location.is_in_doaj', 'Primary Location.type']].copy()
doi_df

,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
0,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
1,https://openalex.org/W4398279955,https://doi.org/10.7910/dvn/3vdc4w,"ArcticDEM - Mosaics, Version 4.1",2023,2023-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2,https://openalex.org/W4398501648,https://doi.org/10.7910/dvn/ebw8uc,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
3,https://openalex.org/W4398731861,https://doi.org/10.7910/dvn/c98dvs,"ArcticDEM - Strips, Version 4.1",2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
4,https://openalex.org/W4398943877,https://doi.org/10.7910/dvn/x7ndny,The Reference Elevation Model of Antarctica - ...,2022,2022-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2512,https://openalex.org/W4398340829,https://doi.org/10.7910/dvn/awsqtw,Replication Data for: Parties as Disciplinaria...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2513,https://openalex.org/W4398481394,https://doi.org/10.7910/dvn/9y0ssl,Supplemental Appendices for Correcting What’s ...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2514,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2515,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2516,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [287]:
MN_df.columns

Index(['id', 'doi', 'title', 'publication_year', 'publiation_date', 'URL',
       'language', 'is_oa', 'oa_status', 'author ID', 'type', 'index location',
       'Authors', 'Primary Location.id', 'Primary Location.display_name',
       'Primary Location.issn_l', 'Primary Location.is_oa',
       'Primary Location.is_in_doaj', 'Primary Location.type'],
      dtype='object')

In [ ]:
# concat original data to unnested authors_df
authors_df = pd.concat([authors_df, doi_df], axis=1)
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,[(National Geospatial-Intelligence Agency)],[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2514,first,"{'id': 'https://openalex.org/A5046355938', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Yoon-Hee Cha,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398493566,https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2515,first,"{'id': 'https://openalex.org/A5069760554', 'di...","[{'id': 'https://openalex.org/I121934306', 'di...",[US],False,Julie Schaffner,"[(The Fletcher School, Tufts University)]",[{'raw_affiliation_string': '(The Fletcher Sch...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2515,middle,"{'id': 'https://openalex.org/A5111425891', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Glewwe,"[(Department of Applied Economics, University ...",[{'raw_affiliation_string': '(Department of Ap...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2515,last,"{'id': 'https://openalex.org/A5059288908', 'di...",[],[],False,Uttam Sharma,[(Independent Consultant)],[{'raw_affiliation_string': '(Independent Cons...,https://openalex.org/W4398712537,https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2516,first,"{'id': 'https://openalex.org/A5031469107', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],True,Paul Goren,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398740109,https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [289]:
authors_df = authors_df.rename(columns={'raw_author_name': 'author_name'})

In [290]:
# reset index to concat with author information_df
authors_df = authors_df.reset_index()

In [291]:
# normalize author column
author_info_df= pd.json_normalize(authors_df['author'])
author_info_df = author_info_df[['id', 'orcid']]
author_info_df = author_info_df.rename(columns={'id': 'author_id'})
author_info_df

                              author_id                                  orcid
0      https://openalex.org/A5016996755  https://orcid.org/0009-0005-4979-9778
1      https://openalex.org/A5074382278  https://orcid.org/0000-0002-4512-0642
2      https://openalex.org/A5068237537  https://orcid.org/0000-0002-8072-6260
3      https://openalex.org/A5102675431                                   None
4      https://openalex.org/A5109469110                                   None
...                                 ...                                    ...
10550  https://openalex.org/A5046355938  https://orcid.org/0000-0003-3804-0879
10551  https://openalex.org/A5069760554                                   None
10552  https://openalex.org/A5111425891                                   None
10553  https://openalex.org/A5059288908  https://orcid.org/0000-0001-5108-8872
10554  https://openalex.org/A5031469107                                   None

[10555 rows x 2 columns]

In [292]:
# concat author_info_df to author_df
authors_df = pd.concat([authors_df, author_info_df], axis=1).reset_index(drop=True)
authors_df.head()

,index,author_position,author,institutions,countries,is_corresponding,author_name,raw_affiliation_strings,affiliations,id,doi,title,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,author_id,orcid
0,0,first,"{'id': 'https://openalex.org/A5016996755', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Claire Porter,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778
1,0,middle,"{'id': 'https://openalex.org/A5074382278', 'di...","[{'id': 'https://openalex.org/I130238516', 'di...",[US],False,Paul Morin,[(University of Minnesota)],[{'raw_affiliation_string': '(University of Mi...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642
2,0,middle,"{'id': 'https://openalex.org/A5068237537', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Ian Howat,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/A5068237537,https://orcid.org/0000-0002-8072-6260
3,0,middle,"{'id': 'https://openalex.org/A5102675431', 'di...","[{'id': 'https://openalex.org/I52357470', 'dis...",[US],False,Myoung-Jon Noh,[(The Ohio State University)],[{'raw_affiliation_string': '(The Ohio State U...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/A5102675431,None
4,0,middle,"{'id': 'https://openalex.org/A5109469110', 'di...","[{'id': 'https://openalex.org/I1319259000', 'd...",[US],False,Brian Bates,[(National Geospatial-Intelligence Agency)],[{'raw_affiliation_string': '(National Geospat...,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/A5109469110,None

In [293]:
# normalize nested Insituttion column
institution_df = CleanJSON('institutions', authors_df)

# remove list format for lineage
institution_df['lineage'] = institution_df['lineage'].str[0]
institution_df

,id,display_name,ror,country_code,type,lineage
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
...,...,...,...,...,...,...
10549,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
10550,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
10551,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306
10552,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
10554,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516

In [342]:
institution_df.head(50)

,level_0,index,institution_id,institution_name,ror,country_code,instiution_type,lineage
0,0,0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
1,1,1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
2,2,2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
3,3,3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
4,4,4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
5,5,5,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
6,6,6,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
7,7,7,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
8,8,8,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
9,9,9,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
10,10,10,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,education,https://openalex.org/I188538660
11,11,11,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
12,12,12,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
13,13,13,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
14,14,14,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
15,15,15,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
16,16,16,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
17,17,17,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
18,18,18,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
19,19,23,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
20,20,24,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
21,21,25,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
22,22,26,https://openalex.org/I1292842697,Environmental Systems Research Institute (Unit...,https://ror.org/0428exr50,US,company,https://openalex.org/I1292842697
23,23,27,https://openalex.org/I4210139463,The White House,https://ror.org/04ars5103,US,government,https://openalex.org/I4210139463
24,24,27,https://openalex.org/I4210116747,Office of Science and Technology Policy,https://ror.org/02bjkqr85,US,government,https://openalex.org/I1308683654
25,25,28,https://openalex.org/I4210154540,Asiaq Greenland Survey,https://ror.org/05pzd7w96,GL,government,https://openalex.org/I4210154540
26,26,29,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
27,27,30,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
28,28,31,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
29,29,32,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
30,30,33,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
31,31,34,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
32,32,35,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
33,33,36,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
34,34,37,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
35,35,38,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
36,36,39,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
37,37,40,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
38,38,41,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
39,39,42,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
40,40,46,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
41,41,47,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
42,42,48,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
43,43,49,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
44,44,50,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
45,45,51,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
46,46,52,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
47,47,53,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
48,48,54,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,facility,https://openalex.org/I34077533
49,49,55,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470

In [308]:
institution_df = institution_df.rename(columns={'id':'institution_id', 'display_name': 'institution_name', 'type': 'instiution_type'})
authors_df = authors_df.rename(columns={'display_name': 'author_name','id': 'record_id'})
institution_df.head()

,institution_id,institution_name,ror,country_code,instiution_type,lineage
0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516
2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470
4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000

In [325]:
# normalize nested affiliations column
affilliations_df = CleanJSON('affiliations', authors_df)
affilliations_df['institution_ids'] = affilliations_df['institution_ids'].str[0]
affilliations_df = affilliations_df.rename(columns={'institution_ids': 'afilliation_lineage'})
affilliations_df

,raw_affiliation_string,afilliation_lineage
0,(University of Minnesota),https://openalex.org/I130238516
1,(University of Minnesota),https://openalex.org/I130238516
2,(The Ohio State University),https://openalex.org/I52357470
3,(The Ohio State University),https://openalex.org/I52357470
4,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...
10550,(University of Minnesota),https://openalex.org/I130238516
10551,"(The Fletcher School, Tufts University)",https://openalex.org/I121934306
10552,"(Department of Applied Economics, University o...",https://openalex.org/I130238516
10553,(Independent Consultant),NaN
10554,(University of Minnesota),https://openalex.org/I130238516

In [327]:
# concat insitution_df and affiliations_df
institution_df = institution_df.reset_index()
affilliations_df = affilliations_df.reset_index()
institutions_list = [institution_df, affilliations_df ]
institutions_df = pd.concat(institutions_list, axis=1)
institutions_df

,level_0,index,institution_id,institution_name,ror,country_code,instiution_type,lineage,index,raw_affiliation_string,afilliation_lineage
0,0,0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516
1,1,1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516
2,2,2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470
3,3,3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470
4,4,4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...
10888,10888,10549,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10889,10889,10550,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10890,10890,10551,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306,NaN,NaN,NaN
10891,10891,10552,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10892,10892,10554,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN

In [328]:
#authors_df = authors_df[['index', 'author_name', 'author_id', 'orcid', 'author_position', 'is_corresponding', 'institutions', 'countries', 'doi']]
authors_df = authors_df[['author_name', 'author_id', 'orcid', 'author_position', 'is_corresponding', 'countries', 'doi', 'title', 'record_id', 'publication_year', 'publiation_date', 'URL',
       'language', 'is_oa', 'oa_status', 'type', 'index location', 'Primary Location.id', 'Primary Location.display_name',
       'Primary Location.issn_l', 'Primary Location.is_oa', 'Primary Location.is_in_doaj',
       'Primary Location.type']]
#authors_df = authors_df.loc[:,~authors_df.columns.duplicated()].copy()

authors_df

,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
1,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
2,Ian Howat,https://openalex.org/A5068237537,https://orcid.org/0000-0002-8072-6260,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
3,Myoung-Jon Noh,https://openalex.org/A5102675431,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
4,Brian Bates,https://openalex.org/A5109469110,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10550,Yoon-Hee Cha,https://openalex.org/A5046355938,https://orcid.org/0000-0003-3804-0879,first,True,[US],https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,https://openalex.org/W4398493566,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10551,Julie Schaffner,https://openalex.org/A5069760554,None,first,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10552,Paul Glewwe,https://openalex.org/A5111425891,None,middle,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10553,Uttam Sharma,https://openalex.org/A5059288908,https://orcid.org/0000-0001-5108-8872,last,False,[],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10554,Paul Goren,https://openalex.org/A5031469107,None,first,True,[US],https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,https://openalex.org/W4398740109,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [ ]:
# concat institution_df to authors_df
authors_df = authors_df.reset_index()
institutions_df = institutions_df.reset_index()
author_inst_df = [authors_df, institutions_df ]
final_author_inst_df = pd.concat(author_inst_df, axis=1)
final_author_inst_df

,index,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,level_0,index,institution_id,institution_name,ror,country_code,instiution_type,lineage,index,raw_affiliation_string,afilliation_lineage
0,0.0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,0,0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516
1,1.0,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,1,1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516
2,2.0,Ian Howat,https://openalex.org/A5068237537,https://orcid.org/0000-0002-8072-6260,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,2,2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470
3,3.0,Myoung-Jon Noh,https://openalex.org/A5102675431,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,3,3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470
4,4.0,Brian Bates,https://openalex.org/A5109469110,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,4,4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10888,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10888,10549,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10889,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10889,10550,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10890,10551,https://openalex.org/I121934306,Tufts University,https://ror.org/05wvpxv85,US,education,https://openalex.org/I121934306,NaN,NaN,NaN
10891,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10891,10552,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN
10892,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10892,10554,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,NaN,NaN,NaN

In [331]:
# remove rows where authors are NaN
final_author_inst_df = final_author_inst_df.iloc[:10555]
final_author_inst_df

,index,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,level_0,index,institution_id,institution_name,ror,country_code,instiution_type,lineage,index,raw_affiliation_string,afilliation_lineage
0,0.0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,0,0,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,0.0,(University of Minnesota),https://openalex.org/I130238516
1,1.0,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,1,1,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,1.0,(University of Minnesota),https://openalex.org/I130238516
2,2.0,Ian Howat,https://openalex.org/A5068237537,https://orcid.org/0000-0002-8072-6260,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,2,2,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,2.0,(The Ohio State University),https://openalex.org/I52357470
3,3.0,Myoung-Jon Noh,https://openalex.org/A5102675431,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,3,3,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,3.0,(The Ohio State University),https://openalex.org/I52357470
4,4.0,Brian Bates,https://openalex.org/A5109469110,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,4,4,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,4.0,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10550,10550.0,Yoon-Hee Cha,https://openalex.org/A5046355938,https://orcid.org/0000-0003-3804-0879,first,True,[US],https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,https://openalex.org/W4398493566,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,10550,10252,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,10453.0,"DESY, Platanenallee 6, 15738 Zeuthen, Germany",NaN
10551,10551.0,Julie Schaffner,https://openalex.org/A5069760554,None,first,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,10551,10253,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,10454.0,"Physics Department, McGill University, Montrea...",https://openalex.org/I5023651
10552,10552.0,Paul Glewwe,https://openalex.org/A5111425891,None,middle,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,10552,10254,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,10455.0,"Department of Physics and Astronomy, Universit...",https://openalex.org/I161318765
10553,10553.0,Uttam Sharma,https://openalex.org/A5059288908,https://orcid.org/0000-0001-5108-8872,last,False,[],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,10553,10255,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,10456.0,"Department of Physics and Astronomy, Universit...",https://openalex.org/I126307644
10554,10554.0,Paul Goren,https://openalex.org/A5031469107,None,first,True,[US],https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,https://openalex.org/W4398740109,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,10554,10256,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,10457.0,"Institute of Physics and Astronomy, University...",https://openalex.org/I176453806

In [332]:
# check for nan authors
final_author_inst_df['author_name'].isnull().values.any()

False

In [333]:
final_author_inst_df = final_author_inst_df[['author_name', 'author_id', 'orcid', 'author_position',
       'is_corresponding', 'countries', 'doi', 'title', 'record_id', 'publication_year',
       'publiation_date', 'URL', 'language', 'is_oa', 'oa_status', 'type',
       'index location', 'Primary Location.id',
       'Primary Location.display_name', 'Primary Location.issn_l',
       'Primary Location.is_oa', 'Primary Location.is_in_doaj',
       'Primary Location.type',  'institution_id',
       'institution_name', 'ror', 'country_code', 'instiution_type', 'lineage', 'raw_affiliation_string', 'afilliation_lineage']]
# = final_author_inst_df.loc[:,~final_author_inst_df.columns.duplicated()].copy()
final_author_inst_df

,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,institution_id,institution_name,ror,country_code,instiution_type,lineage,raw_affiliation_string,afilliation_lineage
0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
1,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
2,Ian Howat,https://openalex.org/A5068237537,https://orcid.org/0000-0002-8072-6260,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,(The Ohio State University),https://openalex.org/I52357470
3,Myoung-Jon Noh,https://openalex.org/A5102675431,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,education,https://openalex.org/I52357470,(The Ohio State University),https://openalex.org/I52357470
4,Brian Bates,https://openalex.org/A5109469110,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000,(National Geospatial-Intelligence Agency),https://openalex.org/I1319259000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10550,Yoon-Hee Cha,https://openalex.org/A5046355938,https://orcid.org/0000-0003-3804-0879,first,True,[US],https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,https://openalex.org/W4398493566,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,"DESY, Platanenallee 6, 15738 Zeuthen, Germany",NaN
10551,Julie Schaffner,https://openalex.org/A5069760554,None,first,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,"Physics Department, McGill University, Montrea...",https://openalex.org/I5023651
10552,Paul Glewwe,https://openalex.org/A5111425891,None,middle,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,"Department of Physics and Astronomy, Universit...",https://openalex.org/I161318765
10553,Uttam Sharma,https://openalex.org/A5059288908,https://orcid.org/0000-0001-5108-8872,last,False,[],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,"Department of Physics and Astronomy, Universit...",https://openalex.org/I126307644
10554,Paul Goren,https://openalex.org/A5031469107,None,first,True,[US],https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,https://openalex.org/W4398740109,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I180670191,"University of California, San Francisco",https://ror.org/043mz5j54,US,education,https://openalex.org/I180670191,"Institute of Physics and Astronomy, University...",https://openalex.org/I176453806

In [334]:
# set author ror id to institutions
ror_df = final_author_inst_df[final_author_inst_df['ror'] == 'https://ror.org/017zqws13']
ror_df

,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,institution_id,institution_name,ror,country_code,instiution_type,lineage,raw_affiliation_string,afilliation_lineage
0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
1,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
11,Cole Kelleher,https://openalex.org/A5114168374,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
12,Michael Cloutier,https://openalex.org/A5111210501,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
13,Eric Husby,https://openalex.org/A5098790376,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10490,J.L. Christiansen,https://openalex.org/A5075785559,https://orcid.org/0000-0002-8035-4778,middle,False,[US],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,"Genomics and Health Group, Department of Bioch...",https://openalex.org/I158438070
10505,P. Kaaret,https://openalex.org/A5076711454,https://orcid.org/0000-0002-3638-0637,middle,False,[US],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,Department of Electrical Engineering and Infor...,https://openalex.org/I117963379
10535,A. Sulaiman,https://openalex.org/A5049276421,https://orcid.org/0000-0002-0971-5016,middle,False,[US],https://doi.org/10.5281/zenodo.5663848,Analysis of Whistler-Mode and Z-Mode Emission ...,https://openalex.org/W4394037563,2021.0,2021-10-09,https://zenodo.org/record/5663848,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,"Department of Physics, California State Univer...",https://openalex.org/I184813773
10543,Jared Mullenbach,https://openalex.org/A5079704419,None,middle,False,[US],https://doi.org/10.5281/zenodo.5721568,Data for Roles of Granularity and Timescales i...,https://openalex.org/W4394049207,2021.0,2021-11-23,https://zenodo.org/record/5721568,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,"Department of Physics and Astronomy, Universit...",https://openalex.org/I126307644
10553,Uttam Sharma,https://openalex.org/A5059288908,https://orcid.org/0000-0001-5108-8872,last,False,[],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021.0,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,"Department of Physics and Astronomy, Universit...",https://openalex.org/I126307644

In [336]:
authors_df.tail(5)

,index,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type
10550,10550,Yoon-Hee Cha,https://openalex.org/A5046355938,https://orcid.org/0000-0003-3804-0879,first,True,[US],https://doi.org/10.7910/dvn/fiteyy,tACS_MdDS_Symptom Response_Onsite,https://openalex.org/W4398493566,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10551,10551,Julie Schaffner,https://openalex.org/A5069760554,None,first,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10552,10552,Paul Glewwe,https://openalex.org/A5111425891,None,middle,False,[US],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10553,10553,Uttam Sharma,https://openalex.org/A5059288908,https://orcid.org/0000-0001-5108-8872,last,False,[],https://doi.org/10.7910/dvn/8v9i67,Evaluation of secondary school teacher trainin...,https://openalex.org/W4398712537,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository
10554,10554,Paul Goren,https://openalex.org/A5031469107,None,first,True,[US],https://doi.org/10.7910/dvn/miova9,Replication Data for: Pliable Prejudice: The C...,https://openalex.org/W4398740109,2021,2021-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository

In [337]:
afil_lineage_df = final_author_inst_df[final_author_inst_df['afilliation_lineage'] == 'https://openalex.org/I130238516']
afil_lineage_df

,author_name,author_id,orcid,author_position,is_corresponding,countries,doi,title,record_id,publication_year,publiation_date,URL,language,is_oa,oa_status,type,index location,Primary Location.id,Primary Location.display_name,Primary Location.issn_l,Primary Location.is_oa,Primary Location.is_in_doaj,Primary Location.type,institution_id,institution_name,ror,country_code,instiution_type,lineage,raw_affiliation_string,afilliation_lineage
0,Claire Porter,https://openalex.org/A5016996755,https://orcid.org/0009-0005-4979-9778,first,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
1,Paul Morin,https://openalex.org/A5074382278,https://orcid.org/0000-0002-4512-0642,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
11,Cole Kelleher,https://openalex.org/A5114168374,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
12,Michael Cloutier,https://openalex.org/A5111210501,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
13,Eric Husby,https://openalex.org/A5098790376,None,middle,False,[US],https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",https://openalex.org/W4398549858,2018.0,2018-01-01,https://dataverse.harvard.edu/citation?persist...,en,True,gold,dataset,datacite,https://openalex.org/S4377196806,Harvard Dataverse,None,False,False,repository,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,education,https://openalex.org/I130238516,(University of Minnesota),https://openalex.org/I130238516
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10496,L. Fortson,https://openalex.org/A5033082144,https://orcid.org/0000-0002-1067-8558,middle,False,[US],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I98540497,Barnard College,https://ror.org/04rt94r53,US,education,https://openalex.org/I98540497,"College of Biological Sciences, Univ. of Minne...",https://openalex.org/I130238516
10501,O. Hervet,https://openalex.org/A5047756698,https://orcid.org/0000-0003-3878-1677,middle,False,[US],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I100930933,University College Dublin,https://ror.org/05m7pjf47,IE,education,https://openalex.org/I100930933,"University of Minnesota, University of Bergen",https://openalex.org/I130238516
10511,R. Mukherjee,https://openalex.org/A5016443752,https://orcid.org/0000-0002-3223-0754,middle,False,[US],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I78577930,Columbia University,https://ror.org/00hj8s172,US,education,https://openalex.org/I78577930,"Department of Physics, University of Minnesota...",https://openalex.org/I130238516
10518,J. Quinn,https://openalex.org/A5056157422,https://orcid.org/0000-0002-4855-2694,middle,False,[IE],https://doi.org/10.5281/zenodo.4723220,VTSCat: The VERITAS Catalog of Gamma-Ray Obser...,https://openalex.org/W4394027132,2021.0,2021-04-27,https://zenodo.org/record/4723220,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I98540497,Barnard College,https://ror.org/04rt94r53,US,education,https://openalex.org/I98540497,"University of Minnesota, Institute on the Envi...",https://openalex.org/I130238516
10534,S. S. Elliott,https://openalex.org/A5007892891,https://orcid.org/0000-0001-8661-7252,middle,False,[US],https://doi.org/10.5281/zenodo.5663848,Analysis of Whistler-Mode and Z-Mode Emission ...,https://openalex.org/W4394037563,2021.0,2021-10-09,https://zenodo.org/record/5663848,en,True,gold,dataset,datacite,https://openalex.org/S4306400562,Zenodo (CERN European Organization for Nuclear...,None,True,False,repository,https://openalex.org/I139787848,Capital University,https://ror.org/00jy9e726,US,education,https://openalex.org/I139787848,"School of Physics and Astronomy, University of...",https://openalex.org/I130238516

In [339]:
departments = ror_df.groupby('raw_affiliation_string').size().sort_values(ascending=False)
departments.head(25)

raw_affiliation_string
(University of Minnesota)                                                                                                           162
Department of Genetics, Cell Biology and Development, University of Minnesota, USA                                                  125
(US Census Bureau, Center for Economic Studies)                                                                                      93
Department of Biochemistry, Molecular Biology and Biophysics, University of Minnesota, USA                                           91
(Duke University)                                                                                                                    90
(University of Minnesota, Twin Cities and NBER)                                                                                      90
Department of Pediatrics, University of Minnesota, USA                                                                               77
Department of Plant Biology, University of Minnesota, USA                                                                            68
Department of Pharmacology, University of Toledo, Toledo, Ohio, USA, (ST)                                                            44
Department of Pharmacochemistry, Vrije University, Amsterdam, Netherlands (now Emeritus Section Molecular Toxicology), (TGM)         44
Drug Metabolism, Daiichi Pharm. Corp., Ltd., Chuo, Tokyo, Japan (now retired), (TGM)                                                 44
Department of Clinical Pharmacology, Flinders University, Adelaide, Australia (now Emeritus), (TGM)                                  43
Center for Drug Discovery, University of Florida, Belle Glade, FL, USA (now Emeritus Grad Res Prof/CEO Bodor Labs), (TGM)            43
Department of Medicinal and Biological Chemistry, University of Toledo, Toledo, Ohio, USA, (ST)                                      40
Division of Toxicology, University Arkansas for Medical Sciences, Little Rock, Arkansas, USA (now Emeritus Dist Prof), (TGM)         40
Department of Medicinal Chemistry, University of Minnesota, Minneapolis, Minnesota, USA (now same), (TGM)                            40
Center for Drug Design and Development, University of Toledo, Toledo, Ohio, USA                                                      40
Huntingdon Life Sciences, Huntingdon, UK (now retired), (TGM)                                                                        39
Department of Laboratory Medicine and Pathology, University of Minnesota, USA                                                        38
Department of Pharmacokinetics and Drug Metabolism, Laboratories Dr. Esteve, S.A., Barcelona, Spain (now Head Early ADME), (TGM)     37
Department of Forest Resources, University of Minnesota Center for Forest Ecology, USA                                               34
Stem Cell Institute, University of Minnesota, USA                                                                                    33
Department of Veterinary and Biomedical Sciences, University of Minnesota, USA                                                       33
Department of Urology, University of Minnesota, USA                                                                                  26
Eli Lilly, Inc., Indianapolis, Indiana, USA (now retired), (TGM)                                                                     25
dtype: int64

In [340]:
departments.tail(25)

raw_affiliation_string
Department of Environmental Science, Shinshu University                                                                                                                                                                          1
Department of Environmental Science and Geology, Wayne State University                                                                                                                                                          1
Department of Ecology, Evolution, and Behavior, University of Minnesota Twin Cities, USA                                                                                                                                         1
Department of Ecology, Evolution and Behavior, University of Minnesota, St Paul, Minnesota 55108                                                                                                                                 1
Department of Ecology, Evolution & Behavior, University of Minnesota                                                                                                                                                             1
Department of Earth and Environmental Sciences, University of Minnesota, Twin Cities, Minnesota, United States                                                                                                                   1
Department of Laboratory Medicine and Pathology Center for Immunology, University of Minnesota, USA                                                                                                                              1
Department of Mechanical Engineering and the BioTechnology Institute at the University of Minnesota in Minneapolis, Minnesota.                                                                                                   1
Department of Mechanical Engineering, University of Minnesota Twin Cities, Minneapolis, Minnesota 55455, USA                                                                                                                     1
 professor of education at the University of Minnesota;                                                                                                                                                                          1
Department of Physics, Massachusetts Institute of Technology                                                                                                                                                                     1
Department of Physics, Deshbandhu College, University of Delhi                                                                                                                                                                   1
Department of Physics, American University of Sharjah                                                                                                                                                                            1
Department of Physics and Astronomy, University of Victoria, Victoria, BC, V8W 2Y2, Canada; Joint Institute for Nuclear Astrophysics – Center for the Evolution of the Elements, USA                                             1
Department of Physics and Astronomy, Haverford College, 370 Lancaster Avenue, Haverford, PA, 19041, USA.                                                                                                                         1
Department of Physics and Astronomy, Georgia State University, Atlanta GA 30303, USA                                                                                                                                             1
Department of Pediatrics, University of Minnesota                                                                                                                                                                                1
Department of Medicine, Masonic Canter Center, University of Minnesota, United States                                                                                                                                            1
Department of Otolaryngology, University of Minnesota, Minneapolis, Minnesota 55455                                                                                                                                              1
Department of Otolaryngology, Head and Neck Surgery, University of Minnesota, USA                                                                                                                                                1
Department of Neuroscience, University of Minnesota, USA                                                                                                                                                                         1
Department of Molecular & Cell Biology, University of California, Berkeley, USA                                                                                                                                                  1
Department of Microbiology, Immunology, and Cancer Biology, University of Minnesota, USA                                                                                                                                         1
Department of Medicine, University of California San Francisco, San Francisco, California, USA; Department of Bioengineering and Therapeutic Sciences, University of California San Francisco, San Francisco, California, USA    1
Zhejiang University                                                                                                                                                                                                              1
dtype: int64

In [ ]:
final_author_inst_df.to_csv('OpenAlexMNData.csv')

In [ ]:
# set ror ids for all institutions
final_author_inst_df = final_author_inst_df[(final_author_inst_df['ror'] == 'https://ror.org/017zqws13') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295')
                                            | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295')
                                            | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295')
                                            | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295')
                                            | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295') | (final_author_inst_df['ror'] == 'https://ror.org/i205783295')]
final_author_inst_df

In [ ]:
# graveyard code beyond

In [ ]:
test.loc[~test.index.get_level_values('display_name').duplicated(keep='last')]

In [ ]:
test.loc[test.index[1]]

In [ ]:
test.loc[test.index.levels[0][1]]

In [ ]:
MN_df = pd.concat([pd.DataFrame(x) for x in MN_df2['affiliations']], keys=MN_df2.index).reset_index(level=1,drop=True)
MN_df

In [ ]:
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [ ]:
def WriteReadCSV(filename, URL):
    write_df = pd.DataFrame(OpenAlexAPI(URL, parameters))
    write_df.to_csv(filename)
    
    read_df = pd.read_csv(filename, sep=',',on_bad_lines='skip', index_col=False, dtype='unicode')
    read_df = read_df.drop(columns=['Unnamed: 0'])
    
    return read_df

In [ ]:
df = WriteReadCSV('OpenAlexData.csv', 'https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901')