In [4]:
import pandas as pd
import matplotlib.pyplot as plt

In [5]:
df = pd.read_csv('2026-04-22-UMN-Source.csv', index_col=0)

In [6]:
pd.set_option("display.max_columns", 55)

In [7]:
df.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
def Matching_columns(df, col1, col2):
    match = df[col1].equals(df[col2])
    return match

In [9]:
# primary topic
Matching_columns(df, 'primary_topic-display_name', 'topics-display_name')

True

In [10]:
# subfield
Matching_columns(df, 'primary_topic-subfield', 'topics-subfield-id')

True

In [11]:
# field
Matching_columns(df, 'primary_topic-field', 'topics-field-id')

True

In [12]:
# domain
Matching_columns(df, 'primary_topic-domain', 'topics-domain-id')

True

In [13]:
len(df['topics-display_name'])

2459

In [14]:
df['ror'].isna().sum(), df['orcid'].isna().sum()

(2177, 872)

In [15]:
(df['ror'].isna() & df['orcid'].isna()).sum()

767

In [16]:
df['ror'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['ror'], ascending=False).reset_index(drop=True)

    publication_year  ror
0               2026   88
1               2025   65
2               2018   25
3               2019   20
4               2020   17
5               2021   15
6               2022   12
7               2016   10
8               2017    8
9               2014    5
10              2015    5
11              2006    3
12              1998    2
13              2003    2
14              2011    2
15              2023    1
16              2005    1
17              2010    1
18              1990    0
19              1971    0
20              1973    0
21              1972    0
22              1966    0
23              1970    0
24              1969    0
25              1979    0
26              2024    0
27              1964    0
28              1975    0
29              2012    0
30              1983    0
31              2013    0
32              1993    0
33              2009    0
34              2008    0
35              2007    0
36              1959    0
37              2004    0
38              2002    0
39              2001    0
40              1912    0

In [17]:
topics_display_name_ror_perc = df['ror'].count()
print('the # of ROR IDs assigned to DOIs is:', topics_display_name_ror_perc), print('the % of ROR IDs assigned to DOIs is:', round(topics_display_name_ror_perc / len(df) * 100, 3),'%')

the # of ROR IDs assigned to DOIs is: 282
the % of ROR IDs assigned to DOIs is: 11.468 %

(None, None)

In [18]:
topics_display_name_ror = df['ror'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_display_name_ror['ror %'] = round(topics_display_name_ror['ror'] / sum(topics_display_name_ror['ror']) * 100, 4)
topics_display_name_ror.head(15).reset_index(drop=True)

                           topics-display_name  ror   ror %
0               Smoking Behavior and Cessation  102  5.0271
1   Nanopore and Nanochannel Transport Studies   71  3.4993
2          Fish Ecology and Management Studies   39  1.9221
3            Rangeland and Wildlife Management   36  1.7743
4               DNA and Nucleic Acid Chemistry   35  1.7250
5           3D Printing in Biomedical Research   34  1.6757
6      Species Distribution and Climate Change   33  1.6264
7                Forest ecology and management   33  1.6264
8      Wheat and Barley Genetics and Pathology   31  1.5278
9              Archaeology and Natural History   26  1.2814
10   Aquatic Invertebrate Ecology and Behavior   24  1.1828
11       Remote Sensing and LiDAR Applications   24  1.1828
12                        Data Analysis with R   23  1.1336
13  Genetic and phenotypic traits in livestock   21  1.0350
14  Groundwater flow and contamination studies   19  0.9364

In [19]:
df['orcid'].notna().groupby(df['publication_year']).sum().reset_index().sort_values(by=['orcid'], ascending=False).reset_index(drop=True)

    publication_year  orcid
0               2018    235
1               2017    174
2               2019    159
3               2020    152
4               2016    135
5               2015    126
6               2021    117
7               2014    105
8               2013    102
9               2025     53
10              2026     40
11              2010     40
12              2012     35
13              2009     19
14              2022     14
15              2006     14
16              1993     10
17              1983      9
18              2007      8
19              1998      5
20              2011      5
21              1964      4
22              2008      4
23              2001      4
24              2005      3
25              1975      3
26              1990      2
27              1979      2
28              1966      1
29              2024      1
30              2023      1
31              2002      1
32              2003      1
33              1959      1
34              2004      1
35              1912      1
36              1972      0
37              1971      0
38              1970      0
39              1969      0
40              1973      0

In [20]:
topics_display_name_orcid_perc = df['orcid'].count()
print('the # of ORCID IDs assigned to DOIs is:', topics_display_name_orcid_perc), print('the % of ORCID IDs assigned to DOIs is:', round(topics_display_name_orcid_perc / len(df) * 100, 3),'%')

the # of ORCID IDs assigned to DOIs is: 1587
the % of ORCID IDs assigned to DOIs is: 64.538 %

(None, None)

In [21]:
topics_display_name_orcid = df['orcid'].isna().groupby(df['topics-display_name']).sum().reset_index().sort_values(by=['orcid'], ascending=False)
topics_display_name_orcid['orcid %'] = round(topics_display_name_orcid['orcid'] / sum(topics_display_name_orcid['orcid']) * 100, 4)
topics_display_name_orcid.head(15).reset_index(drop=True)

                           topics-display_name  orcid  orcid %
0               Smoking Behavior and Cessation    102  15.3614
1              Archaeology and Natural History     24   3.6145
2   Nanopore and Nanochannel Transport Studies     17   2.5602
3          Fish Ecology and Management Studies     14   2.1084
4        Remote Sensing and LiDAR Applications     14   2.1084
5   Genetic and phenotypic traits in livestock     13   1.9578
6   Groundwater flow and contamination studies     11   1.6566
7            Solar Radiation and Photovoltaics     11   1.6566
8            Rangeland and Wildlife Management     11   1.6566
9          Water Quality and Resources Studies     10   1.5060
10              DNA and Nucleic Acid Chemistry      9   1.3554
11                        Data Analysis with R      9   1.3554
12           Urban Transport and Accessibility      9   1.3554
13               Forest ecology and management      8   1.2048
14              Soil Geostatistics and Mapping      8   1.2048

In [22]:
topics_subfield_display_name_ror = df['ror'].isna().groupby(df['topics-subfield-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_subfield_display_name_ror.head(15).reset_index(drop=True)

                    topics-subfield-display_name  ror
0                                        Ecology  153
1                         Biomedical Engineering  139
2                              Molecular Biology  132
3                                  Plant Science  111
4                                     Physiology  102
5                        Artificial Intelligence   93
6              Nature and Landscape Conservation   76
7                      Environmental Engineering   75
8                            Materials Chemistry   65
9                    Global and Planetary Change   48
10                                      Genetics   44
11  Ecology, Evolution, Behavior and Systematics   37
12                  Water Science and Technology   34
13                           Ecological Modeling   33
14                         Aerospace Engineering   30

In [23]:

topics_field_display_name_ror = df['ror'].isna().groupby(df['topics-field-display_name']).sum().reset_index().sort_values(by=['ror'], ascending=False)
topics_field_display_name_ror.head(15).reset_index(drop=True)

                       topics-field-display_name  ror
0                          Environmental Science  498
1                                    Engineering  277
2   Biochemistry, Genetics and Molecular Biology  211
3           Agricultural and Biological Sciences  209
4                               Computer Science  153
5                                       Medicine  147
6                                Social Sciences  101
7                              Materials Science   96
8                                      Chemistry   69
9                   Earth and Planetary Sciences   45
10                                    Psychology   32
11           Economics, Econometrics and Finance   25
12                         Physics and Astronomy   25
13                            Health Professions   22
14                          Chemical Engineering   19

In [24]:
topic_view = df.copy()

In [25]:
topic_view.head()

,id,doi,type,institutions-type,title,publication_year,publication_date,language,authorships-author-author_id,authorships-author-display_name,author_position,orcid,primary_topic-id,primary_topic-display_name,primary_topic-score,primary_topic-subfield,primary_topic-field,primary_topic-domain,topics-id,topics-display_name,topics-subfield-id,topics-subfield-display_name,topics-field-id,topics-field-display_name,topics-domain-id,topics-domain-display_name,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,volume,issue,first_page,last_page,index location,primary_location-source-display_name,retracted,is_oa,oa_status,license,institutions-id,institutions-display_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5061017744,Aleksandr V. Marenich,first,https://orcid.org/0000-0003-0288-843X,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
1,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5053083096,Casey P. Kelly,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
2,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5111863630,Jason D. Thompson,middle,https://orcid.org/0009-0002-4710-8505,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
3,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,https://openalex.org/A5113505750,Gregory D. Hawkins,middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN
4,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,dataset,NaN,Minnesota Solvation Database (MNSOL) version 2012,1998,1998-01-01,en,NaN,"Chambers, Candy C",middle,NaN,https://openalex.org/T12157,Geochemistry and Geologic Mapping,0.6013,https://openalex.org/subfields/1702,https://openalex.org/fields/17,https://openalex.org/domains/3,https://openalex.org/T12157,Geochemistry and Geologic Mapping,https://openalex.org/subfields/1702,Artificial Intelligence,https://openalex.org/fields/17,Computer Science,https://openalex.org/domains/3,Physical Sciences,NaN,NaN,NaN,False,41,NaN,NaN,NaN,NaN,datacite,University of Minnesota Digital Conservancy (U...,False,True,green,cc-by-nc-nd,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
topic_view = topic_view[~topic_view.id.duplicated(keep='first')]

In [38]:
topic_view = topic_view[['id', 'doi', 'title', 'publication_date', 'topics-display_name', 'topics-field-display_name', 'topics-subfield-display_name', 'topics-domain-display_name']]
topic_view.head()

,id,doi,title,publication_date,topics-display_name,topics-field-display_name,topics-subfield-display_name,topics-domain-display_name
0,https://openalex.org/W3081810959,https://doi.org/10.13020/3eks-j059,Minnesota Solvation Database (MNSOL) version 2012,1998-01-01,Geochemistry and Geologic Mapping,Computer Science,Artificial Intelligence,Physical Sciences
9,https://openalex.org/W2297941261,https://doi.org/10.13020/d6g014,White-tailed deer density estimates across the...,2016-01-01,Wildlife Ecology and Conservation,Environmental Science,Ecology,Physical Sciences
12,https://openalex.org/W2898833073,https://doi.org/10.13020/d6kx2r,Global nitrogen deposition (2°×2.5° grid resol...,2018-01-01,Atmospheric and Environmental Gas Dynamics,Environmental Science,Global and Planetary Change,Physical Sciences
13,https://openalex.org/W2525336510,https://doi.org/10.13020/d6jp4s,Minnesota Land Cover Classification and Imperv...,2016-01-01,Rangeland and Wildlife Management,Environmental Science,Ecology,Physical Sciences
14,https://openalex.org/W3043928535,https://doi.org/10.13020/g1gx-y834,TrashCan 1.0 An Instance-Segmentation Labeled ...,2019-06-24,Electron and X-Ray Spectroscopy Techniques,Materials Science,"Surfaces, Coatings and Films",Physical Sciences

In [40]:
topic_view.to_csv('2026-04-22-UMN-Source-Topics-View.csv')