In [2]:
import requests
import json
import pandas as pd
import time

In [ ]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Loop through pages
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        record_number = 0
        page += 1
        for record in records:
            record_number += 1
            print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append(record) 
            

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets
# types/dataset,
parameters = {
    #"filter": f"authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549",  # University of Tasmania
    "per-page": 100,
    #"select": "id,doi,publication_year,title,primary_location,authorships,topics",
}

OpenAlexDataset= OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549', parameters)
# OpenAlexDatasetExMichigan = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549', parameters)
# OpenAlexDatasetMichigan = OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i27837315', parameters)

df = pd.DataFrame(OpenAlexDataset)
df.to_csv('OpenAlexData2.csv')

In [11]:
import os
df = pd.read_csv('OpenAlexData.csv', sep=',',on_bad_lines='skip', index_col=False, dtype='unicode')
df = df.drop(columns=['Unnamed: 0'])
df

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,referenced_works_count,referenced_works,related_works,abstract_inverted_index,cited_by_api_url,counts_by_year,updated_date,created_date,fulltext_origin,is_authors_truncated
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,Cognitive Therapy for Depression,Cognitive Therapy for Depression,2012,2012-01-01,{'openalex': 'https://openalex.org/W213417050'...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,130,"['https://openalex.org/W1965356075', 'https://...","['https://openalex.org/W59104321', 'https://op...","{'We': [0], 'provide': [1], 'an': [2], 'overvi...",https://api.openalex.org/works?filter=cites:W2...,"[{'year': 2024, 'cited_by_count': 3}, {'year':...",2024-09-29T23:51:23.780591,2016-06-24,NaN,NaN
1,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,Telephone Interview for Cognitive Status,Telephone Interview for Cognitive Status,1988,1988-01-01,{'openalex': 'https://openalex.org/W165338889'...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2931662336', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W1...,"[{'year': 2024, 'cited_by_count': 46}, {'year'...",2024-10-16T13:03:33.373865,2016-06-24,NaN,NaN
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,{'openalex': 'https://openalex.org/W2913255424...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2748952813', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W2...,"[{'year': 2024, 'cited_by_count': 83}, {'year'...",2024-10-24T01:55:28.862751,2019-02-21,NaN,NaN
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,The Loss of Sadness: How Psychiatry Transforme...,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,{'openalex': 'https://openalex.org/W1639235375...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W4311605484', 'https://...","{'1.': [0], 'The': [1, 6, 43, 48, 56, 63], 'co...",https://api.openalex.org/works?filter=cites:W1...,"[{'year': 2024, 'cited_by_count': 1}, {'year':...",2024-09-30T22:51:54.729044,2016-06-24,NaN,NaN
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,Cognitive Therapy for Depression,Cognitive Therapy for Depression,1996,1996-01-01,{'openalex': 'https://openalex.org/W2995669665...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W59104321', 'https://op...",NaN,https://api.openalex.org/works?filter=cites:W2...,"[{'year': 2021, 'cited_by_count': 8}, {'year':...",2024-10-05T09:10:07.684782,2019-12-26,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498407,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,Changes in School Mathematics: Curricular Chan...,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,{'openalex': 'https://openalex.org/W4214770937...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W4245490552', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W4...,[],2024-09-15T13:20:26.095340,2022-03-02,NaN,NaN
498408,https://openalex.org/W4244240224,https://doi.org/10.3334/cdiac/sar.db1002,ICRCCM Infrared (Clear-Sky) Line-by Line Radia...,ICRCCM Infrared (Clear-Sky) Line-by Line Radia...,1994,1994-01-01,{'openalex': 'https://openalex.org/W4244240224...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W4286825833', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W4...,[],2024-09-26T02:40:29.796516,2022-05-12,NaN,NaN
498409,https://openalex.org/W4250036444,https://doi.org/10.1037/e665402011-394,Age memory changes a necessary consequence of ...,Age memory changes a necessary consequence of ...,1991,1991-01-01,{'openalex': 'https://openalex.org/W4250036444...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2899084033', 'https://...","{'When': [0], 'large': [1, 55], 'decrements': ...",https://api.openalex.org/works?filter=cites:W4...,[],2024-10-17T22:59:12.216617,2022-05-12,NaN,NaN
498410,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,"National Support for World Order, 1966","National Support for World Order, 1966",1984,1984-05-03,{'openalex': 'https://openalex.org/W4301724758...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,7,"['https://openalex.org/W2014820827', 'https://...","['https://openalex.org/W2899084033', 'https://...","{'The': [0], 'research': [1, 147], 'aims': [2]...",https://api.openalex.org/works?filter=cites:W4...,[],2024-10-02T11:32:02.096938,2022-10-05,pdf,NaN
498411,https://openalex.org/W752851061,https://doi.org/10.1037/e506172009-011,The Representation Of Action Plans In Long Ter...,The Representation Of Action Plans In Long Ter...,1984,1984-01-01,{'openalex': 'https://openalex.org/W752851061'...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2899084033', 'https://...","{'A': [0], 'sequence': [1], 'of': [2, 15, 44, ...",https://api.openalex.org/works?filter=cites:W7...,[],2024-09-26T10:13:39.200719,2016-06-24,NaN,NaN

In [22]:
list(df)

['id',
 'doi',
 'title',
 'display_name',
 'publication_year',
 'publication_date',
 'ids',
 'language',
 'primary_location',
 'type',
 'type_crossref',
 'indexed_in',
 'open_access',
 'authorships',
 'institution_assertions',
 'countries_distinct_count',
 'institutions_distinct_count',
 'corresponding_author_ids',
 'corresponding_institution_ids',
 'apc_list',
 'apc_paid',
 'fwci',
 'has_fulltext',
 'cited_by_count',
 'citation_normalized_percentile',
 'cited_by_percentile_year',
 'biblio',
 'is_retracted',
 'is_paratext',
 'primary_topic',
 'topics',
 'keywords',
 'concepts',
 'mesh',
 'locations_count',
 'locations',
 'best_oa_location',
 'sustainable_development_goals',
 'grants',
 'datasets',
 'versions',
 'referenced_works_count',
 'referenced_works',
 'related_works',
 'abstract_inverted_index',
 'cited_by_api_url',
 'counts_by_year',
 'updated_date',
 'created_date',
 'fulltext_origin',
 'is_authors_truncated']

In [4]:
df.tail()

,id,doi,title,display_name,publication_year,publication_date,ids,language,primary_location,type,...,referenced_works_count,referenced_works,related_works,abstract_inverted_index,cited_by_api_url,counts_by_year,updated_date,created_date,fulltext_origin,is_authors_truncated
498407,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,Changes in School Mathematics: Curricular Chan...,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,{'openalex': 'https://openalex.org/W4214770937...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W4245490552', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W4...,[],2024-09-15T13:20:26.095340,2022-03-02,NaN,NaN
498408,https://openalex.org/W4244240224,https://doi.org/10.3334/cdiac/sar.db1002,ICRCCM Infrared (Clear-Sky) Line-by Line Radia...,ICRCCM Infrared (Clear-Sky) Line-by Line Radia...,1994,1994-01-01,{'openalex': 'https://openalex.org/W4244240224...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W4286825833', 'https://...",NaN,https://api.openalex.org/works?filter=cites:W4...,[],2024-09-26T02:40:29.796516,2022-05-12,NaN,NaN
498409,https://openalex.org/W4250036444,https://doi.org/10.1037/e665402011-394,Age memory changes a necessary consequence of ...,Age memory changes a necessary consequence of ...,1991,1991-01-01,{'openalex': 'https://openalex.org/W4250036444...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2899084033', 'https://...","{'When': [0], 'large': [1, 55], 'decrements': ...",https://api.openalex.org/works?filter=cites:W4...,[],2024-10-17T22:59:12.216617,2022-05-12,NaN,NaN
498410,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,"National Support for World Order, 1966","National Support for World Order, 1966",1984,1984-05-03,{'openalex': 'https://openalex.org/W4301724758...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,7,"['https://openalex.org/W2014820827', 'https://...","['https://openalex.org/W2899084033', 'https://...","{'The': [0], 'research': [1, 147], 'aims': [2]...",https://api.openalex.org/works?filter=cites:W4...,[],2024-10-02T11:32:02.096938,2022-10-05,pdf,NaN
498411,https://openalex.org/W752851061,https://doi.org/10.1037/e506172009-011,The Representation Of Action Plans In Long Ter...,The Representation Of Action Plans In Long Ter...,1984,1984-01-01,{'openalex': 'https://openalex.org/W752851061'...,en,"{'is_oa': False, 'landing_page_url': 'https://...",dataset,...,0,[],"['https://openalex.org/W2899084033', 'https://...","{'A': [0], 'sequence': [1], 'of': [2, 15, 44, ...",https://api.openalex.org/works?filter=cites:W7...,[],2024-09-26T10:13:39.200719,2016-06-24,NaN,NaN