In [3]:
import requests
import pandas as pd
import time
import json

In [4]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Create a container
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        
        # create a loop iterator
        record_number = 0
        page += 1
       
       # Loop over all the records
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'type': record['type'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                'index location': record['indexed_in'],
                                'primary_location': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'], 
                                'authors': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions'],
                                'apc_list': record['apc_list'],
                                'apc_paid': record['apc_paid'],
                                'fwci': record['fwci'],
                                'has_fulltext': record['has_fulltext'],
                                'cited_by_count': record['cited_by_count'], 
                                'citation_normalized_percentile': record['citation_normalized_percentile'],
                                'cited_by_percentile_year': record['cited_by_percentile_year'],
                                'biblio': record['biblio']
                                })         

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

parameters = {
    "per-page": 100,
}   
# types/dataset,
#parameters = {
    #"filter": f"authorships.institutions.lineage:i205783295|i2801744472|i170897317|i145311948|i2802508227|i57206974|i130769515|i20089843|i2801919071|i188538660|i79576946|i27837315|i2800403580|i4210130704|i114395901|i169521973|i135310074|i859038795|i204465549",  # University of Tasmania
    #"per-page": 100,
    #"select": "id,doi,publication_year,title,primary_location,authorships,topics",
#}

In [2]:
import os
from dotenv import load_dotenv

load_dotenv('.env')

my_api_key = os.getenv('82SAK9zRh1JuQsQRglUJkf')
if my_api_key is None:
    print("No API key found!!!")
else:
    print("API key is set!")

No API key found!!!

In [5]:
# API Call to scrape UMN Data
#with open('OpenAlexDataCitation.json', 'w') as outfile:
#    json.dump(OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters), outfile)
  
#df = pd.read_json('OpenAlexDataCitation.json')
#df
#apiKey = '16B98mxBe1EkTVBDiZLmm3'
URL = f"https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901|i4210115145|i4210120349|i2799834026|i4210159608|i4400600966|i4210162301|i74973139|i173911158|i145311948|i40347166|i107639228&api_key={my_api_key}"
#URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901|i4210115145|i4210120349|i2799834026|i4210159608|i4400600966|i4210162301|i74973139|i173911158|i145311948|i40347166|i107639228}'

In [6]:
with open('OpenAlexTwo.json', 'w') as outfile:
    json.dump(OpenAlexAPI(URL, parameters), outfile)

Oh no! Something went wrong during the live demo! How embarrassing!

HTTPError: 401 Client Error: Unauthorized for url: https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974%7Ci130238516%7Ci2801744472%7Ci27837315%7Ci157725225%7Ci2802508227%7Ci4210135927%7Ci188538660%7Ci205783295%7Ci859038795%7Ci135310074%7Ci20089843%7Ci130769515%7Ci51556381%7Ci79576946%7Ci170897317%7Ci204465549%7Ci169521973%7Ci114395901%7Ci4210115145%7Ci4210120349%7Ci2799834026%7Ci4210159608%7Ci4400600966%7Ci4210162301%7Ci74973139%7Ci173911158%7Ci145311948%7Ci40347166%7Ci107639228&api_key=None&per-page=100&cursor=%2A

In [18]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [19]:
def missing_index(df):
    missing_indices = ([i for i in range(0, len(df)) if i not in df.index])
    return missing_indices

In [20]:
pd.set_option("display.max_columns", 55)

In [21]:
df = pd.read_json('OpenAlexDataCitation.json')
df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,Cognitive Therapy for Depression,dataset,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,[crossref],"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Psychology, Vande...","[{'id': 'https://openalex.org/I200719446', 'di...",None,NaN,NaN,False,9958,"{'value': 0.9963900000000001, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,[crossref],"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1313,"{'value': 0.998591, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,The Loss of Sadness: How Psychiatry Transforme...,dataset,2009,2009-01-01,"[{'id': 'https://openalex.org/T12308', 'displa...",en,False,[crossref],"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Rutgers Universit...,"[{'id': 'https://openalex.org/I102322142', 'di...",None,NaN,NaN,False,719,"{'value': 0.9858159999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,Cognitive Therapy for Depression,dataset,1996,1996-01-01,"[{'id': 'https://openalex.org/T13272', 'displa...",en,False,[crossref],"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Psy...,"[{'id': 'https://openalex.org/I78577930', 'dis...",None,NaN,NaN,False,715,"{'value': 0.990741, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."

In [22]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio'],
      dtype='object')

In [23]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,Cognitive Therapy for Depression,dataset,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Psychology, Vande...","[{'id': 'https://openalex.org/I200719446', 'di...",None,NaN,NaN,False,9958,"{'value': 0.9963900000000001, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1313,"{'value': 0.998591, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,The Loss of Sadness: How Psychiatry Transforme...,dataset,2009,2009-01-01,"[{'id': 'https://openalex.org/T12308', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Rutgers Universit...,"[{'id': 'https://openalex.org/I102322142', 'di...",None,NaN,NaN,False,719,"{'value': 0.9858159999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,Cognitive Therapy for Depression,dataset,1996,1996-01-01,"[{'id': 'https://openalex.org/T13272', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Psy...,"[{'id': 'https://openalex.org/I78577930', 'dis...",None,NaN,NaN,False,715,"{'value': 0.990741, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495208,https://openalex.org/W83332581,https://doi.org/10.3334/ornldaac/332,BOREAS TE-06 PREDAWN LEAF WATER POTENTIALS AND...,dataset,1999,1999-01-30,"[{'id': 'https://openalex.org/T10266', 'displa...",en,False,crossref,None,False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'NASA Goddard Spac...,"[{'id': 'https://openalex.org/I1306266525', 'd...",None,NaN,NaN,False,0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 56}","{'volume': None, 'issue': None, 'first_page': ..."
495209,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,Incentive Effects of Tournaments Revisited: Ev...,dataset,1996,1996-01-03,"[{'id': 'https://openalex.org/T11705', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'bv Cornell Univer...,"[{'id': 'https://openalex.org/I205783295', 'di...",None,NaN,NaN,True,0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 54}","{'volume': None, 'issue': None, 'first_page': ..."
495210,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,How Prevalent Are Psychiatric Disorders? Resul...,dataset,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Institute for Soc...,"[{'id': 'https://openalex.org/I27837315', 'dis...",None,NaN,NaN,False,0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 53}","{'volume': None, 'issue': None, 'first_page': ..."
495211,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,Changes in School Mathematics: Curricular Chan...,dataset,1988,1988-01-01,"[{'id': 'https://openalex.org/T10130', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Pen...,"[{'id': 'https://openalex.org/I79576946', 'dis...",None,NaN,NaN,False,0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 53}","{'volume': None, 'issue': None, 'first_page': ..."
495212,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,"National Support for World Order, 1966",dataset,1984,1984-05-03,"[{'id': 'https://openalex.org/T13938', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4363604084', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Soc...,"[{'id': 'https://openalex.org/I27837315', 'dis...",None,NaN,NaN,True,0,"{'value': 0.0, 'is_in_top_1_percent': False, '...","{'min': 0, 'max': 53}","{'volume': None, 'issue': None, 'first_page': ..."

In [24]:
# normalize  citation metric columns data

citation_normalized_percentile_df = pd.json_normalize(df['citation_normalized_percentile'])
cited_by_percentile_year_df = pd.json_normalize(df['cited_by_percentile_year'])
biblio_df = pd.json_normalize(df['biblio'])
# concat normalized data into original df

df = pd.concat([df, citation_normalized_percentile_df], axis=1)
df = pd.concat([df, cited_by_percentile_year_df], axis=1)
df = pd.concat([df, biblio_df], axis=1)

#r ename column
df = df.rename(columns={'value': 'citation_normalized_value'})


df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,Cognitive Therapy for Depression,dataset,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Psychology, Vande...","[{'id': 'https://openalex.org/I200719446', 'di...",None,NaN,NaN,False,9958,"{'value': 0.9963900000000001, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.996390,True,True,99,100,None,None,None,None
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1313,"{'value': 0.998591, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.998591,True,True,99,100,None,None,None,None
2,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,The Loss of Sadness: How Psychiatry Transforme...,dataset,2009,2009-01-01,"[{'id': 'https://openalex.org/T12308', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Rutgers Universit...,"[{'id': 'https://openalex.org/I102322142', 'di...",None,NaN,NaN,False,719,"{'value': 0.9858159999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.985816,False,True,99,100,None,None,None,None
3,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,Cognitive Therapy for Depression,dataset,1996,1996-01-01,"[{'id': 'https://openalex.org/T13272', 'displa...",en,False,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Psy...,"[{'id': 'https://openalex.org/I78577930', 'dis...",None,NaN,NaN,False,715,"{'value': 0.990741, 'is_in_top_1_percent': Tru...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.990741,True,True,99,100,None,None,None,None
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,gold,other-oa,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': '(University of Mi...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,484,"{'value': 0.9977349999999999, 'is_in_top_1_per...","{'min': 99, 'max': 100}","{'volume': None, 'issue': None, 'first_page': ...",0.997735,True,True,99,100,None,None,None,None

In [25]:
# normalize columns data
primary_location_df = pd.json_normalize(df['primary_location'])


# extract only display name column
primary_location_df = primary_location_df[['display_name']]

#rename display name column
primary_location_df = primary_location_df.rename(columns={'display_name': 'Repository'})

#primary_location_df = primary_location_df.reindex(range(primary_location_df.index.min(), primary_location_df .index.max()+1))

# concat display name column to main df
df = pd.concat([df, primary_location_df], axis=1)

In [26]:
# Use function to normalize Authors nested list
authors_df = CleanJSON('authors', df)
authors_df['raw_affiliation_strings'] = authors_df['raw_affiliation_strings'].str[0]
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5082277627', 'di...","[{'id': 'https://openalex.org/I200719446', 'di...",[US],False,Steven D. Hollon,"Psychology, Vanderbilt University","[{'raw_affiliation_string': 'Psychology, Vande..."
0,last,"{'id': 'https://openalex.org/A5059319052', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania","[{'raw_affiliation_string': 'Psychology,Univer..."
1,first,"{'id': 'https://openalex.org/A5025339678', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,John W. Creswell,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...
1,middle,"{'id': 'https://openalex.org/A5077068355', 'di...","[{'id': 'https://openalex.org/I72816309', 'dis...",[US],False,Ann Carroll Klassen,Drexel University,[{'raw_affiliation_string': 'Drexel University...
1,middle,"{'id': 'https://openalex.org/A5021840711', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...
...,...,...,...,...,...,...,...,...
495210,middle,"{'id': 'https://openalex.org/A5071415595', 'di...",[],[],False,S. Eshleman,NaN,[]
495210,middle,"{'id': 'https://openalex.org/A5080980894', 'di...",[],[],False,H. Wittchen,NaN,[]
495210,last,"{'id': 'https://openalex.org/A5110840892', 'di...",[],[],False,K. S. Kendler,NaN,[]
495211,first,"{'id': 'https://openalex.org/A5013000614', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],True,Thomas A. Romberg,University of Pennsylvania ScholarlyCommons,[{'raw_affiliation_string': 'University of Pen...
495212,first,"{'id': 'https://openalex.org/A5048046292', 'di...","[{'id': 'https://openalex.org/I27837315', 'dis...",[US],True,Robert C. Angell,Department of Sociology University of Michigan,[{'raw_affiliation_string': 'Department of Soc...

In [27]:
missing_index(authors_df['raw_affiliation_strings'])

[495213,
 495214,
 495215,
 495216,
 495217,
 495218,
 495219,
 495220,
 495221,
 495222,
 495223,
 495224,
 495225,
 495226,
 495227,
 495228,
 495229,
 495230,
 495231,
 495232,
 495233,
 495234,
 495235,
 495236,
 495237,
 495238,
 495239,
 495240,
 495241,
 495242,
 495243,
 495244,
 495245,
 495246,
 495247,
 495248,
 495249,
 495250,
 495251,
 495252,
 495253,
 495254,
 495255,
 495256,
 495257,
 495258,
 495259,
 495260,
 495261,
 495262,
 495263,
 495264,
 495265,
 495266,
 495267,
 495268,
 495269,
 495270,
 495271,
 495272,
 495273,
 495274,
 495275,
 495276,
 495277,
 495278,
 495279,
 495280,
 495281,
 495282,
 495283,
 495284,
 495285,
 495286,
 495287,
 495288,
 495289,
 495290,
 495291,
 495292,
 495293,
 495294,
 495295,
 495296,
 495297,
 495298,
 495299,
 495300,
 495301,
 495302,
 495303,
 495304,
 495305,
 495306,
 495307,
 495308,
 495309,
 495310,
 495311,
 495312,
 495313,
 495314,
 495315,
 495316,
 495317,
 495318,
 495319,
 495320,
 495321,
 495322,
 495323,
 495324,
 495325,
 495326,
 495327,
 495328,
 495329,
 495330,
 495331,
 495332,
 495333,
 495334,
 495335,
 495336,
 495337,
 495338,
 495339,
 495340,
 495341,
 495342,
 495343,
 495344,
 495345,
 495346,
 495347,
 495348,
 495349,
 495350,
 495351,
 495352,
 495353,
 495354,
 495355,
 495356,
 495357,
 495358,
 495359,
 495360,
 495361,
 495362,
 495363,
 495364,
 495365,
 495366,
 495367,
 495368,
 495369,
 495370,
 495371,
 495372,
 495373,
 495374,
 495375,
 495376,
 495377,
 495378,
 495379,
 495380,
 495381,
 495382,
 495383,
 495384,
 495385,
 495386,
 495387,
 495388,
 495389,
 495390,
 495391,
 495392,
 495393,
 495394,
 495395,
 495396,
 495397,
 495398,
 495399,
 495400,
 495401,
 495402,
 495403,
 495404,
 495405,
 495406,
 495407,
 495408,
 495409,
 495410,
 495411,
 495412,
 495413,
 495414,
 495415,
 495416,
 495417,
 495418,
 495419,
 495420,
 495421,
 495422,
 495423,
 495424,
 495425,
 495426,
 495427,
 495428,
 495429,
 495430,
 495431,
 495432,
 495433,
 495434,
 495435,
 495436,
 495437,
 495438,
 495439,
 495440,
 495441,
 495442,
 495443,
 495444,
 495445,
 495446,
 495447,
 495448,
 495449,
 495450,
 495451,
 495452,
 495453,
 495454,
 495455,
 495456,
 495457,
 495458,
 495459,
 495460,
 495461,
 495462,
 495463,
 495464,
 495465,
 495466,
 495467,
 495468,
 495469,
 495470,
 495471,
 495472,
 495473,
 495474,
 495475,
 495476,
 495477,
 495478,
 495479,
 495480,
 495481,
 495482,
 495483,
 495484,
 495485,
 495486,
 495487,
 495488,
 495489,
 495490,
 495491,
 495492,
 495493,
 495494,
 495495,
 495496,
 495497,
 495498,
 495499,
 495500,
 495501,
 495502,
 495503,
 495504,
 495505,
 495506,
 495507,
 495508,
 495509,
 495510,
 495511,
 495512,
 495513,
 495514,
 495515,
 495516,
 495517,
 495518,
 495519,
 495520,
 495521,
 495522,
 495523,
 495524,
 495525,
 495526,
 495527,
 495528,
 495529,
 495530,
 495531,
 495532,
 495533,
 495534,
 495535,
 495536,
 495537,
 495538,
 495539,
 495540,
 495541,
 495542,
 495543,
 495544,
 495545,
 495546,
 495547,
 495548,
 495549,
 495550,
 495551,
 495552,
 495553,
 495554,
 495555,
 495556,
 495557,
 495558,
 495559,
 495560,
 495561,
 495562,
 495563,
 495564,
 495565,
 495566,
 495567,
 495568,
 495569,
 495570,
 495571,
 495572,
 495573,
 495574,
 495575,
 495576,
 495577,
 495578,
 495579,
 495580,
 495581,
 495582,
 495583,
 495584,
 495585,
 495586,
 495587,
 495588,
 495589,
 495590,
 495591,
 495592,
 495593,
 495594,
 495595,
 495596,
 495597,
 495598,
 495599,
 495600,
 495601,
 495602,
 495603,
 495604,
 495605,
 495606,
 495607,
 495608,
 495609,
 495610,
 495611,
 495612,
 495613,
 495614,
 495615,
 495616,
 495617,
 495618,
 495619,
 495620,
 495621,
 495622,
 495623,
 495624,
 495625,
 495626,
 495627,
 495628,
 495629,
 495630,
 495631,
 495632,
 495633,
 495634,
 495635,
 495636,
 495637,
 495638,
 495639,
 495640,
 495641,
 495642,
 495643,
 495644,
 495645,
 495646,
 495647,
 495648,
 495649,
 495650,
 495651,
 495652,
 495653,
 495654,
 495655,
 495656,
 495657,
 495658,
 495659,
 495660,
 495661,
 495662,
 495663,
 495664,
 495665,
 495666,
 495667,
 495668,
 495669,
 495670,
 495671,
 495672,
 495673,
 495674,
 495675,
 495676,
 495677,
 495678,
 495679,
 495680,
 495681,
 495682,
 495683,
 495684,
 495685,
 495686,
 495687,
 495688,
 495689,
 495690,
 495691,
 495692,
 495693,
 495694,
 495695,
 495696,
 495697,
 495698,
 495699,
 495700,
 495701,
 495702,
 495703,
 495704,
 495705,
 495706,
 495707,
 495708,
 495709,
 495710,
 495711,
 495712,
 495713,
 495714,
 495715,
 495716,
 495717,
 495718,
 495719,
 495720,
 495721,
 495722,
 495723,
 495724,
 495725,
 495726,
 495727,
 495728,
 495729,
 495730,
 495731,
 495732,
 495733,
 495734,
 495735,
 495736,
 495737,
 495738,
 495739,
 495740,
 495741,
 495742,
 495743,
 495744,
 495745,
 495746,
 495747,
 495748,
 495749,
 495750,
 495751,
 495752,
 495753,
 495754,
 495755,
 495756,
 495757,
 495758,
 495759,
 495760,
 495761,
 495762,
 495763,
 495764,
 495765,
 495766,
 495767,
 495768,
 495769,
 495770,
 495771,
 495772,
 495773,
 495774,
 495775,
 495776,
 495777,
 495778,
 495779,
 495780,
 495781,
 495782,
 495783,
 495784,
 495785,
 495786,
 495787,
 495788,
 495789,
 495790,
 495791,
 495792,
 495793,
 495794,
 495795,
 495796,
 495797,
 495798,
 495799,
 495800,
 495801,
 495802,
 495803,
 495804,
 495805,
 495806,
 495807,
 495808,
 495809,
 495810,
 495811,
 495812,
 495813,
 495814,
 495815,
 495816,
 495817,
 495818,
 495819,
 495820,
 495821,
 495822,
 495823,
 495824,
 495825,
 495826,
 495827,
 495828,
 495829,
 495830,
 495831,
 495832,
 495833,
 495834,
 495835,
 495836,
 495837,
 495838,
 495839,
 495840,
 495841,
 495842,
 495843,
 495844,
 495845,
 495846,
 495847,
 495848,
 495849,
 495850,
 495851,
 495852,
 495853,
 495854,
 495855,
 495856,
 495857,
 495858,
 495859,
 495860,
 495861,
 495862,
 495863,
 495864,
 495865,
 495866,
 495867,
 495868,
 495869,
 495870,
 495871,
 495872,
 495873,
 495874,
 495875,
 495876,
 495877,
 495878,
 495879,
 495880,
 495881,
 495882,
 495883,
 495884,
 495885,
 495886,
 495887,
 495888,
 495889,
 495890,
 495891,
 495892,
 495893,
 495894,
 495895,
 495896,
 495897,
 495898,
 495899,
 495900,
 495901,
 495902,
 495903,
 495904,
 495905,
 495906,
 495907,
 495908,
 495909,
 495910,
 495911,
 495912,
 495913,
 495914,
 495915,
 495916,
 495917,
 495918,
 495919,
 495920,
 495921,
 495922,
 495923,
 495924,
 495925,
 495926,
 495927,
 495928,
 495929,
 495930,
 495931,
 495932,
 495933,
 495934,
 495935,
 495936,
 495937,
 495938,
 495939,
 495940,
 495941,
 495942,
 495943,
 495944,
 495945,
 495946,
 495947,
 495948,
 495949,
 495950,
 495951,
 495952,
 495953,
 495954,
 495955,
 495956,
 495957,
 495958,
 495959,
 495960,
 495961,
 495962,
 495963,
 495964,
 495965,
 495966,
 495967,
 495968,
 495969,
 495970,
 495971,
 495972,
 495973,
 495974,
 495975,
 495976,
 495977,
 495978,
 495979,
 495980,
 495981,
 495982,
 495983,
 495984,
 495985,
 495986,
 495987,
 495988,
 495989,
 495990,
 495991,
 495992,
 495993,
 495994,
 495995,
 495996,
 495997,
 495998,
 495999,
 496000,
 496001,
 496002,
 496003,
 496004,
 496005,
 496006,
 496007,
 496008,
 496009,
 496010,
 496011,
 496012,
 496013,
 496014,
 496015,
 496016,
 496017,
 496018,
 496019,
 496020,
 496021,
 496022,
 496023,
 496024,
 496025,
 496026,
 496027,
 496028,
 496029,
 496030,
 496031,
 496032,
 496033,
 496034,
 496035,
 496036,
 496037,
 496038,
 496039,
 496040,
 496041,
 496042,
 496043,
 496044,
 496045,
 496046,
 496047,
 496048,
 496049,
 496050,
 496051,
 496052,
 496053,
 496054,
 496055,
 496056,
 496057,
 496058,
 496059,
 496060,
 496061,
 496062,
 496063,
 496064,
 496065,
 496066,
 496067,
 496068,
 496069,
 496070,
 496071,
 496072,
 496073,
 496074,
 496075,
 496076,
 496077,
 496078,
 496079,
 496080,
 496081,
 496082,
 496083,
 496084,
 496085,
 496086,
 496087,
 496088,
 496089,
 496090,
 496091,
 496092,
 496093,
 496094,
 496095,
 496096,
 496097,
 496098,
 496099,
 496100,
 496101,
 496102,
 496103,
 496104,
 496105,
 496106,
 496107,
 496108,
 496109,
 496110,
 496111,
 496112,
 496113,
 496114,
 496115,
 496116,
 496117,
 496118,
 496119,
 496120,
 496121,
 496122,
 496123,
 496124,
 496125,
 496126,
 496127,
 496128,
 496129,
 496130,
 496131,
 496132,
 496133,
 496134,
 496135,
 496136,
 496137,
 496138,
 496139,
 496140,
 496141,
 496142,
 496143,
 496144,
 496145,
 496146,
 496147,
 496148,
 496149,
 496150,
 496151,
 496152,
 496153,
 496154,
 496155,
 496156,
 496157,
 496158,
 496159,
 496160,
 496161,
 496162,
 496163,
 496164,
 496165,
 496166,
 496167,
 496168,
 496169,
 496170,
 496171,
 496172,
 496173,
 496174,
 496175,
 496176,
 496177,
 496178,
 496179,
 496180,
 496181,
 496182,
 496183,
 496184,
 496185,
 496186,
 496187,
 496188,
 496189,
 496190,
 496191,
 496192,
 496193,
 496194,
 496195,
 496196,
 496197,
 496198,
 496199,
 496200,
 496201,
 496202,
 496203,
 496204,
 496205,
 496206,
 496207,
 496208,
 496209,
 496210,
 496211,
 496212,
 ...]

In [28]:
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'min', 'max', 'volume',
       'issue', 'first_page', 'last_page', 'Repository'],
      dtype='object')

In [29]:
# Create new DataFrame to concat original data from
cleaned_df = df[['id', 'doi', 'type', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'Repository',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext','cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page',
       'last_page',]].copy()
cleaned_df

,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None
2,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,dataset,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,"[{'id': 'https://openalex.org/T12308', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,719,0.985816,False,True,99,100,None,None,None,None
3,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,dataset,Cognitive Therapy for Depression,1996,1996-01-01,"[{'id': 'https://openalex.org/T13272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,715,0.990741,True,True,99,100,None,None,None,None
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018,2018-01-01,"[{'id': 'https://openalex.org/T10995', 'displa...",en,False,datacite,True,gold,other-oa,Harvard Dataverse,None,NaN,NaN,False,484,0.997735,True,True,99,100,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495208,https://openalex.org/W83332581,https://doi.org/10.3334/ornldaac/332,dataset,BOREAS TE-06 PREDAWN LEAF WATER POTENTIALS AND...,1999,1999-01-30,"[{'id': 'https://openalex.org/T10266', 'displa...",en,False,crossref,False,closed,None,NaN,None,NaN,NaN,False,0,0.000000,False,False,0,56,None,None,None,None
495209,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,"[{'id': 'https://openalex.org/T11705', 'displa...",en,False,crossref,True,green,None,ICPSR Data Holdings,None,NaN,NaN,True,0,0.000000,False,False,0,54,None,None,None,None
495210,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495211,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,"[{'id': 'https://openalex.org/T10130', 'displa...",en,False,crossref,True,green,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495212,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,"National Support for World Order, 1966",1984,1984-05-03,"[{'id': 'https://openalex.org/T13938', 'displa...",en,False,crossref,True,green,None,ICPSR Data Holdings,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None

In [30]:
# concat original data to unnested cleaned_df
cleaned_df = pd.concat([authors_df, cleaned_df], axis=1)
cleaned_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page
0,first,"{'id': 'https://openalex.org/A5082277627', 'di...","[{'id': 'https://openalex.org/I200719446', 'di...",[US],False,Steven D. Hollon,"Psychology, Vanderbilt University","[{'raw_affiliation_string': 'Psychology, Vande...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None
0,last,"{'id': 'https://openalex.org/A5059319052', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania","[{'raw_affiliation_string': 'Psychology,Univer...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None
1,first,"{'id': 'https://openalex.org/A5025339678', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,John W. Creswell,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None
1,middle,"{'id': 'https://openalex.org/A5077068355', 'di...","[{'id': 'https://openalex.org/I72816309', 'dis...",[US],False,Ann Carroll Klassen,Drexel University,[{'raw_affiliation_string': 'Drexel University...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None
1,middle,"{'id': 'https://openalex.org/A5021840711', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495210,middle,"{'id': 'https://openalex.org/A5071415595', 'di...",[],[],False,S. Eshleman,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495210,middle,"{'id': 'https://openalex.org/A5080980894', 'di...",[],[],False,H. Wittchen,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495210,last,"{'id': 'https://openalex.org/A5110840892', 'di...",[],[],False,K. S. Kendler,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495211,first,"{'id': 'https://openalex.org/A5013000614', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],True,Thomas A. Romberg,University of Pennsylvania ScholarlyCommons,[{'raw_affiliation_string': 'University of Pen...,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,"[{'id': 'https://openalex.org/T10130', 'displa...",en,False,crossref,True,green,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None
495212,first,"{'id': 'https://openalex.org/A5048046292', 'di...","[{'id': 'https://openalex.org/I27837315', 'dis...",[US],True,Robert C. Angell,Department of Sociology University of Michigan,[{'raw_affiliation_string': 'Department of Soc...,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,"National Support for World Order, 1966",1984,1984-05-03,"[{'id': 'https://openalex.org/T13938', 'displa...",en,False,crossref,True,green,None,ICPSR Data Holdings,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None

In [31]:
# reset index to concat with author information_df
cleaned_df = cleaned_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(cleaned_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'author_id', 'display_name': 'author_name'})
author_info_df

,author_id,author_name,orcid
0,https://openalex.org/A5082277627,Steven D. Hollon,https://orcid.org/0000-0001-5005-3862
1,https://openalex.org/A5059319052,Aaron T. Beck,https://orcid.org/0000-0001-6210-9528
2,https://openalex.org/A5025339678,John W. Creswell,https://orcid.org/0000-0002-5006-880X
3,https://openalex.org/A5077068355,Ann C. Klassen,https://orcid.org/0000-0001-6981-5708
4,https://openalex.org/A5021840711,Vicki L. Plano Clark,https://orcid.org/0000-0002-9709-7982
...,...,...,...
709342,https://openalex.org/A5071415595,Suzann Eshleman,None
709343,https://openalex.org/A5080980894,Hans‐Ulrich Wïttchen,https://orcid.org/0000-0002-6311-7711
709344,https://openalex.org/A5110840892,K. S. Kendler,None
709345,https://openalex.org/A5013000614,Thomas A. Romberg,None
709346,https://openalex.org/A5048046292,Robert C. Angell,None

In [32]:
# concat author_info_df to cleaned_df
cleaned_df = pd.concat([cleaned_df, author_info_df], axis=1).reset_index(drop=True)
cleaned_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5082277627', 'di...","[{'id': 'https://openalex.org/I200719446', 'di...",[US],False,Steven D. Hollon,"Psychology, Vanderbilt University","[{'raw_affiliation_string': 'Psychology, Vande...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/A5082277627,Steven D. Hollon,https://orcid.org/0000-0001-5005-3862
1,0,last,"{'id': 'https://openalex.org/A5059319052', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania","[{'raw_affiliation_string': 'Psychology,Univer...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/A5059319052,Aaron T. Beck,https://orcid.org/0000-0001-6210-9528
2,1,first,"{'id': 'https://openalex.org/A5025339678', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,John W. Creswell,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5025339678,John W. Creswell,https://orcid.org/0000-0002-5006-880X
3,1,middle,"{'id': 'https://openalex.org/A5077068355', 'di...","[{'id': 'https://openalex.org/I72816309', 'dis...",[US],False,Ann Carroll Klassen,Drexel University,[{'raw_affiliation_string': 'Drexel University...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5077068355,Ann C. Klassen,https://orcid.org/0000-0001-6981-5708
4,1,middle,"{'id': 'https://openalex.org/A5021840711', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5021840711,Vicki L. Plano Clark,https://orcid.org/0000-0002-9709-7982

In [33]:
# normalize nested Insituttion column
institution_df = CleanJSON('institutions', cleaned_df)

# remove list format for lineage
institution_df['lineage'] = institution_df['lineage'].str[0]
institution_df

# rename columns
institution_df = institution_df.rename(columns={'id': 'institution_id', 'display_name': 'institution_name', 'type': 'funding_type'})

In [34]:
# remove duplicate indices 
institution_df = institution_df[~institution_df.index.duplicated(keep='first')]

# fill nan values on missinging indices
institution_df = institution_df.reindex(range(institution_df.index.min(), institution_df.index.max()+1))

In [35]:
institution_df.head(25)

,institution_id,institution_name,ror,country_code,funding_type,lineage
0,https://openalex.org/I200719446,Vanderbilt University,https://ror.org/02vm5rt34,US,funder,https://openalex.org/I200719446
1,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946
2,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901
3,https://openalex.org/I72816309,Drexel University,https://ror.org/04bdffz58,US,funder,https://openalex.org/I72816309
4,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901
5,https://openalex.org/I145311948,Johns Hopkins University,https://ror.org/00za53h95,US,funder,https://openalex.org/I145311948
6,https://openalex.org/I102322142,"Rutgers, The State University of New Jersey",https://ror.org/05vt9qd57,US,funder,https://openalex.org/I102322142
7,https://openalex.org/I57206974,New York University,https://ror.org/0190ak572,US,funder,https://openalex.org/I57206974
8,https://openalex.org/I78577930,Columbia University,https://ror.org/00hj8s172,US,funder,https://openalex.org/I78577930
9,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946
10,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
11,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
12,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470
13,https://openalex.org/I52357470,The Ohio State University,https://ror.org/00rs6vg23,US,funder,https://openalex.org/I52357470
14,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
15,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
16,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
17,https://openalex.org/I1319259000,National Geospatial-Intelligence Agency,https://ror.org/02k4pxv54,US,government,https://openalex.org/I1319259000
18,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,funder,https://openalex.org/I34077533
19,https://openalex.org/I34077533,Ohio Supercomputer Center,https://ror.org/01apna436,US,funder,https://openalex.org/I34077533
20,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,funder,https://openalex.org/I188538660
21,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
22,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
23,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516
24,https://openalex.org/I130238516,University of Minnesota,https://ror.org/017zqws13,US,funder,https://openalex.org/I130238516

In [36]:
missing_index(institution_df)

[]

In [37]:
#  Use afiliations column that is already fixed
# normalize nested  column
#affiliations_df = CleanJSON('affiliations', authors_df)

# remove list format for lineage
#affiliations_df['institution_ids'] = affiliations_df['institution_ids'].str[0]

# rename columns
#affiliations_df = affiliations_df.rename(columns={'institution_ids': 'affiliations_lineage'})
#affiliations_df

#affiliations_df

In [38]:
#missing_index(affiliations_df)

In [39]:
#len(affiliations_df)

In [40]:
#remove duplicate indices 
#affiliations_df = affiliations_df.reset_index()
#affiliations_df = affiliations_df.reindex(range(affiliations_df.index.min(), affiliations_df.index.max()+1))
#affiliations_df

In [41]:
#  check if there are any mission indices
#missing_index(affiliations_df)

In [42]:
topics_df = CleanJSON('topics', cleaned_df)
topics_df = topics_df.rename(columns={'id': 'topic_id', 'display_name': 'topic_name'})
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T11071,Treatment of Major Depression,0.9993,"{'id': 'https://openalex.org/subfields/2736', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
0,https://openalex.org/T13283,Mental Health Research Topics,0.9971,"{'id': 'https://openalex.org/subfields/3205', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
0,https://openalex.org/T10241,Functional Brain Connectivity Studies,0.9949,"{'id': 'https://openalex.org/subfields/2805', ...","{'id': 'https://openalex.org/fields/28', 'disp...","{'id': 'https://openalex.org/domains/1', 'disp..."
1,https://openalex.org/T11071,Treatment of Major Depression,0.9993,"{'id': 'https://openalex.org/subfields/2736', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
1,https://openalex.org/T13283,Mental Health Research Topics,0.9971,"{'id': 'https://openalex.org/subfields/3205', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
...,...,...,...,...,...,...
709342,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709343,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709344,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709345,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,0.9134,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709346,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,0.8155,"{'id': 'https://openalex.org/subfields/1202', ...","{'id': 'https://openalex.org/fields/12', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."

In [43]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [44]:
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T11071,Treatment of Major Depression,0.9993,"{'id': 'https://openalex.org/subfields/2736', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
1,https://openalex.org/T11071,Treatment of Major Depression,0.9993,"{'id': 'https://openalex.org/subfields/2736', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
2,https://openalex.org/T10629,Health Policy Implementation Science,0.0918,"{'id': 'https://openalex.org/subfields/3600', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
3,https://openalex.org/T10629,Health Policy Implementation Science,0.0918,"{'id': 'https://openalex.org/subfields/3600', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
4,https://openalex.org/T10629,Health Policy Implementation Science,0.0918,"{'id': 'https://openalex.org/subfields/3600', ...","{'id': 'https://openalex.org/fields/36', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
...,...,...,...,...,...,...
709342,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709343,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709344,https://openalex.org/T10272,Mental Health Treatment and Access,0.9435,"{'id': 'https://openalex.org/subfields/3207', ...","{'id': 'https://openalex.org/fields/32', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709345,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,0.9134,"{'id': 'https://openalex.org/subfields/3304', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
709346,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,0.8155,"{'id': 'https://openalex.org/subfields/1202', ...","{'id': 'https://openalex.org/fields/12', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."

In [45]:
missing_index(topics_df)

[]

In [46]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'subfield_id', 'display_name': 'subfield_name'})
field_df = field_df.rename(columns={'id': 'field_id', 'display_name': 'field_name'})
domain_df = domain_df.rename(columns={'id': 'domain_id', 'display_name': 'domain_name'})

field_df

                              field_id           field_name
0       https://openalex.org/fields/27             Medicine
1       https://openalex.org/fields/27             Medicine
2       https://openalex.org/fields/36   Health Professions
3       https://openalex.org/fields/36   Health Professions
4       https://openalex.org/fields/36   Health Professions
...                                ...                  ...
709342  https://openalex.org/fields/32           Psychology
709343  https://openalex.org/fields/32           Psychology
709344  https://openalex.org/fields/32           Psychology
709345  https://openalex.org/fields/33      Social Sciences
709346  https://openalex.org/fields/12  Arts and Humanities

[709347 rows x 2 columns]

In [47]:
topics_df = topics_df[['topic_id', 'topic_name']]

In [48]:
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
1,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
2,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
3,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
4,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
...,...,...,...,...,...,...,...,...
709342,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709343,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709344,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709345,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
709346,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences

In [49]:
# concat insitution_df and topics_df
#institution_df = institution_df.reset_index()
#merged_list = [institution_df, affiliations_df, topics_df]

merged_list = [institution_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/I200719446,Vanderbilt University,https://ror.org/02vm5rt34,US,funder,https://openalex.org/I200719446,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
1,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
2,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
3,https://openalex.org/I72816309,Drexel University,https://ror.org/04bdffz58,US,funder,https://openalex.org/I72816309,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
4,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709342,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709343,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709344,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709345,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
709346,https://openalex.org/I27837315,University of Michigan,https://ror.org/00jmfr291,US,funder,https://openalex.org/I27837315,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences

In [50]:
unnested_df = cleaned_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5082277627', 'di...","[{'id': 'https://openalex.org/I200719446', 'di...",[US],False,Steven D. Hollon,"Psychology, Vanderbilt University","[{'raw_affiliation_string': 'Psychology, Vande...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/A5082277627,Steven D. Hollon,https://orcid.org/0000-0001-5005-3862
1,0,last,"{'id': 'https://openalex.org/A5059319052', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania","[{'raw_affiliation_string': 'Psychology,Univer...",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,"[{'id': 'https://openalex.org/T11071', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/A5059319052,Aaron T. Beck,https://orcid.org/0000-0001-6210-9528
2,1,first,"{'id': 'https://openalex.org/A5025339678', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,John W. Creswell,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5025339678,John W. Creswell,https://orcid.org/0000-0002-5006-880X
3,1,middle,"{'id': 'https://openalex.org/A5077068355', 'di...","[{'id': 'https://openalex.org/I72816309', 'dis...",[US],False,Ann Carroll Klassen,Drexel University,[{'raw_affiliation_string': 'Drexel University...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5077068355,Ann C. Klassen,https://orcid.org/0000-0001-6981-5708
4,1,middle,"{'id': 'https://openalex.org/A5021840711', 'di...","[{'id': 'https://openalex.org/I114395901', 'di...",[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,[{'raw_affiliation_string': 'University of Neb...,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/A5021840711,Vicki L. Plano Clark,https://orcid.org/0000-0002-9709-7982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709342,495210,middle,"{'id': 'https://openalex.org/A5071415595', 'di...",[],[],False,S. Eshleman,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/A5071415595,Suzann Eshleman,None
709343,495210,middle,"{'id': 'https://openalex.org/A5080980894', 'di...",[],[],False,H. Wittchen,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/A5080980894,Hans‐Ulrich Wïttchen,https://orcid.org/0000-0002-6311-7711
709344,495210,last,"{'id': 'https://openalex.org/A5110840892', 'di...",[],[],False,K. S. Kendler,NaN,[],https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,"[{'id': 'https://openalex.org/T10272', 'displa...",en,False,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/A5110840892,K. S. Kendler,None
709345,495211,first,"{'id': 'https://openalex.org/A5013000614', 'di...","[{'id': 'https://openalex.org/I79576946', 'dis...",[US],True,Thomas A. Romberg,University of Pennsylvania ScholarlyCommons,[{'raw_affiliation_string': 'University of Pen...,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,"[{'id': 'https://openalex.org/T10130', 'displa...",en,False,crossref,True,green,None,PsycEXTRA Dataset,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/A5013000614,Thomas A. Romberg,None
709346,495212,first,"{'id': 'https://openalex.org/A5048046292', 'di...","[{'id': 'https://openalex.org/I27837315', 'dis...",[US],True,Robert C. Angell,Department of Sociology University of Michigan,[{'raw_affiliation_string': 'Department of Soc...,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,"National Support for World Order, 1966",1984,1984-05-03,"[{'id': 'https://openalex.org/T13938', 'displa...",en,False,crossref,True,green,None,ICPSR Data Holdings,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/A5048046292,Robert C. Angell,None

In [51]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'topics', 'language', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'min', 'max', 'volume',
       'issue', 'first_page', 'last_page', 'author_id', 'author_name',
       'orcid'],
      dtype='object')

In [52]:
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'author_id',
       'author_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid
0,first,[US],False,Steven D. Hollon,"Psychology, Vanderbilt University",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,en,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5082277627,Steven D. Hollon,https://orcid.org/0000-0001-5005-3862
1,last,[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,en,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5059319052,Aaron T. Beck,https://orcid.org/0000-0001-6210-9528
2,first,[US],False,John W. Creswell,University of Nebraska— Lincoln,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5025339678,John W. Creswell,https://orcid.org/0000-0002-5006-880X
3,middle,[US],False,Ann Carroll Klassen,Drexel University,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5077068355,Ann C. Klassen,https://orcid.org/0000-0001-6981-5708
4,middle,[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5021840711,Vicki L. Plano Clark,https://orcid.org/0000-0002-9709-7982
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709342,middle,[],False,S. Eshleman,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5071415595,Suzann Eshleman,None
709343,middle,[],False,H. Wittchen,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5080980894,Hans‐Ulrich Wïttchen,https://orcid.org/0000-0002-6311-7711
709344,last,[],False,K. S. Kendler,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5110840892,K. S. Kendler,None
709345,first,[US],True,Thomas A. Romberg,University of Pennsylvania ScholarlyCommons,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,True,green,None,PsycEXTRA Dataset,https://openalex.org/A5013000614,Thomas A. Romberg,None
709346,first,[US],True,Robert C. Angell,Department of Sociology University of Michigan,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,"National Support for World Order, 1966",1984,1984-05-03,en,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,True,green,None,ICPSR Data Holdings,https://openalex.org/A5048046292,Robert C. Angell,None

In [53]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,first,[US],False,Steven D. Hollon,"Psychology, Vanderbilt University",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,en,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5082277627,Steven D. Hollon,https://orcid.org/0000-0001-5005-3862,https://openalex.org/I200719446,Vanderbilt University,https://ror.org/02vm5rt34,US,funder,https://openalex.org/I200719446,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
1,last,[US],False,Aaron T. Beck,"Psychology,University of Pennsylvania",https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,Cognitive Therapy for Depression,2012,2012-01-01,en,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5059319052,Aaron T. Beck,https://orcid.org/0000-0001-6210-9528,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
2,first,[US],False,John W. Creswell,University of Nebraska— Lincoln,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5025339678,John W. Creswell,https://orcid.org/0000-0002-5006-880X,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
3,middle,[US],False,Ann Carroll Klassen,Drexel University,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5077068355,Ann C. Klassen,https://orcid.org/0000-0001-6981-5708,https://openalex.org/I72816309,Drexel University,https://ror.org/04bdffz58,US,funder,https://openalex.org/I72816309,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
4,middle,[US],False,Vicki L. Plano Clark,University of Nebraska— Lincoln,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5021840711,Vicki L. Plano Clark,https://orcid.org/0000-0002-9709-7982,https://openalex.org/I114395901,University of Nebraska–Lincoln,https://ror.org/043mer456,US,funder,https://openalex.org/I114395901,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709342,middle,[],False,S. Eshleman,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5071415595,Suzann Eshleman,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709343,middle,[],False,H. Wittchen,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5080980894,Hans‐Ulrich Wïttchen,https://orcid.org/0000-0002-6311-7711,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709344,last,[],False,K. S. Kendler,NaN,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,False,closed,None,PsycEXTRA Dataset,https://openalex.org/A5110840892,K. S. Kendler,None,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences
709345,first,[US],True,Thomas A. Romberg,University of Pennsylvania ScholarlyCommons,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,True,green,None,PsycEXTRA Dataset,https://openalex.org/A5013000614,Thomas A. Romberg,None,https://openalex.org/I79576946,University of Pennsylvania,https://ror.org/00b30xv10,US,funder,https://openalex.org/I79576946,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
709346,first,[US],True,Robert C. Angell,Department of Sociology University of Michigan,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,"National Support for World Order, 1966",1984,1984-05-03,en,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None,False,crossref,True,green,None,ICPSR Data Holdings,https://openalex.org/A5048046292,Robert C. Angell,None,https://openalex.org/I27837315,University of Michigan,https://ror.org/00jmfr291,US,funder,https://openalex.org/I27837315,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences

In [54]:
# check for nan authors
unnested_df['author_name'].isnull().values.any()

False

In [55]:
# remove rows where authors are NaN
#unnested_df = unnested_df.iloc[:10568]
#unnested_df

In [56]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location', 'is_oa', 'oa_status',
       'license', 'Repository', 'author_id', 'author_name', 'orcid',
       'institution_id', 'institution_name', 'ror', 'country_code',
       'funding_type', 'lineage', 'topic_id', 'topic_name', 'subfield_id',
       'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name'],
      dtype='object')

In [57]:
unnested_df = unnested_df[['id', 'doi', 'type', 'funding_type', 'title', 'publication_year', 'publication_date', 'language', 
       'author_id','author_name', 'author_position', 'orcid',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value', 
              'is_in_top_1_percent', 'is_in_top_10_percent', 'min', 'max', 'volume', 'issue', 'first_page', 'last_page', 
       'topic_id', 'topic_name', 'subfield_id', 'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name', 
       'retracted', 'index location', 'Repository', 'is_oa', 'oa_status', 'license',  
       'institution_id', 'institution_name', 'raw_affiliation_strings',  'country_code', 'ror', 'lineage']]
unnested_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,author_id,author_name,author_position,orcid,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/A5082277627,Steven D. Hollon,first,https://orcid.org/0000-0001-5005-3862,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I200719446,Vanderbilt University,"Psychology, Vanderbilt University",US,https://ror.org/02vm5rt34,https://openalex.org/I200719446
1,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I79576946,University of Pennsylvania,"Psychology,University of Pennsylvania",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/A5077068355,Ann C. Klassen,middle,https://orcid.org/0000-0001-6981-5708,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I72816309,Drexel University,Drexel University,US,https://ror.org/04bdffz58,https://openalex.org/I72816309
4,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
709342,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,NaN,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/A5071415595,Suzann Eshleman,middle,None,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,NaN,NaN,NaN,NaN,NaN,NaN
709343,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,NaN,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/A5080980894,Hans‐Ulrich Wïttchen,middle,https://orcid.org/0000-0002-6311-7711,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,NaN,NaN,NaN,NaN,NaN,NaN
709344,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,NaN,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/A5110840892,K. S. Kendler,last,None,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,NaN,NaN,NaN,NaN,NaN,NaN
709345,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,funder,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,https://openalex.org/A5013000614,Thomas A. Romberg,first,None,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,True,green,None,https://openalex.org/I79576946,University of Pennsylvania,University of Pennsylvania ScholarlyCommons,US,https://ror.org/00b30xv10,https://openalex.org/I79576946
709346,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,funder,"National Support for World Order, 1966",1984,1984-05-03,en,https://openalex.org/A5048046292,Robert C. Angell,first,None,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,None,https://openalex.org/I27837315,University of Michigan,Department of Sociology University of Michigan,US,https://ror.org/00jmfr291,https://openalex.org/I27837315

In [58]:
# subset to ror ids
ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572') | (unnested_df['ror'] == 'https://ror.org/017zqws13') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') 
                                            | (unnested_df['ror'] == 'https://ror.org/00x6h5n95') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') | (unnested_df['ror'] == 'https://ror.org/047426m28') 
                                            | (unnested_df['ror'] == 'https://ror.org/03arq3225') | (unnested_df['ror'] == 'https://ror.org/04sac7215') | (unnested_df['ror'] == 'https://ror.org/02ttsq026') 
                                            | (unnested_df['ror'] == 'https://ror.org/05bnh6r87') | (unnested_df['ror'] == 'https://ror.org/02smfhw86') | (unnested_df['ror'] == 'https://ror.org/01y2jtd41') 
                                            | (unnested_df['ror'] == 'https://ror.org/00hx57361') | (unnested_df['ror'] == 'https://ror.org/04p491231') | (unnested_df['ror'] == 'https://ror.org/0153tk833')
                                            | (unnested_df['ror'] == 'https://ror.org/00b30xv10') | (unnested_df['ror'] == 'https://ror.org/00py81415') | (unnested_df['ror'] == 'https://ror.org/01yc7t268') 
                                            | (unnested_df['ror'] == 'https://ror.org/05fs6jp91') | (unnested_df['ror'] == 'https://ror.org/043mer456')].reset_index(drop=True)
ror_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,author_id,author_name,author_position,orcid,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W213417050,https://doi.org/10.1037/e675542012-001,dataset,funder,Cognitive Therapy for Depression,2012,2012-01-01,en,https://openalex.org/A5059319052,Aaron T. Beck,last,https://orcid.org/0000-0001-6210-9528,None,NaN,NaN,False,9958,0.996390,True,True,99,100,None,None,None,None,https://openalex.org/T11071,Treatment of Major Depression,https://openalex.org/subfields/2736,Pharmacology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I79576946,University of Pennsylvania,"Psychology,University of Pennsylvania",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
1,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,funder,Best Practices for Mixed Methods Research in H...,2011,2011-01-01,en,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,None,NaN,NaN,False,1313,0.998591,True,True,99,100,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W1639235375,https://doi.org/10.1037/e671332011-001,dataset,funder,The Loss of Sadness: How Psychiatry Transforme...,2009,2009-01-01,en,https://openalex.org/A5091505956,Jerome C. Wakefield,last,https://orcid.org/0000-0002-6809-5515,None,NaN,NaN,False,719,0.985816,False,True,99,100,None,None,None,None,https://openalex.org/T12308,Mental Health and Psychiatry,https://openalex.org/subfields/1211,Philosophy,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I57206974,New York University,"New York University, New York, NY, US",US,https://ror.org/0190ak572,https://openalex.org/I57206974
4,https://openalex.org/W2995669665,https://doi.org/10.1037/e555342011-003,dataset,funder,Cognitive Therapy for Depression,1996,1996-01-01,en,https://openalex.org/A5047792029,Aaron T. Beck,last,None,None,NaN,NaN,False,715,0.990741,True,True,99,100,None,None,None,None,https://openalex.org/T13272,Psychological Treatments and Assessments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I79576946,University of Pennsylvania,"Department of Psychiatry, School of Medicine, ...",US,https://ror.org/00b30xv10,https://openalex.org/I79576946
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
517781,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/A5008503776,Ronald G. Ehrenberg,first,None,None,NaN,NaN,True,0,0.000000,False,False,0,54,None,None,None,None,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,None,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517782,https://openalex.org/W4210334465,https://doi.org/10.3886/icpsr01011.v1,dataset,funder,Incentive Effects of Tournaments Revisited: Ev...,1996,1996-01-03,en,https://openalex.org/A5020341649,Michael L. Bognanno,last,None,None,NaN,NaN,True,0,0.000000,False,False,0,54,None,None,None,None,https://openalex.org/T11705,Gambling Behavior and Treatments,https://openalex.org/subfields/3203,Clinical Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,None,https://openalex.org/I205783295,Cornell University,"Ann Arbor, Michigan",US,https://ror.org/05bnh6r87,https://openalex.org/I205783295
517783,https://openalex.org/W2900506720,https://doi.org/10.1037/e500182006-010,dataset,funder,How Prevalent Are Psychiatric Disorders? Resul...,1994,1994-01-01,en,https://openalex.org/A5057810294,Ronald C. Kessler,first,https://orcid.org/0000-0003-4831-2305,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10272,Mental Health Treatment and Access,https://openalex.org/subfields/3207,Social Psychology,https://openalex.org/fields/32,Psychology,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I27837315,University of Michigan,"Institute for Social Research, University of M...",US,https://ror.org/00jmfr291,https://openalex.org/I27837315
517784,https://openalex.org/W4214770937,https://doi.org/10.1037/e579792012-001,dataset,funder,Changes in School Mathematics: Curricular Chan...,1988,1988-01-01,en,https://openalex.org/A5013000614,Thomas A. Romberg,first,None,None,NaN,NaN,False,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T10130,Mathematics Education and Teaching Techniques,https://openalex.org/subfields/3304,Education,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,False,crossref,PsycEXTRA Dataset,True,green,None,https://openalex.org/I79576946,University of Pennsylvania,University of Pennsylvania ScholarlyCommons,US,https://ror.org/00b30xv10,https://openalex.org/I79576946
517785,https://openalex.org/W4301724758,https://doi.org/10.3886/icpsr05001,dataset,funder,"National Support for World Order, 1966",1984,1984-05-03,en,https://openalex.org/A5048046292,Robert C. Angell,first,None,None,NaN,NaN,True,0,0.000000,False,False,0,53,None,None,None,None,https://openalex.org/T13938,Historical and Contemporary Political Dynamics,https://openalex.org/subfields/1202,History,https://openalex.org/fields/12,Arts and Humanities,https://openalex.org/domains/2,Social Sciences,False,crossref,ICPSR Data Holdings,True,green,None,https://openalex.org/I27837315,University of Michigan,Department of Sociology University of Michigan,US,https://ror.org/00jmfr291,https://openalex.org/I27837315

In [ ]:
# Only authors from DCN institutions
ror_df.to_csv('3-16-DCN-UMN-Data.csv')

: