In [2]:
import requests
import pandas as pd
import time
import json

In [3]:
def OpenAlexAPI(url, params):
    
    # Initialize cursor
    cursor = "*"

    # Create a container
    all_datasets = []
    page = 0
    while cursor:
        params["cursor"] = cursor
        
        # Check for request success
        response = requests.get(url, params=params)
        if response.status_code == 200:
            print(f"Status code: {response.status_code}", ';',  "Page number: ", page)
        if response.status_code != 200:
            print("Oh no! Something went wrong during the live demo! How embarrassing!")
            response.raise_for_status()
        records = response.json()['results']
        
        # create a loop iterator
        record_number = 0
        page += 1
       
       # Loop over all the records
        for record in records:
            record_number += 1
            #print("Page number: ", page, 'Record number:', record_number, record)
            all_datasets.append({'id': record['id'],
                                'doi': record['doi'],
                                'title': record['title'],
                                'type': record['type'],
                                'publication_year': record['publication_year'],
                                'publication_date': record['publication_date'],
                                'topics': record['topics'][:],
                                'language': record['language'],
                                'retracted': record['is_retracted'],
                                'index location': record['indexed_in'],
                                'primary_location': record['primary_location']['source'],
                                'is_oa': record['open_access']['is_oa'],
                                'oa_status': record['open_access']['oa_status'],
                                'license': record['primary_location']['license'], 
                                'authors': record['authorships'][:],
                                'affiliations': record['authorships'][0]['affiliations'],
                                'Institution': record['authorships'][0]['institutions'],
                                'apc_list': record['apc_list'],
                                'apc_paid': record['apc_paid'],
                                'fwci': record['fwci'],
                                'has_fulltext': record['has_fulltext'],
                                'cited_by_count': record['cited_by_count'], 
                                'citation_normalized_percentile': record['citation_normalized_percentile'],
                                'cited_by_percentile_year': record['cited_by_percentile_year'],
                                'biblio': record['biblio']
                                })         

        # Update cursor
        cursor = response.json()['meta']['next_cursor']
        
        time.sleep(3)
    return all_datasets

parameters = {
    "per-page": 100,
}

import os
from dotenv import load_dotenv

load_dotenv('.env')

my_api_key = os.getenv('82SAK9zRh1JuQsQRglUJkf')
if my_api_key is None:
    print("No API key found!!!")
else:
    print("API key is set!")

In [4]:
# API Call to scrape UMN Data
#with open('OpenAlexDataCitation.json', 'w') as outfile:
#    json.dump(OpenAlexAPI('https://api.openalex.org/works?page=1&filter=type:types/dataset,authorships.institutions.lineage:i130238516', parameters), outfile)
  
#df = pd.read_json('OpenAlexDataCitation.json')
#df
#apiKey = '16B98mxBe1EkTVBDiZLmm3'
#URL = f"https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901|i4210115145|i4210120349|i2799834026|i4210159608|i4400600966|i4210162301|i74973139|i173911158|i145311948|i40347166|i107639228&api_key={my_api_key}"
#URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901|i4210115145|i4210120349|i2799834026|i4210159608|i4400600966|i4210162301|i74973139|i173911158|i145311948|i40347166|i107639228}'
DCN_URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,authorships.institutions.lineage:i57206974|i130238516|i2801744472|i27837315|i157725225|i2802508227|i4210135927|i188538660|i205783295|i859038795|i135310074|i20089843|i130769515|i51556381|i79576946|i170897317|i204465549|i169521973|i114395901|i4210115145|i4210120349|i2799834026|i4210159608|i4400600966|i4210162301|i74973139|i173911158|i145311948|i40347166|i107639228'
UMN_URL = 'https://api.openalex.org/works?page=1&filter=type:dataset,primary_location.source.id:s4306402521|s4306481838|s4377196712|s4306464182|s4306490497|s4306480819|s4377196595|s7407053140|s4306476050|s4306401616'
UMN_JSONOutFile= '3-18-UMN-API.json'
DCN_JSONOutFile = '3-23-DCN-API'

In [5]:
with open(DCN_JSONOutFile, 'w') as outfile:
    json.dump(OpenAlexAPI(DCN_URL, parameters), outfile)

Status code: 200 ; Page number:  0
Status code: 200 ; Page number:  1
Status code: 200 ; Page number:  2
Status code: 200 ; Page number:  3
Status code: 200 ; Page number:  4
Status code: 200 ; Page number:  5
Status code: 200 ; Page number:  6
Status code: 200 ; Page number:  7
Status code: 200 ; Page number:  8
Status code: 200 ; Page number:  9
Status code: 200 ; Page number:  10
Status code: 200 ; Page number:  11
Status code: 200 ; Page number:  12
Status code: 200 ; Page number:  13
Status code: 200 ; Page number:  14
Status code: 200 ; Page number:  15
Status code: 200 ; Page number:  16
Status code: 200 ; Page number:  17
Status code: 200 ; Page number:  18
Status code: 200 ; Page number:  19
Status code: 200 ; Page number:  20
Status code: 200 ; Page number:  21
Status code: 200 ; Page number:  22
Status code: 200 ; Page number:  23
Status code: 200 ; Page number:  24
Status code: 200 ; Page number:  25
Status code: 200 ; Page number:  26
Status code: 200 ; Page number:  27
Status code: 200 ; Page number:  28
Status code: 200 ; Page number:  29
Status code: 200 ; Page number:  30
Status code: 200 ; Page number:  31
Status code: 200 ; Page number:  32
Status code: 200 ; Page number:  33
Status code: 200 ; Page number:  34
Status code: 200 ; Page number:  35
Status code: 200 ; Page number:  36
Status code: 200 ; Page number:  37
Status code: 200 ; Page number:  38
Status code: 200 ; Page number:  39
Status code: 200 ; Page number:  40
Status code: 200 ; Page number:  41
Status code: 200 ; Page number:  42
Status code: 200 ; Page number:  43
Status code: 200 ; Page number:  44
Status code: 200 ; Page number:  45
Status code: 200 ; Page number:  46
Status code: 200 ; Page number:  47
Status code: 200 ; Page number:  48
Status code: 200 ; Page number:  49
Status code: 200 ; Page number:  50
Status code: 200 ; Page number:  51
Status code: 200 ; Page number:  52
Status code: 200 ; Page number:  53
Status code: 200 ; Page number:  54
Status code: 200 ; Page number:  55
Status code: 200 ; Page number:  56
Status code: 200 ; Page number:  57
Status code: 200 ; Page number:  58
Status code: 200 ; Page number:  59
Status code: 200 ; Page number:  60
Status code: 200 ; Page number:  61
Status code: 200 ; Page number:  62
Status code: 200 ; Page number:  63
Status code: 200 ; Page number:  64
Status code: 200 ; Page number:  65
Status code: 200 ; Page number:  66
Status code: 200 ; Page number:  67
Status code: 200 ; Page number:  68
Status code: 200 ; Page number:  69
Status code: 200 ; Page number:  70
Status code: 200 ; Page number:  71
Status code: 200 ; Page number:  72
Status code: 200 ; Page number:  73
Status code: 200 ; Page number:  74
Status code: 200 ; Page number:  75
Status code: 200 ; Page number:  76
Status code: 200 ; Page number:  77
Status code: 200 ; Page number:  78
Status code: 200 ; Page number:  79
Status code: 200 ; Page number:  80
Status code: 200 ; Page number:  81
Status code: 200 ; Page number:  82
Status code: 200 ; Page number:  83
Status code: 200 ; Page number:  84
Status code: 200 ; Page number:  85
Status code: 200 ; Page number:  86
Status code: 200 ; Page number:  87
Status code: 200 ; Page number:  88
Status code: 200 ; Page number:  89
Status code: 200 ; Page number:  90
Status code: 200 ; Page number:  91
Status code: 200 ; Page number:  92
Status code: 200 ; Page number:  93
Status code: 200 ; Page number:  94
Status code: 200 ; Page number:  95
Status code: 200 ; Page number:  96
Status code: 200 ; Page number:  97
Status code: 200 ; Page number:  98
Status code: 200 ; Page number:  99
Status code: 200 ; Page number:  100
Status code: 200 ; Page number:  101
Status code: 200 ; Page number:  102
Status code: 200 ; Page number:  103
Status code: 200 ; Page number:  104
Status code: 200 ; Page number:  105
Status code: 200 ; Page number:  106
Status code: 200 ; Page number:  107
Status code: 200 ; Page number:  108
Status code: 200 ; Page number:  109
Status code: 200 ; Page number:  110
Status code: 200 ; Page number:  111
Status code: 200 ; Page number:  112
Status code: 200 ; Page number:  113
Status code: 200 ; Page number:  114
Status code: 200 ; Page number:  115
Status code: 200 ; Page number:  116
Status code: 200 ; Page number:  117
Status code: 200 ; Page number:  118
Status code: 200 ; Page number:  119
Status code: 200 ; Page number:  120
Status code: 200 ; Page number:  121
Status code: 200 ; Page number:  122
Status code: 200 ; Page number:  123
Status code: 200 ; Page number:  124
Status code: 200 ; Page number:  125
Status code: 200 ; Page number:  126
Status code: 200 ; Page number:  127
Status code: 200 ; Page number:  128
Status code: 200 ; Page number:  129
Status code: 200 ; Page number:  130
Status code: 200 ; Page number:  131
Status code: 200 ; Page number:  132
Status code: 200 ; Page number:  133
Status code: 200 ; Page number:  134
Status code: 200 ; Page number:  135
Status code: 200 ; Page number:  136
Status code: 200 ; Page number:  137
Status code: 200 ; Page number:  138
Status code: 200 ; Page number:  139
Status code: 200 ; Page number:  140
Status code: 200 ; Page number:  141
Status code: 200 ; Page number:  142
Status code: 200 ; Page number:  143
Status code: 200 ; Page number:  144
Status code: 200 ; Page number:  145
Status code: 200 ; Page number:  146
Status code: 200 ; Page number:  147
Status code: 200 ; Page number:  148
Status code: 200 ; Page number:  149
Status code: 200 ; Page number:  150
Status code: 200 ; Page number:  151
Status code: 200 ; Page number:  152
Status code: 200 ; Page number:  153
Status code: 200 ; Page number:  154
Status code: 200 ; Page number:  155
Status code: 200 ; Page number:  156
Status code: 200 ; Page number:  157
Status code: 200 ; Page number:  158
Status code: 200 ; Page number:  159
Status code: 200 ; Page number:  160
Status code: 200 ; Page number:  161
Status code: 200 ; Page number:  162
Status code: 200 ; Page number:  163
Status code: 200 ; Page number:  164
Status code: 200 ; Page number:  165
Status code: 200 ; Page number:  166
Status code: 200 ; Page number:  167
Status code: 200 ; Page number:  168
Status code: 200 ; Page number:  169
Status code: 200 ; Page number:  170
Status code: 200 ; Page number:  171
Status code: 200 ; Page number:  172
Status code: 200 ; Page number:  173
Status code: 200 ; Page number:  174
Status code: 200 ; Page number:  175
Status code: 200 ; Page number:  176
Status code: 200 ; Page number:  177
Status code: 200 ; Page number:  178
Status code: 200 ; Page number:  179
Status code: 200 ; Page number:  180
Status code: 200 ; Page number:  181
Status code: 200 ; Page number:  182
Status code: 200 ; Page number:  183
Status code: 200 ; Page number:  184
Status code: 200 ; Page number:  185
Status code: 200 ; Page number:  186
Status code: 200 ; Page number:  187
Status code: 200 ; Page number:  188
Status code: 200 ; Page number:  189
Status code: 200 ; Page number:  190
Status code: 200 ; Page number:  191
Status code: 200 ; Page number:  192
Status code: 200 ; Page number:  193
Status code: 200 ; Page number:  194
Status code: 200 ; Page number:  195
Status code: 200 ; Page number:  196
Status code: 200 ; Page number:  197
Status code: 200 ; Page number:  198
Status code: 200 ; Page number:  199
Status code: 200 ; Page number:  200
Status code: 200 ; Page number:  201
Status code: 200 ; Page number:  202
Status code: 200 ; Page number:  203
Status code: 200 ; Page number:  204
Status code: 200 ; Page number:  205
Status code: 200 ; Page number:  206
Status code: 200 ; Page number:  207
Status code: 200 ; Page number:  208
Status code: 200 ; Page number:  209
Status code: 200 ; Page number:  210
Status code: 200 ; Page number:  211
Status code: 200 ; Page number:  212
Status code: 200 ; Page number:  213
Status code: 200 ; Page number:  214
Status code: 200 ; Page number:  215
Status code: 200 ; Page number:  216
Status code: 200 ; Page number:  217
Status code: 200 ; Page number:  218
Status code: 200 ; Page number:  219
Status code: 200 ; Page number:  220
Status code: 200 ; Page number:  221
Status code: 200 ; Page number:  222
Status code: 200 ; Page number:  223
Status code: 200 ; Page number:  224
Status code: 200 ; Page number:  225
Status code: 200 ; Page number:  226
Status code: 200 ; Page number:  227
Status code: 200 ; Page number:  228
Status code: 200 ; Page number:  229
Status code: 200 ; Page number:  230
Status code: 200 ; Page number:  231
Status code: 200 ; Page number:  232
Status code: 200 ; Page number:  233
Status code: 200 ; Page number:  234
Status code: 200 ; Page number:  235
Status code: 200 ; Page number:  236
Status code: 200 ; Page number:  237
Status code: 200 ; Page number:  238
Status code: 200 ; Page number:  239
Status code: 200 ; Page number:  240
Status code: 200 ; Page number:  241
Status code: 200 ; Page number:  242
Status code: 200 ; Page number:  243
Status code: 200 ; Page number:  244
Status code: 200 ; Page number:  245
Status code: 200 ; Page number:  246
Status code: 200 ; Page number:  247
Status code: 200 ; Page number:  248
Status code: 200 ; Page number:  249
Status code: 200 ; Page number:  250
Status code: 200 ; Page number:  251
Status code: 200 ; Page number:  252
Status code: 200 ; Page number:  253
Status code: 200 ; Page number:  254
Status code: 200 ; Page number:  255
Status code: 200 ; Page number:  256
Status code: 200 ; Page number:  257
Status code: 200 ; Page number:  258
Status code: 200 ; Page number:  259
Status code: 200 ; Page number:  260
Status code: 200 ; Page number:  261
Status code: 200 ; Page number:  262
Status code: 200 ; Page number:  263
Status code: 200 ; Page number:  264
Status code: 200 ; Page number:  265
Status code: 200 ; Page number:  266
Status code: 200 ; Page number:  267
Status code: 200 ; Page number:  268
Status code: 200 ; Page number:  269
Status code: 200 ; Page number:  270
Status code: 200 ; Page number:  271
Status code: 200 ; Page number:  272
Status code: 200 ; Page number:  273
Status code: 200 ; Page number:  274
Status code: 200 ; Page number:  275
Status code: 200 ; Page number:  276
Status code: 200 ; Page number:  277
Status code: 200 ; Page number:  278
Status code: 200 ; Page number:  279
Status code: 200 ; Page number:  280
Status code: 200 ; Page number:  281
Status code: 200 ; Page number:  282
Status code: 200 ; Page number:  283
Status code: 200 ; Page number:  284
Status code: 200 ; Page number:  285
Status code: 200 ; Page number:  286
Status code: 200 ; Page number:  287
Status code: 200 ; Page number:  288
Status code: 200 ; Page number:  289
Status code: 200 ; Page number:  290
Status code: 200 ; Page number:  291
Status code: 200 ; Page number:  292
Status code: 200 ; Page number:  293
Status code: 200 ; Page number:  294
Status code: 200 ; Page number:  295
Status code: 200 ; Page number:  296
Status code: 200 ; Page number:  297
Status code: 200 ; Page number:  298
Status code: 200 ; Page number:  299
Status code: 200 ; Page number:  300
Status code: 200 ; Page number:  301
Status code: 200 ; Page number:  302
Status code: 200 ; Page number:  303
Status code: 200 ; Page number:  304
Status code: 200 ; Page number:  305
Status code: 200 ; Page number:  306
Status code: 200 ; Page number:  307
Status code: 200 ; Page number:  308
Status code: 200 ; Page number:  309
Status code: 200 ; Page number:  310
Status code: 200 ; Page number:  311
Status code: 200 ; Page number:  312
Status code: 200 ; Page number:  313
Status code: 200 ; Page number:  314
Status code: 200 ; Page number:  315
Status code: 200 ; Page number:  316
Status code: 200 ; Page number:  317
Status code: 200 ; Page number:  318
Status code: 200 ; Page number:  319
Status code: 200 ; Page number:  320
Status code: 200 ; Page number:  321
Status code: 200 ; Page number:  322
Status code: 200 ; Page number:  323
Status code: 200 ; Page number:  324
Status code: 200 ; Page number:  325
Status code: 200 ; Page number:  326
Status code: 200 ; Page number:  327
Status code: 200 ; Page number:  328
Status code: 200 ; Page number:  329
Status code: 200 ; Page number:  330
Status code: 200 ; Page number:  331
Status code: 200 ; Page number:  332
Status code: 200 ; Page number:  333
Status code: 200 ; Page number:  334
Status code: 200 ; Page number:  335
Status code: 200 ; Page number:  336
Status code: 200 ; Page number:  337
Status code: 200 ; Page number:  338
Status code: 200 ; Page number:  339
Status code: 200 ; Page number:  340
Status code: 200 ; Page number:  341
Status code: 200 ; Page number:  342
Status code: 200 ; Page number:  343
Status code: 200 ; Page number:  344
Status code: 200 ; Page number:  345
Status code: 200 ; Page number:  346
Status code: 200 ; Page number:  347
Status code: 200 ; Page number:  348
Status code: 200 ; Page number:  349
Status code: 200 ; Page number:  350
Status code: 200 ; Page number:  351
Status code: 200 ; Page number:  352
Status code: 200 ; Page number:  353
Status code: 200 ; Page number:  354
Status code: 200 ; Page number:  355
Status code: 200 ; Page number:  356
Status code: 200 ; Page number:  357
Status code: 200 ; Page number:  358
Status code: 200 ; Page number:  359
Status code: 200 ; Page number:  360
Status code: 200 ; Page number:  361
Status code: 200 ; Page number:  362
Status code: 200 ; Page number:  363
Status code: 200 ; Page number:  364
Status code: 200 ; Page number:  365
Status code: 200 ; Page number:  366
Status code: 200 ; Page number:  367
Status code: 200 ; Page number:  368
Status code: 200 ; Page number:  369
Status code: 200 ; Page number:  370
Status code: 200 ; Page number:  371
Status code: 200 ; Page number:  372
Status code: 200 ; Page number:  373
Status code: 200 ; Page number:  374
Status code: 200 ; Page number:  375
Status code: 200 ; Page number:  376
Status code: 200 ; Page number:  377
Status code: 200 ; Page number:  378
Status code: 200 ; Page number:  379
Status code: 200 ; Page number:  380
Status code: 200 ; Page number:  381
Status code: 200 ; Page number:  382
Status code: 200 ; Page number:  383
Status code: 200 ; Page number:  384
Status code: 200 ; Page number:  385
Status code: 200 ; Page number:  386
Status code: 200 ; Page number:  387
Status code: 200 ; Page number:  388
Status code: 200 ; Page number:  389
Status code: 200 ; Page number:  390
Status code: 200 ; Page number:  391
Status code: 200 ; Page number:  392
Status code: 200 ; Page number:  393
Status code: 200 ; Page number:  394
Status code: 200 ; Page number:  395
Status code: 200 ; Page number:  396
Status code: 200 ; Page number:  397
Status code: 200 ; Page number:  398
Status code: 200 ; Page number:  399
Status code: 200 ; Page number:  400
Status code: 200 ; Page number:  401
Status code: 200 ; Page number:  402
Status code: 200 ; Page number:  403
Status code: 200 ; Page number:  404
Status code: 200 ; Page number:  405
Status code: 200 ; Page number:  406
Status code: 200 ; Page number:  407
Status code: 200 ; Page number:  408
Status code: 200 ; Page number:  409
Status code: 200 ; Page number:  410
Status code: 200 ; Page number:  411
Status code: 200 ; Page number:  412
Status code: 200 ; Page number:  413
Status code: 200 ; Page number:  414
Status code: 200 ; Page number:  415
Status code: 200 ; Page number:  416
Status code: 200 ; Page number:  417
Status code: 200 ; Page number:  418
Status code: 200 ; Page number:  419
Status code: 200 ; Page number:  420
Status code: 200 ; Page number:  421
Status code: 200 ; Page number:  422
Status code: 200 ; Page number:  423
Status code: 200 ; Page number:  424
Status code: 200 ; Page number:  425
Status code: 200 ; Page number:  426
Status code: 200 ; Page number:  427
Status code: 200 ; Page number:  428
Status code: 200 ; Page number:  429
Status code: 200 ; Page number:  430
Status code: 200 ; Page number:  431
Status code: 200 ; Page number:  432
Status code: 200 ; Page number:  433
Status code: 200 ; Page number:  434
Status code: 200 ; Page number:  435
Status code: 200 ; Page number:  436
Status code: 200 ; Page number:  437
Status code: 200 ; Page number:  438
Status code: 200 ; Page number:  439
Status code: 200 ; Page number:  440
Status code: 200 ; Page number:  441
Status code: 200 ; Page number:  442
Status code: 200 ; Page number:  443
Status code: 200 ; Page number:  444
Status code: 200 ; Page number:  445
Status code: 200 ; Page number:  446
Status code: 200 ; Page number:  447
Status code: 200 ; Page number:  448
Status code: 200 ; Page number:  449
Status code: 200 ; Page number:  450
Status code: 200 ; Page number:  451
Status code: 200 ; Page number:  452
Status code: 200 ; Page number:  453
Status code: 200 ; Page number:  454
Status code: 200 ; Page number:  455
Status code: 200 ; Page number:  456
Status code: 200 ; Page number:  457
Status code: 200 ; Page number:  458
Status code: 200 ; Page number:  459
Status code: 200 ; Page number:  460
Status code: 200 ; Page number:  461
Status code: 200 ; Page number:  462
Status code: 200 ; Page number:  463
Status code: 200 ; Page number:  464
Status code: 200 ; Page number:  465
Status code: 200 ; Page number:  466
Status code: 200 ; Page number:  467
Status code: 200 ; Page number:  468
Status code: 200 ; Page number:  469
Status code: 200 ; Page number:  470
Status code: 200 ; Page number:  471
Status code: 200 ; Page number:  472
Status code: 200 ; Page number:  473
Status code: 200 ; Page number:  474
Status code: 200 ; Page number:  475
Status code: 200 ; Page number:  476
Status code: 200 ; Page number:  477
Status code: 200 ; Page number:  478
Status code: 200 ; Page number:  479
Status code: 200 ; Page number:  480
Status code: 200 ; Page number:  481
Status code: 200 ; Page number:  482
Status code: 200 ; Page number:  483
Status code: 200 ; Page number:  484
Status code: 200 ; Page number:  485
Status code: 200 ; Page number:  486
Status code: 200 ; Page number:  487
Status code: 200 ; Page number:  488
Status code: 200 ; Page number:  489
Status code: 200 ; Page number:  490
Status code: 200 ; Page number:  491
Status code: 200 ; Page number:  492
Status code: 200 ; Page number:  493
Status code: 200 ; Page number:  494
Status code: 200 ; Page number:  495
Status code: 200 ; Page number:  496
Status code: 200 ; Page number:  497
Status code: 200 ; Page number:  498
Status code: 200 ; Page number:  499
Status code: 200 ; Page number:  500
Status code: 200 ; Page number:  501
Status code: 200 ; Page number:  502
Status code: 200 ; Page number:  503
Status code: 200 ; Page number:  504
Status code: 200 ; Page number:  505
Status code: 200 ; Page number:  506
Status code: 200 ; Page number:  507
Status code: 200 ; Page number:  508
Status code: 200 ; Page number:  509
Status code: 200 ; Page number:  510
Status code: 200 ; Page number:  511
Status code: 200 ; Page number:  512
Status code: 200 ; Page number:  513
Status code: 200 ; Page number:  514
Status code: 200 ; Page number:  515
Status code: 200 ; Page number:  516
Status code: 200 ; Page number:  517
Status code: 200 ; Page number:  518
Status code: 200 ; Page number:  519
Status code: 200 ; Page number:  520
Status code: 200 ; Page number:  521
Status code: 200 ; Page number:  522
Status code: 200 ; Page number:  523
Status code: 200 ; Page number:  524
Status code: 200 ; Page number:  525
Status code: 200 ; Page number:  526
Status code: 200 ; Page number:  527
Status code: 200 ; Page number:  528
Status code: 200 ; Page number:  529
Status code: 200 ; Page number:  530
Status code: 200 ; Page number:  531
Status code: 200 ; Page number:  532
Status code: 200 ; Page number:  533
Status code: 200 ; Page number:  534
Status code: 200 ; Page number:  535
Status code: 200 ; Page number:  536
Status code: 200 ; Page number:  537
Status code: 200 ; Page number:  538
Status code: 200 ; Page number:  539
Status code: 200 ; Page number:  540
Status code: 200 ; Page number:  541
Status code: 200 ; Page number:  542

In [6]:
# Function that creates new dataframe from nested list
def CleanJSON(column,InputDF):
    df = pd.concat([pd.DataFrame(x) for x in InputDF[column]], keys=InputDF.index).reset_index(level=1,drop=True)
    return df

In [7]:
def missing_index(df):
    missing_indices = ([i for i in range(0, len(df)) if i not in df.index])
    return missing_indices

In [8]:
pd.set_option("display.max_columns", 55)

In [9]:
df = pd.read_json(DCN_JSONOutFile)
df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,Statistical properties of magnetic structures ...,dataset,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4306402487', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Ast...,"[{'id': 'https://openalex.org/I2799567181', 'd...",None,NaN,0.0,False,1,"{'value': 0.24338768, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': '2020', 'issue': None, 'first_page'..."
1,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,A two-frame movie of X-ray induced structural ...,dataset,2015.0,2015-01-01,"[{'id': 'https://openalex.org/T11183', 'displa...",en,0.0,"[arxiv, datacite]","{'id': 'https://openalex.org/S4306400194', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Laboratory for So...,"[{'id': 'https://openalex.org/I35440088', 'dis...",None,NaN,0.0,False,1,"{'value': 0.42324679, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011.0,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,0.0,[crossref],"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1559,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,Telephone Interview for Cognitive Status,dataset,1988.0,1988-01-01,[],en,0.0,[crossref],"{'id': 'https://openalex.org/S4306524922', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Johns Hopkins U, ...","[{'id': 'https://openalex.org/I145311948', 'di...",None,NaN,NaN,False,1487,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018.0,2018-09-26,"[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,[datacite],"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,746,None,None,"{'volume': None, 'issue': None, 'first_page': ..."

In [10]:
# investigate the columns
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio'],
      dtype='object')

In [11]:
# Remove list element from column
df['index location'] = df['index location'].str[0]
df

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,Statistical properties of magnetic structures ...,dataset,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4306402487', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Ast...,"[{'id': 'https://openalex.org/I2799567181', 'd...",None,NaN,0.0,False,1,"{'value': 0.24338768, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': '2020', 'issue': None, 'first_page'..."
1,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,A two-frame movie of X-ray induced structural ...,dataset,2015.0,2015-01-01,"[{'id': 'https://openalex.org/T11183', 'displa...",en,0.0,arxiv,"{'id': 'https://openalex.org/S4306400194', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Laboratory for So...,"[{'id': 'https://openalex.org/I35440088', 'dis...",None,NaN,0.0,False,1,"{'value': 0.42324679, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': None, 'issue': None, 'first_page': ..."
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011.0,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1559,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
3,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,Telephone Interview for Cognitive Status,dataset,1988.0,1988-01-01,[],en,0.0,crossref,"{'id': 'https://openalex.org/S4306524922', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Johns Hopkins U, ...","[{'id': 'https://openalex.org/I145311948', 'di...",None,NaN,NaN,False,1487,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018.0,2018-09-26,"[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,746,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526923,https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,665 Glaucomatous Damage of the Macula as Revea...,dataset,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4363604086', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Ophthalmology, NY...","[{'id': 'https://openalex.org/I57206974', 'dis...",None,NaN,NaN,False,0,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
526924,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,4105 Statistical Validation Of An Automatic Al...,dataset,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4363604086', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Electrical and Co...,"[{'id': 'https://openalex.org/I169521973', 'di...",None,NaN,NaN,False,0,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
526925,https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,2994 Fenretinide Prevents Retinal Neovasculari...,dataset,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11559', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4363604086', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Ophthalmology, Jo...","[{'id': 'https://openalex.org/I145311948', 'di...",None,NaN,NaN,False,0,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
526926,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,The Politics of Takings Clauses,dataset,2018.0,2018-01-01,"[{'id': 'https://openalex.org/T13357', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196282', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Vir...,"[{'id': 'https://openalex.org/I51556381', 'dis...",None,NaN,NaN,False,0,None,None,"{'volume': None, 'issue': None, 'first_page': ..."
526927,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,4100 Detection Of Hard Exudates In The Macula ...,dataset,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4363604086', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Electrical & Comp...,"[{'id': 'https://openalex.org/I169521973', 'di...",None,NaN,NaN,False,0,None,None,"{'volume': None, 'issue': None, 'first_page': ..."

In [12]:
# normalize  citation metric columns data

citation_normalized_percentile_df = pd.json_normalize(df['citation_normalized_percentile'])
cited_by_percentile_year_df = pd.json_normalize(df['cited_by_percentile_year'])
biblio_df = pd.json_normalize(df['biblio'])
# concat normalized data into original df

df = pd.concat([df, citation_normalized_percentile_df], axis=1)
df = pd.concat([df, cited_by_percentile_year_df], axis=1)
df = pd.concat([df, biblio_df], axis=1)

#rename column
df = df.rename(columns={'value': 'citation_normalized_value'})


df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,Statistical properties of magnetic structures ...,dataset,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4306402487', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Ast...,"[{'id': 'https://openalex.org/I2799567181', 'd...",None,NaN,0.0,False,1,"{'value': 0.24338768, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': '2020', 'issue': None, 'first_page'...",0.243388,False,False,90.0,94.0,2020,None,None,None
1,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,A two-frame movie of X-ray induced structural ...,dataset,2015.0,2015-01-01,"[{'id': 'https://openalex.org/T11183', 'displa...",en,0.0,arxiv,"{'id': 'https://openalex.org/S4306400194', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Laboratory for So...,"[{'id': 'https://openalex.org/I35440088', 'dis...",None,NaN,0.0,False,1,"{'value': 0.42324679, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': None, 'issue': None, 'first_page': ...",0.423247,False,False,90.0,94.0,None,None,None,None
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011.0,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1559,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None
3,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,Telephone Interview for Cognitive Status,dataset,1988.0,1988-01-01,[],en,0.0,crossref,"{'id': 'https://openalex.org/S4306524922', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Johns Hopkins U, ...","[{'id': 'https://openalex.org/I145311948', 'di...",None,NaN,NaN,False,1487,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018.0,2018-09-26,"[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,746,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None

In [13]:
# normalize columns data
primary_location_df = pd.json_normalize(df['primary_location'])


# extract only display name column
primary_location_df = primary_location_df[['display_name']]

#rename display name column
primary_location_df = primary_location_df.rename(columns={'display_name': 'Repository'})

#primary_location_df = primary_location_df.reindex(range(primary_location_df.index.min(), primary_location_df .index.max()+1))

# concat display name column to main df
df = pd.concat([df, primary_location_df], axis=1)

In [14]:
# Use function to normalize Authors nested list
authors_df = CleanJSON('authors', df)
authors_df['raw_affiliation_strings'] = authors_df['raw_affiliation_strings'].str[0]
authors_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations
0,first,"{'id': 'https://openalex.org/A5022038441', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,[{'raw_affiliation_string': 'Department of Ast...
0,middle,"{'id': 'https://openalex.org/A5073970199', 'di...","[{'id': 'https://openalex.org/I20089843', 'dis...",[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,[{'raw_affiliation_string': 'Princeton Plasma ...
0,middle,"{'id': 'https://openalex.org/A5054740802', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...
0,middle,"{'id': 'https://openalex.org/A5047581227', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...
0,middle,"{'id': 'https://openalex.org/A5036030876', 'di...","[{'id': 'https://openalex.org/I188538660', 'di...",[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,[{'raw_affiliation_string': 'Laboratory of Atm...
...,...,...,...,...,...,...,...,...
526923,last,"{'id': 'https://openalex.org/A5109964783', 'di...","[{'id': 'https://openalex.org/I2799431996', 'd...",[US],False,Robert Ritch,"Ophthalmology, New York Eye and Ear Infirmary,...","[{'raw_affiliation_string': 'Ophthalmology, Ne..."
526924,first,"{'id': 'https://openalex.org/A5110253366', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,E Simon Barriga,"Electrical and Computer Engineering, Universit...",[{'raw_affiliation_string': 'Electrical and Co...
526925,first,"{'id': 'https://openalex.org/A5114017782', 'di...","[{'id': 'https://openalex.org/I145311948', 'di...",[US],True,Brian Oveson,"Ophthalmology, Johns Hopkins University, Balti...","[{'raw_affiliation_string': 'Ophthalmology, Jo..."
526926,first,"{'id': 'https://openalex.org/A5057875125', 'di...","[{'id': 'https://openalex.org/I51556381', 'dis...",[US],True,"Versteeg, Mila",University of Virginia School of Law,[{'raw_affiliation_string': 'University of Vir...
526927,first,"{'id': 'https://openalex.org/A5015635036', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,Carla Agurto Rios,"Electrical & Computer Engineering, University ...",[{'raw_affiliation_string': 'Electrical & Comp...

In [15]:
missing_index(authors_df['raw_affiliation_strings'])

[526928,
 526929,
 526930,
 526931,
 526932,
 526933,
 526934,
 526935,
 526936,
 526937,
 526938,
 526939,
 526940,
 526941,
 526942,
 526943,
 526944,
 526945,
 526946,
 526947,
 526948,
 526949,
 526950,
 526951,
 526952,
 526953,
 526954,
 526955,
 526956,
 526957,
 526958,
 526959,
 526960,
 526961,
 526962,
 526963,
 526964,
 526965,
 526966,
 526967,
 526968,
 526969,
 526970,
 526971,
 526972,
 526973,
 526974,
 526975,
 526976,
 526977,
 526978,
 526979,
 526980,
 526981,
 526982,
 526983,
 526984,
 526985,
 526986,
 526987,
 526988,
 526989,
 526990,
 526991,
 526992,
 526993,
 526994,
 526995,
 526996,
 526997,
 526998,
 526999,
 527000,
 527001,
 527002,
 527003,
 527004,
 527005,
 527006,
 527007,
 527008,
 527009,
 527010,
 527011,
 527012,
 527013,
 527014,
 527015,
 527016,
 527017,
 527018,
 527019,
 527020,
 527021,
 527022,
 527023,
 527024,
 527025,
 527026,
 527027,
 527028,
 527029,
 527030,
 527031,
 527032,
 527033,
 527034,
 527035,
 527036,
 527037,
 527038,
 527039,
 527040,
 527041,
 527042,
 527043,
 527044,
 527045,
 527046,
 527047,
 527048,
 527049,
 527050,
 527051,
 527052,
 527053,
 527054,
 527055,
 527056,
 527057,
 527058,
 527059,
 527060,
 527061,
 527062,
 527063,
 527064,
 527065,
 527066,
 527067,
 527068,
 527069,
 527070,
 527071,
 527072,
 527073,
 527074,
 527075,
 527076,
 527077,
 527078,
 527079,
 527080,
 527081,
 527082,
 527083,
 527084,
 527085,
 527086,
 527087,
 527088,
 527089,
 527090,
 527091,
 527092,
 527093,
 527094,
 527095,
 527096,
 527097,
 527098,
 527099,
 527100,
 527101,
 527102,
 527103,
 527104,
 527105,
 527106,
 527107,
 527108,
 527109,
 527110,
 527111,
 527112,
 527113,
 527114,
 527115,
 527116,
 527117,
 527118,
 527119,
 527120,
 527121,
 527122,
 527123,
 527124,
 527125,
 527126,
 527127,
 527128,
 527129,
 527130,
 527131,
 527132,
 527133,
 527134,
 527135,
 527136,
 527137,
 527138,
 527139,
 527140,
 527141,
 527142,
 527143,
 527144,
 527145,
 527146,
 527147,
 527148,
 527149,
 527150,
 527151,
 527152,
 527153,
 527154,
 527155,
 527156,
 527157,
 527158,
 527159,
 527160,
 527161,
 527162,
 527163,
 527164,
 527165,
 527166,
 527167,
 527168,
 527169,
 527170,
 527171,
 527172,
 527173,
 527174,
 527175,
 527176,
 527177,
 527178,
 527179,
 527180,
 527181,
 527182,
 527183,
 527184,
 527185,
 527186,
 527187,
 527188,
 527189,
 527190,
 527191,
 527192,
 527193,
 527194,
 527195,
 527196,
 527197,
 527198,
 527199,
 527200,
 527201,
 527202,
 527203,
 527204,
 527205,
 527206,
 527207,
 527208,
 527209,
 527210,
 527211,
 527212,
 527213,
 527214,
 527215,
 527216,
 527217,
 527218,
 527219,
 527220,
 527221,
 527222,
 527223,
 527224,
 527225,
 527226,
 527227,
 527228,
 527229,
 527230,
 527231,
 527232,
 527233,
 527234,
 527235,
 527236,
 527237,
 527238,
 527239,
 527240,
 527241,
 527242,
 527243,
 527244,
 527245,
 527246,
 527247,
 527248,
 527249,
 527250,
 527251,
 527252,
 527253,
 527254,
 527255,
 527256,
 527257,
 527258,
 527259,
 527260,
 527261,
 527262,
 527263,
 527264,
 527265,
 527266,
 527267,
 527268,
 527269,
 527270,
 527271,
 527272,
 527273,
 527274,
 527275,
 527276,
 527277,
 527278,
 527279,
 527280,
 527281,
 527282,
 527283,
 527284,
 527285,
 527286,
 527287,
 527288,
 527289,
 527290,
 527291,
 527292,
 527293,
 527294,
 527295,
 527296,
 527297,
 527298,
 527299,
 527300,
 527301,
 527302,
 527303,
 527304,
 527305,
 527306,
 527307,
 527308,
 527309,
 527310,
 527311,
 527312,
 527313,
 527314,
 527315,
 527316,
 527317,
 527318,
 527319,
 527320,
 527321,
 527322,
 527323,
 527324,
 527325,
 527326,
 527327,
 527328,
 527329,
 527330,
 527331,
 527332,
 527333,
 527334,
 527335,
 527336,
 527337,
 527338,
 527339,
 527340,
 527341,
 527342,
 527343,
 527344,
 527345,
 527346,
 527347,
 527348,
 527349,
 527350,
 527351,
 527352,
 527353,
 527354,
 527355,
 527356,
 527357,
 527358,
 527359,
 527360,
 527361,
 527362,
 527363,
 527364,
 527365,
 527366,
 527367,
 527368,
 527369,
 527370,
 527371,
 527372,
 527373,
 527374,
 527375,
 527376,
 527377,
 527378,
 527379,
 527380,
 527381,
 527382,
 527383,
 527384,
 527385,
 527386,
 527387,
 527388,
 527389,
 527390,
 527391,
 527392,
 527393,
 527394,
 527395,
 527396,
 527397,
 527398,
 527399,
 527400,
 527401,
 527402,
 527403,
 527404,
 527405,
 527406,
 527407,
 527408,
 527409,
 527410,
 527411,
 527412,
 527413,
 527414,
 527415,
 527416,
 527417,
 527418,
 527419,
 527420,
 527421,
 527422,
 527423,
 527424,
 527425,
 527426,
 527427,
 527428,
 527429,
 527430,
 527431,
 527432,
 527433,
 527434,
 527435,
 527436,
 527437,
 527438,
 527439,
 527440,
 527441,
 527442,
 527443,
 527444,
 527445,
 527446,
 527447,
 527448,
 527449,
 527450,
 527451,
 527452,
 527453,
 527454,
 527455,
 527456,
 527457,
 527458,
 527459,
 527460,
 527461,
 527462,
 527463,
 527464,
 527465,
 527466,
 527467,
 527468,
 527469,
 527470,
 527471,
 527472,
 527473,
 527474,
 527475,
 527476,
 527477,
 527478,
 527479,
 527480,
 527481,
 527482,
 527483,
 527484,
 527485,
 527486,
 527487,
 527488,
 527489,
 527490,
 527491,
 527492,
 527493,
 527494,
 527495,
 527496,
 527497,
 527498,
 527499,
 527500,
 527501,
 527502,
 527503,
 527504,
 527505,
 527506,
 527507,
 527508,
 527509,
 527510,
 527511,
 527512,
 527513,
 527514,
 527515,
 527516,
 527517,
 527518,
 527519,
 527520,
 527521,
 527522,
 527523,
 527524,
 527525,
 527526,
 527527,
 527528,
 527529,
 527530,
 527531,
 527532,
 527533,
 527534,
 527535,
 527536,
 527537,
 527538,
 527539,
 527540,
 527541,
 527542,
 527543,
 527544,
 527545,
 527546,
 527547,
 527548,
 527549,
 527550,
 527551,
 527552,
 527553,
 527554,
 527555,
 527556,
 527557,
 527558,
 527559,
 527560,
 527561,
 527562,
 527563,
 527564,
 527565,
 527566,
 527567,
 527568,
 527569,
 527570,
 527571,
 527572,
 527573,
 527574,
 527575,
 527576,
 527577,
 527578,
 527579,
 527580,
 527581,
 527582,
 527583,
 527584,
 527585,
 527586,
 527587,
 527588,
 527589,
 527590,
 527591,
 527592,
 527593,
 527594,
 527595,
 527596,
 527597,
 527598,
 527599,
 527600,
 527601,
 527602,
 527603,
 527604,
 527605,
 527606,
 527607,
 527608,
 527609,
 527610,
 527611,
 527612,
 527613,
 527614,
 527615,
 527616,
 527617,
 527618,
 527619,
 527620,
 527621,
 527622,
 527623,
 527624,
 527625,
 527626,
 527627,
 527628,
 527629,
 527630,
 527631,
 527632,
 527633,
 527634,
 527635,
 527636,
 527637,
 527638,
 527639,
 527640,
 527641,
 527642,
 527643,
 527644,
 527645,
 527646,
 527647,
 527648,
 527649,
 527650,
 527651,
 527652,
 527653,
 527654,
 527655,
 527656,
 527657,
 527658,
 527659,
 527660,
 527661,
 527662,
 527663,
 527664,
 527665,
 527666,
 527667,
 527668,
 527669,
 527670,
 527671,
 527672,
 527673,
 527674,
 527675,
 527676,
 527677,
 527678,
 527679,
 527680,
 527681,
 527682,
 527683,
 527684,
 527685,
 527686,
 527687,
 527688,
 527689,
 527690,
 527691,
 527692,
 527693,
 527694,
 527695,
 527696,
 527697,
 527698,
 527699,
 527700,
 527701,
 527702,
 527703,
 527704,
 527705,
 527706,
 527707,
 527708,
 527709,
 527710,
 527711,
 527712,
 527713,
 527714,
 527715,
 527716,
 527717,
 527718,
 527719,
 527720,
 527721,
 527722,
 527723,
 527724,
 527725,
 527726,
 527727,
 527728,
 527729,
 527730,
 527731,
 527732,
 527733,
 527734,
 527735,
 527736,
 527737,
 527738,
 527739,
 527740,
 527741,
 527742,
 527743,
 527744,
 527745,
 527746,
 527747,
 527748,
 527749,
 527750,
 527751,
 527752,
 527753,
 527754,
 527755,
 527756,
 527757,
 527758,
 527759,
 527760,
 527761,
 527762,
 527763,
 527764,
 527765,
 527766,
 527767,
 527768,
 527769,
 527770,
 527771,
 527772,
 527773,
 527774,
 527775,
 527776,
 527777,
 527778,
 527779,
 527780,
 527781,
 527782,
 527783,
 527784,
 527785,
 527786,
 527787,
 527788,
 527789,
 527790,
 527791,
 527792,
 527793,
 527794,
 527795,
 527796,
 527797,
 527798,
 527799,
 527800,
 527801,
 527802,
 527803,
 527804,
 527805,
 527806,
 527807,
 527808,
 527809,
 527810,
 527811,
 527812,
 527813,
 527814,
 527815,
 527816,
 527817,
 527818,
 527819,
 527820,
 527821,
 527822,
 527823,
 527824,
 527825,
 527826,
 527827,
 527828,
 527829,
 527830,
 527831,
 527832,
 527833,
 527834,
 527835,
 527836,
 527837,
 527838,
 527839,
 527840,
 527841,
 527842,
 527843,
 527844,
 527845,
 527846,
 527847,
 527848,
 527849,
 527850,
 527851,
 527852,
 527853,
 527854,
 527855,
 527856,
 527857,
 527858,
 527859,
 527860,
 527861,
 527862,
 527863,
 527864,
 527865,
 527866,
 527867,
 527868,
 527869,
 527870,
 527871,
 527872,
 527873,
 527874,
 527875,
 527876,
 527877,
 527878,
 527879,
 527880,
 527881,
 527882,
 527883,
 527884,
 527885,
 527886,
 527887,
 527888,
 527889,
 527890,
 527891,
 527892,
 527893,
 527894,
 527895,
 527896,
 527897,
 527898,
 527899,
 527900,
 527901,
 527902,
 527903,
 527904,
 527905,
 527906,
 527907,
 527908,
 527909,
 527910,
 527911,
 527912,
 527913,
 527914,
 527915,
 527916,
 527917,
 527918,
 527919,
 527920,
 527921,
 527922,
 527923,
 527924,
 527925,
 527926,
 527927,
 ...]

In [16]:
df.columns

Index(['id', 'doi', 'title', 'type', 'publication_year', 'publication_date',
       'topics', 'language', 'retracted', 'index location', 'primary_location',
       'is_oa', 'oa_status', 'license', 'authors', 'affiliations',
       'Institution', 'apc_list', 'apc_paid', 'fwci', 'has_fulltext',
       'cited_by_count', 'citation_normalized_percentile',
       'cited_by_percentile_year', 'biblio', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'min', 'max', 'volume',
       'issue', 'first_page', 'last_page', 'Repository'],
      dtype='object')

In [17]:
df.head()

,id,doi,title,type,publication_year,publication_date,topics,language,retracted,index location,primary_location,is_oa,oa_status,license,authors,affiliations,Institution,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_percentile,cited_by_percentile_year,biblio,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,min,max,volume,issue,first_page,last_page,Repository
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,Statistical properties of magnetic structures ...,dataset,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4306402487', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Department of Ast...,"[{'id': 'https://openalex.org/I2799567181', 'd...",None,NaN,0.0,False,1,"{'value': 0.24338768, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': '2020', 'issue': None, 'first_page'...",0.243388,False,False,90.0,94.0,2020,None,None,None,OSTI OAI (U.S. Department of Energy Office of ...
1,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,A two-frame movie of X-ray induced structural ...,dataset,2015.0,2015-01-01,"[{'id': 'https://openalex.org/T11183', 'displa...",en,0.0,arxiv,"{'id': 'https://openalex.org/S4306400194', 'di...",True,green,cc-by,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'Laboratory for So...,"[{'id': 'https://openalex.org/I35440088', 'dis...",None,NaN,0.0,False,1,"{'value': 0.42324679, 'is_in_top_1_percent': F...","{'min': 90, 'max': 94}","{'volume': None, 'issue': None, 'first_page': ...",0.423247,False,False,90.0,94.0,None,None,None,None,arXiv (Cornell University)
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,Best Practices for Mixed Methods Research in H...,dataset,2011.0,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,0.0,crossref,"{'id': 'https://openalex.org/S4306524878', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Neb...,"[{'id': 'https://openalex.org/I114395901', 'di...",None,NaN,NaN,False,1559,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None,PsycEXTRA Dataset
3,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,Telephone Interview for Cognitive Status,dataset,1988.0,1988-01-01,[],en,0.0,crossref,"{'id': 'https://openalex.org/S4306524922', 'di...",False,closed,None,"[{'author_position': 'first', 'author': {'id':...","[{'raw_affiliation_string': 'Johns Hopkins U, ...","[{'id': 'https://openalex.org/I145311948', 'di...",None,NaN,NaN,False,1487,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None,PsycTESTS Dataset
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,"ArcticDEM, Version 3",dataset,2018.0,2018-09-26,"[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,"{'id': 'https://openalex.org/S4377196806', 'di...",True,green,None,"[{'author_position': 'first', 'author': {'id':...",[{'raw_affiliation_string': 'University of Min...,"[{'id': 'https://openalex.org/I130238516', 'di...",None,NaN,NaN,False,746,None,None,"{'volume': None, 'issue': None, 'first_page': ...",NaN,NaN,NaN,NaN,NaN,None,None,None,None,Harvard Dataverse

In [18]:
# what was , 'min', 'max'
# Create new DataFrame to concat original data from
cleaned_df = df[['id', 'doi', 'type', 'title', 'publication_year', 'publication_date', 'topics',
       'language', 'retracted', 'index location', 'is_oa',
       'oa_status', 'license', 'Repository',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext','cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page',
       'last_page',]].copy()
cleaned_df

,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
1,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,dataset,A two-frame movie of X-ray induced structural ...,2015.0,2015-01-01,"[{'id': 'https://openalex.org/T11183', 'displa...",en,0.0,arxiv,True,green,cc-by,arXiv (Cornell University),None,NaN,0.0,False,1,0.423247,False,False,None,None,None,None
2,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,Best Practices for Mixed Methods Research in H...,2011.0,2011-01-01,"[{'id': 'https://openalex.org/T10629', 'displa...",en,0.0,crossref,False,closed,None,PsycEXTRA Dataset,None,NaN,NaN,False,1559,NaN,NaN,NaN,None,None,None,None
3,https://openalex.org/W165338889,https://doi.org/10.1037/t28542-000,dataset,Telephone Interview for Cognitive Status,1988.0,1988-01-01,[],en,0.0,crossref,False,closed,None,PsycTESTS Dataset,None,NaN,NaN,False,1487,NaN,NaN,NaN,None,None,None,None
4,https://openalex.org/W4398549858,https://doi.org/10.7910/dvn/ohhukh,dataset,"ArcticDEM, Version 3",2018.0,2018-09-26,"[{'id': 'https://openalex.org/T10995', 'displa...",en,0.0,datacite,True,green,None,Harvard Dataverse,None,NaN,NaN,False,746,NaN,NaN,NaN,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526923,https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526924,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526925,https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11559', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526926,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,The Politics of Takings Clauses,2018.0,2018-01-01,"[{'id': 'https://openalex.org/T13357', 'displa...",en,0.0,datacite,True,green,cc-by,Figshare,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526927,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
# concat original data to unnested cleaned_df
cleaned_df = pd.concat([authors_df, cleaned_df], axis=1)
cleaned_df

,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page
0,first,"{'id': 'https://openalex.org/A5022038441', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,[{'raw_affiliation_string': 'Department of Ast...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
0,middle,"{'id': 'https://openalex.org/A5073970199', 'di...","[{'id': 'https://openalex.org/I20089843', 'dis...",[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
0,middle,"{'id': 'https://openalex.org/A5054740802', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
0,middle,"{'id': 'https://openalex.org/A5047581227', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
0,middle,"{'id': 'https://openalex.org/A5036030876', 'di...","[{'id': 'https://openalex.org/I188538660', 'di...",[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,[{'raw_affiliation_string': 'Laboratory of Atm...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
526923,last,"{'id': 'https://openalex.org/A5109964783', 'di...","[{'id': 'https://openalex.org/I2799431996', 'd...",[US],False,Robert Ritch,"Ophthalmology, New York Eye and Ear Infirmary,...","[{'raw_affiliation_string': 'Ophthalmology, Ne...",https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526924,first,"{'id': 'https://openalex.org/A5110253366', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,E Simon Barriga,"Electrical and Computer Engineering, Universit...",[{'raw_affiliation_string': 'Electrical and Co...,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526925,first,"{'id': 'https://openalex.org/A5114017782', 'di...","[{'id': 'https://openalex.org/I145311948', 'di...",[US],True,Brian Oveson,"Ophthalmology, Johns Hopkins University, Balti...","[{'raw_affiliation_string': 'Ophthalmology, Jo...",https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11559', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526926,first,"{'id': 'https://openalex.org/A5057875125', 'di...","[{'id': 'https://openalex.org/I51556381', 'dis...",[US],True,"Versteeg, Mila",University of Virginia School of Law,[{'raw_affiliation_string': 'University of Vir...,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,The Politics of Takings Clauses,2018.0,2018-01-01,"[{'id': 'https://openalex.org/T13357', 'displa...",en,0.0,datacite,True,green,cc-by,Figshare,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
526927,first,"{'id': 'https://openalex.org/A5015635036', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,Carla Agurto Rios,"Electrical & Computer Engineering, University ...",[{'raw_affiliation_string': 'Electrical & Comp...,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [20]:
# reset index to concat with author information_df
cleaned_df = cleaned_df.reset_index()

# normalize author column
author_info_df= pd.json_normalize(cleaned_df['author'])
author_info_df = author_info_df.rename(columns={'id': 'author_id', 'display_name': 'author_name'})
author_info_df

,author_id,author_name,orcid
0,https://openalex.org/A5022038441,Kendra Bergstedt,https://orcid.org/0000-0002-4992-6387
1,https://openalex.org/A5073970199,Hantao Ji,https://orcid.org/0000-0001-9600-9963
2,https://openalex.org/A5054740802,Jonathan Jara-Almonte,https://orcid.org/0000-0003-0760-6198
3,https://openalex.org/A5047581227,Jongsoo Yoo,https://orcid.org/0000-0003-3881-1995
4,https://openalex.org/A5036030876,R. E. Ergun,https://orcid.org/0000-0002-3096-8579
...,...,...,...
861185,https://openalex.org/A5109964783,Robert Ritch,None
861186,https://openalex.org/A5110253366,E Simon Barriga,None
861187,https://openalex.org/A5114017782,Brian C. Oveson,None
861188,https://openalex.org/A5057875125,Mila Versteeg,https://orcid.org/0000-0001-5231-9847
861189,https://openalex.org/A5015635036,Carla Agurto Rios,None

In [21]:
# concat author_info_df to cleaned_df
cleaned_df = pd.concat([cleaned_df, author_info_df], axis=1).reset_index(drop=True)
cleaned_df.head()

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5022038441', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,[{'raw_affiliation_string': 'Department of Ast...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5022038441,Kendra Bergstedt,https://orcid.org/0000-0002-4992-6387
1,0,middle,"{'id': 'https://openalex.org/A5073970199', 'di...","[{'id': 'https://openalex.org/I20089843', 'dis...",[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5073970199,Hantao Ji,https://orcid.org/0000-0001-9600-9963
2,0,middle,"{'id': 'https://openalex.org/A5054740802', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5054740802,Jonathan Jara-Almonte,https://orcid.org/0000-0003-0760-6198
3,0,middle,"{'id': 'https://openalex.org/A5047581227', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5047581227,Jongsoo Yoo,https://orcid.org/0000-0003-3881-1995
4,0,middle,"{'id': 'https://openalex.org/A5036030876', 'di...","[{'id': 'https://openalex.org/I188538660', 'di...",[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,[{'raw_affiliation_string': 'Laboratory of Atm...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5036030876,R. E. Ergun,https://orcid.org/0000-0002-3096-8579

In [22]:
# normalize nested Insituttion column
institution_df = CleanJSON('institutions', cleaned_df)

# remove list format for lineage
institution_df['lineage'] = institution_df['lineage'].str[0]
institution_df

# rename columns
institution_df = institution_df.rename(columns={'id': 'institution_id', 'display_name': 'institution_name', 'type': 'funding_type'})

In [23]:
# remove duplicate indices 
institution_df = institution_df[~institution_df.index.duplicated(keep='first')]

# fill nan values on missinging indices
institution_df = institution_df.reindex(range(institution_df.index.min(), institution_df.index.max()+1))

In [24]:
institution_df.head(25)

,institution_id,institution_name,ror,country_code,funding_type,lineage
0,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302
1,https://openalex.org/I20089843,Princeton University,https://ror.org/00hx57361,US,education,https://openalex.org/I20089843
2,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302
3,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302
4,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,education,https://openalex.org/I188538660
5,https://openalex.org/I1306266525,Goddard Space Flight Center,https://ror.org/0171mag52,US,facility,https://openalex.org/I1306266525
6,https://openalex.org/I35440088,ETH Zurich,https://ror.org/05a28rw58,CH,education,https://openalex.org/I2799323385
7,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782
8,https://openalex.org/I2738703131,Commissariat à l'Énergie Atomique et aux Énerg...,https://ror.org/00jjx8s55,FR,government,https://openalex.org/I2738703131
9,https://openalex.org/I1282105669,Argonne National Laboratory,https://ror.org/05gvnxz63,US,facility,https://openalex.org/I1282105669
10,https://openalex.org/I35440088,ETH Zurich,https://ror.org/05a28rw58,CH,education,https://openalex.org/I2799323385
11,https://openalex.org/I2801876189,Deutsches Elektronen-Synchrotron DESY,https://ror.org/01js2sh04,DE,facility,https://openalex.org/I1305996414
12,NaN,NaN,NaN,NaN,NaN,NaN
13,https://openalex.org/I196829312,La Trobe University,https://ror.org/01rxfrp27,AU,education,https://openalex.org/I196829312
14,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782
15,NaN,NaN,NaN,NaN,NaN,NaN
16,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782
17,https://openalex.org/I98885092,Nara Women's University,https://ror.org/05kzadn81,JP,education,https://openalex.org/I98885092
18,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782
19,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782
20,https://openalex.org/I2801876189,Deutsches Elektronen-Synchrotron DESY,https://ror.org/01js2sh04,DE,facility,https://openalex.org/I1305996414
21,https://openalex.org/I2801876189,Deutsches Elektronen-Synchrotron DESY,https://ror.org/01js2sh04,DE,facility,https://openalex.org/I1305996414
22,https://openalex.org/I189590672,Kansas State University,https://ror.org/05p1j8758,US,education,https://openalex.org/I189590672
23,https://openalex.org/I2801876189,Deutsches Elektronen-Synchrotron DESY,https://ror.org/01js2sh04,DE,facility,https://openalex.org/I1305996414
24,https://openalex.org/I4577782,Technische Universität Berlin,https://ror.org/03v4gjf40,DE,education,https://openalex.org/I4577782

In [25]:
missing_index(institution_df)

[]

In [26]:
#  Use afiliations column that is already fixed
# normalize nested  column
#affiliations_df = CleanJSON('affiliations', authors_df)

# remove list format for lineage
#affiliations_df['institution_ids'] = affiliations_df['institution_ids'].str[0]

# rename columns
#affiliations_df = affiliations_df.rename(columns={'institution_ids': 'affiliations_lineage'})
#affiliations_df

#affiliations_df

In [27]:
#missing_index(affiliations_df)

In [28]:
#len(affiliations_df)

In [29]:
#remove duplicate indices 
#affiliations_df = affiliations_df.reset_index()
#affiliations_df = affiliations_df.reindex(range(affiliations_df.index.min(), affiliations_df.index.max()+1))
#affiliations_df

In [30]:
#  check if there are any mission indices
#missing_index(affiliations_df)

In [31]:
topics_df = CleanJSON('topics', cleaned_df)
topics_df = topics_df.rename(columns={'id': 'topic_id', 'display_name': 'topic_name'})
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T10251,Solar and Space Plasma Dynamics,0.9985,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
0,https://openalex.org/T11786,Geomagnetism and Paleomagnetism Studies,0.9867,"{'id': 'https://openalex.org/subfields/1312', ...","{'id': 'https://openalex.org/fields/13', 'disp...","{'id': 'https://openalex.org/domains/1', 'disp..."
1,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10251,Solar and Space Plasma Dynamics,0.9985,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
861187,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,0.9882,"{'id': 'https://openalex.org/subfields/1312', ...","{'id': 'https://openalex.org/fields/13', 'disp...","{'id': 'https://openalex.org/domains/1', 'disp..."
861187,https://openalex.org/T10170,Retinal Diseases and Treatments,0.9488,"{'id': 'https://openalex.org/subfields/2731', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
861188,https://openalex.org/T13357,Property Rights and Legal Doctrine,0.9874,"{'id': 'https://openalex.org/subfields/3308', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
861188,https://openalex.org/T11789,Land Rights and Reforms,0.9093,"{'id': 'https://openalex.org/subfields/1111', ...","{'id': 'https://openalex.org/fields/11', 'disp...","{'id': 'https://openalex.org/domains/1', 'disp..."
861189,https://openalex.org/T10250,Glaucoma and retinal disorders,0.9407,"{'id': 'https://openalex.org/subfields/2731', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."

In [32]:
topics_df = topics_df[~topics_df.index.duplicated(keep='first')]

topics_df = topics_df.reindex(range(topics_df.index.min(), topics_df.index.max()+1))

In [33]:
topics_df

,topic_id,topic_name,score,subfield,field,domain
0,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
1,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
2,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
3,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
4,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,0.9993,"{'id': 'https://openalex.org/subfields/3103', ...","{'id': 'https://openalex.org/fields/31', 'disp...","{'id': 'https://openalex.org/domains/3', 'disp..."
...,...,...,...,...,...,...
861185,https://openalex.org/T10250,Glaucoma and retinal disorders,0.9652,"{'id': 'https://openalex.org/subfields/2731', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
861186,https://openalex.org/T11438,Retinal Imaging and Analysis,0.9548,"{'id': 'https://openalex.org/subfields/2741', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."
861187,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,0.9882,"{'id': 'https://openalex.org/subfields/1312', ...","{'id': 'https://openalex.org/fields/13', 'disp...","{'id': 'https://openalex.org/domains/1', 'disp..."
861188,https://openalex.org/T13357,Property Rights and Legal Doctrine,0.9874,"{'id': 'https://openalex.org/subfields/3308', ...","{'id': 'https://openalex.org/fields/33', 'disp...","{'id': 'https://openalex.org/domains/2', 'disp..."
861189,https://openalex.org/T10250,Glaucoma and retinal disorders,0.9407,"{'id': 'https://openalex.org/subfields/2731', ...","{'id': 'https://openalex.org/fields/27', 'disp...","{'id': 'https://openalex.org/domains/4', 'disp..."

In [34]:
missing_index(topics_df)

[]

In [35]:
subfield_df = pd.json_normalize(topics_df['subfield'])
field_df = pd.json_normalize(topics_df['field'])
domain_df = pd.json_normalize(topics_df['domain'])

# rename 
subfield_df = subfield_df.rename(columns={'id': 'subfield_id', 'display_name': 'subfield_name'})
field_df = field_df.rename(columns={'id': 'field_id', 'display_name': 'field_name'})
domain_df = domain_df.rename(columns={'id': 'domain_id', 'display_name': 'domain_name'})

field_df

,field_id,field_name
0,https://openalex.org/fields/31,Physics and Astronomy
1,https://openalex.org/fields/31,Physics and Astronomy
2,https://openalex.org/fields/31,Physics and Astronomy
3,https://openalex.org/fields/31,Physics and Astronomy
4,https://openalex.org/fields/31,Physics and Astronomy
...,...,...
861185,https://openalex.org/fields/27,Medicine
861186,https://openalex.org/fields/27,Medicine
861187,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology"
861188,https://openalex.org/fields/33,Social Sciences
861189,https://openalex.org/fields/27,Medicine

In [36]:
topics_df = topics_df[['topic_id', 'topic_name']]

In [37]:
topics_df = pd.concat([topics_df, subfield_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, field_df], axis=1).reset_index(drop=True)
topics_df = pd.concat([topics_df, domain_df], axis=1).reset_index(drop=True)
topics_df

,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...
861185,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861186,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861187,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,https://openalex.org/subfields/1312,Molecular Biology,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology",https://openalex.org/domains/1,Life Sciences
861188,https://openalex.org/T13357,Property Rights and Legal Doctrine,https://openalex.org/subfields/3308,Law,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
861189,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [38]:
# concat insitution_df and topics_df
#institution_df = institution_df.reset_index()
#merged_list = [institution_df, affiliations_df, topics_df]

merged_list = [institution_df, topics_df]
merged_df = pd.concat(merged_list, axis=1)
merged_df

,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
1,https://openalex.org/I20089843,Princeton University,https://ror.org/00hx57361,US,education,https://openalex.org/I20089843,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
2,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
3,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
4,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,education,https://openalex.org/I188538660,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861185,https://openalex.org/I2799431996,New York Eye and Ear Infirmary,https://ror.org/00tcb9k97,US,healthcare,https://openalex.org/I2799431996,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861186,https://openalex.org/I169521973,University of New Mexico,https://ror.org/05fs6jp91,US,education,https://openalex.org/I169521973,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861187,https://openalex.org/I145311948,Johns Hopkins University,https://ror.org/00za53h95,US,education,https://openalex.org/I145311948,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,https://openalex.org/subfields/1312,Molecular Biology,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology",https://openalex.org/domains/1,Life Sciences
861188,https://openalex.org/I51556381,University of Virginia,https://ror.org/0153tk833,US,education,https://openalex.org/I51556381,https://openalex.org/T13357,Property Rights and Legal Doctrine,https://openalex.org/subfields/3308,Law,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
861189,https://openalex.org/I169521973,University of New Mexico,https://ror.org/05fs6jp91,US,education,https://openalex.org/I169521973,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [39]:
unnested_df = cleaned_df.copy()
unnested_df

,index,author_position,author,institutions,countries,is_corresponding,raw_author_name,raw_affiliation_strings,affiliations,id,doi,type,title,publication_year,publication_date,topics,language,retracted,index location,is_oa,oa_status,license,Repository,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,author_id,author_name,orcid
0,0,first,"{'id': 'https://openalex.org/A5022038441', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,[{'raw_affiliation_string': 'Department of Ast...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5022038441,Kendra Bergstedt,https://orcid.org/0000-0002-4992-6387
1,0,middle,"{'id': 'https://openalex.org/A5073970199', 'di...","[{'id': 'https://openalex.org/I20089843', 'dis...",[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5073970199,Hantao Ji,https://orcid.org/0000-0001-9600-9963
2,0,middle,"{'id': 'https://openalex.org/A5054740802', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5054740802,Jonathan Jara-Almonte,https://orcid.org/0000-0003-0760-6198
3,0,middle,"{'id': 'https://openalex.org/A5047581227', 'di...","[{'id': 'https://openalex.org/I2799567181', 'd...",[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",[{'raw_affiliation_string': 'Princeton Plasma ...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5047581227,Jongsoo Yoo,https://orcid.org/0000-0003-3881-1995
4,0,middle,"{'id': 'https://openalex.org/A5036030876', 'di...","[{'id': 'https://openalex.org/I188538660', 'di...",[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,[{'raw_affiliation_string': 'Laboratory of Atm...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,"[{'id': 'https://openalex.org/T10159', 'displa...",en,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/A5036030876,R. E. Ergun,https://orcid.org/0000-0002-3096-8579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861185,526923,last,"{'id': 'https://openalex.org/A5109964783', 'di...","[{'id': 'https://openalex.org/I2799431996', 'd...",[US],False,Robert Ritch,"Ophthalmology, New York Eye and Ear Infirmary,...","[{'raw_affiliation_string': 'Ophthalmology, Ne...",https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5109964783,Robert Ritch,None
861186,526924,first,"{'id': 'https://openalex.org/A5110253366', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,E Simon Barriga,"Electrical and Computer Engineering, Universit...",[{'raw_affiliation_string': 'Electrical and Co...,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11438', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5110253366,E Simon Barriga,None
861187,526925,first,"{'id': 'https://openalex.org/A5114017782', 'di...","[{'id': 'https://openalex.org/I145311948', 'di...",[US],True,Brian Oveson,"Ophthalmology, Johns Hopkins University, Balti...","[{'raw_affiliation_string': 'Ophthalmology, Jo...",https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T11559', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5114017782,Brian C. Oveson,None
861188,526926,first,"{'id': 'https://openalex.org/A5057875125', 'di...","[{'id': 'https://openalex.org/I51556381', 'dis...",[US],True,"Versteeg, Mila",University of Virginia School of Law,[{'raw_affiliation_string': 'University of Vir...,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,The Politics of Takings Clauses,2018.0,2018-01-01,"[{'id': 'https://openalex.org/T13357', 'displa...",en,0.0,datacite,True,green,cc-by,Figshare,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5057875125,Mila Versteeg,https://orcid.org/0000-0001-5231-9847
861189,526927,first,"{'id': 'https://openalex.org/A5015635036', 'di...","[{'id': 'https://openalex.org/I169521973', 'di...",[US],True,Carla Agurto Rios,"Electrical & Computer Engineering, University ...",[{'raw_affiliation_string': 'Electrical & Comp...,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,"[{'id': 'https://openalex.org/T10250', 'displa...",en,0.0,crossref,False,closed,None,SciVee,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/A5015635036,Carla Agurto Rios,None

In [40]:
unnested_df.columns

Index(['index', 'author_position', 'author', 'institutions', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'affiliations', 'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'topics', 'language', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value',
       'is_in_top_1_percent', 'is_in_top_10_percent', 'volume', 'issue',
       'first_page', 'last_page', 'author_id', 'author_name', 'orcid'],
      dtype='object')

In [41]:
# what was , 'min', 'max'
unnested_df = unnested_df[['author_position', 'countries',
       'is_corresponding', 'raw_author_name', 'raw_affiliation_strings',
       'id', 'doi', 'type', 'title', 'publication_year',
       'publication_date', 'language', 'apc_list', 'apc_paid',
       'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page',
       'last_page', 'retracted', 'index location',
       'is_oa', 'oa_status', 'license', 'Repository', 'author_id',
       'author_name', 'orcid']]
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid
0,first,[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5022038441,Kendra Bergstedt,https://orcid.org/0000-0002-4992-6387
1,middle,[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5073970199,Hantao Ji,https://orcid.org/0000-0001-9600-9963
2,middle,[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5054740802,Jonathan Jara-Almonte,https://orcid.org/0000-0003-0760-6198
3,middle,[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5047581227,Jongsoo Yoo,https://orcid.org/0000-0003-3881-1995
4,middle,[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5036030876,R. E. Ergun,https://orcid.org/0000-0002-3096-8579
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861185,last,[US],False,Robert Ritch,"Ophthalmology, New York Eye and Ear Infirmary,...",https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5109964783,Robert Ritch,None
861186,first,[US],True,E Simon Barriga,"Electrical and Computer Engineering, Universit...",https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5110253366,E Simon Barriga,None
861187,first,[US],True,Brian Oveson,"Ophthalmology, Johns Hopkins University, Balti...",https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5114017782,Brian C. Oveson,None
861188,first,[US],True,"Versteeg, Mila",University of Virginia School of Law,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,The Politics of Takings Clauses,2018.0,2018-01-01,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,datacite,True,green,cc-by,Figshare,https://openalex.org/A5057875125,Mila Versteeg,https://orcid.org/0000-0001-5231-9847
861189,first,[US],True,Carla Agurto Rios,"Electrical & Computer Engineering, University ...",https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5015635036,Carla Agurto Rios,None

In [42]:
unnested_df = pd.concat([unnested_df, merged_df], axis=1)
unnested_df

,author_position,countries,is_corresponding,raw_author_name,raw_affiliation_strings,id,doi,type,title,publication_year,publication_date,language,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,retracted,index location,is_oa,oa_status,license,Repository,author_id,author_name,orcid,institution_id,institution_name,ror,country_code,funding_type,lineage,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name
0,first,[US],True,"Bergstedt, K.",Department of Astrophysical Sciences Princeton...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5022038441,Kendra Bergstedt,https://orcid.org/0000-0002-4992-6387,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
1,middle,[US],False,"Ji, H.",Princeton Plasma Physics Laboratory Princeton...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5073970199,Hantao Ji,https://orcid.org/0000-0001-9600-9963,https://openalex.org/I20089843,Princeton University,https://ror.org/00hx57361,US,education,https://openalex.org/I20089843,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
2,middle,[US],False,"Jara-Almonte, J.","Princeton Plasma Physics Laboratory , Princeto...",https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5054740802,Jonathan Jara-Almonte,https://orcid.org/0000-0003-0760-6198,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
3,middle,[US],False,"Yoo, J.","Princeton Plasma Physics Laboratory , Princeto...",https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5047581227,Jongsoo Yoo,https://orcid.org/0000-0003-3881-1995,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,https://ror.org/03vn1ts68,US,facility,https://openalex.org/I1330989302,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
4,middle,[US],False,"Ergun, R. E.",Laboratory of Atmospheric and Space Sciences U...,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,0.0,datacite,True,green,None,OSTI OAI (U.S. Department of Energy Office of ...,https://openalex.org/A5036030876,R. E. Ergun,https://orcid.org/0000-0002-3096-8579,https://openalex.org/I188538660,University of Colorado Boulder,https://ror.org/02ttsq026,US,education,https://openalex.org/I188538660,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861185,last,[US],False,Robert Ritch,"Ophthalmology, New York Eye and Ear Infirmary,...",https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5109964783,Robert Ritch,None,https://openalex.org/I2799431996,New York Eye and Ear Infirmary,https://ror.org/00tcb9k97,US,healthcare,https://openalex.org/I2799431996,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861186,first,[US],True,E Simon Barriga,"Electrical and Computer Engineering, Universit...",https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5110253366,E Simon Barriga,None,https://openalex.org/I169521973,University of New Mexico,https://ror.org/05fs6jp91,US,education,https://openalex.org/I169521973,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences
861187,first,[US],True,Brian Oveson,"Ophthalmology, Johns Hopkins University, Balti...",https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5114017782,Brian C. Oveson,None,https://openalex.org/I145311948,Johns Hopkins University,https://ror.org/00za53h95,US,education,https://openalex.org/I145311948,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,https://openalex.org/subfields/1312,Molecular Biology,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology",https://openalex.org/domains/1,Life Sciences
861188,first,[US],True,"Versteeg, Mila",University of Virginia School of Law,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,The Politics of Takings Clauses,2018.0,2018-01-01,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,datacite,True,green,cc-by,Figshare,https://openalex.org/A5057875125,Mila Versteeg,https://orcid.org/0000-0001-5231-9847,https://openalex.org/I51556381,University of Virginia,https://ror.org/0153tk833,US,education,https://openalex.org/I51556381,https://openalex.org/T13357,Property Rights and Legal Doctrine,https://openalex.org/subfields/3308,Law,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences
861189,first,[US],True,Carla Agurto Rios,"Electrical & Computer Engineering, University ...",https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,en,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,crossref,False,closed,None,SciVee,https://openalex.org/A5015635036,Carla Agurto Rios,None,https://openalex.org/I169521973,University of New Mexico,https://ror.org/05fs6jp91,US,education,https://openalex.org/I169521973,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences

In [43]:
# check for nan authors
unnested_df['author_name'].isnull().values.any()

False

In [44]:
# remove rows where authors are NaN
#unnested_df = unnested_df.iloc[:10568]
#unnested_df

In [45]:
unnested_df.columns

Index(['author_position', 'countries', 'is_corresponding', 'raw_author_name',
       'raw_affiliation_strings', 'id', 'doi', 'type', 'title',
       'publication_year', 'publication_date', 'language', 'apc_list',
       'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count',
       'citation_normalized_value', 'is_in_top_1_percent',
       'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page',
       'retracted', 'index location', 'is_oa', 'oa_status', 'license',
       'Repository', 'author_id', 'author_name', 'orcid', 'institution_id',
       'institution_name', 'ror', 'country_code', 'funding_type', 'lineage',
       'topic_id', 'topic_name', 'subfield_id', 'subfield_name', 'field_id',
       'field_name', 'domain_id', 'domain_name'],
      dtype='object')

In [46]:
unnested_df = unnested_df[['id', 'doi', 'type', 'funding_type', 'title', 'publication_year', 'publication_date', 'language', 
       'author_id','author_name', 'author_position', 'orcid',
       'apc_list', 'apc_paid', 'fwci', 'has_fulltext', 'cited_by_count', 'citation_normalized_value', 
              'is_in_top_1_percent', 'is_in_top_10_percent', 'volume', 'issue', 'first_page', 'last_page', 
       'topic_id', 'topic_name', 'subfield_id', 'subfield_name', 'field_id', 'field_name', 'domain_id', 'domain_name', 
       'retracted', 'index location', 'Repository', 'is_oa', 'oa_status', 'license',  
       'institution_id', 'institution_name', 'raw_affiliation_strings',  'country_code', 'ror', 'lineage']]
unnested_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,author_id,author_name,author_position,orcid,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,facility,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5022038441,Kendra Bergstedt,first,https://orcid.org/0000-0002-4992-6387,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,Department of Astrophysical Sciences Princeton...,US,https://ror.org/03vn1ts68,https://openalex.org/I1330989302
1,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,education,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5073970199,Hantao Ji,middle,https://orcid.org/0000-0001-9600-9963,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I20089843,Princeton University,Princeton Plasma Physics Laboratory Princeton...,US,https://ror.org/00hx57361,https://openalex.org/I20089843
2,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,facility,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5054740802,Jonathan Jara-Almonte,middle,https://orcid.org/0000-0003-0760-6198,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,"Princeton Plasma Physics Laboratory , Princeto...",US,https://ror.org/03vn1ts68,https://openalex.org/I1330989302
3,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,facility,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5047581227,Jongsoo Yoo,middle,https://orcid.org/0000-0003-3881-1995,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I2799567181,Princeton Plasma Physics Laboratory,"Princeton Plasma Physics Laboratory , Princeto...",US,https://ror.org/03vn1ts68,https://openalex.org/I1330989302
4,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,education,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5036030876,R. E. Ergun,middle,https://orcid.org/0000-0002-3096-8579,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I188538660,University of Colorado Boulder,Laboratory of Atmospheric and Space Sciences U...,US,https://ror.org/02ttsq026,https://openalex.org/I188538660
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
861185,https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,healthcare,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,en,https://openalex.org/A5109964783,Robert Ritch,last,None,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I2799431996,New York Eye and Ear Infirmary,"Ophthalmology, New York Eye and Ear Infirmary,...",US,https://ror.org/00tcb9k97,https://openalex.org/I2799431996
861186,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,education,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,en,https://openalex.org/A5110253366,E Simon Barriga,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I169521973,University of New Mexico,"Electrical and Computer Engineering, Universit...",US,https://ror.org/05fs6jp91,https://openalex.org/I169521973
861187,https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,education,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,en,https://openalex.org/A5114017782,Brian C. Oveson,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,https://openalex.org/subfields/1312,Molecular Biology,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology",https://openalex.org/domains/1,Life Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I145311948,Johns Hopkins University,"Ophthalmology, Johns Hopkins University, Balti...",US,https://ror.org/00za53h95,https://openalex.org/I145311948
861188,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,education,The Politics of Takings Clauses,2018.0,2018-01-01,en,https://openalex.org/A5057875125,Mila Versteeg,first,https://orcid.org/0000-0001-5231-9847,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T13357,Property Rights and Legal Doctrine,https://openalex.org/subfields/3308,Law,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,0.0,datacite,Figshare,True,green,cc-by,https://openalex.org/I51556381,University of Virginia,University of Virginia School of Law,US,https://ror.org/0153tk833,https://openalex.org/I51556381
861189,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,education,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,en,https://openalex.org/A5015635036,Carla Agurto Rios,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I169521973,University of New Mexico,"Electrical & Computer Engineering, University ...",US,https://ror.org/05fs6jp91,https://openalex.org/I169521973

In [47]:
# subset to ror ids
ror_df = unnested_df[(unnested_df['ror'] == 'https://ror.org/0190ak572') | (unnested_df['ror'] == 'https://ror.org/017zqws13') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') 
                                            | (unnested_df['ror'] == 'https://ror.org/00x6h5n95') | (unnested_df['ror'] == 'https://ror.org/00jmfr291') | (unnested_df['ror'] == 'https://ror.org/047426m28') 
                                            | (unnested_df['ror'] == 'https://ror.org/03arq3225') | (unnested_df['ror'] == 'https://ror.org/04sac7215') | (unnested_df['ror'] == 'https://ror.org/02ttsq026') 
                                            | (unnested_df['ror'] == 'https://ror.org/05bnh6r87') | (unnested_df['ror'] == 'https://ror.org/02smfhw86') | (unnested_df['ror'] == 'https://ror.org/01y2jtd41') 
                                            | (unnested_df['ror'] == 'https://ror.org/00hx57361') | (unnested_df['ror'] == 'https://ror.org/04p491231') | (unnested_df['ror'] == 'https://ror.org/0153tk833')
                                            | (unnested_df['ror'] == 'https://ror.org/00b30xv10') | (unnested_df['ror'] == 'https://ror.org/00py81415') | (unnested_df['ror'] == 'https://ror.org/01yc7t268') 
                                            | (unnested_df['ror'] == 'https://ror.org/05fs6jp91') | (unnested_df['ror'] == 'https://ror.org/043mer456') | (unnested_df['ror'] == 'https://ror.org/00b30xv10')
                                            | (unnested_df['ror'] == 'https://ror.org/00mkhxb43') | (unnested_df['ror'] == 'https://ror.org/024mw5h28') | (unnested_df['ror'] == 'https://ror.org/00za53h95')
                                            | (unnested_df['ror'] == 'https://ror.org/04rswrd78') | (unnested_df['ror'] == 'https://ror.org/05x2bcf33')].reset_index(drop=True)


ror_df

,id,doi,type,funding_type,title,publication_year,publication_date,language,author_id,author_name,author_position,orcid,apc_list,apc_paid,fwci,has_fulltext,cited_by_count,citation_normalized_value,is_in_top_1_percent,is_in_top_10_percent,volume,issue,first_page,last_page,topic_id,topic_name,subfield_id,subfield_name,field_id,field_name,domain_id,domain_name,retracted,index location,Repository,is_oa,oa_status,license,institution_id,institution_name,raw_affiliation_strings,country_code,ror,lineage
0,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,education,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5073970199,Hantao Ji,middle,https://orcid.org/0000-0001-9600-9963,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I20089843,Princeton University,Princeton Plasma Physics Laboratory Princeton...,US,https://ror.org/00hx57361,https://openalex.org/I20089843
1,https://openalex.org/W3191156716,https://doi.org/10.11578/1814936,dataset,education,Statistical properties of magnetic structures ...,2020.0,2020-01-01,en,https://openalex.org/A5036030876,R. E. Ergun,middle,https://orcid.org/0000-0002-3096-8579,None,NaN,0.0,False,1,0.243388,False,False,2020,None,None,None,https://openalex.org/T10159,Ionosphere and magnetosphere dynamics,https://openalex.org/subfields/3103,Astronomy and Astrophysics,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,datacite,OSTI OAI (U.S. Department of Energy Office of ...,True,green,None,https://openalex.org/I188538660,University of Colorado Boulder,Laboratory of Atmospheric and Space Sciences U...,US,https://ror.org/02ttsq026,https://openalex.org/I188538660
2,https://openalex.org/W4390091665,https://doi.org/10.3204/pubdb-2024-00403,dataset,education,A two-frame movie of X-ray induced structural ...,2015.0,2015-01-01,en,https://openalex.org/A5041351354,Björn Senfftleben,middle,https://orcid.org/0000-0003-1716-5445,None,NaN,0.0,False,1,0.423247,False,False,None,None,None,None,https://openalex.org/T11183,Advanced X-ray Imaging Techniques,https://openalex.org/subfields/3108,Radiation,https://openalex.org/fields/31,Physics and Astronomy,https://openalex.org/domains/3,Physical Sciences,0.0,arxiv,arXiv (Cornell University),True,green,cc-by,https://openalex.org/I114395901,University of Nebraska–Lincoln,"European XFEL, 22869 Schenefeld, Germany",US,https://ror.org/043mer456,https://openalex.org/I114395901
3,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,education,Best Practices for Mixed Methods Research in H...,2011.0,2011-01-01,en,https://openalex.org/A5025339678,John W. Creswell,first,https://orcid.org/0000-0002-5006-880X,None,NaN,NaN,False,1559,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,0.0,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
4,https://openalex.org/W2913255424,https://doi.org/10.1037/e566732013-001,dataset,education,Best Practices for Mixed Methods Research in H...,2011.0,2011-01-01,en,https://openalex.org/A5021840711,Vicki L. Plano Clark,middle,https://orcid.org/0000-0002-9709-7982,None,NaN,NaN,False,1559,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T10629,Health Policy Implementation Science,https://openalex.org/subfields/3600,General Health Professions,https://openalex.org/fields/36,Health Professions,https://openalex.org/domains/4,Health Sciences,0.0,crossref,PsycEXTRA Dataset,False,closed,None,https://openalex.org/I114395901,University of Nebraska–Lincoln,University of Nebraska— Lincoln,US,https://ror.org/043mer456,https://openalex.org/I114395901
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
563227,https://openalex.org/W904275815,https://doi.org/10.4016/40293.01,dataset,education,665 Glaucomatous Damage of the Macula as Revea...,2012.0,2012-03-12,en,https://openalex.org/A5104364080,Carlos De Moraes,middle,None,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I57206974,New York University,"Ophthalmology, New York University School of M...",US,https://ror.org/0190ak572,https://openalex.org/I57206974
563228,https://openalex.org/W911787724,https://doi.org/10.4016/40866.01,dataset,education,4105 Statistical Validation Of An Automatic Al...,2012.0,2012-03-12,en,https://openalex.org/A5110253366,E Simon Barriga,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T11438,Retinal Imaging and Analysis,https://openalex.org/subfields/2741,"Radiology, Nuclear Medicine and Imaging",https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I169521973,University of New Mexico,"Electrical and Computer Engineering, Universit...",US,https://ror.org/05fs6jp91,https://openalex.org/I169521973
563229,https://openalex.org/W951062899,https://doi.org/10.4016/40698.01,dataset,education,2994 Fenretinide Prevents Retinal Neovasculari...,2012.0,2012-03-12,en,https://openalex.org/A5114017782,Brian C. Oveson,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T11559,Retinoids in leukemia and cellular processes,https://openalex.org/subfields/1312,Molecular Biology,https://openalex.org/fields/13,"Biochemistry, Genetics and Molecular Biology",https://openalex.org/domains/1,Life Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I145311948,Johns Hopkins University,"Ophthalmology, Johns Hopkins University, Balti...",US,https://ror.org/00za53h95,https://openalex.org/I145311948
563230,https://openalex.org/W964481991,https://doi.org/10.6084/m9.figshare.7508570,dataset,education,The Politics of Takings Clauses,2018.0,2018-01-01,en,https://openalex.org/A5057875125,Mila Versteeg,first,https://orcid.org/0000-0001-5231-9847,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T13357,Property Rights and Legal Doctrine,https://openalex.org/subfields/3308,Law,https://openalex.org/fields/33,Social Sciences,https://openalex.org/domains/2,Social Sciences,0.0,datacite,Figshare,True,green,cc-by,https://openalex.org/I51556381,University of Virginia,University of Virginia School of Law,US,https://ror.org/0153tk833,https://openalex.org/I51556381
563231,https://openalex.org/W966165312,https://doi.org/10.4016/40862.01,dataset,education,4100 Detection Of Hard Exudates In The Macula ...,2012.0,2012-03-12,en,https://openalex.org/A5015635036,Carla Agurto Rios,first,None,None,NaN,NaN,False,0,NaN,NaN,NaN,None,None,None,None,https://openalex.org/T10250,Glaucoma and retinal disorders,https://openalex.org/subfields/2731,Ophthalmology,https://openalex.org/fields/27,Medicine,https://openalex.org/domains/4,Health Sciences,0.0,crossref,SciVee,False,closed,None,https://openalex.org/I169521973,University of New Mexico,"Electrical & Computer Engineering, University ...",US,https://ror.org/05fs6jp91,https://openalex.org/I169521973

# Only authors from DCN institutions
ror_df.to_csv('3-18-UMN-Source-API.csv')

In [48]:
#unnested_df.to_csv('3-18-UMN-Source-API.csv')
ror_df.to_csv('3-24-DCN-API.csv')